### PR TITLE
module: zfs: arc: hdr_full_crypt_dest: drop unevaulated-only variable

### LINKED ISSUE #13194: zfs-2.1.3/module/zfs/arc.c:1208:17: error: unused variable ‘hdr’
Compiling on Centos 8 Stream with latest elrep kernel-ml  5.16.13-1.el8.elrepo.x86_64 fails

```
Making all in module
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)
  You are using:           gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10)
/root/zfs-2.1.3/module/zfs/arc.c: In function ‘hdr_l2only_dest’:
/root/zfs-2.1.3/module/zfs/arc.c:1208:17: error: unused variable ‘hdr’ [-Werror=unused-variable]
  arc_buf_hdr_t *hdr = vbuf;
                 ^~~
cc1: all warnings being treated as errors
make[5]: *** [scripts/Makefile.build:287: /root/zfs-2.1.3/module/zfs/arc.o] Error 1
make[4]: *** [scripts/Makefile.build:549: /root/zfs-2.1.3/module/zfs] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:1846: /root/zfs-2.1.3/module] Error 2
make[2]: *** [Makefile:55: modules-Linux] Error 2
make[1]: *** [Makefile:920: all-recursive] Error 1
```

### System information
Distribution Name	| Centos-Stream
Distribution Version	| 8
Kernel Version	| 5.16.13-1.el8.elrepo.x86_64
Architecture	| x886_64
OpenZFS Version	| 2.1.3

### PR DESCRIPTION
**Pull request by nabijaczleweli**
### Motivation and Context
#13194

### Description
Doesn't fix #13194

### How Has This Been Tested?
Builds

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes. – none apply
- [ ] I have run the ZFS Test Suite with this change applied. – CI take my hand
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/arc.c [hunk 1]
```diff
@@ -1204,11 +1204,10 @@ hdr_full_dest(void *vbuf, void *unused)
 static void
 hdr_full_crypt_dest(void *vbuf, void *unused)
```
Comment (TheUbuntuGuy) [inline module/zfs/arc.c:1205]: This is not the same function as in #13194. That issue relates to v2.1.3, which is line 1217 on master.

**Comment by freqlabs** [comment]
The problem is that we didn't backport all those changes to the debug macros to zfs-2.1-release.

**Comment by freqlabs** [comment]
"Just `git log master include/os/freebsd/spl/sys/debug.h`," I said to myself. "EZ"
Turns out there are a whole lot of separate commits all over the place needed to unbreak this.

File: module/zfs/arc.c (hunk 1 above)
Comment (nabijaczleweli) [reply module/zfs/arc.c:1205]: oh, that's fair enough actually

**Comment by nabijaczleweli** [comment]
I mean, there's really only one: the one that turns non-debug ASSERTs from nothing into void-casts.

**Comment by freqlabs** [comment]
I didn't find that one on master, I found one that used sizeof which then needed to be fixed a couple times, and then the args actually being used in non-debug builds had its own problems where struct members didn't necessarily exist anymore but were being used, and some function wasn't defined, and eventually I went back to the `__maybe_unused` :)

**Review by ahrens — APPROVED** [review]

**Review by freqlabs — APPROVED** [review]

**Review by behlendorf — APPROVED** [review]
It looks like this just needs the style warning fixed.

**Comment by nabijaczleweli** [comment]
Fixed
