### PR TITLE
linux/uio: remove "skip" offset for `UIO_ITER`

### LINKED ISSUE #17277: Kernel update breaks loopbacks on ZFS volumes
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Unraid
Distribution Version	| 7.1.0-rc.2
Kernel Version	| 6.12.25
Architecture	| x86_64
OpenZFS Version	| 2.3.1

### Describe the problem you're observing

This looks more like a kernel issue to me, but if I report it there I expect them to say that ZFS is not supported, so thought of reporting it here first to see what you think.

After updating the kernel from 6.12.24 to 6.12.25, loopbacks on a ZFS volume hang

### Describe how to reproduce the problem

Create a new loopback image on a zfs volume, can be a single device zfs volume, format the loopback device xfs, attempt to mount it and it hangs:

```
root@test2:~# dd if=/dev/zero of=/mnt/tank/image bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.219488 s, 4.9 GB/s
root@test2:~# losetup /dev/loop2 /mnt/tank/image 
root@test2:~# mkfs.xfs /dev/loop2
meta-data=/dev/loop2             isize=512    agcount=4, agsize=65536 blks
         =                       sectsz=512   attr=2, projid32bit=1
         =                       crc=1        finobt=1, sparse=1, rmapbt=1
         =                       reflink=1    bigtime=1 inobtcount=1 nrext64=1
         =                       exchange=0   metadir=0
data     =                       bsize=4096   blocks=262144, imaxpct=25
         =                       sunit=0      swidth=0 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1, parent=0
log      =internal log           bsize=4096   blocks=16384, version=2
         =                       sectsz=512   sunit=0 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
         =                       rgcount=0    rgsize=0 extents
Discarding blocks...Done.
root@test2:~# mkdir /x
root@test2:~# mount /dev/loop2 /x


```

There are no panic/crashes logged, it stops here:

```
Apr 27 11:25:24 test2 kernel: loop2: detected capacity change from 0 to 2097152
Apr 27 11:26:04 test2 kernel: XFS (loop2): Mounting V5 Filesystem a6d3b0f6-ef7f-4e97-a665-e19a7b1074d2
```
Top shows that process using 100% CPU, it cannot be killed, and the server needs a hard reboot to recover:

```
top - 11:28:35 up 14 min,  0 users,  load average: 1.98, 0.96, 0.43
Tasks: 252 total, 2 running, 249 sleep, 1 d-sleep, 0 stopped, 0 zombie
%Cpu(s):  1.5 us, 26.3 sy,  0.0 ni, 72.1 id,  0.1 wa,  0.0 hi,  0.1 si,  0.0 st 
MiB Mem :  31932.4 total,  30148.2 free,    952.7 used,   1351.2 buff/cache     
MiB Swap:      0.0 total,      0.0 free,      0.0 used.  30979.7 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                    
    449 root      20   0       0      0      0 R 100.0   0.0   2:30.51 kworker/u16:5+loop2          
```

P.S. if I format the loopback device btrfs, it doesn't hang on mount, but it does immediately after some i/o, reverting the kernel to 6.12.24 resolves the issue, if any other info is needed, please let me know.

Thanks.

### PR DESCRIPTION
**Pull request by robn**
### Motivation and Context

torvalds/linux@f2fed441c69b9237760840a45a004730ff324faf changes the Linux loop device to (effectively) pass the iterator received from the upper filesystem down the the lower filesystem, where previously it would walk the iterator, create a new single-item iterator over each element, and call into the VFS layer for service.

This change exposed a bug in `UIO_ITER` uios, which wrap `iov_iter`: when we advance the uio, if the offset of the data inside the `iov_iter` is non-zero (the "skip"), we would try to advance the iterator ourselves. But, this is not our iterator, and we don't have to do that - the iterator internals will sort that out if it needs to.

The end result is that if we get an iterator with a first element with a non-zero offset, every time we advance we would skip that many bytes. This either lands somewhere in the middle of the iterator, getting the wrong data, or runs off the end, usually resulting in an `EFAULT` somewhere.

In the case of #17277, the iterator passed down from XFS consistently contains segments with non-zero offsets. The additional skipping runs the iterator position off the end of the available data, and results in an `EFAULT` loop in `zpl_write_iter()`.

Fixes #17277.

### Description

The bug proper is fixed by removing the unnecessary advance in `zfs_uiomove_iter()` and just let the underlying iterator sort it out. (note: the first version of this PR did _only_ this).

As it turns out, we don't even set the skip for `UIO_ITER` for read, and in the few other places we try to use it (some of the direct IO support code), we don't do anything meaningful with it, so I've removed all traces of skip handling for `UIO_ITER`.

### How Has This Been Tested?

The test case in #17277 is to create a file on a pool, use `losetup` to create a loop device over it, then format the loop device as XFS and try to mount it. Something like:

```
zpool create tank ...
truncate -s 512M /tank/img
dev=$(losetup -f /tank/img)
mkfs.xfs $dev
mount $dev /mnt
```

On kernels with the aforementioned change (eg 6.12.25), without this PR, the `mount` call hangs. With this patch, it succeeds.

I've done this same test on all release kernels back to 4.19 _without_ the upstream change but _with_ this PR, and that experiment still succeeds.

I do not have a more specific test case.

The `direct` suite appears to pass correctly, but with some tracing shows that `from->iov_offset` in `zpl_iter_write` was always zero, so if it's possible for it to be anything else in the direct IO cases, I have not tested it.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by mcmilk — APPROVED** [review]

**Review by amotin — COMMENTED** [review]
It seems to make sense, but I think it is only a part of the confusion.  I see `zfs_uio_iov_iter_init()` receiving `skip` of 0 in `zpl_iter_read()`, but `iov_offset` in `zpl_iter_write()`.  Same time aside of this one place I don't see `uio_skip` ever used for `UIO_ITER` uios.  Could we also remove the skip parameter from `zfs_uio_iov_iter_init()`?

**Comment by robn** [comment]
> It seems to make sense, but I think it is only a part of the confusion. I see `zfs_uio_iov_iter_init()` receiving `skip` of 0 in `zpl_iter_read()`, but `iov_offset` in `zpl_iter_write()`. Same time aside of this one place I don't see `uio_skip` ever used for `UIO_ITER` uios. Could we also remove the skip parameter from `zfs_uio_iov_iter_init()`?

@amotin agreed. I was wary, because I could see it being used in some of the direct IO support code and I wasn't sure. I've not studied it closely, but it does seem like the skip is not used in any interesting way there, as the kernel is asked for pages and the whole point of direct IO is that it's all properly aligned anyway.

So, last push removes setting the skip for `UIO_ITER` (removes the whole parameter entirely). PR title and description updated. Retesting all looks good. Nice cleanup I reckon :)

**Comment by tonyhutter** [comment]
@robn I wrote a [test case](https://github.com/tonyhutter/zfs/commit/072478d8c2d4aca1d5077ad710c07f643643c16c) based off the reproducer in the PR description.  Sure enough, the test case reliably hangs on Fedora 40-42, but passes with this PR.

**Review by tonyhutter — APPROVED** [review]

File: module/os/linux/zfs/zfs_uio.c [hunk 1]
```diff
@@ -507,12 +504,13 @@ static int
 zfs_uio_pin_user_pages(zfs_uio_t *uio, zfs_uio_rw_t rw)
 {
 	long res;
-	size_t skip = uio->uio_skip;
-	size_t len = uio->uio_resid - skip;
+	size_t len = uio->uio_resid;
```
Comment (amotin) [inline module/os/linux/zfs/zfs_uio.c:507]: Looking again, I think this function should get `size_t skip = uio->uio_iter->iov_offset` instead of removing it, similar to what iov_iter_alignment() and iov_iter_alignment_iovec() do in Linux kernel.  It was wrong to call `iov_iter_advance()` on the `iov_offset` value, when we are getting inside the `uio_iter`, we should take it into account.

Comment (bwatkinson) [reply module/os/linux/zfs/zfs_uio.c:507]: @robn I agree with @amotin on this one. So this code was me having to do things by hand outside of `iov_iter` interfaces because they are GPL only. We would in fact need to take into account the `iov_offset` here.

File: module/os/linux/zfs/zfs_uio.c [hunk 2]
```diff
@@ -577,7 +573,7 @@ static int
 zfs_uio_get_dio_pages_iov_iter(zfs_uio_t *uio, zfs_uio_rw_t rw)
 {
 	size_t start;
-	size_t wanted = uio->uio_resid - uio->uio_skip;
+	size_t wanted = uio->uio_resid;
```
Comment (bwatkinson) [inline module/os/linux/zfs/zfs_uio.c:576]: This could just be replaced bo `iov_iter_count()` instead I believe? This is just making sure we take into account the actual amount requested including the deduction of the `iov_offset`.

File: module/os/linux/zfs/zfs_uio.c [hunk 3]
```diff
@@ -611,7 +607,7 @@ zfs_uio_get_dio_pages_iov_iter(zfs_uio_t *uio, zfs_uio_rw_t rw)
 #endif
 
 	}
-	ASSERT3U(rollback, ==, uio->uio_resid - uio->uio_skip);
+	ASSERT3U(rollback, ==, uio->uio_resid);
```
Comment (bwatkinson) [inline module/os/linux/zfs/zfs_uio.c:610]: See my other comment about setting `wanted` as it was previously.

**Review by bwatkinson — CHANGES_REQUESTED** [review]

**Comment by robn** [comment]
Sigh, this is why my original patch was focused on a specific case - I was here to fix a bug, not rework the whole thing. I'll have a look at next opportunity, maybe not until tomorrow or the weekend.

File: module/os/linux/zfs/zfs_uio.c (hunk 2 above)
Comment (robn) [reply module/os/linux/zfs/zfs_uio.c]: I couldn't quickly confirm that `iov_iter_count()` was exactly the same thing, so I just reverted it to what it was.

**Comment by robn** [comment]
@amotin @bwatkinson I've (effectively) reverted the change in `zfs_uio_pin_user_pages()` and `zfs_uio_get_dio_pages_iov_iter()`. Still not capturing the offset as `uio_skip`, just looking it up in `uio->uio_iter->iov_offset` when we need it. Hopefully that's the same.

File: module/os/linux/zfs/zfs_uio.c (hunk 2 above)
Comment (amotin) [reply module/os/linux/zfs/zfs_uio.c]: Looking on this:
```
static unsigned long iov_iter_alignment_iovec(const struct iov_iter *i)
{
<------>const struct iovec *iov = iter_iov(i);
<------>unsigned long res = 0;
<------>size_t size = i->count;
<------>size_t skip = i->iov_offset;

<------>do {
<------><------>size_t len = iov->iov_len - skip;
<------><------>if (len) {
<------><------><------>res |= (unsigned long)iov->iov_base + skip;
<------><------><------>if (len > size)
<------><------><------><------>len = size;
<------><------><------>res |= len;
<------><------><------>size -= len;
<------><------>}
<------><------>iov++;
<------><------>skip = 0;
<------>} while (size);
<------>return res;
}
```
I'd say that `i->count` already has `i->iov_offset` excluded.  So you should not subtract `skip`/`iov_offset` from `uio_resid`, which is `iov_iter_count()` and so `i->count`.

**Comment by robn** [comment]
> I've (effectively) reverted the change
And the rest of it in the last push, sigh.

File: module/os/linux/zfs/zfs_uio.c (hunk 2 above)
Comment (robn) [reply module/os/linux/zfs/zfs_uio.c]: Hrm, so it was wrong on master, too?

I've just put this through the `direct` tests, all passed. Seem good?

```diff
@@ -577,7 +576,8 @@ static int
 zfs_uio_get_dio_pages_iov_iter(zfs_uio_t *uio, zfs_uio_rw_t rw)
 {
        size_t start;
-       size_t wanted = uio->uio_resid - uio->uio_skip;
+       size_t total = iov_iter_count(uio->uio_iter);
+       size_t wanted = total;
        ssize_t rollback = 0;
        ssize_t cnt;
        unsigned maxpages = DIV_ROUND_UP(wanted, PAGE_SIZE);
@@ -611,7 +611,7 @@ zfs_uio_get_dio_pages_iov_iter(zfs_uio_t *uio, zfs_uio_rw_t rw)
 #endif

        }
-       ASSERT3U(rollback, ==, uio->uio_resid - uio->uio_skip);
+       ASSERT3U(rollback, ==, total);
        iov_iter_revert(uio->uio_iter, rollback);

        return (0);
```

Comment (robn) [reply module/os/linux/zfs/zfs_uio.c]: Pushed, might as well let CI get a look at it too.

Comment (amotin) [reply module/os/linux/zfs/zfs_uio.c]: I am not sure whether `uio->uio_resid` or `iov_iter_count()` would be cleaner from a big picture, but they should be equal now.  I think I'd prefer `uio->uio_resid`.

I don 't see how the assertion can ever be false, but whatever.

Otherwise fine to me.

Comment (robn) [reply module/os/linux/zfs/zfs_uio.c]: Yeah, I prefer `uio->uio_resid` too, just a bit less at the whim of the kernel. So I'll put this bit back how I had it ¯\_(ツ)_/¯

**Review by amotin — APPROVED** [review]
Looks good to me now. Thanks.

**Comment by robn** [comment]
Heh, and to you :)

**Comment by mcmilk** [comment]
Wow, it looked so simple in the beginning... really good work to all :+1:
