### PR TITLE
display pbkdf2iters property as plain number

### LINKED ISSUE #10691: pbkdf2iters property displayed in binary units
### System information
Type | Version/Name
 --- | ---
Distribution Name | Fedora
Distribution Version | 32
Linux Kernel | 5.7.11-200.fc32.x86_64
Architecture | x86_64
ZFS Version | 0.8.4-1
SPL Version | 0.8.4-1

### Describe the problem you're observing

In human-readable mode, the `pbkdf2iters` property seems to be displayed in binary units (as opposed to SI ones). `zfs get -p` displays the correct exact value. I don't imagine this property (a plain count) is actually handled in binary units or should be displayed as such.

### Describe how to reproduce the problem

```
$ sudo zfs change-key -o pbkdf2iters=500000 tank/backup
Enter new passphrase for 'tank/backup': 
Re-enter new passphrase for 'tank/backup': 

$ zfs get pbkdf2iters tank/backup
NAME         PROPERTY     VALUE        SOURCE
tank/backup  pbkdf2iters  488K         -

$ echo $(( 500000 / 1024 ))
488

$ zfs get -p pbkdf2iters tank/backup
NAME         PROPERTY     VALUE        SOURCE
tank/backup  pbkdf2iters  500000       -
```

### PR DESCRIPTION
**Pull request by SirOibaf**
### Motivation and Context
The pbkdf2iters property is an iteration counter and should be displayed as plain number rather than in binary unit.

### Description
Fixes #10691 

### How Has This Been Tested?
Inspected visually the output of `zfs get pbkdf2iters`

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: lib/libzfs/libzfs_dataset.c [hunk 1]
```diff
@@ -2923,6 +2923,18 @@ zfs_prop_get(zfs_handle_t *zhp, zfs_prop_t prop, char *propbuf, size_t proplen,
 		zcp_check(zhp, prop, val, NULL);
 		break;
 
+	case ZFS_PROP_PBKDF2_ITERS:
```
Comment (behlendorf) [inline lib/libzfs/libzfs_dataset.c:2926]: It looks like we could add `ZFS_PROP_PBKDF2_ITERS` after the `ZFS_PROP_OBJSETID` above so it's handled the same way as those properties and the full value is always printed.

**Review by behlendorf — COMMENTED** [review]
Thanks tackling this issue and opening a PR.

**Review by behlendorf — APPROVED** [review]
