### PR TITLE
draid: fix data corruption after disk clear

### LINKED ISSUE #18286: CKSUM errors on dRAID spares after clearing disk with attached spare
### System information

Type | Version/Name
 --- | ---
Distribution Name	| N/A
Distribution Version	| N/A
Kernel Version	| N/A
Architecture	| N/A
OpenZFS Version	| all versions, including the latest master (commit f8e5af53e)

### Describe the problem you're observing

In dRAID vdev, when there there are several faulted disks with attached dRAID spares, and one of those disks is cleared from errors (`zpool clear`), followed by its spare being detached, the data in all the remaining spares that were attached while the cleared disk was in FAULTED state might get corrupted (which can be seen by running scrub). In some cases, when too many disks get cleared at a time, this can result in data loss.

### Describe how to reproduce the problem

Here's a simple scenario to reproduce the problem with 2 faulted disks:
1. Create a pool with dRAID vdev and at least 2 dRAID spares and write some amount of data to it, around 70% of its capacity or at least 70G (depending on the number of children, in my case it was 30).
2. Fail any disk (`zpool offline -f`).
3. Wait until it gets sequentially resilvered and scan is finished.
4. Fail another disk in a similar way.
5. Again wait until it gets resilvered and scan is finished.
6. Now, clear the 1st failed disk from errors (`zpool clear`).
7. Wait until healing resilver is finished and spare is detached.
8. Now scrub the pool (`pool scrub`).

After this, you can see CKSUM errors on the remaining spare and non-zero bytes repaired by scrub, for example:
```
$ zpool status
  pool: testpool
 state: DEGRADED
status: One or more devices are faulted in response to persistent errors.
	Sufficient replicas exist for the pool to continue functioning in a
	degraded state.
action: Replace the faulted device, or use 'zpool clear' to mark the device
	repaired.
  scan: scrub repaired 363M in 00:00:32 with 0 errors on Tue Mar  3 23:42:27 2026
config:

	NAME                          STATE     READ WRITE CKSUM
	testpool                      DEGRADED     0     0     0
	  draid3:11d:30c:5s-0         DEGRADED     0     0     0
	    wwn-0x5000c29fe204526e    ONLINE       0     0     0
...
	    wwn-0x5000c29f067a65c2    ONLINE       0     0     0
	    spare-22                  DEGRADED     0     0 36.7K
	      wwn-0x5000c29de2f04c96  FAULTED      0     0     0  external device fault
	      draid3-0-1              ONLINE       0     0     0
	    wwn-0x5000c29027282b9d    ONLINE       0     0     0
...
```

Here's a simple script that might be helpful to reproduce the problem easily:
```
#!/bin/bash

sudo systemctl stop zed

while true; do
  echo "try $((++c)), fail two random disks one after another..."
  disks=$(zpool status | grep 'wwn.*ONL' | shuf | head -2 | awk '{print $1}')
  i=0
  for d in $disks; do
    echo "failing $d..."
    sudo zpool offline -f testpool $d
    sudo zpool replace -s -w testpool $d "draid3-0-$((i++))"
  done
  zpool status
  echo "wait for scan to complete..."
  while ! zpool status | grep -q 'scan: scrub repaired'; do sleep 1; done
  zpool status | grep 'scan: scrub repaired 0B' || break
  zpool status
  echo "clearing 1st disk..."
  d1=$(zpool status | grep -B1 'draid3-0-0' | grep wwn | awk '{print $1}')
  sudo zpool clear testpool $d1
  echo "wait for resilver to complete..."
  while ! zpool status | grep -q 'scan: resilvered'; do sleep 1; done
  zpool status
  echo "scrub..."
  sudo zpool scrub testpool
  while ! zpool status | grep -q 'scan: scrub repaired'; do sleep 1; done
  zpool status | grep 'scan: scrub repaired 0B' || break
  echo "clearing pool..."
  sudo zpool clear testpool
  while ! zpool status | grep -q 'scan: resilvered'; do sleep 1; done
done
```

### Root cause of the problem

dRAID spare is a virtual device whose blocks are distributed among other disks. Those disks can be also in FAULTED state with attached spares on their own. When a disk gets sequentiall resilvered (or "rebuilt", as it is called in ZFS code), the changes made by that resilvering won't get captured in the DTL (Dirty Time Log) of other FAULTED disks with the attached spares to which the data is written during the resilvering (as it would normally be done for the changes made by the user if a new file is written or some existing one is deleted). It is because sequential resilvering works on the block level, without touching or looking into metadata, so it doesn't know anything about the old BPs or transactions groups that it is resilvering.

So later on, when that disk gets cleared from errors and healing resilvering is trying to sync all the data from its spare onto it, all the changes made on its spare during the resilvering of other disks will be missed because they won't be captured in its DTL. That's why other dRAID spares may get corrupted.

Here's another way to explain it that might be helpful. Imagine a scenario:

1. d1 fails and gets resilvered to some spare s1 - OK.
2. d2 fails and gets sequentially resilvered on draid spare s2. Now, in some slices s2 would map to d1, which is failed. But d1 has s1 spare attached, so the data from that resilvering goes to s1, but not recorded in d1's DTL.
3. Now, d1 gets cleared and its s1 gets detached. All the changes done by the user (writes or deletions) have their txgs captured in d1's DTL, so they will be resilvered by the healing resilver from its spare (s1) - that part works fine. But the data which was written during resilvering of d2 and went to s1 - that one will be missed from d1's DTL and won't get resilvered to it. So here we are:
4. s2 under d2 is corrupted in the slices which map to d1, because d1 doesn't have that data resilvered from s1.

Now, if there are more failed disks with draid spares attached which were sequentially resilvered while d1 was failed, d3+s3, d4+s4 and so on - all their spares will be corrupted. Because, in some slices, each of them will map to d1 which will miss their data.

As a workaround, to avoid losing the data in the pool, one can clear no more that one disk at a time and run scrub after it, which should be able to repair the remaining spares.

### PR DESCRIPTION
**Pull request by andriytk**
### Motivation and Context

Currently, when there there are several faulted disks with attached dRAID spares, and one of those disks is cleared from errors (zpool clear), followed by its spare being detached, the data in all the remaining spares that were attached while the cleared disk was in FAULTED state might get corrupted (which can be seen by running scrub). In some cases, when too many disks get cleared at a time, this can result in data corruption/loss.

### Description

dRAID spare is a virtual device whose blocks are distributed among other disks. Those disks can be also in FAULTED state with attached spares on their own. When a disk gets sequentiall resilvered (rebuilt), the changes made by that resilvering won't get captured in the DTL (Dirty Time Log) of other FAULTED disks with the attached spares to which the data is written during the resilvering (as it would normally be done for the changes made by the user if a new file is written or some existing one is deleted). It is because sequential resilvering works on the block level, without touching or looking into metadata, so it doesn't know anything about the old BPs or transactions groups that it is resilvering. So later on, when that disk gets cleared from errors and healing resilvering is trying to sync all the data from its spare onto it, all the changes made on its spare during the resilvering of other disks will be missed because they won't be captured in its DTL. That's why other dRAID spares may get corrupted.

Here's another way to explain it that might be helpful. Imagine a scenario:

1. d1 fails and gets resilvered to some spare s1 - OK.
2. d2 fails and gets sequentially resilvered on draid spare s2. Now, in some slices, s2 would map to d1, which is failed. But d1 has s1 spare attached, so the data from that resilvering goes to s1, but not recorded in d1's DTL.
3. Now, d1 gets cleared and its s1 gets detached. All the changes done by the user (writes or deletions) have their txgs captured in d1's DTL, so they will be resilvered by the healing resilver from its spare (s1) - that part works fine. But the data which was written during resilvering of d2 and went to s1 - that one will be missed from d1's DTL and won't get resilvered to it. So here we are:
4. s2 under d2 is corrupted in the slices which map to d1, because d1 doesn't have that data resilvered from s1.

Now, if there are more failed disks with draid spares attached which were sequentially resilvered while d1 was failed, d3+s3, d4+s4 and so on - all their spares will be corrupted. Because, in some slices, each of them will map to d1 which will miss their data.

Solution: add all known txgs starting from TXG_INITIAL to DTLs of non-writable devices during sequential resilvering so when healing resilver starts on disk clear, it would be able to check and heal blocks from all txgs.

### How Has This Been Tested?

Here's a simple scenario to reproduce the problem:

1. Create a pool with dRAID vdev and at least 2 dRAID spares and write some amount of data to it, around 70% of its capacity or at least 70G (depending on the number of children, in my case it was 30).
2. Fail any disk (`zpool offline -f`).
3. Wait until it gets sequentially resilvered and scan is finished.
4. Fail another disk in a similar way.
5. Again wait until it gets resilvered and scan is finished.
6. Now, clear the 1st failed disk from errors (`zpool clear`).
7. Wait until healing resilver is finished and spare is detached.
8. Now scrub the pool (`pool scrub`).

Here's a helper script for this scenario:

```
#!/bin/bash

sudo systemctl stop zed

while true; do
  echo "try $((++c)), fail two random disks one after another..."
  disks=$(zpool status | grep 'wwn.*ONL' | shuf | head -2 | awk '{print $1}')
  i=0
  for d in $disks; do
    echo "failing $d..."
    sudo zpool offline -f testpool $d
    sudo zpool replace -s -w testpool $d "draid3-0-$((i++))"
  done
  zpool status
  echo "wait for scan to complete..."
  while ! zpool status | grep -q 'scan: scrub repaired'; do sleep 1; done
  zpool status | grep 'scan: scrub repaired 0B' || break
  zpool status
  echo "clearing 1st disk..."
  d1=$(zpool status | grep -B1 'draid3-0-0' | grep wwn | awk '{print $1}')
  sudo zpool clear testpool $d1
  echo "wait for resilver to complete..."
  while ! zpool status | grep -q 'scan: resilvered'; do sleep 1; done
  zpool status
  echo "scrub..."
  sudo zpool scrub testpool
  while ! zpool status | grep -q 'scan: scrub repaired'; do sleep 1; done
  zpool status | grep 'scan: scrub repaired 0B' || break
  echo "clearing pool..."
  sudo zpool clear testpool
  while ! zpool status | grep -q 'scan: resilvered'; do sleep 1; done
done
```

Without fix, it would reproduce on the 1st try on most of cases. With the fix, it didn't reproduce after running overnight.

I've also updated `redundancy_draid_spare1` automation test which captures the problem in 30% cases without the patch and doesn't fail with the patch:
```
Results Summary
PASS	 298
FAIL	   2

Running Time:	00:36:10
Percent passed:	99.3%
```
(Those 2 failures were not after disk clear, and they seem to be caused by some other known issue(s), see commit d565835c47.)

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Quality assurance (non-breaking change which makes the code more robust against bugs)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

Closes #18286.

### CODE REVIEW

File: module/zfs/vdev_draid.c [hunk 1]
```diff
@@ -1452,13 +1452,6 @@ vdev_draid_group_missing(vdev_t *vd, uint64_t offset, uint64_t txg,
 		/* Transaction group is known to be partially replicated. */
 		if (vdev_draid_partial(cvd, physical_offset, txg, size))
 			return (B_TRUE);
-
-		/*
-		 * Always check groups with active distributed spares
-		 * because any vdev failure in the pool will affect them.
-		 */
-		if (vdev_draid_find_spare(cvd) != NULL)
-			return (B_TRUE);
```
Comment (andriytk) [inline module/zfs/vdev_draid.c:1461]: This seems like a redundant check giving too many false positives causing spurious resilvers.

With this check, vdev_draid_group_missing() would return true in 66% cases and false in 33%. Without this check, it would return false/true in around 50/50 % of cases, which is a considerable optimisation.

File: module/zfs/vdev.c [hunk 2]
```diff
@@ -5044,6 +5044,33 @@ vdev_scan_stat_init(vdev_t *vd)
...
+		while (!vdev_dtl_contains(vd, DTL_MISSING, start, 1))
+			start--;
+		start++;
+	}
+
+	for (uint64_t txg = start; txg <= max_txg; txg++) {
+		vdev_dtl_dirty(vd, DTL_MISSING, txg, 1);
+		for (pvd = vd; pvd != rvd; pvd = pvd->vdev_parent)
+			vdev_dtl_dirty(pvd, DTL_PARTIAL, txg, 1);
+	}
```
Comment (behlendorf) [inline module/zfs/vdev.c]: Pools can have millions, even 10's of millions, of TXGs so on the first pass when nothing has been added to the DTL this is going to be very expensive.  Since the DTLs are implemented as range trees let's take advantage of that and add/check for the entire range to get rid of the looping.  It looks like `vdev_dtl_dirty()` just needs to be updated to clear the range first to avoid adding it twice.

```diff
@@ -3096,8 +3096,11 @@ vdev_dtl_dirty(vdev_t *vd, vdev_dtl_type_t t, uint64_t txg, uint64_t size)
        ASSERT(spa_writeable(vd->vdev_spa));
 
        mutex_enter(&vd->vdev_dtl_lock);
-       if (!zfs_range_tree_contains(rt, txg, size))
+       if (!zfs_range_tree_contains(rt, txg, size)) {
+               zfs_range_tree_clear(rt, txg, size);
                zfs_range_tree_add(rt, txg, size);
+       }
        mutex_exit(&vd->vdev_dtl_lock);
 }
```

File: module/zfs/vdev.c [hunk 3]
```diff
@@ -5044,6 +5044,33 @@ vdev_scan_stat_init(vdev_t *vd)
 	mutex_exit(&vd->vdev_stat_lock);
 }
 
+/*
+ * For rebuild, since we don't have any information about BPs and txgs that
+ * are being rebuild, we need to add all known txgs starting from TXG_INITIAL
```
Comment (behlendorf) [inline module/zfs/vdev.c]:
```suggestion
 * are being rebuilt, we need to add all known txgs starting from TXG_INITIAL
```

File: module/zfs/vdev.c [hunk 4]
```diff
@@ -5044,6 +5044,33 @@ vdev_scan_stat_init(vdev_t *vd)
...
+ * to DTL so that during healing resilver we would be able to check all txgs
+ * at vdev_draid_need_resilver().
```
Comment (behlendorf) [inline module/zfs/vdev.c]: Adding all of the txgs to the DTL effectively turns this in to a full resilver.  That'll be safe and correct, but not fast.  We'd probably want to introduce a new DTL type which tracks offsets to make sure we only rebuild the known missing regions.

File: module/zfs/vdev_draid.c (hunk 1 above)
Comment (behlendorf) [reply module/zfs/vdev_draid.c:1461]: My recollection is this was added to try and avoid adding all of the txgs to the DTLs.  But if the DTLs now contain all the txgs then I agree it seems like this shouldn't be needed.

File: module/zfs/vdev.c (hunk 2 above)
Comment (andriytk) [reply module/zfs/vdev.c]: Yes, this was my worry too. You suggestion sounds great, will try it...

File: module/zfs/vdev.c (hunk 4 above)
Comment (andriytk) [reply module/zfs/vdev.c]: I believe the needless resilverings should be filtered out by `vdev_draid_need_resilver()`, but I agree, there will be too many calls to it, and the new special DTL could help to drop the number of those calls.

File: module/zfs/vdev.c (hunk 2 above)
Comment (andriytk) [reply module/zfs/vdev.c]: Done.

File: module/zfs/vdev.c (hunk 3 above)
Comment (andriytk) [reply module/zfs/vdev.c]: Fixed.

File: module/zfs/vdev.c [hunk 5]
```diff
@@ -5246,6 +5269,11 @@ vdev_stat_update(zio_t *zio, uint64_t psize)
 			} else if (spa->spa_claiming) {
 				ASSERT(flags & ZIO_FLAG_IO_REPAIR);
 				commit_txg = spa_first_txg(spa);
+			} else if (zio->io_priority == ZIO_PRIORITY_REBUILD) {
+				ASSERT(flags & ZIO_FLAG_IO_REPAIR);
+				txg = spa_syncing_txg(spa);
+				vdev_dtl_dirty_rebuild(vd, rvd, txg);
+				return;
```
Comment (behlendorf) [inline module/zfs/vdev.c]: We need to add a call to `vdev_dirty()` before returning to ensure the updated DTLs are written to the pool.

Now that `vdev_dtl_dirty_rebuild()` is a bit more concise it's tempting to pull those few lines in to this block and then describe the sequential resilver case in the comment above where the normal write, scrub, and zil claim cases are discussed.

**Comment by andriytk** [comment]
> This likely explains the rare checksum errors reported by `redundancy_draid_spare[1,3]` which both use `zpool detach`...

I'm afraid, it's not. I tried `redundancy_draid_spare1` with the patch 100 times in the loop, and I still saw those rare cksum errors 2 times, as I mentioned in the description. It must be something else...

And it may happen even before `zpool detach` after only a single disk failure, for example:
```
20:58:39.28 SUCCESS: zpool create -O compression=off -f -m /var/tmp/testdir testpool draid2:5d:13c:2s /var/tmp/basedir.317136/vde
v0 /var/tmp/basedir.317136/vdev1 /var/tmp/basedir.317136/vdev2 /var/tmp/basedir.317136/vdev3 /var/tmp/basedir.317136/vdev4 /var/t
mp/basedir.317136/vdev5 /var/tmp/basedir.317136/vdev6 /var/tmp/basedir.317136/vdev7 /var/tmp/basedir.317136/vdev8 /var/tmp/basedi
r.317136/vdev9 /var/tmp/basedir.317136/vdev10 /var/tmp/basedir.317136/vdev11 /var/tmp/basedir.317136/vdev12
20:58:39.28 NOTE: Filling up the filesystem ...
20:58:40.52 SUCCESS: zpool sync testpool
20:58:40.53 SUCCESS: eval du -a /var/tmp/testdir > /var/tmp/basedir.317136/pre-record-file.317136 2>&1
20:58:40.89 SUCCESS: zpool offline -f testpool /var/tmp/basedir.317136/vdev0
20:58:40.90 SUCCESS: check_vdev_state testpool /var/tmp/basedir.317136/vdev0 FAULTED
20:58:46.05 SUCCESS: zpool replace -w -s testpool /var/tmp/basedir.317136/vdev0 draid2-0-0
20:58:46.06 SUCCESS: check_vdev_state spare-0 DEGRADED
20:58:46.06 SUCCESS: check_vdev_state draid2-0-0 ONLINE
20:58:46.08 SUCCESS: check_hotspare_state testpool draid2-0-0 INUSE
20:58:46.13 SUCCESS: zpool scrub testpool
20:58:47.18 SUCCESS: wait_scrubbed testpool
20:58:47.22   pool: testpool
20:58:47.22  state: DEGRADED
20:58:47.22 status: One or more devices are faulted in response to persistent errors.
20:58:47.22     Sufficient replicas exist for the pool to continue functioning in a
20:58:47.22     degraded state.
20:58:47.22 action: Replace the faulted device, or use 'zpool clear' to mark the device
20:58:47.22     repaired.
20:58:47.22   scan: scrub repaired 1K in 00:00:00 with 0 errors on Mon Mar  9 20:58:46 2026
20:58:47.22   scan: resilvered (draid2:5d:13c:2s-0) 54.6M in 00:00:05 with 0 errors on Mon Mar  9 20:58:45 2026
20:58:47.22 config:
20:58:47.22
20:58:47.22     NAME                                 STATE     READ WRITE CKSUM
20:58:47.22     testpool                             DEGRADED     0     0     0
20:58:47.22       draid2:5d:13c:2s-0                 DEGRADED     0     0     0
20:58:47.22         spare-0                          DEGRADED     0     0     1
20:58:47.22           /var/tmp/basedir.317136/vdev0  FAULTED      0     0     0  external device fault
20:58:47.22           draid2-0-0                     ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev1    ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev2    ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev3    ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev4    ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev5    ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev6    ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev7    ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev8    ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev9    ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev10   ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev11   ONLINE       0     0     0
20:58:47.22         /var/tmp/basedir.317136/vdev12   ONLINE       0     0     0
20:58:47.22     spares
20:58:47.22       draid2-0-0                         INUSE     currently in use
20:58:47.22       draid2-0-1                         AVAIL
20:58:47.22
20:58:47.22 errors: No known data errors
```

But it always happens after sequential resilvering, as far as I've noticed.

File: module/zfs/vdev.c (hunk 5 above)
Comment (andriytk) [reply module/zfs/vdev.c]: > We need to add a call to vdev_dirty() before returning...

Well spotted! Let me update it...

**Comment by behlendorf** [comment]
> I still saw those rare cksum errors 3 times...

Ah okay.  That's good to know.  I somehow missed that in your initial comment.

File: module/zfs/vdev.c (hunk 5 above)
Comment (andriytk) [reply module/zfs/vdev.c]: Updated, please check.

File: module/zfs/vdev.c [hunk 6]
```diff
@@ -5235,27 +5241,40 @@ vdev_stat_update(zio_t *zio, uint64_t psize)
...
+			} else if (zio->io_priority == ZIO_PRIORITY_REBUILD) {
+				ASSERT(flags & ZIO_FLAG_IO_REPAIR);
+				txg = TXG_INITIAL;
+				commit_txg = spa_syncing_txg(spa);
+				size = commit_txg - txg;
 			}
 			ASSERT(commit_txg >= spa_syncing_txg(spa));
-			if (vdev_dtl_contains(vd, DTL_MISSING, txg, 1))
+			if (zio->io_priority != ZIO_PRIORITY_REBUILD &&
+			    vdev_dtl_contains(vd, DTL_MISSING, txg, size))
```
Comment (amotin) [inline module/zfs/vdev.c]: Why do you exclude `ZIO_PRIORITY_REBUILD` here?  As I can see, `vdev_dtl_contains()` means that all the range is already there, and if so, we should have nothing to do and exit.  Am I wrong?

Comment (andriytk) [reply module/zfs/vdev.c]: You are quite right, Alexander. Initially, it was `1` instead of `size`. But now it can be dropped, let me updated the patch...

**Comment by behlendorf** [comment]
> I hope we won't shoot ourself in a foot, declaring whole disks missing after few transient write errors.

Yeah, that's a valid concern.  Marking the whole disk suspect does mean the mirror/raidz/draid code will skip this vdev when reading.  Only if the checksum verification fails will the vdev code attempt to read the stale vdev in order to reconstruct the data.  That's not great, but functionally it doesn't seem wrong.  The vdev is missing data, and without a real mechanism to track those known missing offsets we can't really really trust it until a healing resilver or scrub completes (even if it is mostly intact).

**Comment by andriytk** [comment]
> I hope we won't shoot ourself in a foot, declaring whole disks missing after few transient write errors.

The testing shows that it doesn't. It only starts the whole disk healing resilver when there were other failed disks rebuilt already after that disk failure.

Here's how I tested it:
1. Fail a disk on a pool with some data in it.
2. Wait for it to be rebuilt (sequential resilver).
3. Clear that disk.

The healing resilver after the clearing will complete almost immediately, much faster than the sequential resilver of the disk when it was faulted.

It looks like DTL of the faulted disk is not touched when it is being rebuilt. It's only when other disks are rebuilt to its spare its DTL is updated. Which is what we need.

File: tests/zfs-tests/include/libtest.shlib [hunk 7]
```diff
@@ -3161,6 +3161,21 @@ function wait_scrubbed #pool timeout
...
+#
+# $1 pool name
+# $2 timeout
+#
+function wait_resilvered #pool timeout
+{
+       typeset timeout=${2:-300}
+       typeset pool=${1:-$TESTPOOL}
+       for (( timer = 0; timer < $timeout; timer++ )); do
+               is_pool_resilvered $pool && break;
```
Comment (amotin) [inline tests/zfs-tests/include/libtest.shlib:3174]: Generally there is a `zpool wait -t resilver ...`, but seems it is an established practice there, and the test uses `check_pool_status` any way...

Comment (andriytk) [reply tests/zfs-tests/include/libtest.shlib:3174]: Nice, I didn't know that.

**Comment by andriytk** [comment]
@behlendorf detected a regression in `redundancy_draid_spare3` automation test, so we are going to update the patch. The culprit change is this one:

```
--- a/module/zfs/vdev_rebuild.c
+++ b/module/zfs/vdev_rebuild.c
@@ -593,6 +593,7 @@ vdev_rebuild_range(vdev_rebuild_t *vr, uint64_t start, uint64_t size)
        dmu_tx_t *tx = dmu_tx_create_dd(spa_get_dsl(spa)->dp_mos_dir);
        VERIFY0(dmu_tx_assign(tx, DMU_TX_WAIT | DMU_TX_SUSPEND));
        uint64_t txg = dmu_tx_get_txg(tx);
+       BP_SET_BIRTH(&blk, txg, txg);

        spa_config_enter(spa, SCL_STATE_ALL, vd, RW_READER);
        mutex_enter(&vd->vdev_rebuild_lock);
```

**Comment by andriytk** [comment]
The patch is updated, mainly with the changes suggested by @behlendorf:
1. At `vdev_stat_update()`, pull the open txg from the dsl_pool_t. Added `spa_open_txg()` helper for this.
2. Use the min and max txgs which were stored when starting the sequential resilver to set the DTL txg range.  One nice side effect is newly written txg won't be added to the DTL unless there were failed writes. Added `vdev_rebuild_txgs()` helper for this.
3. Start vrp_min_txg at TXG_INITIAL. Technically not needed, but it's a bit nicer.

File: module/zfs/vdev_rebuild.c [hunk 8]
```diff
@@ -1127,6 +1127,22 @@ vdev_rebuild_stop_all(spa_t *spa)
...
+ * that was written to their spares during the rebuild.
+ */
+void
+vdev_rebuild_txgs(vdev_t *vd, uint64_t *min_txg, uint64_t *size)
+{
+	vdev_rebuild_t *vr = &vd->vdev_rebuild_config;
+	vdev_rebuild_phys_t *vrp = &vr->vr_rebuild_phys;
+
+	*min_txg = vrp->vrp_min_txg;
+	*size = vrp->vrp_max_txg - vrp->vrp_min_txg;
```
Comment (amotin) [inline module/zfs/vdev_rebuild.c:1143]: Those variables are updated by `vdev_resilver_needed()` based on DTLs, but then we update DTLs based on them.  My head hurts here.  I hope it makes some sense.

Comment (behlendorf) [reply module/zfs/vdev_rebuild.c:1143]: The `vrp_min_txg` and `vrp_max_txg` variables are set when the sequential resilver is started (or reset).  Those ranges get propagated in to the DTLs based on failed sequential resilver zio writes.  `vdev_resilver_needed()` checks the txgs ranges in the DTL, but I don't see anywhere it modifies them during sequential resilver.  Once the sequential resilver completes successfully the `vdev_dtl_reassess()` is clears that whole txg ranges from the DTLs.

Comment (amotin) [reply module/zfs/vdev_rebuild.c:1143]: As I can see, `vdev_rebuild_should_cancel()` calls `vdev_resilver_needed(vd, &vrp->vrp_min_txg, &vrp->vrp_max_txg)` before processing each new metaslab.  So it looks like a constantly moving target.

Comment (andriytk) [reply module/zfs/vdev_rebuild.c:1143]: Looks like DTLs for attached spares are set at `spa_vdev_attach()`:

```c
        /*
         * Set newvd's DTL to [TXG_INITIAL, dtl_max_txg) so that we account
         * for any dmu_sync-ed blocks.  It will propagate upward when
         * spa_vdev_exit() calls vdev_dtl_reassess().
         */
        dtl_max_txg = txg + TXG_CONCURRENT_STATES;

        if (raidz) {
                ...
        } else {
                vdev_dtl_dirty(newvd, DTL_MISSING, TXG_INITIAL,
                    dtl_max_txg - TXG_INITIAL);
```

That's what `vdev_resilver_needed()` is returned at `vdev_rebuild_initiate_sync()`, and that's what `vdev_rebuild_txgs()` returns also when updating DTL of faulted devices to whose spares we are resilvering during rebuild - exactly what we need.

Note: `vdev_resilver_needed()` checks only `vdev_writeable()` devices:

```c
boolean_t
vdev_resilver_needed(vdev_t *vd, uint64_t *minp, uint64_t *maxp)
{
        ...
        if (vd->vdev_children == 0) {
                mutex_enter(&vd->vdev_dtl_lock);
                if (!zfs_range_tree_is_empty(vd->vdev_dtl[DTL_MISSING]) &&
                    vdev_writeable(vd)) {
```

So it won't check those faulted devices whose DTLs we are updating at `vdev_stat_update()`.

Comment (amotin) [reply module/zfs/vdev_rebuild.c:1143]: Write errors might happen not only on a faulted device, but OK.

Comment (behlendorf) [reply module/zfs/vdev_rebuild.c:1143]: That's true, in which case we'd extend the max txg in those DTLs and propagate it back to the `vr_rebuild_phys` struct.  That's probably not strictly nessisary, but shouldn't be harmful.  We'll also automatically kick off a scrub after the sequential resilver completes.  If we had a handful of failed writes they'll get fixed by the scrub.

**Comment by andriytk** [comment]
Testing result of redundancy tests run in loop 100 times:

```
$ ./scripts/zfs-tests.sh -T redundancy -I 100
...
Results Summary
PASS	 1699
FAIL	   1

Running Time:	08:29:17
Percent passed:	99.9%
```

The single failure was from `redundancy_draid_spare1`, which is the known issue:

```
10:44:10.76 SUCCESS: mkdir /var/tmp/basedir.692865
10:44:10.77 SUCCESS: truncate -s 268435456 /var/tmp/basedir.692865/vdev0 /var/tmp/basedir.692865/vdev1 /var/tmp/basedir.692865/vdev2 /var/tmp/basedir.692865/vdev3 /var/tmp/
basedir.692865/vdev4 /var/tmp/basedir.692865/vdev5 /var/tmp/basedir.692865/vdev6 /var/tmp/basedir.692865/vdev7 /var/tmp/basedir.692865/vdev8 /var/tmp/basedir.692865/vdev9 /
var/tmp/basedir.692865/vdev10 /var/tmp/basedir.692865/vdev11
10:44:10.85 SUCCESS: zpool create -O compression=off -f -m /var/tmp/testdir testpool draid1:1d:12c:3s /var/tmp/basedir.692865/vdev0 /var/tmp/basedir.692865/vdev1 /var/tmp/b
asedir.692865/vdev2 /var/tmp/basedir.692865/vdev3 /var/tmp/basedir.692865/vdev4 /var/tmp/basedir.692865/vdev5 /var/tmp/basedir.692865/vdev6 /var/tmp/basedir.692865/vdev7 /v
ar/tmp/basedir.692865/vdev8 /var/tmp/basedir.692865/vdev9 /var/tmp/basedir.692865/vdev10 /var/tmp/basedir.692865/vdev11
10:44:10.85 NOTE: Filling up the filesystem ...
10:44:11.23 SUCCESS: zpool sync testpool
10:44:11.24 SUCCESS: eval du -a /var/tmp/testdir > /var/tmp/basedir.692865/pre-record-file.692865 2>&1
10:44:11.45 SUCCESS: zpool offline -f testpool /var/tmp/basedir.692865/vdev0
10:44:11.46 SUCCESS: check_vdev_state testpool /var/tmp/basedir.692865/vdev0 FAULTED
10:44:11.51 SUCCESS: zpool replace -w -s testpool /var/tmp/basedir.692865/vdev0 draid1-0-0
10:44:11.52 SUCCESS: check_vdev_state spare-0 DEGRADED
10:44:11.52 SUCCESS: check_vdev_state draid1-0-0 ONLINE
10:44:11.53 SUCCESS: check_hotspare_state testpool draid1-0-0 INUSE
10:44:11.57 SUCCESS: zpool scrub testpool
10:44:12.63 SUCCESS: wait_scrubbed testpool
10:44:12.65 SUCCESS: verify_pool testpool
10:44:12.66 SUCCESS: check_pool_status testpool scan repaired 0B
10:44:12.68 SUCCESS: check_pool_status testpool scan with 0 errors
10:44:12.70 SUCCESS: zpool offline -f testpool /var/tmp/basedir.692865/vdev1
10:44:12.71 SUCCESS: check_vdev_state testpool /var/tmp/basedir.692865/vdev1 FAULTED
10:44:12.76 SUCCESS: zpool replace -w -s testpool /var/tmp/basedir.692865/vdev1 draid1-0-1
10:44:12.76 SUCCESS: check_vdev_state spare-1 DEGRADED
10:44:12.77 SUCCESS: check_vdev_state draid1-0-1 ONLINE
10:44:12.78 SUCCESS: check_hotspare_state testpool draid1-0-1 INUSE
10:44:12.81 SUCCESS: zpool detach testpool /var/tmp/basedir.692865/vdev1
10:44:12.84 SUCCESS: zpool scrub testpool
10:44:13.92 SUCCESS: wait_scrubbed testpool
10:44:13.96   pool: testpool
10:44:13.96  state: DEGRADED
10:44:13.96 status: One or more devices are faulted in response to persistent errors.
10:44:13.96     Sufficient replicas exist for the pool to continue functioning in a
10:44:13.96     degraded state.
10:44:13.96 action: Replace the faulted device, or use 'zpool clear' to mark the device
10:44:13.96     repaired.
10:44:13.96   scan: scrub repaired 2K in 00:00:00 with 0 errors on Wed Mar 11 10:44:12 2026
10:44:13.96   scan: resilvered (draid1:1d:12c:3s-0) 63.7M in 00:00:00 with 0 errors on Wed Mar 11 10:44:12 2026
10:44:13.96 config:
10:44:13.96
10:44:13.96     NAME                                 STATE     READ WRITE CKSUM
10:44:13.96     testpool                             DEGRADED     0     0     0
10:44:13.96       draid1:1d:12c:3s-0                 DEGRADED     0     0     0
10:44:13.96         spare-0                          DEGRADED     0     0     0
10:44:13.96           /var/tmp/basedir.692865/vdev0  FAULTED      0     0     0  external device fault
10:44:13.96           draid1-0-0                     ONLINE       0     0     0
10:44:13.96         draid1-0-1                       ONLINE       0     0     1
10:44:13.96         /var/tmp/basedir.692865/vdev2    ONLINE       0     0     0
10:44:13.96         /var/tmp/basedir.692865/vdev3    ONLINE       0     0     0
10:44:13.96         /var/tmp/basedir.692865/vdev4    ONLINE       0     0     0
10:44:13.96         /var/tmp/basedir.692865/vdev5    ONLINE       0     0     0
10:44:13.96         /var/tmp/basedir.692865/vdev6    ONLINE       0     0     0
10:44:13.96         /var/tmp/basedir.692865/vdev7    ONLINE       0     0     0
10:44:13.96         /var/tmp/basedir.692865/vdev8    ONLINE       0     0     0
10:44:13.96         /var/tmp/basedir.692865/vdev9    ONLINE       0     0     0
10:44:13.96         /var/tmp/basedir.692865/vdev10   ONLINE       0     0     0
10:44:13.96         /var/tmp/basedir.692865/vdev11   ONLINE       0     0     0
10:44:13.96     spares
10:44:13.96       draid1-0-0                         INUSE     currently in use
10:44:13.96       draid1-0-1                         INUSE     currently in use
10:44:13.96       draid1-0-2                         AVAIL
10:44:13.96
10:44:13.96 errors: No known data errors
10:44:13.96 SUCCESS: zpool status -v
10:44:13.96 Unexpected CKSUM errors found on testpool (1)
```

**Comment by behlendorf** [comment]
Thanks for the additional local testing, my local test results match up with yours.  I'll wait for the remaining CI builder to wrap up and get this merged.
