### PR TITLE
dmu_objset_from_ds must be called with dp_config_rwlock held

### LINKED ISSUE #9662: deadlock when calling dmu_objset_from_ds() without dp_config_rwlock
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 0.7.8
SPL Version	| 

### Describe the problem you're observing
System hangs when receiving dataset.

### Describe how to reproduce the problem
When running the Datto application.  Reproducer needed.

### Include any warning/errors/backtraces from the system logs
```
Thread 25240 is performing an online recv.
It takes ds_opening_lock and requests dp_config_lock as READER.
The request is blocked because thread 26120 (spa_sync) has requested
dp_config_rwlock as WRITER.
This spa_sync RW request is blocked because thread 12943 is in zvol_create_minors_cb.
It has taken dp_config_rwlock as READER.  This continues to be held
because 12493 blocks trying to get ds_opening_lock, which is still 
held by 25240.


2019-11-06T20:14:11.654315 kern.err isw1-bfyii-747 kernel: [86273.858579] INFO: task z_zvol:12943 blocked for more than 120 seconds.
2019-11-06T20:14:11.654345 kern.err isw1-bfyii-747 kernel: [86273.865165]       Tainted: P        W  OE    4.15.0-54-generic #58~16.04.1-Ubuntu
2019-11-06T20:14:11.654348 kern.err isw1-bfyii-747 kernel: [86273.872683] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
2019-11-06T20:14:11.662333 kern.info isw1-bfyii-747 kernel: [86273.880544] z_zvol          D    0 12943      2 0x80000080
2019-11-06T20:14:11.662354  [86273.880549] Call Trace:
2019-11-06T20:14:11.662356  [86273.880565]  __schedule+0x3d6/0x8b0
2019-11-06T20:14:11.662357  [86273.880568]  schedule+0x36/0x80
2019-11-06T20:14:11.662359  [86273.880571]  schedule_preempt_disabled+0xe/0x10
2019-11-06T20:14:11.662444  [86273.880575]  __mutex_lock.isra.2+0x2ae/0x4e0
2019-11-06T20:14:11.662466  [86273.880582]  __mutex_lock_slowpath+0x13/0x20
2019-11-06T20:14:11.662469  [86273.880593]  ? __mutex_lock_slowpath+0x13/0x20
2019-11-06T20:14:11.662470  [86273.880598]  mutex_lock+0x2f/0x40
2019-11-06T20:14:11.662472  [86273.880737]  dmu_objset_from_ds+0x44/0x190 [zfs]       <==== blocked on ds_opening_lock
2019-11-06T20:14:11.662590  [86273.880788]  dmu_objset_hold+0x7f/0xb0 [zfs]           <==== dp_config_rwlock is held 
2019-11-06T20:14:11.662602  [86273.880835]  dsl_prop_get+0x44/0xa0 [zfs]
2019-11-06T20:14:11.662605  [86273.880882]  dsl_prop_get_integer+0x1e/0x20 [zfs]
2019-11-06T20:14:11.662607  [86273.880938]  zvol_create_minors_cb+0x3b/0x100 [zfs]
2019-11-06T20:14:11.662608  [86273.880999]  ? rrw_exit+0x61/0xb0 [zfs]
2019-11-06T20:14:11.662691  [86273.881049]  dmu_objset_find_impl+0x116/0x400 [zfs]   
2019-11-06T20:14:11.662699  [86273.881103]  ? list_insert_tail+0x20/0x20 [zfs]
2019-11-06T20:14:11.669813  [86273.881162]  ? spa_open_common+0x2f5/0x4c0 [zfs]
2019-11-06T20:14:11.669835  [86273.881216]  ? list_insert_tail+0x20/0x20 [zfs]
2019-11-06T20:14:11.669837  [86273.881261]   +0x58/0x90 [zfs]
2019-11-06T20:14:11.669839  [86273.881314]  zvol_create_minors_impl+0x190/0x1b0 [zfs]
2019-11-06T20:14:11.669840  [86273.881369]  zvol_task_cb+0x6d/0xe0 [zfs]
2019-11-06T20:14:11.669842  [86273.881378]  taskq_thread+0x2b0/0x4e0 [spl]
2019-11-06T20:14:11.669844  [86273.881385]  ? wake_up_q+0x70/0x70
2019-11-06T20:14:11.669846  [86273.881391]  kthread+0x105/0x140
2019-11-06T20:14:11.669847  [86273.881395]  ? taskq_thread_should_stop+0x70/0x70 [spl]
2019-11-06T20:14:11.669849  [86273.881398]  ? kthread_destroy_worker+0x50/0x50
2019-11-06T20:14:11.669850  [86273.881401]  ret_from_fork+0x35/0x40
2019-11-06T20:14:11.669856 kern.err isw1-bfyii-747 kernel: [86273.881413] INFO: task txg_sync:26120 blocked for more than 120 seconds.
2019-11-06T20:14:11.669858 kern.err isw1-bfyii-747 kernel: [86273.888147]       Tainted: P        W  OE    4.15.0-54-generic #58~16.04.1-Ubuntu
2019-11-06T20:14:11.677299 kern.err isw1-bfyii-747 kernel: [86273.895661] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
2019-11-06T20:14:11.685445 kern.info isw1-bfyii-747 kernel: [86273.903521] txg_sync        D    0 26120      2 0x80000080
2019-11-06T20:14:11.685465  [86273.903524] Call Trace:
2019-11-06T20:14:11.685468  [86273.903527]  __schedule+0x3d6/0x8b0
2019-11-06T20:14:11.685470  [86273.903530]  ? _cond_resched+0x1a/0x50
2019-11-06T20:14:11.685471  [86273.903532]  schedule+0x36/0x80
2019-11-06T20:14:11.685472  [86273.903538]  cv_wait_common+0x101/0x140 [spl]
2019-11-06T20:14:11.685474  [86273.903544]  ? wait_woken+0x80/0x80
2019-11-06T20:14:11.685476  [86273.903548]  __cv_wait+0x15/0x20 [spl]
2019-11-06T20:14:11.685478  [86273.903592]  rrw_enter_write+0x3d/0xa0 [zfs]           <==== blocked on dp_config_rwlock RW
2019-11-06T20:14:11.685479  [86273.903642]  rrw_enter+0x13/0x20 [zfs]
2019-11-06T20:14:11.685480  [86273.903697]  spa_sync_upgrades+0x38/0x210 [zfs]
2019-11-06T20:14:11.685482  [86273.903745]  spa_sync+0x6ff/0x8c0 [zfs]
2019-11-06T20:14:11.685484  [86273.903799]  txg_sync_thread+0x29b/0x340 [zfs]
2019-11-06T20:14:11.685486  [86273.903853]  ? txg_dispatch_callbacks+0x100/0x100 [zfs]
2019-11-06T20:14:11.685502  [86273.903863]  thread_generic_wrapper+0x74/0x90 [spl]
2019-11-06T20:14:11.685504  [86273.903868]  kthread+0x105/0x140
2019-11-06T20:14:11.685506  [86273.903872]  ? __thread_exit+0x20/0x20 [spl]
2019-11-06T20:14:11.685514  [86273.903875]  ? kthread_destroy_worker+0x50/0x50
2019-11-06T20:14:11.685517  [86273.903877]  ret_from_fork+0x35/0x40
2019-11-06T20:14:11.692080 kern.err isw1-bfyii-747 kernel: [86273.904231] INFO: task zfs:7227 blocked for more than 120 seconds.
2019-11-06T20:14:11.692100 kern.err isw1-bfyii-747 kernel: [86273.910440]       Tainted: P        W  OE    4.15.0-54-generic #58~16.04.1-Ubuntu
2019-11-06T20:14:11.699578 kern.err isw1-bfyii-747 kernel: [86273.917948] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
2019-11-06T20:14:11.707635 kern.info isw1-bfyii-747 kernel: [86273.925804] zfs             D    0  7227   7225 0x00000080
2019-11-06T20:14:11.707655  [86273.925806] Call Trace:
2019-11-06T20:14:11.707658  [86273.925809]  __schedule+0x3d6/0x8b0
2019-11-06T20:14:11.707659  [86273.925812]  schedule+0x36/0x80
2019-11-06T20:14:11.707661  [86273.925817]  cv_wait_common+0x101/0x140 [spl]
2019-11-06T20:14:11.707662  [86273.925820]  ? wait_woken+0x80/0x80
2019-11-06T20:14:11.707664  [86273.925825]  __cv_wait+0x15/0x20 [spl]
2019-11-06T20:14:11.707666  [86273.925871]  txg_wait_synced+0x88/0xd0 [zfs]
2019-11-06T20:14:11.707667  [86273.925921]  dsl_sync_task+0x17b/0x250 [zfs]
2019-11-06T20:14:11.707669  [86273.925966]  ? add_ds_to_guidmap+0xf0/0xf0 [zfs]
2019-11-06T20:14:11.707670  [86273.926003]  ? list_remove.isra.5+0x10/0x10 [zfs]
2019-11-06T20:14:11.707672  [86273.926043]  ? add_ds_to_guidmap+0xf0/0xf0 [zfs]
2019-11-06T20:14:11.707748  [86273.926079]  ? list_remove.isra.5+0x10/0x10 [zfs]
2019-11-06T20:14:11.707751  [86273.926112]  dmu_recv_begin+0x177/0x1d0 [zfs]
2019-11-06T20:14:11.707753  [86273.926165]  zfs_ioc_recv_impl+0xe1/0xa00 [zfs]
2019-11-06T20:14:11.707974  [86273.926215]  zfs_ioc_recv_new+0x362/0x400 [zfs]
2019-11-06T20:14:11.707986  [86273.926223]  ? spl_kmem_alloc_impl+0xc1/0x1b0 [spl]
2019-11-06T20:14:11.707988  [86273.926227]  ? spl_vmem_alloc+0x19/0x20 [spl]
2019-11-06T20:14:11.707990  [86273.926237]  ? nv_alloc_sleep_spl+0x1f/0x30 [znvpair]
2019-11-06T20:14:11.707991  [86273.926242]  ? nv_mem_zalloc.isra.0+0x30/0x40 [znvpair]
2019-11-06T20:14:11.707993  [86273.926246]  ? nvlist_xalloc+0x6c/0x90 [znvpair]
2019-11-06T20:14:11.708000  [86273.926251]  ? nvlist_alloc+0x27/0x30 [znvpair]
2019-11-06T20:14:11.708004  [86273.926295]  zfsdev_ioctl+0x2b7/0x5d0 [zfs]
2019-11-06T20:14:11.708005  [86273.926305]  do_vfs_ioctl+0xa4/0x600
2019-11-06T20:14:11.708008  [86273.926313]  ? __audit_syscall_entry+0xac/0x100
2019-11-06T20:14:11.708009  [86273.926319]  ? syscall_trace_enter+0x1d6/0x2f0
2019-11-06T20:14:11.708011  [86273.926322]  SyS_ioctl+0x79/0x90
2019-11-06T20:14:11.708014  [86273.926324]  do_syscall_64+0x73/0x130
2019-11-06T20:14:11.708016  [86273.926326]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
2019-11-06T20:14:11.708018  [86273.926335] RIP: 0033:0x7f2f7b272f47
2019-11-06T20:14:11.708020  [86273.926338] RSP: 002b:00007fff30fe91f8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
2019-11-06T20:14:11.708021  [86273.926348] RAX: ffffffffffffffda RBX: 000000000000000c RCX: 00007f2f7b272f47
2019-11-06T20:14:11.708023  [86273.926349] RDX: 00007fff30fe9210 RSI: 0000000000005a46 RDI: 0000000000000005
2019-11-06T20:14:11.708025  [86273.926350] RBP: 00007fff30fe9210 R08: 00007f2f7b53b038 R09: 0000000000000000
2019-11-06T20:14:11.708027  [86273.926351] R10: 00007f2f7b53ab78 R11: 0000000000000246 R12: 00007fff30fec840
2019-11-06T20:14:11.708028  [86273.926353] R13: 0000000000005a46 R14: 0000000000000005 R15: 00000000021fdb80
2019-11-06T20:14:11.708030 kern.err isw1-bfyii-747 kernel: [86273.926362] INFO: task zfs:25240 blocked for more than 120 seconds.
2019-11-06T20:14:11.714291 kern.err isw1-bfyii-747 kernel: [86273.932654]       Tainted: P        W  OE    4.15.0-54-generic #58~16.04.1-Ubuntu
2019-11-06T20:14:11.721797 kern.err isw1-bfyii-747 kernel: [86273.940160] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
2019-11-06T20:14:11.729691 kern.info isw1-bfyii-747 kernel: [86273.948012] zfs             D    0 25240  25238 0x80000080
2019-11-06T20:14:11.729710  [86273.948014] Call Trace:
2019-11-06T20:14:11.729712  [86273.948018]  __schedule+0x3d6/0x8b0
2019-11-06T20:14:11.729714  [86273.948045]  ? abd_to_buf+0x12/0x20 [zfs]
2019-11-06T20:14:11.729715  [86273.948073]  ? arc_buf_is_shared.isra.15+0x35/0x50 [zfs]
2019-11-06T20:14:11.729717  [86273.948085]  schedule+0x36/0x80
2019-11-06T20:14:11.729719  [86273.948095]  cv_wait_common+0x101/0x140 [spl]
2019-11-06T20:14:11.729785  [86273.948106]  ? wait_woken+0x80/0x80
2019-11-06T20:14:11.729787  [86273.948112]  __cv_wait+0x15/0x20 [spl]
2019-11-06T20:14:11.729789  [86273.948153]  rrw_enter_read_impl+0x4a/0x100 [zfs]
2019-11-06T20:14:11.729791  [86273.948199]  rrw_enter_read+0x13/0x20 [zfs]
2019-11-06T20:14:11.736697  [86273.948246]  rrw_enter+0x1d/0x20 [zfs]
2019-11-06T20:14:11.736716  [86273.948287]  dsl_pool_config_enter+0x1d/0x20 [zfs]         <==== blocked on dp_config_rwlock R
2019-11-06T20:14:11.736718  [86273.948321]  dmu_objset_open_impl+0x7a3/0x820 [zfs]        <==== holding ds_opening_lock
2019-11-06T20:14:11.736720  [86273.948363]  ? do_raw_spin_unlock+0x9/0x10 [zfs]
2019-11-06T20:14:11.736721  [86273.948397]  dmu_objset_from_ds+0xeb/0x190 [zfs]
2019-11-06T20:14:11.736723  [86273.948431]  ? dmu_objset_evict_dbufs+0x18c/0x1a0 [zfs]
2019-11-06T20:14:11.736725  [86273.948477]  zfs_resume_fs+0x75/0x2a0 [zfs]
2019-11-06T20:14:11.736726  [86273.948525]  ? zfsvfs_teardown+0x1ff/0x320 [zfs]
2019-11-06T20:14:11.736728  [86273.948570]  zfs_ioc_recv_impl+0x7ce/0xa00 [zfs]
2019-11-06T20:14:11.736729  [86273.948617]  zfs_ioc_recv_new+0x362/0x400 [zfs]
2019-11-06T20:14:11.736730  [86273.948623]  ? spl_kmem_alloc_impl+0xc1/0x1b0 [spl]
2019-11-06T20:14:11.736732  [86273.948630]  ? spl_vmem_alloc+0x19/0x20 [spl]
2019-11-06T20:14:11.736734  [86273.948634]  ? nv_alloc_sleep_spl+0x1f/0x30 [znvpair]
2019-11-06T20:14:11.736736  [86273.948639]  ? nv_mem_zalloc.isra.0+0x30/0x40 [znvpair]
2019-11-06T20:14:11.736737  [86273.948643]  ? nvlist_xalloc+0x6c/0x90 [znvpair]
2019-11-06T20:14:11.736739  [86273.948647]  ? nvlist_alloc+0x27/0x30 [znvpair]
2019-11-06T20:14:11.736740  [86273.948690]  zfsdev_ioctl+0x2b7/0x5d0 [zfs]
2019-11-06T20:14:11.736742  [86273.948695]  do_vfs_ioctl+0xa4/0x600
2019-11-06T20:14:11.736744  [86273.948698]  ? __audit_syscall_entry+0xac/0x100
2019-11-06T20:14:11.736745  [86273.948703]  ? syscall_trace_enter+0x1d6/0x2f0
2019-11-06T20:14:11.736747  [86273.948705]  SyS_ioctl+0x79/0x90
2019-11-06T20:14:11.736748  [86273.948707]  do_syscall_64+0x73/0x130
2019-11-06T20:14:11.736749  [86273.948709]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
2019-11-06T20:14:11.736757  [86273.948712] RIP: 0033:0x7f6e6cb8ef47
2019-11-06T20:14:11.736762  [86273.948712] RSP: 002b:00007ffcbb1bcf98 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
2019-11-06T20:14:11.736765  [86273.948714] RAX: ffffffffffffffda RBX: 000000000000000c RCX: 00007f6e6cb8ef47
2019-11-06T20:14:11.736789  [86273.948716] RDX: 00007ffcbb1bcfb0 RSI: 0000000000005a46 RDI: 0000000000000005
2019-11-06T20:14:11.736792  [86273.948717] RBP: 00007ffcbb1bcfb0 R08: 0000000000fc3000 R09: 0000000000000000
2019-11-06T20:14:11.736798  [86273.948718] R10: 0000000000fc3000 R11: 0000000000000246 R12: 00007ffcbb1c05e0
2019-11-06T20:14:11.736800  [86273.948719] R13: 0000000000005a46 R14: 0000000000000005 R15: 0000000000f42200
2019-11-06T20:14:11.736803 kern.err isw1-bfyii-747 kernel: [86273.948722] INFO: task zfs:27387 blocked for more than 120 seconds.
2019-11-06T20:14:11.736805 kern.err isw1-bfyii-747 kernel: [86273.955013]       Tainted: P        W  OE    4.15.0-54-generic #58~16.04.1-Ubuntu
2019-11-06T20:14:11.744148 kern.err isw1-bfyii-747 kernel: [86273.962518] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
2019-11-06T20:14:11.752217 kern.info isw1-bfyii-747 kernel: [86273.970376] zfs             D    0 27387  27385 0x00000080
2019-11-06T20:14:11.752236  [86273.970378] Call Trace:
2019-11-06T20:14:11.752238  [86273.970381]  __schedule+0x3d6/0x8b0
2019-11-06T20:14:11.752240  [86273.970384]  schedule+0x36/0x80
2019-11-06T20:14:11.752241  [86273.970389]  cv_wait_common+0x101/0x140 [spl]
2019-11-06T20:14:11.752242  [86273.970392]  ? wait_woken+0x80/0x80
2019-11-06T20:14:11.752244  [86273.970396]  __cv_wait+0x15/0x20 [spl]
2019-11-06T20:14:11.752246  [86273.970439]  rrw_enter_read_impl+0x4a/0x100 [zfs]
2019-11-06T20:14:11.752247  [86273.970487]  rrw_enter_read+0x13/0x20 [zfs]
2019-11-06T20:14:11.752249  [86273.970537]  rrw_enter+0x1d/0x20 [zfs]
2019-11-06T20:14:11.752250  [86273.970578]  dsl_pool_config_enter+0x1d/0x20 [zfs]
2019-11-06T20:14:11.752252  [86273.970622]  dsl_pool_hold+0x51/0x80 [zfs]
2019-11-06T20:14:11.752307  [86273.970662]  dmu_objset_hold+0x35/0xb0 [zfs]
2019-11-06T20:14:11.752310  [86273.970667]  ? __kmalloc+0x17d/0x220
2019-11-06T20:14:11.752312  [86273.970711]  zfs_ioc_objset_stats+0x30/0x80 [zfs]
2019-11-06T20:14:11.752314  [86273.970724]  ? strdup+0x51/0x60 [spl]
2019-11-06T20:14:11.758711  [86273.970771]  zfsdev_ioctl+0x54a/0x5d0 [zfs]
2019-11-06T20:14:11.758729  [86273.970776]  do_vfs_ioctl+0xa4/0x600
2019-11-06T20:14:11.758731  [86273.970779]  ? __audit_syscall_entry+0xac/0x100
2019-11-06T20:14:11.758733  [86273.970783]  ? syscall_trace_enter+0x1d6/0x2f0
2019-11-06T20:14:11.758734  [86273.970786]  SyS_ioctl+0x79/0x90
2019-11-06T20:14:11.758736  [86273.970788]  do_syscall_64+0x73/0x130
2019-11-06T20:14:11.758738  [86273.970790]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
2019-11-06T20:14:11.758740  [86273.970792] RIP: 0033:0x7fc21d5ddf47
2019-11-06T20:14:11.758741  [86273.970793] RSP: 002b:00007ffdaabe9988 EFLAGS: 00000206 ORIG_RAX: 0000000000000010
2019-11-06T20:14:11.758743  [86273.970794] RAX: ffffffffffffffda RBX: 00007ffdaabe99b0 RCX: 00007fc21d5ddf47
2019-11-06T20:14:11.758744  [86273.970795] RDX: 00007ffdaabe99b0 RSI: 0000000000005a12 RDI: 0000000000000003
2019-11-06T20:14:11.758746  [86273.970796] RBP: 0000000002472090 R08: 000000000000ffff R09: 00007ffdaabf0c69
2019-11-06T20:14:11.758748  [86273.970797] R10: 000000000000053f R11: 0000000000000206 R12: 0000000002472090
2019-11-06T20:14:11.758750  [86273.970799] R13: 00007ffdaabf0c50 R14: 0000000002472090 R15: 00007ffdaabf0850
2019-11-06T20:14:11.758751 kern.err isw1-bfyii-747 kernel: [86273.970802] INFO: task zfs:31561 blocked for more than 120 seconds.
2019-11-06T20:14:11.758752 kern.err isw1-bfyii-747 kernel: [86273.977094]       Tainted: P        W  OE    4.15.0-54-generic #58~16.04.1-Ubuntu
2019-11-06T20:14:11.766191 kern.err isw1-bfyii-747 kernel: [86273.984600] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
2019-11-06T20:14:11.774304 kern.info isw1-bfyii-747 kernel: [86273.992458] zfs             D    0 31561  31545 0x00000080
2019-11-06T20:14:11.774323  [86273.992461] Call Trace:
2019-11-06T20:14:11.774325  [86273.992464]  __schedule+0x3d6/0x8b0
2019-11-06T20:14:11.774327  [86273.992466]  schedule+0x36/0x80
2019-11-06T20:14:11.774328  [86273.992472]  cv_wait_common+0x101/0x140 [spl]
2019-11-06T20:14:11.774329  [86273.992475]  ? wait_woken+0x80/0x80
2019-11-06T20:14:11.774331  [86273.992479]  __cv_wait+0x15/0x20 [spl]
2019-11-06T20:14:11.774333  [86273.992522]  rrw_enter_read_impl+0x4a/0x100 [zfs]
2019-11-06T20:14:11.774334  [86273.992570]  rrw_enter_read+0x13/0x20 [zfs]
2019-11-06T20:14:11.774336  [86273.992621]  rrw_enter+0x1d/0x20 [zfs]
2019-11-06T20:14:11.774337  [86273.992663]  dsl_pool_config_enter+0x1d/0x20 [zfs]
2019-11-06T20:14:11.774339  [86273.992708]  dsl_pool_hold+0x51/0x80 [zfs]
2019-11-06T20:14:11.774393  [86273.992749]  dmu_objset_hold+0x35/0xb0 [zfs]
2019-11-06T20:14:11.774396  [86273.992752]  ? __kmalloc+0x17d/0x220
2019-11-06T20:14:11.774398  [86273.992797]  zfs_ioc_objset_stats+0x30/0x80 [zfs]
2019-11-06T20:14:11.774401  [86273.992810]  ? strdup+0x51/0x60 [spl]
2019-11-06T20:14:11.776020  [86273.992858]  zfsdev_ioctl+0x54a/0x5d0 [zfs]
2019-11-06T20:14:11.776038  [86273.992862]  do_vfs_ioctl+0xa4/0x600
2019-11-06T20:14:11.776039  [86273.992865]  ? __audit_syscall_entry+0xac/0x100
2019-11-06T20:14:11.776041  [86273.992869]  ? syscall_trace_enter+0x1d6/0x2f0
2019-11-06T20:14:11.776042  [86273.992872]  SyS_ioctl+0x79/0x90
2019-11-06T20:14:11.776043  [86273.992874]  do_syscall_64+0x73/0x130
2019-11-06T20:14:11.776045  [86273.992876]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
2019-11-06T20:14:11.776046  [86273.992878] RIP: 0033:0x7fc67d63cf47
2019-11-06T20:14:11.776047  [86273.992879] RSP: 002b:00007fffcecd55f8 EFLAGS: 00000202 ORIG_RAX: 0000000000000010
2019-11-06T20:14:11.776049  [86273.992881] RAX: ffffffffffffffda RBX: 00007fffcecd5620 RCX: 00007fc67d63cf47
2019-11-06T20:14:11.776050  [86273.992882] RDX: 00007fffcecd5620 RSI: 0000000000005a12 RDI: 0000000000000003
2019-11-06T20:14:11.776052  [86273.992883] RBP: 0000000000801090 R08: 000000000000ffff R09: 00007fffcecdc8d9
2019-11-06T20:14:11.776053  [86273.992884] R10: 000000000000053f R11: 0000000000000202 R12: 0000000000801090
2019-11-06T20:14:11.776055  [86273.992885] R13: 00007fffcecdc8c0 R14: 0000000000801090 R15: 00007fffcecdc4c0

```

### PR DESCRIPTION
**Pull request by ahrens**
### Motivation and Context

The normal lock order is that the dp_config_rwlock must be held before
the ds_opening_lock.  For example, dmu_objset_hold() does this.
However, dmu_objset_open_impl() is called with the ds_opening_lock held,
and if the dp_config_rwlock is not already held, it will attempt to
acquire it.  This may lead to deadlock, since the lock order is
reversed.

Looking at all the callers of dmu_objset_open_impl() (which is
principally the callers of dmu_objset_from_ds()), almost all callers
already have the dp_config_rwlock.  However, there are a few places in
the send and receive code paths that do not.  For example:
dsl_crypto_populate_key_nvlist, send_cb, dmu_recv_stream,
receive_write_byref, redact_traverse_thread.

Closes #9662

### Description

This commit resolves the problem by requiring all callers ot
dmu_objset_from_ds() to hold the dp_config_rwlock.  In most cases, the
code has been restructured such that we call dmu_objset_from_ds()
earlier on in the send and receive processes, when we already have the
dp_config_rwlock, and save the objset_t until we need it in the middle
of the send or receive (similar to what we already do with the
dsl_dataset_t).  Thus we do not need to acquire the dp_config_rwlock in
many new places.

I also cleaned up code in dmu_redact_snap() and send_traverse_thread().

### How Has This Been Tested?

test suite

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/os/linux/zfs/zfs_vfsops.c [hunk 1]
```diff
@@ -1804,7 +1804,10 @@ zfs_resume_fs(zfsvfs_t *zfsvfs, dsl_dataset_t *ds)
 	objset_t *os;
 	VERIFY3P(ds->ds_owner, ==, zfsvfs);
 	VERIFY(dsl_dataset_long_held(ds));
+	dsl_pool_t *dp = spa_get_dsl(dsl_dataset_get_spa(ds));
+	dsl_pool_config_enter(dp, FTAG);
```
Comment (PaulZ-98) [inline module/os/linux/zfs/zfs_vfsops.c]: Is it worth adding 
```
ASSERT(!dsl_pool_config_held(dp));
```
before dsl_pool_config_enter(..)?

File: module/os/linux/zfs/zfs_vfsops.c [hunk 2]
```diff
@@ -1895,7 +1898,10 @@ zfs_end_fs(zfsvfs_t *zfsvfs, dsl_dataset_t *ds)
...
```
Comment (PaulZ-98) [inline module/os/linux/zfs/zfs_vfsops.c]: Same question.

**Comment by freqlabs** [comment]
> @freqlabs I wanted to make sure you saw this. After this is merged you'll want to make similar minor updates to the FreeBSD `zfs_resume_fs` and `zfs_end_fs` functions.

Thanks, I appreciate the heads-up.

File: module/os/linux/zfs/zfs_vfsops.c (hunk 1 above)
Comment (ahrens) [reply module/os/linux/zfs/zfs_vfsops.c]: dsl_pool_config_enter() already does that, so I don't think that's needed.
