### PR TITLE
Optionally skip zil_close during zvol_create_minor_impl

### LINKED ISSUE #13999: Importing a degraded pool with zvols is extremely slow
### System information
Type | Version/Name
 --- | ---
Distribution Name	| 
Distribution Version	|
Kernel Version	| FreeBSD 13.1-RELEASE
Architecture	| amd64
OpenZFS Version	| zfs-2.1.4-FreeBSD_g52bad4f23 zfs-kmod-2.1.4-FreeBSD_g52bad4f23

### Describe the problem you're observing

I have a degraded pool with about 1000 zvols.  Importing this pool takes more than an hour.  Procstat shows the following stack trace for most of that time:
```
mi_switch+0xc2
_cv_wait+0x113
txg_wait_synced_impl+0xb9
txg_wait_synced+0xb
zil_close+0xdf
zvol_create_minor_impl+0x67c
zvol_create_minors_recursive+0xf5
spa_import+0x718
zfs_ioc_pool_import+0xb0
zfsdev_ioctl_common+0x548
zfsdev_ioctl+0x143
devfs_ioctl+0xc6
vn_ioctl+0x1a4
devfs_ioctl_f+0x1e
kern_ioctl+0x25b
sys_ioctl+0xf1
amd64_syscall+0x10c
fast_syscall_common+0xf8 
```
Both dtrace and `find /dev/zvol -type c | wc` show that `zvol_create_minor_impl` can take up to 15s to create a single zvol.  At the same time, the `zfs-dbgmsg` dtrace probe shows plenty of activity like this:
```
dsl_scan.c:2451:dsl_scan_visitds(): scanned dataset 471355 (<POOL>/<DATASET>@<SNAP>) with min=2694762 max=2694782; suspending=0
```
So my theory is that the resilver is blocking transactions from syncing for several seconds at a time, which holds up `zil_close`.  That happens even though there shouldn't be any zil entries for these zvols, as they haven't been used for a long time.

### Possible solution

Would it be possible to safely skip `zil_close`, or skip the `txg_wait_synced` within it, if there were no entries to replay in `zil_replay`?

### Describe how to reproduce the problem

I can very easily reproduce the problem on a healthy, already-imported pool just by trying to create a new zvol while user writes are in progress.  Run these two commands in different terminals:
```
sudo dd if=/dev/random bs=16k of=/testpool/randfile.concurrent2
```
and
```
time sudo zfs create -V 64m -s testpool/zvoltest/vol.21
```
The `zfs create` command by itself typically takes less than one second.  But while `dd` is running it can take more than a minute.  And for much of that time it has a similar stack trace as above:
```
mi_switch+0x157
sleepq_switch+0x107
_cv_wait+0x166
txg_wait_synced_impl+0x288
txg_wait_synced+0x29
zil_close+0x2c3
zvol_os_create_minor+0x9ca
zvol_create_minor+0x7f
dmu_objset_create+0xfe
zfs_ioc_create+0x497
zfsdev_ioctl_common+0x5da
zfsdev_ioctl+0x1e5
devfs_ioctl+0xcd
vn_ioctl+0x131
devfs_ioctl_f+0x1e
kern_ioctl+0x202
sys_ioctl+0x12a
amd64_syscall+0x12e 
```

### PR DESCRIPTION
**Pull request by asomers**
If there were no zil entries to replay, skip zil_close.  zil_close waits for a transaction to sync.  That can take several seconds, for example during pool import of a resilvering pool.  Skipping zil_close can cut the time for "zpool import" from 2 hours to 45 seconds on a resilvering pool with a thousand zvols.

Closes #13999
Sponsored-by:	Axcient
Signed-off-by:	Alan Somers <asomers@gmail.com>

### Motivation and Context
Importing a degraded pool with a large number of zvols is extremely slow, due to the need to sync a transaction for each zvol.
Issue #13999 

### Description
Skips zil_close (thus skips syncing a transaction) if the zvol had no zil entries to replay.

### How Has This Been Tested?

Manually tested on FreeBSD 13.1 amd64, using a pool made of 44 HDDs and two SSD slogs that was busy resilvering a spare and containing 992 zvols.  The patch reduced the import time from 2 hours to 45 seconds.

### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by ryao — APPROVED** [review]

**Comment by freqlabs** [comment]
This does seem to work. Could you apply the zvol_os.c change for Linux as well please?

**Comment by ryao** [comment]
@freqlabs Nice catch. I had missed that when reviewing this. :/

**Comment by asomers** [comment]
Ok, I'll apply the change to Linux on Monday.  I can't test it, though.

**Comment by ryao** [comment]
As long as it passes the buildbot, it should be okay.

**Review by freqlabs — APPROVED** [review]

**Comment by asomers** [comment]
Squashed.

File: module/os/freebsd/zfs/zvol_os.c [hunk 1]
```diff
@@ -1490,11 +1491,12 @@ zvol_os_create_minor(const char *name)
...
-			zil_destroy(zv->zv_zilog, B_FALSE);
+			replayed_zil = zil_destroy(zv->zv_zilog, B_FALSE);
 		else
-			zil_replay(os, zv, zvol_replay_vector);
+			replayed_zil = zil_replay(os, zv, zvol_replay_vector);
 	}
-	zil_close(zv->zv_zilog);
+	if (replayed_zil)
+		zil_close(zv->zv_zilog);
 	zv->zv_zilog = NULL;
```
Comment (amotin) [inline module/os/freebsd/zfs/zvol_os.c:1500]: So you are not closing zil but clearing zv->zv_zilog so that it was open again?  zil_open() seems to be quite invariant now, but wouldn't it be better to leave zv->zv_zilog as-is?  I may be wrong, haven't looked too deep.

Comment (asomers) [reply module/os/freebsd/zfs/zvol_os.c:1500]: `zil_open` doesn't actually have any side effects.  All it does is return a pointer to that zilog_t field, and set its callback memebers.  So simply nulling it out doesn't leak anything.  I didn't consider the possibility of not nulling it out, because the existing code always nulls it.

Comment (amotin) [reply module/os/freebsd/zfs/zvol_os.c:1500]: I agree that second open is not a problem now, but still not good.  Also actual zil_close() is not so small, it it even to be called, and I am not sure how much invariant it is.

Comment (amotin) [reply module/os/freebsd/zfs/zvol_os.c:1500]: I've found what looks like identical logic in zvol_shutdown_zv().  So while I still see it as ugly, I have no objections.

**Review by amotin — APPROVED** [review]

**Comment by asomers** [comment]
Thanks all.
