### PR TITLE
FreeBSD: Remove stray debug printf

### LINKED ISSUE #14286: Stray debug printf on FreeBSD
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| 13.1-RELEASE-p5
Kernel Version	| 13.1-RELEASE-p3
Architecture	| amd64
OpenZFS Version	| zfs-2.1.4-FreeBSD_g52bad4f23

### Describe the problem you're observing

While working on porting podman and buildah to FreeBSD, I have noticed many messages logged on the console that look like this:
```
len 4 vecnum: 126 sizeof (zfs_cmd_t) 4528
```
After debugging this, I discovered that this happens when something tries to set non-blocking i/o on a ```/dev/zfs``` filedescriptor which translates to a ```FIONBIO``` ioctl.

The zfs storage layer in for buildah and podman tries to detect whether zfs is available by opening /dev/zfs. The golang runtime libraries unconditionally try to set the descriptor into non-blocking mode causing the error message.

I can work around this in [containers/storage](https://github.com/containers/storage) but it seems to me that the FreeBSD ZFS port should not print this message to console but instead return a suitable error. Currently it returns ```EINVAL``` after the printf which seems reasonable.

### Describe how to reproduce the problem

On FreeBSD-13.1 or later, install the buildah package and run:
```
# buildah from quay.io/dougrabson/freebsd-minimal:13
```
On the system console, the ```len 4 vecnum...``` message quoted above appears.

### Include any warning/errors/backtraces from the system logs
```
len 4 vecnum: 126 sizeof (zfs_cmd_t) 4528
```

### PR DESCRIPTION
**Pull request by dfr**
Fixes #14286.

Signed-off-by: Doug Rabson <dfr@rabson.org>

### Motivation and Context
This removes a cryptic console printf generated when an application tries to set non-blocking i/o on a /dev/zfs file descriptor. See #14284 for a little more context.
### Description
This change simply removes the printf.

### How Has This Been Tested?
Built a recent FreeBSD-14-current kernel with this change and verified that the application triggering this printf no longer causes console logging side effects.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by freqlabs — APPROVED** [review]

**Review by amotin — COMMENTED** [review]
I would remove braces also.  And move uaddr = (void *)zp->zfs_cmd; down after the check.

**Review by amotin — APPROVED** [review]

File: module/os/freebsd/zfs/kmod_core.c [hunk 1]
```diff
@@ -133,18 +133,15 @@ zfsdev_ioctl(struct cdev *dev, ulong_t zcmd, caddr_t arg, int flag,
...
 #endif
 
-	if (len != sizeof (zfs_iocparm_t)) {
-		printf("len %d vecnum: %d sizeof (zfs_cmd_t) %ju\n",
-		    len, vecnum, (uintmax_t)sizeof (zfs_cmd_t));
+	if (len != sizeof (zfs_iocparm_t))
 		return (EINVAL);
-	}
 
+	uaddr = (void *)zp->zfs_cmd;
```
Comment (ryao) [inline module/os/freebsd/zfs/kmod_core.c:144]: Why was this moved to a new line?

Comment (amotin) [reply module/os/freebsd/zfs/kmod_core.c:144]: Because before the len is checked, zp may theoretically point to a single byte.

Comment (dfr) [reply module/os/freebsd/zfs/kmod_core.c:144]: I hadn't even noticed that - good catch @amotin

**Review by freqlabs — APPROVED** [review]

**Review by ryao — APPROVED** [review]
