### PR TITLE
Report dnodes with faulty bonuslen

### LINKED ISSUE #12720: Unable to receive encrypted raw send
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Debian
Distribution Version	| bookworm/testing
Kernel Version	| 5.14.0-2
Architecture	| amd64
OpenZFS Version	| 2.0.6-1

### Describe the problem you're observing
I am trying to transfer an encrypted dataset to another pool using a raw send. Partially through this send, the receive side fails with an unclear error message.

The receiving system is also on 2.0.6, running Debian Bullseye on kernel 5.10.0-9.

Here are the commands that reproduce the issue reliably:

```
source# zfs send -Lcw -v tank/enc/private@zfs-auto-snap_monthly-2020-07-01-1152 | mbuffer -O 10.200.200.2:13337

dest# mbuffer -I 13337 | zfs receive -uv archive/dwight/tank/private
```

The dataset is about 1.3TB; at the 360GB mark, the receive reliably fails with the following error:
```
cannot receive new filesystem stream: invalid backup stream
```

Oddly, if you provide the -s flag to the recv (enable resume support) the error changes to this:
```
cannot receive new filesystem stream: kernel modules must be upgraded to receive this stream.
```

I tried sending the stream through zstreamdump, which did not complain. I also maximized debug logging, generated a resume token and tried resuming (right at whatever transaction caused the recv to fail), which generated [these messages](https://gist.github.com/putnam/49c1f0a0cfb002443a1ef59f83dbb392) (gist). It's noisy; see line 1786 for when receive_object failed.

I don't know the exact steps to reproduce this problem with another dataset. Originally this dataset was on another pool in an unencrypted state. It was sent into the encrypted pool just fine, then I wanted to raw-send the newly-encrypted dataset offsite to another pool. It is at this point that I ran into this show-stopper.

See also the gist below which is the output of ```zstreamdump -vvv``` on the resumed send.

https://gist.github.com/putnam/3a467fdab6fe96ca048264c1bcd8a4b0

UPDATE: In the discussion below, I was able to shrink the affected dataset down to a ~70MB repro. See [this comment](https://github.com/openzfs/zfs/issues/12720#issuecomment-964677615) for an attachment.

### PR DESCRIPTION
**Pull request by gamanakis**
### Motivation and Context
Closes #12720.

In files created/modified before 4254acb there may be a corruption of
xattrs which is not reported during scrub and normal send/receive. It
manifests only as an error when raw sending/receiving. This is because
currently only the raw receive path checks for discrepancies between the
bonus length and the spill pointer flag. 

### Description
In case we encounter a dnode whose bonus length is greater than the
predicted one, we should report an error. Modify in this regard
dnode_sync() with an assertion at the end, dump_dnode() to error out,
and dsl_scan_recurse() to report errors during a scrub. Also added a
test to verify spill blocks are sent correctly in a raw send.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by rincebrain** [comment]
An error on scrub feels kind of unfortunate, since it's not like there's a way to recover short of rewriting your data...I can't think of a better alternative though.

File: module/zfs/dsl_scan.c [hunk 1]
```diff
@@ -1827,6 +1827,13 @@ dsl_scan_recurse(dsl_scan_t *scn, dsl_dataset_t *ds, dmu_objset_type_t ostype,
 
 	ASSERT(!BP_IS_REDACTED(bp));
 
+	if (dnp != NULL &&
+	    dnp->dn_bonuslen > DN_MAX_BONUS_LEN(dnp)) {
+		scn->scn_phys.scn_errors++;
+		spa_log_error(dp->dp_spa, zb);
+		return (SET_ERROR(EINVAL));
+	}
```
Comment (behlendorf) [inline module/zfs/dsl_scan.c:1835]: Detecting it and logging it seems like the most reasonable thing to do for this very unlikely case.  I think we probably could recalculate the correct size and re-dirty the dnode to fix it, but I don't think we really want to extend scrub in that way.  Let's at least add a comment mentioning how this impossible state might occur.

It'd probably make sense to update `zstreamdump` to detect this issue and at least print a warning.

Comment (gamanakis) [reply module/zfs/dsl_scan.c:1841]: I think we are not able to correct it at all, since we don't know if it indeed has a spill block pointer.

**Comment by gamanakis** [comment]
2545ee4: Suggestions from @behlendorf, teach `zstream dump` to report a warning.

**Comment by gamanakis** [comment]
ce90548: fix typos in commit message

**Review by behlendorf — APPROVED** [review]

**Comment by gamanakis** [comment]
b2dfbd0: rebased to master
