### PR TITLE
Fix locale-specific time

### LINKED ISSUE #15878: Locale-specific time in trim status
### System information

Type | Version/Name
 --- | ---
Distribution Name	| FreeBSD
Distribution Version	| 14.0-STABLE
Kernel Version	| 14.0-STABLE
Architecture	| amd64
OpenZFS Version	| `zfs-2.2.2-FreeBSD_g494aaaed8`

### Describe the problem you're observing
In `zpool status -t`, trim status has its date in locale-specific format, like so:
```% zpool status -t
  pool: zroot
 state: ONLINE
  scan: scrub repaired 0B in 00:09:42 with 0 errors on Fri Feb  9 14:11:58 2024
config:

        NAME          STATE     READ WRITE CKSUM
        zroot         ONLINE       0     0     0
          nda0p4.eli  ONLINE       0     0     0  (100% trimmed, completed at пятница,  9 февраля 2024 г. 14:28:37)

errors: No known data errors
```

As seen above, trim completion date/time is in Russian while scrub date/time version is in English.

### Describe how to reproduce the problem

`LANG=ru_RU.UTF-8 zpool status -t`

### PR DESCRIPTION
**Pull request by part1zano**
### Motivation and Context

Fix #15878 
### Description

See the issue for details
### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: cmd/zpool/zpool_main.c [hunk 1]
```diff
@@ -2306,8 +2305,8 @@ print_status_trim(vdev_stat_t *vs, boolean_t verbose)
 				    100 / (vs->vs_trim_bytes_est + 1));
 			}
 
-			(void) localtime_r(&t, &zaction_ts);
-			(void) strftime(tbuf, sizeof (tbuf), "%c", &zaction_ts);
+			(void) ctime_r(&t, tbuf);
+			tbuf[24] = 0;
```
Comment (behlendorf) [inline cmd/zpool/zpool_main.c:2309]: From what I can gather `strftime` is recommended these days instead of `ctime` specifically because it's locale-sensitive. 

> ctime returns a pointer to static data and is not thread-safe. In addition, it modifies the static [tm](https://en.cppreference.com/w/c/chrono/tm) object which may be shared with [gmtime](https://en.cppreference.com/w/c/chrono/gmtime) and [localtime](https://en.cppreference.com/w/c/chrono/localtime). POSIX marks this function obsolete and recommends [strftime](https://en.cppreference.com/w/c/chrono/strftime) instead. The C standard also recommends [strftime](https://en.cppreference.com/w/c/chrono/strftime) instead of ctime and ctime_s because strftime is more flexible and locale-sensitive.  From https://en.cppreference.com/w/c/chrono/ctime

We even use `gettext()` here for the non-data portion but don't provide any translations for the english text.  Removing the locale awareness here seems like the wrong way to go, but I agree the current behavior is also quite undesirable.

I see there are also several other places which make the same assumptions.  If we're going to consider changing this, we'll want to at least be consistent.  Suggestions welcome.

Comment (glebius) [reply cmd/zpool/zpool_main.c:2309]: Originally I suggested Maxim to stay with strftime(), but use format that exactly matches LANG=C format for date instead of %c.

Comment (part1zano) [reply cmd/zpool/zpool_main.c:2309]: I couldn't find the specific format string for `LANG=C` in `man strftime`

Comment (glebius) [reply cmd/zpool/zpool_main.c:2309]: It is defined in the C documentation. C11 document  says:

`%c equivalent to ‘‘%a %b %e %T %Y’’.`

Comment (glebius) [reply cmd/zpool/zpool_main.c:2309]: Ah, but those will be substituted to nationalized names according to running locale. Seems like using ctime() is the most correct approach until ZFS tools are fully localized.

Comment (behlendorf) [reply cmd/zpool/zpool_main.c:2309]: It does seem like the least bad way to handle this for now is to use `ctime_r` in all of the places where `%c` is used with `strftime()`.  A quick grep of the source turned up four locations.  @part1zano can you update this PR to switch all of them.

```
cmd/zpool/zpool_main.c:		(void) strftime(tbuf, sizeof (tbuf), "%c", &zaction_ts);
cmd/zpool/zpool_main.c:		(void) strftime(tbuf, sizeof (tbuf), "%c", &zaction_ts);
lib/libzfs/libzfs_pool.c:	    strftime(timestr, 128, "%c", &t) != 0) {
lib/libzfs/libzfs_pool.c:	    strftime(timestr, 128, "%c", &t) != 0) {
```

Comment (part1zano) [reply cmd/zpool/zpool_main.c:2309]: @behlendorf 
Yep, I'm on it.

Comment (part1zano) [reply cmd/zpool/zpool_main.c:2309]: @behlendorf please take a look.

**Review by mcmilk — APPROVED** [review]

**Comment by mcmilk** [comment]
Some small commit message and the `Signed-off-by: Name <some-mail@example.com>` would be nice.

File: cmd/zpool/zpool_main.c (hunk 1 above)
Comment (part1zano) [reply cmd/zpool/zpool_main.c:2308]: @behlendorf please review

**Comment by part1zano** [comment]
Could someone (including, but not limited to @behlendorf ) please review this already?

**Comment by tonyhutter** [comment]
@part1zano sorry for the lack of response.  Your patch works for me:

Before:
```
$ LANG=ru_RU.UTF-8 ./zpool status -t
  pool: tank
 state: ONLINE
  scan: scrub repaired 0B in 00:00:00 with 0 errors on Thu Mar 28 15:03:39 2024
config:

	NAME          STATE     READ WRITE CKSUM
	tank          ONLINE       0     0     0
	  /tmp/file1  ONLINE       0     0     0  (100% trimmed, completed at Чт 28 мар 2024 15:02:54)
	  /tmp/file2  ONLINE       0     0     0  (100% trimmed, completed at Чт 28 мар 2024 15:02:54)
	  /tmp/file3  ONLINE       0     0     0  (100% trimmed, completed at Чт 28 мар 2024 15:02:54)
	  /tmp/file4  ONLINE       0     0     0  (100% trimmed, completed at Чт 28 мар 2024 15:02:54)
```


After
```
LANG=ru_RU.UTF-8 ./zpool status -t
  pool: tank
 state: ONLINE
  scan: scrub repaired 0B in 00:00:00 with 0 errors on Thu Mar 28 15:03:39 2024
config:

	NAME          STATE     READ WRITE CKSUM
	tank          ONLINE       0     0     0
	  /tmp/file1  ONLINE       0     0     0  (100% trimmed, completed at Thu Mar 28 15:02:54 2024)
	  /tmp/file2  ONLINE       0     0     0  (100% trimmed, completed at Thu Mar 28 15:02:54 2024)
	  /tmp/file3  ONLINE       0     0     0  (100% trimmed, completed at Thu Mar 28 15:02:54 2024)
	  /tmp/file4  ONLINE       0     0     0  (100% trimmed, completed at Thu Mar 28 15:02:54 2024)
```

**Review by tonyhutter — APPROVED** [review]

**Comment by part1zano** [comment]
> @part1zano sorry for the lack of response. Your patch works for me:
> 
> Before:
> 
> ```
> $ LANG=ru_RU.UTF-8 ./zpool status -t
>   pool: tank
>  state: ONLINE
>   scan: scrub repaired 0B in 00:00:00 with 0 errors on Thu Mar 28 15:03:39 2024
> config:
> 
> 	NAME          STATE     READ WRITE CKSUM
> 	tank          ONLINE       0     0     0
> 	  /tmp/file1  ONLINE       0     0     0  (100% trimmed, completed at Чт 28 мар 2024 15:02:54)
> 	  /tmp/file2  ONLINE       0     0     0  (100% trimmed, completed at Чт 28 мар 2024 15:02:54)
> 	  /tmp/file3  ONLINE       0     0     0  (100% trimmed, completed at Чт 28 мар 2024 15:02:54)
> 	  /tmp/file4  ONLINE       0     0     0  (100% trimmed, completed at Чт 28 мар 2024 15:02:54)
> ```
> 
> After
> 
> ```
> LANG=ru_RU.UTF-8 ./zpool status -t
>   pool: tank
>  state: ONLINE
>   scan: scrub repaired 0B in 00:00:00 with 0 errors on Thu Mar 28 15:03:39 2024
> config:
> 
> 	NAME          STATE     READ WRITE CKSUM
> 	tank          ONLINE       0     0     0
> 	  /tmp/file1  ONLINE       0     0     0  (100% trimmed, completed at Thu Mar 28 15:02:54 2024)
> 	  /tmp/file2  ONLINE       0     0     0  (100% trimmed, completed at Thu Mar 28 15:02:54 2024)
> 	  /tmp/file3  ONLINE       0     0     0  (100% trimmed, completed at Thu Mar 28 15:02:54 2024)
> 	  /tmp/file4  ONLINE       0     0     0  (100% trimmed, completed at Thu Mar 28 15:02:54 2024)
> ```

Great to see it works for you! Thanks for the approval! Could you kindly merge it since everything's ok?

**Comment by part1zano** [comment]
Since this has been approved by someone with write access, could someone please merge it?

**Comment by behlendorf** [comment]
@part1zano the formatting changes to `print_history_records()` break the `history_007_pos` test case.  Which is why most of the CI runs failed.  Given that the original format here is all numerical I don't think there's a need to convert this instance.  Plus if there are any other scripts out there parsing the history logs it's be nice not to break them.  Can you revert this hunk, then I think this should be good to go.

```
Test: /usr/share/zfs/zfs-tests/tests/functional/history/history_007_pos (run as root) [00:00] [FAIL]
19:05:05.60 /etc/sudoers:89:24: invalid operator "+=" for "exempt_group"
19:05:05.63 ASSERTION: Verify command history moves with migrated pool.
19:05:05.63 SUCCESS: mkdir -p /mnt/testdir/importdir.1110339
19:05:05.64 SUCCESS: cp /usr/share/zfs/zfs-tests/tests/functional/history/i386.orig_history.txt /mnt/testdir/importdir.1110339
19:05:05.64 SUCCESS: cp /usr/share/zfs/zfs-tests/tests/functional/history/i386.migratedpool.DAT.Z /mnt/testdir/importdir.1110339
19:05:05.89 SUCCESS: uncompress -f /mnt/testdir/importdir.1110339/i386.migratedpool.DAT.Z
19:05:06.06 SUCCESS: zpool import -d /mnt/testdir/importdir.1110339 history_pool
19:05:06.07 SUCCESS: eval TZ=US/Mountain zpool history history_pool | grep -v "^$" >/mnt/testdir/importdir.1110339/migrated_history.1110339
19:05:06.08 2,12c2,12
19:05:06.08 < Fri Oct 20 13:18:37 2006 zpool create history_pool /var/tmp/i386.migratedpool.DAT
19:05:06.08 < Fri Oct 20 13:18:37 2006 zfs create history_pool/fs
19:05:06.08 < Fri Oct 20 13:18:37 2006 zfs set compression=on history_pool/fs
19:05:06.08 < Fri Oct 20 13:18:37 2006 zfs set checksum=on history_pool
19:05:06.08 < Fri Oct 20 13:18:37 2006 zfs snapshot history_pool/fs@snap
19:05:06.08 < Fri Oct 20 13:18:37 2006 zfs clone history_pool/fs@snap history_pool/clone
19:05:06.08 < Fri Oct 20 13:18:37 2006 zfs promote history_pool/clone
19:05:06.08 < Fri Oct 20 13:18:37 2006 zfs promote history_pool/fs
19:05:06.08 < Fri Oct 20 13:18:37 2006 zfs destroy -r -R history_pool/fs
19:05:06.08 < Fri Oct 20 13:18:37 2006 zpool export history_pool
19:05:06.08 < Thu Apr  5 00:05:38 2007 zpool upgrade history_pool
19:05:06.08 ---
19:05:06.08 > 2006-10-20.13:18:37 zpool create history_pool /var/tmp/i386.migratedpool.DAT
19:05:06.08 > 2006-10-20.13:18:37 zfs create history_pool/fs
19:05:06.08 > 2006-10-20.13:18:37 zfs set compression=on history_pool/fs
19:05:06.08 > 2006-10-20.13:18:37 zfs set checksum=on history_pool
19:05:06.08 > 2006-10-20.13:18:37 zfs snapshot history_pool/fs@snap
19:05:06.08 > 2006-10-20.13:18:37 zfs clone history_pool/fs@snap history_pool/clone
19:05:06.08 > 2006-10-20.13:18:37 zfs promote history_pool/clone
19:05:06.08 > 2006-10-20.13:18:37 zfs promote history_pool/fs
19:05:06.08 > 2006-10-20.13:18:37 zfs destroy -r -R history_pool/fs
19:05:06.08 > 2006-10-20.13:18:37 zpool export history_pool
19:05:06.08 > 2007-04-05.00:05:38 zpool upgrade history_pool
```

**Comment by part1zano** [comment]
@behlendorf reverted!

**Review by behlendorf — APPROVED** [review]
