### PR TITLE
Fix history logging for `zpool create -t`

### LINKED ISSUE #18102: `zpool create -t` fails to emit `zpool history` entry for create command
### System information

Type | Version/Name
 --- | ---
Distribution Name	| NixOS
Distribution Version	| 25.11.20250830.d7600c7
Kernel Version	| 6.12.44
Architecture	| x86_64
OpenZFS Version	| zfs-2.3.4-1<br>zfs-kmod-2.3.4-1

### Describe the problem you're observing

in #16408, the reporter’s pool did not have an entry for the `zpool create` command in `zpool history`, even though that was in theory a special case that should never get evicted from the history. `zpool history -i` entries for `create pool version 5000` and `set feature@...` and so on were present as expected.

i ran into those exact symptoms today, just after creating a pool. `zpool history` was empty, with no entry for the `zpool create` command, but `zpool history -i` entries for `create pool version 5000` and `set feature@...` and so on were present as expected.

### Describe how to reproduce the problem

```
$ truncate -s 1G test.img
```

`zpool create` without `-t` works as expected:

```
$ zpool create test ./test.img
$ zpool history test
History for 'test':
2026-01-01.14:59:54 zpool create test ./test.img
```

`zpool create` with `-t` that *does not* rename the pool, also works as expected:

```
$ zpool destroy test
$ zpool create -t test test ./test.img
$ zpool history test
History for 'test':
2026-01-01.15:00:15 zpool create -t test test ./test.img
```

`zpool create` with `-t` that *does* rename the pool, fails to create the history entry:

```
$ zpool destroy test
$ zpool create -t test2 test ./test.img
$ zpool history test
cannot open 'test': no such pool
$ zpool history test2
History for 'test2':
```

`zpool history -i` still contains the internal entries as expected:

```
$ zpool history -i test2
2026-01-01.15:00:29 [txg:4] create pool version 5000; software version unknown; uts venus 6.12.44 #1-NixOS SMP PREEMPT_DYNAMIC Thu Aug 28 14:31:16 UTC 2025 x86_64
2026-01-01.15:00:29 [txg:4] set tname=test2
2026-01-01.15:00:29 [txg:4] set feature@async_destroy=enabled
[...]
2026-01-01.15:00:29 [txg:4] set feature@large_microzap=enabled
```

### PR DESCRIPTION
**Pull request by delan**
### Motivation and Context
`zpool create` is supposed to log the command to the new pool’s history, as a special record that never gets evicted from the ring buffer. but when you create a pool with `zpool create -t`, no such record is ever logged (#18102). that bug may be the cause of issues like #16408.

### Description
`zpool create -t` (83e9986f6eefdf0afc387f06407087bba3ead4e9) and `zpool import -t` (26b42f3f9d03f85cc7966dc2fe4dfe9216601b0e) are both designed to override the on-disk zpool property `name` with an in-core “temporary” name, but they work somewhat differently under the hood.

importing with a temporary name sets `spa->spa_import_flags |= ZFS_IMPORT_TEMP_NAME` in ZFS_IOC_POOL_IMPORT, which tells spa_write_cachefile() and spa_config_generate() to use the ZPOOL_CONFIG_POOL_NAME in `spa->spa_config` instead of `spa->spa_name`.

creating with a temporary name permanently(!) sets the internal zpool property `tname` (ZPOOL_PROP_TNAME) in the `zc->zc_nvlist_src` of ZFS_IOC_POOL_CREATE, which tells zfs_ioc_pool_create() (4ceb8dd6fdfdde3b6ac55cf52132858973fce9d0) and spa_create() to use that name instead of `zc->zc_name`, then sets `spa->spa_import_flags |= ZFS_IMPORT_TEMP_NAME` like an import.

but zfsdev_ioctl_common() fails to check for `tname` when saving the pool name to `zfs_allow_log_key`, so when we call ZFS_IOC_LOG_HISTORY, we call spa_open() on the wrong pool name and get ENOENT, so the logging silently fails.

this patch fixes #18102 by checking for `tname` in zfsdev_ioctl_common() like we do in zfs_ioc_pool_create().

### How Has This Been Tested?
tested using [quiz](https://github.com/robn/quiz), on linux 6.12.44:
```
$ ./quiz -k 6.12.44 -p zfs,ztest /usr/local/share/zfs/zfs-tests.sh -t tests/functional/cli_root/zpool_create/zpool_create_tempname.ksh
$ ./quiz -k 6.12.44 -p memdev,zfs /usr/local/zfs-18102-repro.sh
```

zfs-18102-repro.sh:
```
#!/bin/sh
set -euvx
zpool create -t test2 test /dev/quizm0
zpool history test2
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Quality assurance (non-breaking change which makes the code more robust against bugs)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/zfs_ioctl.c [hunk 1]
```diff
@@ -8151,10 +8151,23 @@ zfsdev_ioctl_common(uint_t vecnum, zfs_cmd_t *zc, int flag)
 	 * Can't use kmem_strdup() as we might truncate the string and
 	 * kmem_strfree() would then free with incorrect size.
 	 */
-	saved_poolname_len = strlen(zc->zc_name) + 1;
+	const char *spa_name = zc->zc_name;
+	if (zc->zc_nvlist_src_size != 0 && (error =
+	    get_nvlist(zc->zc_nvlist_src, zc->zc_nvlist_src_size,
+	    zc->zc_iflags, &props))) {
```
Comment (amotin) [inline module/zfs/zfs_ioctl.c]: May be I am missing something, but what's the difference between `innvl` and `props`?  Why do you need to get the second?

Comment (delan) [reply module/zfs/zfs_ioctl.c]: no difference, thanks for catching it. fixed in 8e95df34f940056e5ff102e69d8894bb078fc65a

**Review by behlendorf — APPROVED** [review]
