### PR TITLE
Trim L2ARC

### LINKED ISSUE #9713: Cannot trim L2ARC on SSD
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian (Proxmox VE 6.1)
Distribution Version	| 10
Linux Kernel	| 5.3.10-1-pve
Architecture	| x86_64
ZFS Version	| 0.8.2-pve2
SPL Version	| 0.8.2-pve2

### Describe the problem you're observing
I believe that trim does currently not work on L2ARC devices.

### Describe how to reproduce the problem

- L2ARC on SSDs
- trim correct pool (`zpool trim rpool`)
- check trim status with `zpool status -t`

```bash
root@server:~# zpool status -t
  pool: rpool
 state: ONLINE
  scan: scrub repaired 0B in 1 days 10:42:22 with 0 errors on Mon Dec  9 11:06:24 2019
config:

        NAME                              STATE     READ WRITE CKSUM
        rpool                             ONLINE       0     0     0
          mirror-0                        ONLINE       0     0     0
            wwn-0x5000cca22bdaa077-part1  ONLINE       0     0     0  (trim unsupported)
            wwn-0x5000cca22bd9d2e5-part1  ONLINE       0     0     0  (trim unsupported)
        logs
          mirror-1                        ONLINE       0     0     0
            wwn-0x500253850016023e-part2  ONLINE       0     0     0  (100% trimmed, completed at Sat 07 Dec 2019 04:48:15 PM CET)
            wwn-0x5002538c403f69a6-part2  ONLINE       0     0     0  (100% trimmed, completed at Sat 07 Dec 2019 04:48:15 PM CET)
        cache
          sda1                            ONLINE       0     0     0  (untrimmed)
          sdb1                            ONLINE       0     0     0  (untrimmed)

errors: No known data errors
```

As you can see in the output the L2ARC is discovered as `untrimmed`. The HDDs are correctly showing `trim unsupported`.

Trying to force a trim on the L2ARC device itself directly, does not work either:

```bash
zpool trim rpool sda1
cannot trim 'sda1': device is in use as a cache
```

Taking the device offline beforehand and issuing the trim command does not change the output.

### Include any warning/errors/backtraces from the system logs

There are no warnings/errors/backtraces in the logs. I can only find trim_start & trim_finish for the corresponding devices that are getting trimmed. The cache devices (sda1/sdb1) are not mentioned in the logs.

### LINKED ISSUE #10224: zpool iostat reporting 16E free on a ~266G l2arc device
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  ubuntu
Distribution Version	|  18.04
Linux Kernel	| Linux version 5.3.0-46-generic (buildd@lcy01-amd64-013) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020
Architecture	| x64
ZFS Version	| HEAD (c614fd6e12c0fe2636a82b341e9ab9d150ee3c8a) + https://github.com/openzfs/zfs/pull/9789
SPL Version	| HEAD (c614fd6e12c0fe2636a82b341e9ab9d150ee3c8a) + https://github.com/openzfs/zfs/pull/9789

### Describe the problem you're observing

My ~266G l2arc cache device is fully utilized and now it's started reporting that it has 16E free when really it has approximately 0 space free.  Hopefully this is a cosmetic issue rather than a fundamental accounting error. :)

I've seen l2arc capacity report errors like this in the past though not for a long time.  But then, I rarely completely fill my l2arc.

I'm using HEAD + https://github.com/openzfs/zfs/pull/9789 ; I don't imagine that https://github.com/openzfs/zfs/pull/9789 has broken accounting but I mention it since it's related to l2arc.

```
% zpool iostat -v
                                          capacity     operations     bandwidth 
pool                                    alloc   free   read  write   read  write
--------------------------------------  -----  -----  -----  -----  -----  -----
...
--------------------------------------  -----  -----  -----  -----  -----  -----
zfs4-on-8tbgold                         3.34T  3.92T     16      5  13.0M  1001K
  ata-WDC_WD8004FRYZ-01VAEB0_VAKDG3ML   3.34T  3.92T     16      5  13.0M  1001K
cache                                       -      -      -      -      -      -
  nvme0n1p4                              266G  16.0E    125      9   117M  7.85M
--------------------------------------  -----  -----  -----  -----  -----  -----
```

### Describe how to reproduce the problem

Not sure - perhaps just filling a resonably large l2arc.

### Include any warning/errors/backtraces from the system logs

n/a

### PR DESCRIPTION
**Pull request by gamanakis**
Implement TRIM on cache devices.

Signed-off-by: George Amanakis <gamanakis@gmail.com>

### Motivation and Context

Closes #9713 
Closes #10224

### Description

The l2arc_evict() function is responsible for evicting buffers which
reference the next bytes of the L2ARC device to be overwritten. Teach
this function to additionally TRIM that vdev space before it is
overwritten if the device has been filled with data. This is done by
vdev_trim_simple() which trims by issuing a new type of TRIM,
TRIM_TYPE_SIMPLE.

We also implement a "Trim Ahead" feature. It is a zfs module parameter,
expressed in % of the current write size. This trims ahead of the
current write size. A minimum of 64MB will be trimmed. The default is 0
which disables TRIM on L2ARC as it can put significant stress to
underlying storage devices. To enable TRIM on L2ARC we set
l2arc_trim_ahead > 0.

We also implement TRIM of the whole cache device upon addition to a
pool, pool creation or when the header of the device is invalid upon
importing a pool or onlining a cache device. This is dependent on
l2arc_trim_ahead > 0. TRIM of the whole device is done with
TRIM_TYPE_MANUAL so that its status can be monitored by zpool status -t.
We save the TRIM state for the whole device and the time of competion
on-disk in the header, and restore these upon L2ARC rebuild so that
zpool status -t can correctly report them. Whole device TRIM is done
asynchronously so that the user can export of the pool or remove the
cache device while it is trimming (ie if it is too slow).

We do not TRIM the whole device if persistent L2ARC has been disabled by
l2arc_rebuild_enabled = 0 because we may not want to lose all cached
buffers (eg we may want to import the pool with
l2arc_rebuild_enabled = 0 only once because of memory pressure). If
persistent L2ARC has been disabled by setting the module parameter
l2arc_rebuild_blocks_min_l2size to a value greater than the size of the
cache device then the whole device is trimmed upon creation or import of
a pool if l2arc_trim_ahead > 0.

### How Has This Been Tested?

Tests have been added in ZTS.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/arc.c [hunk 1]
```diff
@@ -8002,6 +8039,18 @@ l2arc_evict(l2arc_dev_t *dev, uint64_t distance, boolean_t all)
 	DTRACE_PROBE4(l2arc__evict, l2arc_dev_t *, dev, list_t *, buflist,
 	    uint64_t, taddr, boolean_t, all);
 
+	if (!all) {
```
Comment (behlendorf) [inline module/zfs/arc.c]: Adding a `vd->vdev_has_trim` check here would be a sensible precaution.

File: module/zfs/arc.c [hunk 2]
```diff
@@ -8002,6 +8039,18 @@ l2arc_evict(l2arc_dev_t *dev, uint64_t distance, boolean_t all)
...
+		dmu_tx_t *tx = dmu_tx_create_dd(spa_get_dsl(spa)->dp_mos_dir);
+		uint64_t txg = dmu_tx_get_txg(tx);
+
+		spa_config_enter(spa, SCL_STATE_ALL, vd, RW_READER);
+		zio_nowait(zio_trim(spa->spa_txg_zio[txg & TXG_MASK], vd,
+		    dev->l2ad_hand, taddr, trim_cb, NULL,
```
[the remark this answers is not in the document]
Comment (gamanakis) [reply module/zfs/arc.c]: I appreciate your help!
I thought that cache devices cannot be mirrored or part of raidz.

[the remark this answers is not in the document]
Comment (behlendorf) [reply module/zfs/arc.c]: > I thought that cache devices cannot be mirrored or part of raidz.

Ah yes, you're right.  Then only the singleton and striped case need to be handled.
￼

**Comment by gamanakis** [comment]
I will add a test later.

**Comment by gamanakis** [comment]
There is a peculiarity with the current approach:
`l2arc_evict()` runs periodically after the cache device has been filled once completely with data (`dev->l2ad_first`). However `l2arc_write_buffers()` may not actually write data to the space evicted and trimmed by `l2arc_evict()`, and thus `dev->l2ad_hand` does not move. This means that the next time `l2arc_evict()` runs, the space that has been previously evicted and trimmed is going to be evicted and trimmed again, and this is going to happen until `l2arc_write_buffers()` decides to write data and move `dev->l2ad_hand`.

Is this a problem?

**Comment by gamanakis** [comment]
I will try to leverage this by using `vdev->vdev_trim_last_offset`.

**Comment by gamanakis** [comment]
I think it is possible to leverage this in `l2arc_evict()` by using `vd->vdev_trim_last_offset`.

**Comment by pashford** [comment]
Here are some general comments on Trim of the L2ARC.  Sorry, I didn't have time to comment on this a month ago, when it was more active.

My understanding of how L2ARC works (based on Solaris 10 ZFS) is that it's a circular buffer.  New writes are always at the "end" of that buffer, with a block rarely (almost never) being preserved.  Any "old" data that gets overwritten as the end moves forward gets the in-core header released.  This was an excellent design for the 10KRPM/15KRPM disks that were being used for L2ARC at the time.  Alas, time passes and technology moves forward.

On an SSD, when a block of data gets overwritten, it's released and available to be erased.  Issuing a Trim command for the block to be overwritten may help slightly with fragmentation of the space and will give a few additional microseconds for the SSD controller to start erasing blocks before the data arrives.  Increasing the size of the segment being released will help a bit more.  The real gain here is that these blocks will always be on a SSD block boundary, removing any need to defragment the blocks being Trimmed.

Off the top of my head, there are a few other items that might be able to be trimmed.

1.  When an L2ARC is initialized (including clearing a persistent L2ARC), a Trim should be issued for the entire partition.  This might already be being done.

2.  When a block that's in the L2ARC gets updated (COW now places that file block into a different disk block), the old data can probably be trimmed.  The chances of using the old data block through the active file-system are now ZERO, and the chances of it being used through a snapshot are usually low.

3.  When an inode is deallocated, any blocks that it has in the L2ARC can probably be trimmed.  This will probably have a lower ROI than the above, because I expect most blocks in files being deleted (except intermediate/temporary files) won't be in the L2ARC.  If this is done, there would be a lot of chasing through the L2ARC metadata looking for blocks that aren't there.

Items 2 & 3 above would be likely to increase SSD fragmentation.  The SSD controller would be spending a lot more time consolidating mapped blocks to make a device block available to be erased.  As long as the controller can keep up (most modern SSD controllers probably won't have a problem), this should be fine, but older (or low-end) SSDs might have a problem.

**Comment by gamanakis** [comment]
@pashford Thank you for the feedback.
(1) is very reasonable and will be implemented. 
(2) This is what this PR does right now. Though I am not sure L2ARC is COW.
(3) This will probably be not so effective for the reasons you mention.

**Comment by misterbigstuff** [comment]
trimming during adding of l2arc if implemented, should certainly be optional. not all devices trim equally, it would be awful to wait for the entire partition to be done.

**Comment by pashford** [comment]
@misterbigstuff,

Excellent idea.  Perhaps it would be possible to trim the entire partition in "small" chunks, maybe 64MB-1GB/S - at least twice the specified max L2ARC write rate.  That would keep the controller's erase queue short, but still keep the erased blocks ahead of the blocks being written.

**Comment by pashford** [comment]
@gamanakis,

Based on your response, I'm not sure that when I meant came through clearly.  Please allow me to provide an example that should make my meaning clear.

Let's say that there's a 1-block file that's being updated.  The updates are infrequent enough that the blocks often get migrated to L2ARC between updates.  When the update happens, the block might still be valid in a snapshot, but not in the active instance of the file-system, due to COW.

When this happens, the L2ARC instance of the possibly valid block should be released and trimmed.  This is because the chances of the block being used by any snapshot that might still have it allocated are very slim, when compared to the use by the active instance of the file-system.

Does this make more sense?

**Comment by pashford** [comment]
> This is based on Brian Behledorf's comment at #9713.

When I wrote my first comment in this issue, I thought you were referring to Brian's post about using a larger overwrite size.  Since that's not the case, here's another way that Trim can be used to improve performance of SSD-based L2ARCs.

Implement a "TrimAhead" feature.  This is based on the 8MB overwrite feature, but it's more flexible.  The default would be the greater of 64MB or twice the current write speed limit (the initial fill rate can be set higher than the refresh fill rate) with a minimum of 8MB.  It would be a tunable parameter, which would be expressed in MB or %.  This would free farther ahead of the current write pointer.

The purpose of this is to better accommodate write bursts (the L2ARC writes are bursty).  Also, for consumer-grade SSDs, it would effectively reserve the specified amount of SSD space for the controller to catch up, and to lessen the amount of page defragmentation the controller needs to do.  This is superior to leaving a portion of the SSD unused, in that you know that the unused portion will be trimmed and you know that it will never be accidentally used or put to "temporary" use.

**Comment by gamanakis** [comment]
`7b1b009`: update this branch and its description. Also updated the `persist_l2arc` tests to enable autotrim on the pools used. If this passes the buildbots without apparent issues I will remove the draft.

**Comment by gamanakis** [comment]
`bd37d5d`: added man pages, this is now ready for review.

File: module/zfs/vdev_trim.c [hunk 3]
```diff
@@ -1435,6 +1435,52 @@ vdev_autotrim_restart(spa_t *spa)
...
+	physical_rs.rs_end = start + size;
+
+	ASSERT(vdev_is_concrete(vd));
+	ASSERT(vd->vdev_ops->vdev_op_leaf);
+
+	ta.trim_vdev = vd;
+	ta.trim_tree = range_tree_create(NULL, RANGE_SEG64, NULL, 0, 0);
+	ta.trim_type = type;
+	ta.trim_extent_bytes_max = zfs_trim_extent_bytes_max;
+	ta.trim_extent_bytes_min = zfs_trim_extent_bytes_min;
```
Comment (behlendorf) [inline module/zfs/vdev_trim.c:1458]: Since we're requesting that a single extent be trimmed where the caller provides the size I don't think we want to apply the `zfs_trim_extent_bytes_min` limit.  Otherwise, this function cannot be used to TRIM ranges <=32k in size (with the defaults).  Similar to what's done for secure TRIM in `vdev_trim_thread()`, I'd suggest setting this to `SPA_MINBLOCKSIZE`.

`ta.trim_extend_bytes_min = SPA_MINBLOCKSIZE;`

This isn't really an issue for the L2ARC caller, but we may find this helper useful elsewhere in the future.

File: tests/zfs-tests/tests/functional/trim/autotrim_l2arc.ksh [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+typeset trim_extent_bytes_min=$(get_tunable TRIM_EXTENT_BYTES_MIN)
+log_must set_tunable64 TRIM_EXTENT_BYTES_MIN 4096
+
+# Reduced TRIM_TXG_BATCH to make trimming more frequent.
+typeset trim_txg_batch=$(get_tunable TRIM_TXG_BATCH)
+log_must set_tunable64 TRIM_TXG_BATCH 8
+
+# Increased metaslabs to better simulate larger more realistic devices.
+typeset vdev_min_ms_count=$(get_tunable VDEV_MIN_MS_COUNT)
+log_must set_tunable64 VDEV_MIN_MS_COUNT 32
```
Comment (behlendorf) [inline tests/zfs-tests/tests/functional/trim/autotrim_l2arc.ksh:63]: All three of these non-default tunings can be dropped for this test case (here and above).  As their comments describe they pertain to how exactly metaslabs are trimmed which isn't relevant for l2arc trimming as you've implemented it with `vdev_trim_simple()`.

File: tests/zfs-tests/include/libtest.shlib [hunk 5]
```diff
@@ -4066,3 +4066,17 @@ function get_arcstat # stat
...
+		typeset pool=$1
+		typeset stat=$2
+		typeset zfs_iostats="/proc/spl/kstat/zfs/${pool}/iostats"
+		[[ -f "$zfs_iostats" ]] || return 1
+		grep $stat $zfs_iostats | awk '{print $3}'
+		return $?
+	else
+		return 1
+	fi
+}
```
Comment (behlendorf) [inline tests/zfs-tests/include/libtest.shlib:4082]: You can use the `get_trim_io` and `verify_trim_io` functions in ` trim.kshlib` to get these functions in a portable way.  You could even extend them to target just the TRIM status for the L2ARC device by including it in the `zpool iostat` command.  i.e. `zpool iostat -pr <pool> <l2arc vdev>`.

File: tests/zfs-tests/tests/functional/trim/autotrim_l2arc.ksh [hunk 6]
```diff
@@ -0,0 +1,106 @@
...
+export BLOCKSIZE=128K
+export SYNC_TYPE=0
+export DIRECT=1
+
+# Write to the pool.
+log_must fio $FIO_SCRIPTS/mkfiles.fio
+
+# Export and re-import the pool to stop possible trimming on $TRIM_VDEV1.
+log_must zpool export $TESTPOOL
+log_must zpool import -d $TRIM_DIR $TESTPOOL
```
Comment (behlendorf) [inline tests/zfs-tests/tests/functional/trim/autotrim_l2arc.ksh:91]: This shouldn't be needed if you get the per-vdev TRIM stats as mentioned above.

File: module/zfs/arc.c [hunk 7]
```diff
@@ -8340,25 +8365,49 @@ l2arc_evict(l2arc_dev_t *dev, uint64_t distance, boolean_t all)
...
-	}
+		if (vd->vdev_has_trim && dev->l2ad_evict < taddr &&
+		    l2arc_trim_ahead > 0) {
+			/*
+			 * We have to drop the spa_config lock because
+			 * vdev_trim_range will acquire it.
+			 */
+			spa_config_exit(dev->l2ad_spa, SCL_L2ARC, dev);
+			vdev_trim_simple(vd,
+			    dev->l2ad_evict - VDEV_LABEL_START_SIZE,
```
Comment (behlendorf) [inline module/zfs/arc.c:8380]: Can you expand the comment here explaining why we need to subtract the `VDEV_LABEL_START_SIZE`.  Something to the effect that `l2ad_evict` already accounts for the label, and to prevent `vdev_trim_simple()` from adding it again we need to subtract `VDEV_LABEL_START_SIZE`.

**Comment by gamanakis** [comment]
@behlendorf Thank you for your time reviewing this.

`fd4b5f2`: fixes from @behlendorf review, optimize the newly introduced test to stop when we loop around the cache device.

**Comment by behlendorf** [comment]
@gamanakis when you get a moment would you mind rebasing this change on the recently merged FreeBSD changes.

**Comment by gamanakis** [comment]
`94ce4d6`: rebased to master `6b1139e` (with the FreeBSD changes merged in).

**Comment by adamdmoss** [comment]
Do I read right that l2arc won't trim at all unless autotrim=true for the whole pool?
I believe I'd like to keep trimming the pool only occasionally with explicit 'zpool trim' but still have an l2arc which trims/trims-ahead.  (Since as far as I understand, an explicit trim on a full l2arc would be pointless even if it were supported.)

**Comment by gamanakis** [comment]
@adamdmoss Thank you for the feedback. You are correct, a manual trim on L2ARC wouldn't make much sense. 

Let me explain my rational for `autotrim = on`: From my understanding we need L2ARC cache devices on pools that contain magnetic drives to speed up reads. If the pool is made from SSDs having an L2ARC although possible, wouldn't provide much of an advantage. However, my assumption maybe wrong if for example the pool contains SATA SSDs and the L2ARC is on NVMe (I don't have such a setup and cannot test).
Could you share your zpool setup?

**Comment by gamanakis** [comment]
Thinking about this it may be worth it to introduce a new type of TRIM, TRIM_TYPE_L2ARC, to be used only on L2ARC. Will give it a try.

**Comment by gamanakis** [comment]
Implementing a new `TRIM_TYPE_L2ARC` seems straightforward. In terms of de-/activating it we could either introduce a zpool property `l2arc_trim`, or make it dependent on the zfs module parameter `l2arc_trim_ahead`.

@behlendorf I would appreciate your input on this.

**Comment by amotin** [comment]
Has anybody ever shown that TRIM'ing of some really small amounts of soon to be sequentially overwritten space really improves any SSD performance?  On opposite side I saw many SSDs having minimal TRIM time measured in hundreds of milliseconds, that combined with the fact that on many SSDs TRIM is still non-NCQ means respective read latency jumps, that is not nice at all for L2ARC.
I would understand if we TRIM non-persistent L2ARC on pool import, it may have some sense, but that seems to be not the case any more.

**Comment by misterbigstuff** [comment]
> Has anybody ever shown that TRIM'ing of some really small amounts of soon to be sequentially overwritten space really improves any SSD performance? On opposite side I saw many SSDs having minimal TRIM time measured in hundreds of milliseconds, that combined with the fact that on many SSDs TRIM is still non-NCQ means respective read latency jumps, that is not nice at all for L2ARC.
> I would understand if we TRIM non-persistent L2ARC on pool import, it may have some sense, but that seems to be not the case any more.

while we have plenty of evidence that trim can hurt performance we've got no evidence that it'll help L2ARC performance. anecdotes, unfortunately, do not count as evidence.

**Comment by gamanakis** [comment]
@amotin It is worth noting that in the current implementation we trim ahead of the evict hand. So we continuously reserve more space than what will be needed for the writes which leaves a portion of the L2ARC partition unused.

**Comment by behlendorf** [comment]
> Implementing a new TRIM_TYPE_L2ARC along with corresponding iostats seems straightforward.

Adding a new TRIM type shouldn't be difficult but there are a handful of places which would need to be updated to handle the new type.  For example, the `vd->vdev_trim_inflight[]` array is indexed by TRIM type and used to track inflight TRIMs.  There are some additional statistics which would need to be updated as well.  In general, I think it's a good idea.

> I would understand if we TRIM non-persistent L2ARC on pool import, it may have some sense, but that seems to be not the case any more.

The manual TRIM type could be leveraged for this with a little bit of work.  One upside of using the manual TRIM is that when the TRIM occurred would then be reported by `zpool status -t`.  So you could verify it happened when a new L2ARC was attached.

> it we could either introduce a zpool property l2arc_trim, or make it dependent on the zfs module parameter l2arc_trim_ahead.

I'd recommend using the `l2arc_trim_ahead` module option for this.  This make it easy to enable/disable and we don't need to commit to the long term maintenance burden of a new pool property.  If we decide it makes more sense as a pool property in the future it can always be converted then.

As for testing TRIM performance I found this to be quite difficult when initially developing the feature.  Depending on the exact hardware being tested it could either improve or hurt performance.  That said, I do think we need some performance testing of this before enabling it by default.  Since writing to the L2ARC is all done asynchronously I don't think the write latency is to relevant (unless it somehow impacts reads).  But I would be interested to know if trimming ahead can improve the write throughput allowing the device to be filled more quickly.

**Comment by gamanakis** [comment]
`66980c1`: Implements `TRIM_TYPE_L2ARC` along with corresponding iostats. TRIM on L2ARC devices is now controlled by the zfs module `l2arc_trim_ahead` which is set to 0 by default (TRIM on L2ARC disabled).

@behlendorf Let me know if I missed some iostats.

**Comment by pashford** [comment]
> Has anybody ever shown that TRIM'ing of some really small amounts of soon to be sequentially overwritten space really improves any SSD performance? On opposite side I saw many SSDs having minimal TRIM time measured in hundreds of milliseconds, that combined with the fact that on many SSDs TRIM is still non-NCQ means respective read latency jumps, that is not nice at all for L2ARC.
I would understand if we TRIM non-persistent L2ARC on pool import, it may have some sense, but that seems to be not the case any more.

If your SSD properly supports the queued TRIM command, the default TRIM-ahead will TRIM enough data to improve performance.

If the SSD only supports non-queued TRIM, you'll probably need to keep a significant portion of the drive unused (larger TRIM-Ahead values) to see any significant performance improvement.  This is similar to how the older Enterprise SSDs gave the performance they did, except they hid that extra capacity.

The TRIM on allocate has been suggested above, but most of the performance gain from that is short-lived (one write pass through the L2ARC).  I expect George hasn't had the spare time yet to implement this.

Performing a TRIM on individual blocks as they get rewritten or released will provide fodder for the SSD's Garbage Collector, but we should hope that the SSD doesn't get forced to do a Garbage Collection pass often.  Garbage Collection on an SSD increases write amplification and isn't especially fast.

If L2ARC performance is critical, selection of a good SSD is necessary.  Just picking up any cheap thing you find on sale isn't a reliable path to high performance.

**Comment by gamanakis** [comment]
`ba68225`: Implement TRIM of the whole cache device upon addition to a pool, pool creation or when the header of the device is invalid. This is dependent for the time being on `l2arc_trim_ahead > 0`. We do not TRIM the whole device if persistent L2ARC has been disabled (`l2arc_rebuild_enabled = 0`) because we may not want to loose all cached buffers (eg we may want to import the pool with `l2arc_rebuild_enabled = 0` only once because of memory pressure). The TRIM of the whole device is done with `TRIM_TYPE_MANUAL` so that its status can be monitored by `zpool status -t`. I tested this as much as I could in a virtual machine and didn't find any deadlocks or panics.

**Comment by adamdmoss** [comment]
What do you recommend as a l2arc_trim_ahead value for someone testing this?  1, or higher?

**Comment by adamdmoss** [comment]
I've reported https://github.com/openzfs/zfs/issues/10224 on a l2arc capacity reporting issue; I don't particularly believe it's related to testing this PR but I mention it since it's l2arc related and only just appeared for me.

Otherwise, this PR appears to be behaving and performing adequately in my brief testing so far.

**Comment by pashford** [comment]
> We do not TRIM the whole device if persistent L2ARC has been disabled (l2arc_rebuild_enabled = 0) because we may not want to lose all cached buffers (eg we may want to import the pool with l2arc_rebuild_enabled = 0 only once because of memory pressure).

Is there a way a SysAdmin can trigger a full-drive TRIM?  This would only be necessary when retasking an SSD from file-system duty (any file-system), as the data blocks would be scattered.  In this instance, TrimAhead will still require some significant amount of garbage collection on the drive.

If there is, could that be added to the "best practices" WIKI page?

**Comment by gamanakis** [comment]
> Is there a way a SysAdmin can trigger a full-drive TRIM? 

Yes:
```
echo 100 > /sys/module/zfs/parameters/l2arc_trim_ahead
zpool remove pool cache_device
zpool add pool cache cache_device
```

**Comment by adamdmoss** [comment]
My tests with a0cf60332e3b1b78de9c951ac3a3226b5d7f11c9 have unfortunately ended in sadness.
At some point after the l2arc has been warmed with a few 10s of GB, reads for data that is supposed to be resident in the l2arc seem to overwhelmingly fail and fall back to reading from the slow device, and l2arc appears to stop receiving new data, or is doing so very slowly.  (I was too dumb to take note of what l2_cksum_bad was doing or other stats at the time.)

When this happens, a reboot would appear to cause the l2arc to be rebuilt from scratch despite persistence, then function normally for a little while before entering the unhelpful state again.  This happened for my last 4-5 reboots (when I was paying attention - it might have been always been happening on this branch); after the first couple of times I noticed it I removed and re-added the cache device but the problem kept occurring.

Reverting to a non-l2trim zfs build appears to have restored l2arc functionality and performance (touch wood...)

FYI I was using a combination of autotrim=false on my zpools and 'l2arc_trim_ahead=1' module params.  My l2arc is ~266GB on nvme.

**Comment by adamdmoss** [comment]
Some good news however... before trying the l2arc_trim branch, my throughput from l2arc had gradually degraded to the 800-850MB/sec range over the last six months.  Now it's back up to 1050-1100MB/sec which is a lot closer to the peak ~1200MB/sec of the nvme device.

I'm guessing the TRIM of the whole l2arc really helped.

**Comment by gamanakis** [comment]
@adamdmoss Thank you for the feedback. Going back to #10224 I saw that you have `l2arc_write_size=1GB`, this is pretty huge and possibly this is the cause of this PR misbehaving when `l2arc_trim_ahead > 0`. 

This also explains #10224 although having the actual iostats and arcstats would be helpful. All in all this is what I think is going on:
you enable trim ahead with a large l2arc_write_size. Your cache device and cope but gradually its trimming performance degrades to the point it needs a lot of time to trim ahead. Then the L2ARC write start slowing down, which may cause a delay in the L2ARC reads too. 

I think keeping `l2arc_write_size=16-128MB` and `l2arc_trim_ahead=200` seems reasonable. 
Side note: `l2arc_trim_ahead` is expressed as a percentage of `l2arc_write_size`.

I do not think there is anything wrong with #9582 but went ahead and implemented some additional features/fixes which would be helpful in #10228.

**Comment by adamdmoss** [comment]
Thanks for the response, George.

> Going back to #10224 I saw that you have l2arc_write_size=1GB

FWIW I tried various l2arc_write_sizes (and l2arc_feed_min_ms which I usually keep at default) when I noticed that the l2arc had stopped growing, but it didn't help at the time.  I probably didn't reboot with the lower write size though, so if the queue length was the problem then the problem would have persisted...

> l2arc_trim_ahead is expressed as a percentage of l2arc_write_size

I was using l2arc_trim_ahead=1, so that's 10MB of trim-ahead.  That's rather lower than the 32-256MB you recommend but still sort of on the same order.

> gradually its trimming performance degrades

(Is this really a characteristic of trimming?  Or a characteristic of the logical cache head eventually catching up with the cache tail when the cache is almost full?)

**Comment by gamanakis** [comment]
> I was using l2arc_trim_ahead=1, so that's 10MB of trim-ahead.

This would actually be 1GB+10MB of trimming.

**Comment by gamanakis** [comment]
@adamdmoss I introduced a bug in l2arc_evict() in this PR. Will fix it.

**Comment by gamanakis** [comment]
There is a bug in the calculation of the space to evict in l2arc_evict() which caused #10224. I converted this to a draft and will fix it soon.

**Comment by gamanakis** [comment]
`31ec7fb`: Fix a bug introduced by this PR in `l2arc_evict()`: when `l2arc_write_size > 64MB` and `l2arc_trim_ahead*l2arc_write_size/100 <  64MB`, `l2arc_evict()` would not evict enough space to accommodate upcoming writes leading to an overflow of the allocated space on the cache device. This is now fixed thanks to @adamdmoss and #10224.

**Comment by adamdmoss** [comment]
Great job, I'll give this another exercise.

**Comment by adamdmoss** [comment]
Giving fe2e198d450360a191a558cfc6035c6fa8a97724 a spin.
(It persisted the L2 from before the reboot; that's great but is it expected?)
Something unusual/unexpected is still happening; I'm accessing (only) a bunch of data which should already be in L2 and I'm getting these arcstats:
```
evict_l2_cached                 4    170062435328+
evict_l2_eligible               4    81400832
evict_l2_ineligible             4    96256
evict_l2_skip                   4    0
l2_hits                         4    172521+
l2_misses                       4    6615
l2_feeds                        4    920+
l2_rw_clash                     4    0
l2_read_bytes                   4    178279970816+
l2_write_bytes                  4    222318592
l2_writes_sent                  4    60
l2_writes_done                  4    60
l2_writes_error                 4    0
l2_writes_lock_retry            4    0
l2_evict_lock_retry             4    0
l2_evict_reading                4    0
l2_evict_l1cached               4    0
l2_free_on_write                4    0
l2_abort_lowmem                 4    0
l2_cksum_bad                    4    161473+
l2_io_error                     4    0
l2_size                         4    158335937024
l2_asize                        4    143057543680
l2_hdr_size                     4    36517248+
l2_log_blk_writes               4    0
l2_log_blk_avg_size             4    10099
l2_data_to_meta_ratio           4    3229
l2_rebuild_success              4    1
l2_rebuild_unsupported          4    0
l2_rebuild_io_errors            4    0
l2_rebuild_dh_errors            4    0
l2_rebuild_cksum_lb_errors      4    2
l2_rebuild_lowmem               4    0
l2_rebuild_size                 4    158211335680
l2_rebuild_bufs                 4    400420
l2_rebuild_bufs_precached       4    350
l2_rebuild_psize                4    142895288320
l2_rebuild_log_blks             4    837
```
The values I've marked with '+' keep increasing as I repeatedly access this data.
Of note to me (and remarkably none of this seems to happen with zfs-master builds):
* Lots of eviction despite L2 being only about half full (131GB/266GB)
* Lots of l2_cksum_bad
* Despite overwhelming l2_hits vs misses, it's only achieving a small fraction of its usual speed when reading from warm cache - not much faster than the slow media
* Assuming it's correctly identifying l2_cksum_bad bad cached data, for whatever reason, it doesn't seem to be throwing away the bad data and re-caching good data - with each re-access of the data which is supposed to be in-cache, l2_read_bytes keeps climbing, l2_write_bytes is quiescent, and access is still slow.

n.b. I'm still using l2arc_write_max:1000000000 and l2arc_trim_ahead:1 (really I'd like to raise trim_ahead but I wanted to test with the 'trouble' parameters since they seem to tickle bad behavior).

**Comment by adamdmoss** [comment]
After another reboot it automatically blew the cache away and it's been behaving well again since then in all respects (apart from the runaway evict_l2_cached which I guess is somehow normal).  So far.

**Comment by adamdmoss** [comment]
I've aggressively filled my L2ARC to the brim and https://github.com/openzfs/zfs/issues/10224 has not occurred again.  I'll hammer on it for a few more days and close the issue.  Cheers.

I've rebooted again to see if the L2ARC remains intact; it is intact and is behaving (and performing) very well so far.

**Comment by gamanakis** [comment]
@adamdmoss thank you for the feedback.
The `evict_*` arcstats refer to buffers evicted from ARC, not L2ARC if I recall correctly.

It is interesting that the way L2ARC was designed **as far as I can tell from the code in `l2arc_read_done`**, if a buffer is invalid, its L2ARC header does not get evicted from ARC, so it tries to read it from L2ARC first. This would explain why `l2arc_cksum_bad` is still rising. I may be wrong though, need to look thoroughly into it some other time.

**Comment by gamanakis** [comment]
@adamdmoss I think I figured out what happened: If the cache device is still in its first pass, then the evict hand is not advanced (this is on purpose), ie it may be before the write hand. When we enable `l2arc_trim_ahead`, then the evict hand will be advanced possibly trimming already written buffers and log blocks causing `l2_cksum_bad` and `l2_log_blk_cksum_error`. 
Then again if `l2arc_trim_ahead` is enabled we have already trimmed the whole device and we can avoid trimming on the first pass.

**Comment by gamanakis** [comment]
`4d9ad91`: We save the TRIM state for the whole device and the time of completion
on-disk in the header, and restore these upon L2ARC rebuild so that
`zpool status -t` can correctly report them.

**Comment by gamanakis** [comment]
@adamdmoss revision 4d9ad91 stores some TRIM related values in the header of the device. This means that if l2arc_trim_ahead > 0, and the TRIM values in the header are 0 (as in all previous revisions) it will TRIM the whole device upon import of the pool. You can avoid this by l2arc_trim_ahead=0 when importing, and after that set it to > 0.

**Comment by adamdmoss** [comment]
I'm using git master 0aeb0bed6fe12afa9c3c9c5cab0fb287f768d5d5 + l2arc_trim 4d9ad9178aa13ce16040eca707bc4b7c6b6d32d1 (HEAD) at the moment.

Things have continued to be performant and well-behaved since the fixes from https://github.com/openzfs/zfs/pull/9789#issuecomment-619534727 - I've been using some version of master HEAD plus l2arc_trim HEAD since then, constantly.

**Comment by gamanakis** [comment]
ef10ef8: Rebase to master, add a comment and zero out the memory holding the values of the device header before writing a fresh one in `vdev_trim_simple()`.

**Comment by gamanakis** [comment]
968c54b: Rebase to master.

**Comment by gamanakis** [comment]
60837d3: Rebase to master.

**Comment by adamdmoss** [comment]
This is my monthly comment to say that this is still behaving and performing well. ;)  I'm using it on my day-to-day desktop system daily.
trimandfixes2 2617f2e133e94974d0537608ac1ae099de4c3500 + master c946d5a91329b075fb9bda1ac703a2e85139cf1c FYI.

**Comment by gamanakis** [comment]
@adamdmoss Thank you for testing. The branches gamanakis:trimandfixes2 and gamanakis:l2arc_trim (this PR) are the same now that #10228 was merged.

File: module/zfs/arc.c [hunk 8]
```diff
@@ -9290,6 +9354,49 @@ l2arc_stop(void)
...
+	for (int i = 0; i < spa->spa_l2cache.sav_count; i++) {
+		l2arc_dev_t *dev =
+		    l2arc_vdev_get(spa->spa_l2cache.sav_vdevs[i]);
+		if (dev == NULL) {
+			/* Don't attempt TRIM if the vdev is UNAVAIL */
+			continue;
+		}
+
+		if (dev->l2ad_trim_all) {
+			dev->l2ad_vdev->vdev_trim_thread = thread_create(NULL,
```
Comment (behlendorf) [inline module/zfs/arc.c:9380]: Using the `vd->vdev_trim_*` members for this makes sense, but it does mean that a normal manual trim cannot be running when `vdev_trim_simple(, TRIM_TYPE_MANUAL)` is called on the same vdev.  They're mutually exclusive operations.  Given that, I think it would be best to move this threading logic entirely in to `vdev_trim.c` and model it after the manual trim threads.  Specifically adding a new `vdev_trim_l2arc()`  function which kicks off a `vdev_trim_l2arc_thread()` that does what `l2arc_dev_trim` and `vdev_trim_simple` current do.

Then `vdev_trim_simple()` could be restored to a more generic implementation which doesn't modify any of the `vd->vdev_trim_*` state.

**Comment by gamanakis** [comment]
bebd6fd: move the threading logic to `vdev_trim.c` and restore `vdev_trim_simple()` to a more generic implementation which doesn't modify any of the `vd->vdev_trim_*` states.

**Comment by gamanakis** [comment]
@behlendorf I refactored the functions as you suggested. Now `vdev_trim_simple()` uses only  `vd->vdev_trim_inflight[ta.trim_type]` in order to determine whether trimming has been completed.

I can see this possibly conflicting with manual/auto trims if `vdev_trim_simple()` is used on a vdev where manual/auto trim is already running. Should we define one more trim type (e.g. TRIM_TYPE_SIMPLE) to be used with `vdev_trim_simple()` in future use cases? 

Regarding L2ARC:
- `vdev_trim_l2arc_thread()` issues trimming of the whole cache device as TRIM_TYPE_MANUAL. I do not see this being a problem here as we do not provide another mechanism of trimming cache devices manually.

- `l2arc_evict()` trims ahead by issuing `vdev_trim_simple()` with TRIM_TYPE_L2ARC.

**Comment by gamanakis** [comment]
032f438: To keep things simple, I renamed TRIM_TYPE_L2ARC to TRIM_TYPE_SIMPLE (along with all related stats and references). Now `vdev_trim_simple()` uses always TRIM_TYPE_SIMPLE.

File: include/sys/vdev.h [hunk 9]
```diff
@@ -192,6 +192,7 @@ typedef enum {
 } vdev_labeltype_t;
 
 extern int vdev_label_init(vdev_t *vd, uint64_t txg, vdev_labeltype_t reason);
+void vdev_trim_l2arc(spa_t *spa);
```
Comment (behlendorf) [inline include/sys/vdev.h:195]: Can you move this to `include/sys/vdev_trim.h`.

File: man/man5/zfs-module-parameters.5 [hunk 10]
```diff
@@ -194,11 +194,29 @@ Default value: \fB2\fR.
...
 .RE
 
+.sp
+.ne 2
+.na
+\fBl2arc_trim_ahead\fR (ulong)
+.ad
+.RS 12n
+Trims ahead of the current evict hand on L2ARC devices by this percentage of
+write size if we have filled the device. It has a minimum value of 64MB. If
```
Comment (behlendorf) [inline man/man5/zfs-module-parameters.5:210]: I was initially confused by the phrase "It has a minimum value of 64MB.", since the previous sentence stated this was a percentage.  How about rewording it slightly and moving it after the following sentence, something like:

"Trims ahead of the current evict hand on L2ARC devices by this percentage of
write size if we have filled the device.  If set to \fB100\fR we TRIM twice the space
required to accommodate upcoming writes.  A minimum of 64MB will be trimmed.
It also enables TRIM ..."
```

nit: fixed spelling of accommodate in original text.

File: module/zfs/arc.c [hunk 11]
```diff
@@ -864,6 +864,16 @@ static inline void arc_hdr_clear_flags(arc_buf_hdr_t *hdr, arc_flags_t flags);
 static boolean_t l2arc_write_eligible(uint64_t, arc_buf_hdr_t *);
 static void l2arc_read_done(zio_t *);
 
+/*
+ * L2ARC TRIM
+ * l2arc_trim_ahead : A ZFS module parameter that controls how much ahead of
+ * 		the current write size we should TRIM. It is defined as a
+ * 		percentage of the write size. The minimum TRIM size is 64MB.
+ * 		If set to 100 and the write size is greater than 64MB we don't
+ * 		trim ahead. The default is 0, TRIM is disabled for L2ARC.
```
Comment (behlendorf) [inline module/zfs/arc.c:873]: Update to match the final text in the man page description.

Can you also include a brief explanation with the rational for why L2ARC trimming is disabled by default.

**Comment by gamanakis** [comment]
204b00aa0: Addresses comments from @behlendorf
c4cc6691d: Update the commit message.

**Comment by gamanakis** [comment]
298654a: Updated some comments in the code.

**Comment by behlendorf** [comment]
This is ready to merge.  If anyone has additional feedback please post it by Monday June 8th.

**Comment by behlendorf** [comment]
Merged!

**Comment by mailinglists35** [comment]
@gamanakis how to ensure trim can be done on l2arc devices, and how to troubleshoot if it doesn't?

I am in the same situation as https://github.com/openzfs/zfs/issues/14488
`zpool trim -t` only shows the log device being trimmed, but the l2arc devices shows as "(untrimmed)", despite both the log and cache vdevs being on the same ssd

**Comment by mailinglists35** [comment]
````
$ zpool status -t mypool'
  pool: mypool
 state: DEGRADED
status: One or more devices has been taken offline by the administrator.
        Sufficient replicas exist for the pool to continue functioning in a
        degraded state.
action: Online the device using 'zpool online' or replace the device with
        'zpool replace'.
  scan: resilvered 21.6G in 00:07:39 with 0 errors on Thu May 25 09:08:04 2023
config:

        NAME            STATE     READ WRITE CKSUM
        mypool            DEGRADED     0     0     0
          mirror-0      DEGRADED     0     0     0
            hgst        ONLINE       0     0     0  (trim unsupported)
            enterprise  OFFLINE      0     0     0  (trim unsupported)
            iron        ONLINE       0     0     0  (trim unsupported)
        logs
          zlog.mypool     ONLINE       0     0     0  (100% trimmed, completed at Wed 07 Jun 2023 11:45:55 PM EEST)
        cache
          zcache.mypool   ONLINE       0     0     0  (untrimmed)

errors: No known data errors
````

**Comment by adamdmoss** [comment]
> @gamanakis how to ensure trim can be done on l2arc devices, and how to troubleshoot if it doesn't?
> 
> I am in the same situation as #14488 and #9713 `zpool trim -t` only shows the log device being trimmed, but the l2arc devices shows as "(untrimmed)", despite both the log and cache vdevs being on the same ssd

Since an L2ARC's natural state is to be full (since l2arc gained persistence across boots, at least!) it doesn't usually make much sense to trim the l2arc device spontaneously.

If you want the l2arc trimmed, continuous trim-ahead should be effective, as documented at:
https://openzfs.github.io/openzfs-docs/Performance%20and%20Tuning/Module%20Parameters.html#l2arc-trim-ahead

**Comment by Rudd-O** [comment]
```
[root@milena ~]# echo 100 > /sys/module/zfs/parameters/l2arc_trim_ahead 
[root@milena ~]# cat /sys/module/zfs/parameters/l2arc_trim_ahead 
100
[root@milena ~]# zpool trim -w backups
cannot trim: no devices in pool support trim operations
```

Setting this parameter does *not* change the error message produced by `zpool trim`.

https://github.com/openzfs/zfs/issues/14488 is exactly what I am experiencing.

**Comment by mabod** [comment]
I just added an SSD cache device to my main pool. Now I am wondering if this PR will be implemented in 2.2.7 or 2.3.. I am afraid that the SSD cache will loose its performance advantage when not being trimmed.
