### PR TITLE
Fix nfs_truncate_shares without /etc/exports.d

### LINKED ISSUE #15369: "failed to lock /etc/exports.d/zfs.exports.lock: No such file or directory"
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| Latest
Kernel Version	| 6.4.10
Architecture	| x64	
OpenZFS Version	| 2.2.0-rc4

### Describe the problem you're observing

Mounting ZFS filesystems fails with
`failed to lock /etc/exports.d/zfs.exports.lock: No such file or directory`

Further mount attempts may fail with
`cannot mount '<dataset>': filesystem already mounted`

And `zpool export -f <pool>`
results in
`cannot unmount '<dataset>': no such pool or dataset`

### Describe how to reproduce the problem

`zfs mount -a`

### Include any warning/errors/backtraces from the system logs
Can be provided upon request indicating what particular log is needed.

### PR DESCRIPTION
**Pull request by siv0**
calling nfs_reset_shares on Linux prints a warning: 
`failed to lock /etc/exports.d/zfs.exports.lock: No such file or directory`
when /etc/exports.d does not exist. The directory gets created, when a filesystem is actually exported through nfs_toggle_share and nfs_init_share. The truncation of /etc/exports.d/zfs.exports happens unconditionally when calling `zfs mount -a` (via zfs_do_mount and share_mount in `cmd/zfs/zfs_main.c`).

Fixing the issue only in the Linux part, since the exports file on FreeBSD is in `/etc/zfs/`, which seems present on 2 FreeBSD systems I have access to (through `/etc/zfs/compatibility.d/`), while a Debian box does not have the directory even if `/usr/sbin/exportfs` is present through the `nfs-kernel-server` package.

The code for exports_available is copied from nfs_available above.

Fixes: ede037cda73675f42b1452187e8dd3438fafc220
("Make zfs-share service resilient to stale exports") 
Closes #15369

The commit adds a check for existence of `/etc/exports.d`, before trying to lock `/etc/exports.d/zfs.exports.lock`.
This prevents the printing of a warning message on `zfs mount -a` or `zfs share -a`

### Motivation and Context

https://github.com/openzfs/zfs/issues/15369

### How Has This Been Tested?

Compiled Proxmox utils and libs packages with the patch applied on top of ZFS-2.0.0 and verified that 
`zfs mount -a`  does not print the warning anymore

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: lib/libshare/os/linux/nfs.c [hunk 1]
```diff
@@ -539,6 +540,8 @@ nfs_commit_shares(void)
 static void
 nfs_truncate_shares(void)
 {
+	if (!exports_available())
+		return (SA_OK);
```
Comment (behlendorf) [inline lib/libshare/os/linux/nfs.c:544]:
```
lib/libshare/os/linux/nfs.c: In function 'nfs_truncate_shares':
lib/libshare/os/linux/nfs.c:544:3: error: 'return' with a value, in function returning void [-Werror]
   return (SA_OK);
```

**Review by behlendorf — APPROVED** [review]

**Review by bwatkinson — APPROVED** [review]
