### PR TITLE
Simplify/fix dnode_move() for dn_zfetch.

### LINKED ISSUE #11936: dmu_zfetch_run() panic
### System information

Type | Version/Name
 --- | ---
Distribution Name	| DilOS
Distribution Version	|
Linux Kernel	|
Architecture	|
ZFS Version	|
SPL Version	|

### Describe the problem you're observing
we have 4 vm as vmware guests under vmware esxi and 2 vm as bhyve guests with sporadic/periodic panics with the same stack trace below in different scenarios. we have no panic in the same place, but we can see instability and just revert of commit https://github.com/openzfs/zfs/commit/891568c9907b3631f99a1079344bddf62ca70f56 (issue #11652) fixed this issue.  

### Describe how to reproduce the problem
ZTS tests on several different vms in loop

### Include any warning/errors/backtraces from the system logs

```
panic[cpu0]/thread=fffffe0c1836b7e0:
mutex_enter: bad mutex, lp=fffffe0d4bb6a340 owner=deadbeefdeadbee8 thread=fffffe0c1836b7e0


fffffe001116b920 unix:mutex_panic+4a ()
fffffe001116b990 unix:mutex_vector_enter+3a7 ()
fffffe001116ba50 zfs:dmu_zfetch_run+ad ()
fffffe001116bb10 zfs:dmu_buf_hold_array_by_dnode+482 ()
fffffe001116bbd0 zfs:dmu_read_uio_dnode+86 ()
fffffe001116bc40 zfs:dmu_read_uio_dbuf+6f ()
fffffe001116bd20 zfs:zfs_read+5a0 ()
fffffe001116bdc0 genunix:fop_read+fd ()
fffffe001116bef0 genunix:pread+1de ()
fffffe001116bf00 unix:brand_sys_syscall+32f ()

dumping to /dev/zvol/dsk/rpool/dump, offset 65536, content: kernel + curproc
```

### PR DESCRIPTION
**Pull request by amotin**
Previous code tried to keep prefetch streams while moving dnode.  But
it was at least not updating per-stream zs_fetchback pointers, causing
use-after-free on next access.  Instead of that I see much easier and
cleaner to just drop old prefetch state and start new from scratch.

Closes #11936

### How Has This Been Tested?
The code builds on FreeBSD.  Unfortunately I can't run test it, since neither FreeBSD nor Linux dnode_move().

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/dnode.c [hunk 1]
```diff
@@ -822,19 +821,14 @@ dnode_move_impl(dnode_t *odn, dnode_t *ndn)
 	ndn->dn_newgid = odn->dn_newgid;
 	ndn->dn_newprojid = odn->dn_newprojid;
 	ndn->dn_id_flags = odn->dn_id_flags;
-	dmu_zfetch_init(&ndn->dn_zfetch, NULL);
-	list_move_tail(&ndn->dn_zfetch.zf_stream, &odn->dn_zfetch.zf_stream);
-	ndn->dn_zfetch.zf_dnode = odn->dn_zfetch.zf_dnode;
```
Comment (ahrens) [inline module/zfs/dnode.c:827]: Does this leak the zstream_t's on the zf_stream?

The move callbacks are pretty tricky code to get right.  IMO, if we aren't able to maintain the move callbacks, because we can't test them, because they are dead code, we should remove them from the codebase.

Comment (amotin) [reply module/zfs/dnode.c:827]: dmu_zfetch_fini(&odn->dn_zfetch) below should free the old streams gracefully.

Comment (ahrens) [reply module/zfs/dnode.c:827]: OK.  I'm fine with integrating this change, but I would welcome a future PR to remove dnode_move_impl() entirely.

**Review by ahrens — APPROVED** [review]

**Review by ikozhukhov — APPROVED** [review]
it fixed panic. i'll continue to check it in loop
