### PR TITLE
Fix reporting of CKSUM errors in indirect vdevs

### LINKED ISSUE #11257: Removing a vdev and attaching it to another vdev results in CKSUM errors during resilver
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Archlinux
Distribution Version	| (rolling)
Linux Kernel	| 5.9.9
Architecture	| x64
ZFS Version	| 04a82e043d067181a8b352921ef6a3c3ac875b59 and 0.8.5
SPL Version	| see above

### Describe the problem you're observing
Removing a top-vdev and reattaching to another top-vdev in the same pool results in CKSUM errors while resilvering. This was observed in a 11TB production pool with 128kB recordsize and is reproducible in a VM using the following script.

### Describe how to reproduce the problem
This is reproducible in both 0.8.5 and 04a82e043d067181a8b352921ef6a3c3ac875b59:
```
truncate -s 4G {a,b}
zpool create -f -O recordsize=4k test ~/{a,b}
fio --name=test --size=2G --nrfiles=512 --readwrite=read --directory=/test
zpool remove test ~/b
zpool attach test ~/a ~/b
zpool status test
```
After resilvering is done the newly attached vdev shows CKSUM errors in zpool status.
However no real data corruption seems to occur as a zpool scrub does not report any errors.

Looking at the implementation of Nexenta I found two relevant commits:
1) https://github.com/Nexenta/illumos-nexenta/commit/f7d80bb043e6d74054633d0eecb255350d92ce51 based on 
https://github.com/openzfs/zfs/pull/8753 (waiting for current tx to sync while scanning during resilver)

and

2) https://github.com/Nexenta/illumos-nexenta/commit/847e400 (thread locking of scan queues)

However none of these approaches resolve the bug (tested locally).
Removing the vdev and reattaching it is crucial to triggering the bug. When attaching a fresh (ie non previously removed vdev) device, the CKSUM errors do not occur.

### Include any warning/errors/backtraces from the system logs

```
zpool status:
pool: tst3
 state: ONLINE
status: One or more devices has experienced an unrecoverable error.  An
        attempt was made to correct the error.  Applications are unaffected.
action: Determine if the device needs to be replaced, and clear the errors
        using 'zpool clear' or replace the device with 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-9P
  scan: resilvered 2.08G in 0 days 00:00:26 with 0 errors on Tue Dec  1 12:33:40 2020
remove: Removal of vdev 1 copied 1.07G in 0h0m, completed on Tue Dec  1 12:33:10 2020
    8.77K memory used for removed device mappings
config:

        NAME                      STATE     READ WRITE CKSUM
        tst3                      ONLINE       0     0     0
          mirror-0                ONLINE       0     0     0
            /home/user/vdevs/a  ONLINE       0     0     0
            /home/user/vdevs/b  ONLINE       0     0    14

errors: No known data errors

```

```
zpool events -v:
Dec  1 2020 12:33:38.028552122 ereport.fs.zfs.checksum
        class = "ereport.fs.zfs.checksum"
        ena = 0x15985ab1e9e00c01
        detector = (embedded nvlist)
                version = 0x0
                scheme = "zfs"
                pool = 0xf7542d83774def6a
                vdev = 0xb4ae9f5bec165b83
        (end detector)
        pool = "tst3"
        pool_guid = 0xf7542d83774def6a
        pool_state = 0x0
        pool_context = 0x0
        pool_failmode = "wait"
        vdev_guid = 0xb4ae9f5bec165b83
        vdev_type = "file"
        vdev_path = "/home/user/vdevs/b"
        vdev_ashift = 0x9
        vdev_complete_ts = 0x115985afec23
        vdev_delta_ts = 0x4da69
        vdev_read_errors = 0x0
        vdev_write_errors = 0x0
        vdev_cksum_errors = 0xe
        vdev_delays = 0x0
        parent_guid = 0x248200fb1cd637b7
        parent_type = "mirror"
        vdev_spare_paths = 
        vdev_spare_guids = 
        zio_err = 0x0
        zio_flags = 0x1008a8
        zio_stage = 0x200000
        zio_pipeline = 0x1f00000
        zio_delay = 0x0
        zio_timestamp = 0x0
        zio_delta = 0x0
        zio_offset = 0xd413c00
        zio_size = 0x600
        bad_ranges = 0x0 0x600 
        bad_ranges_min_gap = 0x8
        bad_range_sets = 0xbad 
        bad_range_clears = 0xb9a 
        bad_set_histogram = 0x37 0x2d 0x2f 0x38 0x2e 0x2e 0x37 0x2e 0x2f 0x2e 0x37 0x2e 0x2e 0x38 0x2e 0x2e 0x2f 0x27 0x39 0x28 0x31 0x2b 0x2f 0x37 0x2d 0x2d 0x29 0x25 0x35 0x35 0x36 0x2d 0x2c 0x33 0x2e 0x32 0x33 0x39 0x3a 0x2b 0x33 0x35 0x38 0x35 0x34 0x2f 0x2c 0x2d 0x29 0x2e 0x36 0x3c 0x2b 0x30 0x38 0x2f 0x0 0x0 0x0 0x2c 0x31 0x32 0x37 0x3d 
        bad_cleared_histogram = 0x32 0x2b 0x34 0x32 0x2a 0x34 0x33 0x2b 0x2a 0x35 0x32 0x2b 0x34 0x32 0x2a 0x34 0x36 0x3d 0x2e 0x35 0x33 0x39 0x35 0x32 0x34 0x28 0x32 0x3a 0x2f 0x23 0x2f 0x36 0x39 0x32 0x2c 0x2a 0x2f 0x2c 0x2f 0x3a 0x35 0x33 0x33 0x36 0x30 0x2c 0x2f 0x34 0x34 0x2f 0x29 0x2c 0x2d 0x30 0x2b 0x30 0x0 0x0 0x0 0x2b 0x2f 0x35 0x2c 0x33 
        time = 0x5fc62a12 0x1b3abba 
        eid = 0x18e

### PR DESCRIPTION
**Pull request by gamanakis**
### Motivation and Context
When removing and subsequently reattaching a vdev, CKSUM errors may occur
as vdev_indirect_read_all() reads from all children of a mirror in case
of a resilver.

Closes #11257 

### Description
Fix this by avoid reading from children which have the DTL_MISSING flag
set in case of a resilver.

### How Has This Been Tested?
A test was added.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/vdev_indirect.c [hunk 1]
```diff
@@ -1268,19 +1268,14 @@ vdev_indirect_read_all(zio_t *zio)
...
-			 * identically.  (The incorrect data will be
-			 * detected and ignored when we verify the
-			 * checksum.)
+			 * In case of a resilver do not read from a child
+			 * whose DTL indicates it may be missing data.
 			 */
+			if (!vdev_readable(ic->ic_vdev) ||
+			    ((zio->io_flags & ZIO_FLAG_RESILVER) &&
+			    !vdev_dtl_empty(ic->ic_vdev, DTL_MISSING)))
+				continue;
```
Comment (behlendorf) [inline module/zfs/vdev_indirect.c:1278]: How about this.  Rather than skipping a child since it _may_ not contain the correct data I think it would be preferable to do the read but set a flag indicating the data may be incorrect.

Setting a flag gives us every opportunity to reconstruct the split block if it's at all possible which is inline with how all of the existing indirect vdev repair logic is intended to work.  Both raidz and draid roughly [work in the same way](https://github.com/openzfs/zfs/blob/master/module/zfs/vdev_raidz.c#L1791-L1799) for the reconstruction cases which are similar (`rc_error = ESTALE` is set). Then in `vdev_indirect_repair()` you can check the flag and suppress incrementing the checksum counter since we know it was a long shot to begin with.

To check the DTL you'll want to do something like this `vdev_dtl_contains(cvd, DTL_MISSING, zio->io_txg, 1)`.

Comment (gamanakis) [reply module/zfs/vdev_indirect.c:1278]: Thanks for the feedback, will do!

**Comment by gamanakis** [comment]
000bc38: Implemented strategy suggested by @behlendorf

File: module/zfs/vdev_indirect.c [hunk 2]
```diff
@@ -1447,6 +1451,14 @@ vdev_indirect_repair(zio_t *zio)
 			    ZIO_FLAG_IO_REPAIR | ZIO_FLAG_SELF_HEAL,
 			    NULL, NULL));
 
+			/*
+			 * If ic_error is set the current child does not have
+			 * a copy of the data, so suppress incrementing the
+			 * checksum counter.
+			 */
+			if (ic->ic_error == ESTALE)
+				return;
```
Comment (behlendorf) [inline module/zfs/vdev_indirect.c:1460]:
```suggestion
				continue;
```

You don't want to return here since there may be splits on other vdevs to repair.

**Comment by gamanakis** [comment]
bc6fc9a: change `return;` to `continue;`

File: tests/zfs-tests/tests/functional/removal/remove_attach_mirror.ksh [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+log_must zpool create -O recordsize=4k $TESTPOOL $DISK1 $DISK2
+log_onexit cleanup
+
+log_must fio $FIO_SCRIPTS/mkfiles.fio
+log_must fio $FIO_SCRIPTS/sequential_reads.fio
+
+log_must zpool remove -w $TESTPOOL $DISK2
+log_must zpool attach -w $TESTPOOL $DISK1 $DISK2
+
+errors=$(zpool status $TESTPOOL | grep $TMPDIR | grep -cv '0$')
```
Comment (behlendorf) [inline tests/zfs-tests/tests/functional/removal/remove_attach_mirror.ksh:71]: nit: you could use the `verify_pool` helper function here instead to check for checksum errors.  This would also cause a pool scrub, that might be nice since it would ensure the error is repaired when resilvering and warning suppressed.

**Review by behlendorf — APPROVED** [review]

**Comment by gamanakis** [comment]
67c9b69: use `verify_pool` in the test.
