### PR TITLE
special device removal space accounting fixes

### LINKED ISSUE #9142: Space checking of special device removal is too strict
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Ubuntu
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 0.8+
SPL Version	| 

### Describe the problem you're observing

When removing a special device, sometimes we get an error `cannot remove <devname>: out of space`, when there's actually sufficient free space.  We're especially likely to hit this when the device to remove is mostly empty

The problem is that `spa_vdev_remove_top_check()` does not take into account the free space in the device to be removed.  For example, imagine a pool with 1TB available space (in the normal class, per `zfs list`), and a special device of 1.1TB with 0.1TB allocated.  Logically, there is plenty of free space to move the 0.1TB of allocated space.  However, the check being performed is `special_device_size (1.1TB) < normal_available_space (1TB)` which fails.

The solution is probably to always add the free space of the special class to `available` (not just when there will be some devices left in the class after removal).  In the above example, we should be checking `special_device_size (1.1TB) < normal_available_space (1TB) + special_available_space (1TB)` which will succeed.  This is similar to the logic when removing a normal device, where we check `removing_device_size < normal_available_space`, where `normal_available_space` includes the free space on the removing device.

### Describe how to reproduce the problem

The `alloc_class_013_pos` test operates very close to this limit, so making the dedup device slightly larger, or the zvol slightly larger, or the normal devices slightly smaller, will trigger this.

### Include any warning/errors/backtraces from the system logs

```
static int
spa_vdev_remove_top_check(vdev_t *vd)
{
...
    /* available space in the pool's normal class */
    uint64_t available = dsl_dir_space_available(
        spa->spa_dsl_pool->dp_root_dir, NULL, 0, B_TRUE);

    metaslab_class_t *mc = vd->vdev_mg->mg_class;

    /*
     * When removing a vdev from an allocation class that has
     * remaining vdevs, include available space from the class.
     */
    if (mc != spa_normal_class(spa) && mc->mc_groups > 1) {
        uint64_t class_avail = metaslab_class_get_space(mc) -
            metaslab_class_get_alloc(mc);

        /* add class space, adjusted for overhead */
        available += (class_avail * 94) / 100;
    }

    /*
     * There has to be enough free space to remove the
     * device and leave double the "slop" space (i.e. we
     * must leave at least 3% of the pool free, in addition to
     * the normal slop space).
     */
    if (available < vd->vdev_stat.vs_dspace + spa_get_slop_space(spa)) {
        return (SET_ERROR(ENOSPC));
    }
```

### PR DESCRIPTION
**Pull request by ahrens**
### Motivation and Context

The space in special devices is not included in spa_dspace (or
dsl_pool_adjustedsize(), or the zfs `available` property).  Therefore
there is always at least as much free space in the normal class, as
there is allocated in the special class(es).  And therefore, there is
always enough free space to remove a special device.

### Description

However, the checks for free space when removing special devices did not
take this into account.  This commit corrects that.

Additionally, when removing the 2nd-to-last special device, its space
would not be reallocated to the last remaining special device, because
mc_groups has already been decremented.  That is also fixed.

Closes #9142

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/vdev_removal.c [hunk 1]
```diff
@@ -1976,32 +1976,38 @@ spa_vdev_remove_top_check(vdev_t *vd)
...
-	 * must leave at least 3% of the pool free, in addition to
-	 * the normal slop space).
-	 */
-	if (available < vd->vdev_stat.vs_dspace + spa_get_slop_space(spa)) {
-		return (SET_ERROR(ENOSPC));
+	metaslab_class_t *normal = spa_normal_class(spa);
+	if (mc != normal) {
+		/*
+		 * Space allocated from the special (or dedup) class is
+		 * included in the DMU's space usage, but it not included in
```
Comment (don-brady) [inline module/zfs/vdev_removal.c:1985]: nit - typo "it's"

**Review by don-brady — APPROVED** [review]
LGTM

**Comment by behlendorf** [comment]
There was an unexpected ZTS failure of the `alloc_class_012_pos` test case on FreeBSD 12.  This may be unrelated, but it is suspicious.

```
Tests with results other than PASS that are unexpected:
    FAIL alloc_class/alloc_class_012_pos (expected PASS)

Test: /usr/local/share/zfs/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos (run as root) [00:06] [FAIL]
23:48:57.80 ASSERTION: Removing a special device from a pool succeeds.
23:48:57.82 SUCCESS: disk_setup
23:48:57.98 SUCCESS: zpool create testpool /mnt/device-0 /mnt/device-1 /mnt/device-2 special /mnt/device-3 special /mnt/device-4
23:49:00.07 SUCCESS: display_status testpool
23:49:00.17 SUCCESS: zfs create -o special_small_blocks=32K -o recordsize=32K testpool/testfs
23:49:00.40 SUCCESS: dd if=/dev/urandom of=/testpool/testfs/testfile.1 bs=1M count=25
23:49:00.84 SUCCESS: dd if=/dev/urandom of=/testpool/testfs/testfile.2 bs=1M count=50
23:49:02.18 SUCCESS: dd if=/dev/urandom of=/testpool/testfs/testfile.3 bs=1M count=75
23:49:03.77 SUCCESS: dd if=/dev/urandom of=/testpool/testfs/testfile.4 bs=1M count=100
23:49:04.01 SUCCESS: zpool sync testpool
23:49:04.02 SUCCESS: sync_pool testpool
23:49:04.02 NAME              SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
23:49:04.02 testpool         3.75G   269M  3.49G        -         -     0%     7%  1.00x    ONLINE  -
23:49:04.02   /mnt/device-0   960M     6M   954M        -         -     0%  0.62%      -  ONLINE  
23:49:04.02   /mnt/device-1   960M     6M   954M        -         -     0%  0.62%      -  ONLINE  
23:49:04.02   /mnt/device-2   960M  6.12M   954M        -         -     0%  0.63%      -  ONLINE  
23:49:04.02 special              -      -      -        -         -      -      -      -  -
23:49:04.02   /mnt/device-3   480M   121M   359M        -         -     2%  25.3%      -  ONLINE  
23:49:04.02   /mnt/device-4   480M   129M   351M        -         -     2%  26.9%      -  ONLINE  
23:49:04.03 SUCCESS: zpool list -v testpool
23:49:04.04 awk: can't open file { # find DVAs from string "offset level dva" only for L0 (data) blocks if (match($0,"L0 [0-9]+")) { dvas[0]=$3 dvas[1]=$4 dvas[2]=$5 for (i = 0; i < 3; ++i) { if (match(dvas[i],"([^:]+):.*")) { dva = substr(dvas[i], RSTART, RLENGTH); # parse DVA from string "vdev:offset:asize" if (split(dva,arr,":") != 3) { print "Error parsing DVA: <" dva ">"; exit 1; } # verify vdev is "special" if (arr[1] < d) { exit 1; } } } }} source line number 1
23:49:04.04 ERROR: file_in_special_vdev testpool/testfs 2 exited 2
```

File: tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh [hunk 2]
```diff
@@ -33,8 +33,9 @@ function file_in_special_vdev # <dataset> <inode>
 {
 	typeset dataset="$1"
 	typeset inum="$2"
+	typeset num_normal=$(echo $ZPOOL_DISKS | wc -w)
```
Comment (freqlabs) [inline tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh:36]: BSD's `wc` output has a leading tab so this screws up the awk command below. Here's how I usually fix that:
```suggestion
	typeset num_normal=$(echo $ZPOOL_DISKS | wc -w | xargs)
```

Comment (ahrens) [reply tests/zfs-tests/tests/functional/alloc_class/alloc_class_012_pos.ksh]: Thanks for pointing this out!  Would have been very tricky for me to diagnose.

**Comment by ahrens** [comment]
The FreeBSD failure is:
```
20:47:33.90 /usr/local/share/zfs/zfs-tests/tests/functional/cli_root/zpool_initialize/zpool_initialize_verify_initialized.ksh: line 79:  / 512: arithmetic syntax error
```
It looks like either $offset or $size is the empty string?  Perhaps because zdb isn't outputting what it expects?  I don't think this is related to my changes.

**Comment by behlendorf** [comment]
Yes, it's unrelated and has recently started failing consistently.  The a draft PR #11328 open which is investigating the issue.

**Review by behlendorf — APPROVED** [review]

File: module/zfs/vdev_removal.c [hunk 3]
```diff
@@ -1976,32 +1976,38 @@ spa_vdev_remove_top_check(vdev_t *vd)
...
+		    spa->spa_dsl_pool->dp_root_dir, NULL, 0, B_TRUE);
+		if (available <
+		    vd->vdev_stat.vs_dspace + spa_get_slop_space(spa)) {
+			/*
+			 * This is a normal device. There has to be enough free
+			 * space to remove the device and leave double the
+			 * "slop" space (i.e. we must leave at least 3% of the
+			 * pool free, in addition to the normal slop space).
+			 */
+			return (SET_ERROR(ENOSPC));
```
Comment (behlendorf) [inline module/zfs/vdev_removal.c:2009]: While we're here can we refine this calculation.  For very small pools we can hit this case even for newly created empty pools.  See this https://github.com/openzfs/zfs/issues/11356#issue-769273678 for an example.

Comment (ahrens) [reply module/zfs/vdev_removal.c:2009]: That feels out of scope here to me (e.g. I'm not changing the behavior of removing normal-class devices, and I haven't done any manual testing of that).  What specific change would you like to see here?

Comment (behlendorf) [reply module/zfs/vdev_removal.c:2009]: I was hoping you might have a good suggestion.  This has been reported a couple of times now and probably will continue to be until we do something to address it.  But I agree it's really is out of scope for this so I'm fine not tackling it here.
