### PR TITLE
zpool: fix conflict with -v and -o options

### LINKED ISSUE #11040: zpool list -v disregards other options
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Linux Kernel	|
Architecture	| amd64
ZFS Version	| zfs-2.0.0-rc3
SPL Version	|

### Describe the problem you're observing
`zpool list -v -o name,health` displays the requested fields for the pool but then also displays the full verbose output for vdevs. This seems to have been the case for quite some time, I don't think it is a recent regression.

https://jira.ixsystems.com/browse/NAS-107222

### Describe how to reproduce the problem
```
root@truenas[~]# zpool list -v -o name,health
NAME                                            HEALTH
boot-pool                                       ONLINE
  ada0p2                                       936G  50.5G   886G        -         -     0%  5.39%      -  ONLINE
storage                                         ONLINE
  gptid/36101666-46ac-11ea-9231-f01faf47a547   944G  30.0G   914G        -         -     0%  3.17%      -  ONLINE
```

### PR DESCRIPTION
**Pull request by Shreshth3**
Fixes #11040.

Right now, the -v and -o options for `zpool list` work independently, but when paired, the -v "wins out" and the -o effect is lost. This commit fixes that problem.

<details>
<summary>Before my change:</summary>

~~~bash
(master) ~/zfs$ ./zpool list -v -o name,health mypool
NAME          HEALTH
mypool        ONLINE
  mirror-0   960M   110K   960M        -         -     2%  0.01%      -    ONLINE
    loop17     1G      -      -        -         -      -      -      -    ONLINE
    loop18     1G      -      -        -         -      -      -      -    ONLINE
~~~

</details>

<details>
<summary>After my change:</summary>

~~~bash
(v-o-option-conflict) ~/zfs$ ./zpool list -v -o name,health mypool
NAME          HEALTH
mypool        ONLINE
  mirror-0    ONLINE
    loop17    ONLINE
    loop18    ONLINE
~~~

</details>

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Quality assurance (non-breaking change which makes the code more robust against bugs)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: cmd/zpool/zpool_main.c [hunk 1]
```diff
@@ -7031,48 +7030,100 @@ collect_list_stats(zpool_handle_t *zhp, const char *name, nvlist_t *nv,
...
+				    toplevel),
+				    format, cb->cb_json, props,
+				    cb->cb_json_as_int);
+				break;
+
+			case ZPOOL_PROP_CAPACITY:
+				cap =
+				    (vs->vs_space == 0)
+				    ? 0
+				    : (vs->vs_alloc * 10000 / vs->vs_space);
```
Comment (amotin) [inline cmd/zpool/zpool_main.c]: Couldn't we make it more compact here and in other places?  We do have 80 columns for last 30+ years. ;)

Comment (Shreshth3) [reply cmd/zpool/zpool_main.c]: Do you have any advice for a good setup to handle code formatting? I spent quite a bit of time trying to get a good setup, but haven't found anything that works well. I was going for format-on-save based a local .clang-format file. But with that setup, when I make my changes and save, it's re-formatting lines throughout the entire file.

Would be curious what you or any other maintainers do for code formatting. Thank you in advance!

Comment (robn) [reply cmd/zpool/zpool_main.c]: Unfortunately none of the code formatters around appear able to express the exact style, though some come very close. You should run `make cstyle` (or the script under it, `scripts/cstyle.pl`) as often as you can, which will definitely tell you when you've broken the "rules", such as they are.

For things like continuation line layout (the topic here), `cstyle` doesn't have a lot to say except that you get within 80 chars, and that your leading tabs and spaces look right. It won't care too much about where the lines are split and how many. Most people seem to just compress them into as few lines as possible; I usually try a few variations to balance concision with readability, but it can get pretty difficult sometimes.

This one, I would probably do:

```c
			case ZPOOL_PROP_CAPACITY:
				cap = (vs->vs_space == 0) ?
				    0 : (vs->vs_alloc * 10000 / vs->vs_space);
```

I personally prefer to finish lines with an operator if I have the choice, and this is arguably readable as the possible outcomes are grouped together on the same line. If the computation had gone longer than 80, I probably would tried to at least avoid breaking the parens, and so made it more like:

```c
			case ZPOOL_PROP_CAPACITY:
				cap = (vs->vs_space == 0) ? 0 :
				    (vs->vs_alloc * 10000 / vs->vs_space);
```

Sorry that's so vague; it's just what we've inherited. I'd would personally love to develop a (say) clang-format file that expresses most of what we have, and then we just take the defaults on the rest (in fact, I _have_ developed most of this config a few times). The last bits though, that it doesn't support, needs a little thinking through and then someone to make the arguments and get the feedback and consensus and push it over the line.

Comment (Shreshth3) [reply cmd/zpool/zpool_main.c]: Thank you very much for the detailed reply, I very much appreciate it!

I went through and manually made the lines more compact where I could. Although, we are many levels of indentation in, in some places there isn't much space before we hit the 80 column limit. Let me know if you see any places where I could make things tighter, or if there are any other changes I should make.

**Review by Shreshth3 — COMMENTED** [review]
I believe I made the necessary changes.

**Review by amotin — COMMENTED** [review]
Looking closer, while it does look like a step in a right direction, I think we should go further now.  For example, `dedup` field has nothing to do with vdevs, but it is present in this code.  Same time `bclone_ratio` absent here is not printed properly:
```
mav@genoa2:~# zpool list -v -o name,dedup,bclone_ratio,health optane
NAME       DEDUP  BCLONE_RATIO    HEALTH
optane     1.00x         1.00x    ONLINE
  nvd0p1       -    ONLINE
  nvd10p1      -    ONLINE
  nvd11p1      -    ONLINE
  nvd12p1      -    ONLINE
  nvd13p1      -    ONLINE
  nvd1p1       -    ONLINE
  nvd2p1       -    ONLINE
  nvd3p1       -    ONLINE
  nvd4p1       -    ONLINE
  nvd5p1       -    ONLINE
  nvd6p1       -    ONLINE
  nvd7p1       -    ONLINE
  nvd8p1       -    ONLINE
  nvd9p1       -    ONLINE
```
Can we remove explicit mention of not applicable properties, but instead handle them all universally?

**Comment by Shreshth3** [comment]
@amotin Made that change. Here is the new output:
```
(v-o-option-conflict) ~/zfs$ ./zpool list -v -o name,dedup,bclone_ratio,health mypool
NAME       DEDUP  BCLONE_RATIO    HEALTH
mypool     1.00x         1.00x    ONLINE
  loop17       -             0    ONLINE
  loop18       -             0    ONLINE
  loop19       -             0    ONLINE
```

Note: the only "not applicable property" I explicitly removed was `dedup`. I looked through the other explicitly mentioned properties, and I believe they are all applicable, though I'm not 100% sure. Let me know if I missed any.

File: cmd/zpool/zpool_main.c [hunk 2]
```diff
@@ -7031,48 +7030,98 @@ collect_list_stats(zpool_handle_t *zhp, const char *name, nvlist_t *nv,
...
+				    scripted, B_TRUE, format, cb->cb_json,
+				    props, cb->cb_json_as_int);
+				break;
+
+			case ZPOOL_PROP_NAME:
+				break;
+
+			default:
+				collect_vdev_prop(pl->pl_prop, 0,
+				    NULL, scripted, toplevel, format,
```
Comment (amotin) [inline cmd/zpool/zpool_main.c]: I am not sure passing `toplevel` as `valid` for unknown properties is right.

Comment (Shreshth3) [reply cmd/zpool/zpool_main.c]: Fixed. New output:
```
(v-o-option-conflict) ~/zfs$ ./zpool list -v -o name,dedup,bclone_ratio,health mypool
NAME       DEDUP  BCLONE_RATIO    HEALTH
mypool     1.00x         1.00x    ONLINE
  loop17       -             -    ONLINE
  loop18       -             -    ONLINE
  loop19       -             -    ONLINE
```

**Review by amotin — APPROVED** [review]
Thanks.

BTW, I have feeling that `bclone_ratio` may actually be applicable to top-level vdevs, since that is where BRT works.  But unless it is trivial, it might be too far out of this PR scope.

**Comment by Shreshth3** [comment]
I took a look at adding `bclone_ratio` to be shown properly for top-level vdevs. I'm happy to make that change, but I do think it would be better to do that in a separate PR.

**Review by behlendorf — APPROVED** [review]

**Comment by justinpryzby** [comment]
@Shreshth3 Not sure the right place to say it, but I think this commit might have an issue with 'special' vdevs.  It seems like '-o' is still ignored in that case.  With the patch applied on top of 2.3.4:

~/src/zfs-linux-2.3.4$ ./zpool list -v -Hpo name,capacity,frag zfs
zfs     74      58
        vdc     74      58
**special        -      -      -        -         -      -      -      -         -**
        vdd     61      86

**Comment by Shreshth3** [comment]
@justinpryzby Thanks for letting me know. I'll take a look now.

**Comment by behlendorf** [comment]
@Shreshth3 did you get a chance to take a look at the issue @justinpryzby mentioned?  If you can sort it out in the next week or so I can pull this change (and fix) in for the 2.4 release.

**Comment by Shreshth3** [comment]
Yes I did. I'm currently working on another issue, so I planned to come back to it after. But I'll switch to working on this issue now, and I'll do my best to get it sorted out in the next week or so.

**Comment by justinpryzby** [comment]
I'm not sure if the zfs devs care, but maybe you should re-open this PR until the fix is merged ?

**Comment by Shreshth3** [comment]
@justinpryzby The special vdevs issue should be fixed in #17932.
