### PR TITLE
ARC: Avoid overflows in arc_evict_adj()

### LINKED ISSUE #17210: arc_summary shows negative value for MFU data target
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Rocky Linux
Distribution Version	| 9.5
Kernel Version	| 5.14.0-503.16.1.el9_5.x86_64
Architecture	| x86_64
OpenZFS Version	| 2.2.7-1

### Describe the problem you're observing
`arc_summary` shows negative value for `MFU data target`:
```
ARC size (current):                                    99.5 %   15.3 GiB
        Target size (adaptive):                       100.0 %   15.4 GiB
        Min size (hard limit):                          6.2 %  984.0 MiB
        Max size (high water):                           16:1   15.4 GiB
        Anonymous data size:                            0.0 %    0 Bytes
        Anonymous metadata size:                      < 0.1 %  768.0 KiB
        MFU data target:                     -77.6 %  -10898862366 Bytes
        MFU data size:                                  0.2 %   30.5 MiB
```

Poking inside `arc_summary` itself, I can see the following lines:
https://github.com/openzfs/zfs/blob/7be9fa259ed711c3b5adde783b85c92caa54007e/cmd/arc_summary#L626-L627

As on this machine `pd` is currently equal to `20883106811`, `v` becomes negative.

### Describe how to reproduce the problem

Not sure. It seems related to ~prefetch, but what does `s` means in this context?~ ARC states balance, related to the fixed-point arithmetic. From my understanding, `pd` or `pm` should never be bigger than `4294967296`

### Include any warning/errors/backtraces from the system logs

None.

### PR DESCRIPTION
**Pull request by amotin**
With certain combinations of target ARC states balance and ghost hit rates it was possible to get the fractions outside of allowed range.  This patch limits maximum balance adjustment speed, which should make it impossible, and also asserts it.

Fixes #17210

### How Has This Been Tested?
It seems pretty hard to reproduce, but if ever happen again asserts should let us know.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/arc.c [hunk 1]
```diff
@@ -4225,15 +4225,17 @@ static uint64_t
...
-	 * may get close.  Restrict maximum adjustment in that case.
+	 * We should not have more ghost hits than ghost size, but they may
+	 * get close.  To avoid overflows below up/down should not be bigger
+	 * than 1/5 of total.  But to limit maximum adjustment speed restrict
+	 * it some more.
 	 */
-	if (up + down >= total / 4) {
-		uint64_t scale = (up + down) / (total / 8);
+	if (up + down >= total / 16) {
+		uint64_t scale = (up + down) / (total / 32);
```
Comment (adamdmoss) [inline module/zfs/arc.c:4238]: IMHO it's quite unclear why these ratios are guaranteed to avoid overflow while the previous ones weren't.  Or how they related to the stated 1/5 (or indeed where the magic 1/5 comes from).

Comment (amotin) [reply module/zfs/arc.c:4238]: The 5 comes from `frac >= 4 * ofrac` below (1 + 4).  There was a window between 1/5 and 1/4 when both `up + down >= total / 4` and `frac >= 4 * ofrac` were false and so neither scaled `up` down, allowing `frac + up` to overflow over `1ULL << 32`.

File: module/zfs/arc.c [hunk 2]
```diff
@@ -4242,6 +4244,7 @@ arc_evict_adj(uint64_t frac, uint64_t total, uint64_t up, uint64_t down,
 	int s = highbit64(total);
 	s = MIN(64 - s, 32);
 
+	ASSERT3U(frac, <=, 1ULL << 32);
```
Comment (ceedriic) [inline module/zfs/arc.c:4247]: is the value 1ULL << 32 (needing 33 bits) really allowed?

Comment (ceedriic) [reply module/zfs/arc.c:4247]: ok thanks, and sorry for the noise. I was wondering because #17210 mentioned "capped at 32 bit".

**Comment by amotin** [comment]
Just a rebase.

**Review by robn — APPROVED** [review]
Looks right. I reckon we could benefit from some macros to make it look a bit more like proper math, but eh, some other day!

**Review by tonyhutter — APPROVED** [review]
