### PR TITLE
Fix zpool status in case of unloaded keys

### LINKED ISSUE #13675: with unloaded key and errlog feature enabled corruption is not shown in zpool status
Tests for #9372 have revealed what seems to be a regression with the `head_errlog` feature.

If we have a corrupted file in an encrypted dataset and we unload the key, then scrub the affected dataset the expected behavior is the corruption should be reported in zpool status.
Instead, the checksum errors are reported but there is nothing that says that there are file(s) corrupted.

### System information
This is seen on the tip of master

### Describe the problem you're observing
Even though the dataset is corrupted after a scrub, `zpool status` output looks like:
```
22:45:43.13   pool: testpool
22:45:43.13  state: ONLINE
22:45:43.13 status: One or more devices has experienced an unrecoverable error.  An
22:45:43.13     attempt was made to correct the error.  Applications are unaffected.
22:45:43.13 action: Determine if the device needs to be replaced, and clear the errors
22:45:43.13     using 'zpool clear' or replace the device with 'zpool replace'.
22:45:43.13    see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-9P
22:45:43.13   scan: scrub repaired 0B in 00:00:00 with 9 errors on Tue Jul 19 22:45:43 2022
22:45:43.13 config:
22:45:43.13
22:45:43.13     NAME        STATE     READ WRITE CKSUM
22:45:43.13     testpool    ONLINE       0     0     0
22:45:43.13       loop3     ONLINE       0     0    18
22:45:43.13
22:45:43.13 errors: No known data errors
22:45:43.13 SUCCESS: zpool status -v testpool
22:45:43.15 ERROR: eval zpool status -v testpool |     grep "Permanent errors have been detected" exited 1
```
Note that `Applications are unaffected` and `No known data errors` messages are not true as the data at this point is permanently corrupted.

The correct output should looks like (and does with `head_errlog=disabled`):
```
22:47:22.26   pool: testpool
22:47:22.26  state: ONLINE
22:47:22.26 status: One or more devices has experienced an error resulting in data
22:47:22.26     corruption.  Applications may be affected.
22:47:22.26 action: Restore the file in question if possible.  Otherwise restore the
22:47:22.26     entire pool from backup.
22:47:22.26    see: https://openzfs.github.io/openzfs-docs/msg/ZFS-8000-8A
22:47:22.26   scan: scrub repaired 0B in 00:00:00 with 9 errors on Tue Jul 19 22:47:22 2022
22:47:22.26 config:
22:47:22.26
22:47:22.26     NAME        STATE     READ WRITE CKSUM
22:47:22.26     testpool    ONLINE       0     0     0
22:47:22.26       loop3     ONLINE       0     0    18
22:47:22.26
22:47:22.26 errors: Permanent errors have been detected in the following files:
22:47:22.26
22:47:22.26         testpool/testfs1:<0x2>
22:47:22.26 SUCCESS: zpool status -v testpool
22:47:22.28 errors: Permanent errors have been detected in the following files:
22:47:22.28 SUCCESS: eval zpool status -v testpool |     grep "Permanent errors have been detected"
```
### Describe how to reproduce the problem
Here is the minimal zfs-test I used to recreate the problem:
```
#!/bin/ksh -p

. $STF_SUITE/include/libtest.shlib

verify_runnable "both"

DISK=${DISKS%% *}

function cleanup
{
        log_must eval "poolexists $TESTPOOL && destroy_pool $TESTPOOL"
        log_must zpool create -f $TESTPOOL $DISK
}

typeset passphrase="password"
typeset file="/$TESTPOOL/$TESTFS1/$TESTFILE0"

log_onexit cleanup

log_must eval "poolexists $TESTPOOL && destroy_pool $TESTPOOL"
log_must zpool create -f -o feature@head_errlog=enabled $TESTPOOL $DISK

log_must eval "echo $passphrase > /$TESTPOOL/pwd"

log_must zfs create -o encryption=aes-256-ccm -o keyformat=passphrase \
    -o keylocation=file:///$TESTPOOL/pwd -o primarycache=none \
    $TESTPOOL/$TESTFS1

log_must dd if=/dev/urandom of=$file bs=1024 count=1024 oflag=sync
log_must eval "echo 'aaaaaaaa' >> "$file

corrupt_blocks_at_level $file 0
log_must zfs unmount $TESTPOOL/$TESTFS1
log_must zfs unload-key $TESTPOOL/$TESTFS1
log_must zpool sync $TESTPOOL
log_must zpool scrub $TESTPOOL
log_must zpool wait -t scrub $TESTPOOL
log_must zpool status -v $TESTPOOL
log_must eval "zpool status -v $TESTPOOL | \
    grep \"Permanent errors have been detected\""
```

### PR DESCRIPTION
**Pull request by gamanakis**
### Motivation and Context

Closes #13675 

### Description

When scrubbing an encrypted filesystem with unloaded key still report an
error in zpool status. In encrypted filesystems witthout loaded keys or unmounted encrypted filesystems we cannot figure out the birth txg of the error block pointer. In this case let zb_birth = 0 and simply report an error in the filesystem since the head_errlog feature is meaningless.

### How Has This Been Tested?
Added a test in ZTS.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by gamanakis** [comment]
@alek-p let me a comment with your copyright and I will gladly add it to the test.

File: include/sys/zio.h [hunk 1]
```diff
@@ -304,6 +304,11 @@ typedef struct zbookmark_err_phys {
 	int64_t		zb_level;
 	uint64_t	zb_blkid;
 	uint64_t	zb_birth;
+	/*
+	 * Currrently used only when dbuf_dnode_findbp() returns EACCES when
+	 * accessing an encrypted filesystem without the key loaded.
+	 */
+	uint64_t	zb_err;
```
Comment (behlendorf) [inline include/sys/zio.h:311]: We should avoid changing the on-disk format if at all possible.  Is this really needed?

File: tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_005_pos.ksh [hunk 2]
```diff
@@ -0,0 +1,78 @@
...
+# 5. Verify we report errors in the pool in 'zpool status -v'
+
+verify_runnable "both"
+
+DISK=${DISKS%% *}
+
+function cleanup
+{
+	log_must zinject -c all
+	datasetexists $TESTPOOL2 && log_must zpool destroy $TESTPOOL2
```
Comment (behlendorf) [inline tests/zfs-tests/tests/functional/cli_root/zpool_status/zpool_status_005_pos.ksh:46]:
```
        destroy_pool $TESTPOOL2
```

Should be sufficient.

**Review by behlendorf — COMMENTED** [review]
When looking at thge CentOS 9 test failure I saw it was due to a deadlock introduced by this change.  Check out the [console log](http://build.zfsonlinux.org/builders/CentOS%209%20x86_64%20%28TEST%29/builds/180/steps/shell_4/logs/console).

File: include/sys/zio.h (hunk 1 above)
Comment (gamanakis) [reply include/sys/zio.h:311]: There might be a way around this, let me take another look.

**Comment by gamanakis** [comment]
I figured out what is going on with the deadlock. Will update soon.

**Review by behlendorf — APPROVED** [review]
Looks good, thanks for looking in to this and addressing my concerns.  It's a bit surprising that the key not only needs to be loaded by the filesystem must also be mounted, but that seems like potentially a separate issue.
