### PR TITLE
Fix a persistent L2ARC bug in l2arc_write_done()

### LINKED ISSUE #10540: NULL pointer dereference panic in l2arc_write_done
### Overview

We've hit a panic in one of our ZTS runs within Delphix that looks like this:
```
[ 5725.945826]: sd 0:0:0:0: [sda] Synchronizing SCSI cacheSUBSYSTEM=scsi
[ 5725.957189]: zio pool=testpool vdev=/dev/sda1 error=5 type=2 offset=4195328 size=512 flags=808c0
[ 5725.958054]: zio pool=testpool vdev=/dev/sda1 error=5 type=1 offset=270336 size=8192 flags=b08c1
[ 5725.958055]: zio pool=testpool vdev=/dev/sda1 error=5 type=2 offset=4195840 size=512 flags=808c0
[ 5725.958061]: zio pool=testpool vdev=/dev/sda1 error=5 type=1 offset=89661440 size=8192 flags=b08c1
[ 5725.958064]: zio pool=testpool vdev=/dev/sda1 error=5 type=1 offset=89923584 size=8192 flags=b08c1
[ 5725.958221]: BUG: kernel NULL pointer dereference, address: 0000000000000000
[ 5725.963630]: #PF: supervisor read access in kernel mode
[ 5725.967210]: #PF: error_code(0x0000) - not-present page
[ 5725.970043]: PGD 0 P4D 0 \L.5
[ 5725.971565]: Oops: 0000 [#1] SMP NOPTI
[ 5725.973599]: CPU: 0 PID: 374 Comm: l2arc_feed Kdump: loaded Tainted: P           OE     5.3.0-1023-aws #25~18.04.1-Ubuntu.5
[ 5725.979780]: Hardware name: Amazon EC2 t3.large/, BIOS 1.0 10/16/2015/5
[ 5725.983472]: RIP: 0010:l2arc_write_done+0x264/0x460 [zfs]Sk^/5
[ 5725.986122]: Code: 48 89 df e8 0e f7 ff ff 41 8b 85 2c 03 00 00 85 c0 74 4a 48 8b 45 c0 48 8d 98 e0 00 01 00 48 89 df e8 00 c1 ff ff 4c 8b 7d 80 <48> 8b 30 ba 40 00 00 00 49 89 c4 49 8d 7f 48 e8 38 06 cd d5 4c 89
[ 5726.000898]: RSP: 0000:ffffafa3803e3c78 EFLAGS: 00010246
[ 5726.005057]: RAX: 0000000000000000 RBX: ffff9abb7a3100e0 RCX: 0000000000000000
[ 5726.010768]: RDX: ffff9abbd4e50000 RSI: ffff9abbcd764ca0 RDI: ffff9abb7a3100f0
[ 5726.016246]: RBP: ffffafa3803e3cf8 R08: 0000000000000001 R09: ffffffffc042ec00
[ 5726.021676]: R10: ffffafa393cbbda8 R11: 0000000000000000 R12: ffff9abb7a3100e0
[ 5726.028781]: R13: ffff9abb1d4f7a80 R14: 0000000000000000 R15: ffff9abb1568a600
[ 5726.035019]: FS:  0000000000000000(0000) GS:ffff9abbf8600000(0000) knlGS:0000000000000000p35
[ 5726.059737]: CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[ 5726.064404]: CR2: 0000000000000000 CR3: 00000001c3964005 CR4: 00000000007606f0
[ 5726.069862]: DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[ 5726.075040]: DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[ 5726.080297]: PKRU: 55555554
[ 5726.083298]: Call Trace:
[ 5726.086426]:  zio_done+0x3d3/0xdd0 [zfs]
[ 5726.090284]:  ? __raw_spin_unlock+0x9/0x10 [zfs]
[ 5726.094284]:  zio_wait+0xd2/0x230 [zfs]
[ 5726.098266]:  l2arc_write_buffers+0x4ce/0x710 [zfs]
[ 5726.102720]:  l2arc_feed_thread+0x13e/0x250 [zfs]-"65
[ 5726.107148]:  ? l2arc_remove_vdev+0x1a0/0x1a0 [zfs]
[ 5726.111404]:  thread_generic_wrapper+0x74/0x90 [spl]
[ 5726.120834]:  kthread+0x121/0x140Ʈ75
[ 5726.125272]:  ? __thread_exit+0x20/0x20 [spl]L75
[ 5726.129507]:  ? kthread_park+0xb0/0xb0
[ 5726.133666]:  ret_from_fork+0x1f/0x40mg85
```

### Specifics

We don't have the exact test where this situation came up but looking at the ZTS log we have an idea that it is probably one of the first tests within `tests/functional/faults/`:
```
02:33:12  Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/fallocate/fallocate_punch-hole (run as root) [00:00] [PASS]
02:33:12  Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/fallocate/cleanup (run as root) [00:00] [PASS]
02:33:12  Test (Linux): /usr/share/zfs/zfs-tests/tests/functional/fault/setup (run as root) [00:00] [PASS]
02:35:16  ...<jenkins error> -> java.nio.channels.ClosedChannelException...
```

I managed to do some preliminary RCA having captured a crash dump. The exact stack trace of the panicked thread is the following:
```
#0  0xffffffffc05714b4 in memmove (size=<optimized out>, q=<optimized out>, p=<optimized out>)
#1  0xffffffffc05714b4 in l2arc_write_done (zio=0xffff9abb1d4f7a80)
#2  0xffffffffc066e2e3 in zio_done (zio=0xffff9abb1d4f7a80)
#3  0xffffffffc066b742 in __zio_execute (zio=0xffff9abb1d4f7a80)
#4  0xffffffffc066b742 in zio_wait (zio=0xffff9abb1d4f7a80)
#5  0xffffffffc057a29e in l2arc_write_buffers (spa=<optimized out>, dev=0xffff9abb7a300000, target_sz=<optimized out>)
#6  0xffffffffc057b26e in l2arc_feed_thread (unused=<optimized out>)
#7  0xffffffffc0435a34 in thread_generic_wrapper (arg=0xffff9abbd3be6ac0)
#8  0xffffffff958c1981 in kthread (_create=0xffff9abbd3be6240)
#9  0xffffffff964001ff in ret_from_fork ()
```

Looking at the disassembly the relevant code in `l2arc_write_done()` where the panic occurred is the following:
```
	if (zio->io_error != 0) {
		/* restore the lbps array in the header to its previous state */
		lb_ptr_buf = list_head(&dev->l2ad_lbptr_list);
		for (int i = 0; i < 2; i++) {
			bcopy(lb_ptr_buf->lb_ptr, &l2dhdr->dh_start_lbps[i],
			    sizeof (l2arc_log_blkptr_t));
			lb_ptr_buf = list_next(&dev->l2ad_lbptr_list,
			    lb_ptr_buf);
		}
	}
```

For linux we have `bcopy` defined to `memmove` which matches our stack trace, so I looked into the arguments that we pass to `bcopy` with the debugger by introspecting the fields of the zio (address: `0xffff9abb1d4f7a80`) passed as an argument to `l2arc_write_done()`. I discovered that `io_error` is non-zero as expected (its value was 6) and that `&dev->l2ad_lbptr_list` is an empty list. Since that list is empty `list_head()` is returning NULL and thus `lb_ptr_buf` is set to NULL. When `lb_ptr_buf` is later dereferenced we blow up.

Snippets from SDB repl:
```> zfs_dbgmsg
...
arc.c:10017:l2arc_dev_hdr_update(): L2ARC IO error (6) while writing device header, vdev guid: 1827210309281626946

sdb> echo 0xffff9abb1d4f7a80 | cast zio_t * | member io_error
(int)6

> echo 0xffff9abb1d4f7a80 | cast zio_t * | member io_private | cast l2arc_write_callback_t * | member l2wcb_dev.l2ad_lbptr_list | address | walk
...<no output>...
```

The code mentioned above seems to have been introduced by 657fd33bcff17e44ad55dffdf294d7c107b4bf5d :
```
commit 657fd33bcff17e44ad55dffdf294d7c107b4bf5d
Author: George Amanakis <gamanakis@gmail.com>
Date:   Thu May 7 19:34:03 2020 -0400

    Improvements on persistent L2ARC

    Functional changes:

    We implement refcounts of log blocks and their aligned size on the
    cache device along with two corresponding arcstats. The refcounts are
    reflected in the header of the device and provide valuable information
    as to whether log blocks are accounted for correctly. These are
    dynamically adjusted as log blocks are committed/evicted. zdb also uses
    ...
```

### PR DESCRIPTION
**Pull request by gamanakis**
In case l2arc_write_done() handles a zio that was not successful check
that the list of log block pointers is not empty when restoring them
in the device header. Otherwise zero them out. In any case perform the
actual write updating the device header after the zio of
l2arc_write_buffers() completes as l2arc_write_done() may have touched
the memory holding the log block pointers in the device header.

Signed-off-by: George Amanakis <gamanakis@gmail.com>

### Motivation and Context

Closes #10540.

### Description

See above.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/arc.c [hunk 1]
```diff
@@ -8018,9 +8018,27 @@ l2arc_write_done(zio_t *zio)
...
+				 * block pointer in the header.
+				 */
+				if (i == 0) {
+					bzero(l2dhdr, dev->l2ad_dev_hdr_asize);
+				} else {
+					bzero(&l2dhdr->dh_start_lbps[i],
+					    sizeof (l2arc_log_blkptr_t));
+				}
+				break;
+			}
```
Comment (sdimitro) [inline module/zfs/arc.c:8041]: I'm confused by this:
```
		for (int i = 0; i < 2; i++) {
			if (lb_ptr_buf == NULL) {
				/*
				 * If the list is empty zero out the device
				 * header. Otherwise zero out the second log
				 * block pointer in the header.
				 */
				if (i == 0) {
					bzero(l2dhdr, dev->l2ad_dev_hdr_asize);
				} else {
					bzero(&l2dhdr->dh_start_lbps[i],
					    sizeof (l2arc_log_blkptr_t));
				}
				break;
			}
```
It says if the list is empty zero out the device, otherwise (meaning if the list is not empty?) zero out the second log.

What I'm reading from the code is that if the list is empty first zero out the device header, then zero out `&l2dhdr->dh_start_lbps[i]`.

Comment (gamanakis) [reply module/zfs/arc.c:8041]: I will clarify the comment in the code. The device header has two pointers to the two most recently written log blocks (L2ARC metadata). The for loop serves restore them in their previous state, as the current zio failed (and thus did not write any log blocks).

We enter the for loop. If `lb_ptr_buf` is NULL --> this means the `l2ad_lbptr_list` is empty. So we zero out the whole device header, including both log block pointers, as there are no valid log blocks.

However if `l2ad_lbptr_list` contains only one log block pointer, then the first entry l2dhdr->dh_start_lbps[0] is set to that.
Then the for loop iterates, so now i=1. Since `l2ad_lbptr_list` contains only one entry, `l2ad_ptr_buf` is going to be NULL this time around. Then only the second log block pointer in the device header l2ad_lbptr_list[1] is going to be zeroed out.
Does this make sense?

I will improve that comment.

Comment (sdimitro) [reply module/zfs/arc.c:8041]: Ah! That makes sense. I completely missed the `list_next` at the end of the loop and got confused. Marking as resolved.
