### PR TITLE
gcc 11 cleanup

### LINKED ISSUE #12130: zfs/hkdf.c:81: possible wrong sized buffer ?
In function ‘hkdf_sha512_expand’,
    inlined from ‘hkdf_sha512’ at ../../module/zfs/hkdf.c:165:8:
../../module/zfs/hkdf.c:81:24: warning: ‘crypto_mech2id’ accessing 32 bytes in a region of size 16 [-Wstringop-overflow=]
   81 |         mech.cm_type = crypto_mech2id(SUN_CKM_SHA512_HMAC);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../module/zfs/hkdf.c: In function ‘hkdf_sha512’:
../../module/zfs/hkdf.c:81:24: note: referencing argument 1 of type ‘char *’

### LINKED ISSUE #12188: Error building - crypto_mech_name_t
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora
Distribution Version	| fc34
Linux Kernel	|  5.12.8-300-fc34-x86_64
Architecture	| x86_64
ZFS Version	| master, as in f97142c74801a15c4e3840722502d279d1913fb5
SPL Version	| same

### Describe the problem you're observing
Cannot build a new release.  Last release built and installed is
```
zfs-2.1.99-159_g2babd2004
zfs-kmod-2.1.99-159_g2babd2004
```

Latest version has probably been compiled with `gcc-10.3.1`, now I have `gcc-11.1.1`. This can be the real reason, since there is no error to build dkms or kmod.

### Describe how to reproduce the problem

```
git checkout master
./autogen.sh
./configure --enable-silent-rules --enable-dependency-tracking --config-cache \
    --enable-linux-builtin --disable-nls --with-config=all --enable-debuginfo \
    --enable-debug --enable-debug-kmem --enable-debug-kmem-tracking
make
```

### Include any warning/errors/backtraces from the system logs

```
  CC       api/kcf_miscapi.lo
  CC       api/kcf_mac.lo
  CC       algs/aes/aes_impl_aesni.lo
../../module/icp/api/kcf_miscapi.c:65:22: error: argument 1 of type 'char *' declared as a pointer [-Werror=array-parameter=]
   65 | crypto_mech2id(char *mechname)
      |                ~~~~~~^~~~~~~~
In file included from ../../module/icp/api/kcf_miscapi.c:28:
../../include/sys/crypto/api.h:61:61: note: previously declared as an array 'char[32]'
   61 | extern crypto_mech_type_t crypto_mech2id(crypto_mech_name_t name);
      |                                          ~~~~~~~~~~~~~~~~~~~^~~~
cc1: all warnings being treated as errors
  CC       algs/aes/aes_impl_generic.lo
make[5]: *** [Makefile:1159: api/kcf_miscapi.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/tmp/zfs-build-jonny-uISReS3q/BUILD/zfs-2.1.99/lib/libicp'
make[4]: *** [Makefile:708: all-recursive] Error 1
make[4]: Leaving directory '/tmp/zfs-build-jonny-uISReS3q/BUILD/zfs-2.1.99/lib'
```

I tried this kick patch:

```
diff --git i/module/icp/api/kcf_miscapi.c w/module/icp/api/kcf_miscapi.c
index c0f415b26..80cbfc8a5 100644
--- i/module/icp/api/kcf_miscapi.c
+++ w/module/icp/api/kcf_miscapi.c
@@ -62,7 +62,7 @@ static kcf_ntfy_elem_t *ntfy_list_head;
  *     CRYPTO_MECH_INVALID otherwise.
  */
 crypto_mech_type_t
-crypto_mech2id(char *mechname)
+crypto_mech2id(crypto_mech_name_t mechname)
 {
        return (crypto_mech2id_common(mechname, B_TRUE));
 }
```

Just to catch another error, later:

```
make[3]: Entering directory '/root/zfs/zfs/lib/libzfs'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/zfs/zfs/lib/libzfs'
Making all in libzpool
make[3]: Entering directory '/root/zfs/zfs/lib/libzpool'
  CC       hkdf.lo
../../module/zfs/hkdf.c: In function ‘hkdf_sha512_extract’:
../../module/zfs/hkdf.c:34:24: error: ‘crypto_mech2id’ accessing 32 bytes in a region of size 16 [-Werror=stringop-overflow=]
   34 |         mech.cm_type = crypto_mech2id(SUN_CKM_SHA512_HMAC);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../module/zfs/hkdf.c:34:24: note: referencing argument 1 of type ‘char *’
In file included from ../../module/zfs/hkdf.c:20:
../../include/sys/crypto/api.h:61:27: note: in a call to function ‘crypto_mech2id’
   61 | extern crypto_mech_type_t crypto_mech2id(crypto_mech_name_t name);
      |                           ^~~~~~~~~~~~~~
../../module/zfs/hkdf.c: In function ‘hkdf_sha512_expand’:
../../module/zfs/hkdf.c:81:24: error: ‘crypto_mech2id’ accessing 32 bytes in a region of size 16 [-Werror=stringop-overflow=]
   81 |         mech.cm_type = crypto_mech2id(SUN_CKM_SHA512_HMAC);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../module/zfs/hkdf.c:81:24: note: referencing argument 1 of type ‘char *’
In file included from ../../module/zfs/hkdf.c:20:
../../include/sys/crypto/api.h:61:27: note: in a call to function ‘crypto_mech2id’
   61 | extern crypto_mech_type_t crypto_mech2id(crypto_mech_name_t name);
      |                           ^~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [Makefile:1325: hkdf.lo] Error 1
make[3]: Leaving directory '/root/zfs/zfs/lib/libzpool'
make[2]: *** [Makefile:708: all-recursive] Error 1

```

I would submit a PR if I had any idea on how to fix this, but I'm afraid to change something cryptic in crypto (pun intended 😄).

### PR DESCRIPTION
**Pull request by AttilaFueloep**
### Motivation and Context

Building with gcc 11.1.0 fails due to warnings.

### Description

Disable false positive warnings, fix a wrong prototype. 

Closes #12130
Closes #12188

### How Has This Been Tested?

Just a local build.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by AttilaFueloep** [comment]
Not sure if the `#pragma` approach is acceptable, if not please advice.

@felixdoerre Shouldn't we check the return value of `mlock()` in `contrib/pam_zfs_key/pam_zfs_key.c`?

**Comment by felixdoerre** [comment]
Yes, probably we should treat a failure in `mlock` like an allocation failure and just free `pw->value` and `pw` and return `NULL`.

**Comment by AttilaFueloep** [comment]
A bit more detail. 

Not sure where the warning in `contrib/pam_zfs_key/pam_zfs_key.c` is comming from, the code indicates that `pw` can't be used uninitialized. Neither casting the return value to `(void)` nor casting  the first argument of `mlock()`  to `(const void *)` got rid of the warning.

```
pam_zfs_key.c: In function ‘alloc_pw_string’:
pam_zfs_key.c:107:16: error: ‘<unknown>’ may be used uninitialized [-Werror=maybe-uninitialized]
  107 |         (mlock(pw->value, pw->len);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ../../include/sys/zfs_context.h:106,
                 from ../../include/sys/dmu.h:45,
                 from ../../include/sys/dmu_tx.h:33,
                 from ../../include/sys/dsl_crypt.h:23,
                 from pam_zfs_key.c:28:
/usr/include/sys/mman.h:103:12: note: by argument 1 of type ‘const void *’ to ‘mlock’ declared here
  103 | extern int mlock (const void *__addr, size_t __len) __THROW;
      |            ^~~~~
```

The extern declaration in `include/sys/crypto/api.h` does not match the definition in `module/icp/api/kcf_misc_api.c`

```
../../module/icp/api/kcf_miscapi.c:65:22: error: argument 1 of type ‘char *’ declared as a pointer [-Werror=array-parameter=]
   65 | crypto_mech2id(char *mechname)
      |                ~~~~~~^~~~~~~~
In file included from ../../module/icp/api/kcf_miscapi.c:28:
../../include/sys/crypto/api.h:61:61: note: previously declared as an array ‘char[32]’
   61 | extern crypto_mech_type_t crypto_mech2id(crypto_mech_name_t name);
      |                                          ~~~~~~~~~~~~~~~~~~~^~~~
```


The warnings in `module/os/linux/zfs/zio_crypt.c` stem from the fact that we truncated the dnode to 64 bytes to get rid of the non-portable union at the end. Since we don't access the union it's a false positive.

```
../../module/os/linux/zfs/zio_crypt.c:1060:54: error: array subscript ‘dnode_phys_t {aka struct dnode_phys}[0]’ is partly outside array bounds of ‘uint8_t[64]’ {aka ‘unsigned char[64]’} [-Werror=array-bounds]
 1060 |                 adnp->dn_datablkszsec = BSWAP_16(adnp->dn_datablkszsec);
      |                                                      ^~
...
```

**Comment by AttilaFueloep** [comment]
@felixdoerre All right, will open a PR once this is merged.

**Comment by dioni21** [comment]
Aren't we just hiding the real problems with the above patch?  I can also compile if I simply disable the `-Werror` option, but the warning may have something important to say.

In particular, I do not like the idea of using a generic `char *` when we have a better restrained type `crypto_mech_name_t`

**Comment by dioni21** [comment]
BTW: You do not have to make another PR, just add new commits (even forced ones) to the same branch ([AttilaFueloep:zfs-icp-gcc11](https://github.com/AttilaFueloep/zfs/tree/zfs-icp-gcc11)).

**Comment by AttilaFueloep** [comment]
@dioni21 
> Aren't we just hiding the real problems with the above patch?

https://github.com/openzfs/zfs/blob/83ba91adf6c0b4b1a5b0f0a6f3e84d267e689915/module/icp/api/kcf_miscapi.c#L44-L49

So a `char *` is adequate. It is cast to a `void *` later on anyhow.

> BTW: You do not have to make another PR

PRs should be limited to fixing distinct problems.

**Comment by behlendorf** [comment]
> Not sure if the #pragma approach is acceptable, if not please advice.

As a general rule we have tried to avoid using `#pragma GCC diagnostic` and have only fallen back to it as a last resort (which was needed in a few cases).

I briefly looked at the `alloc_pw_string()` function and I'm not sure why gcc is claiming it can be used uninitialized.  That doesn't look possible to me, perhaps the code could be changed slightly so it gets the analysis right.

**Comment by AttilaFueloep** [comment]
Given the weird location of the arrow (`^~~~`) at `mlock` and the `error: ‘<unknown>’` text, I've the impression that something else is going on. I'll try to shuffle the code a bit, let's see if it helps. That leaves the truncated dnode problem, not sure what to change there to get gcc happy.

**Comment by AttilaFueloep** [comment]
> That leaves the truncated dnode problem,

Well, I could introduce a new struct, say `dnode_trunc` and cast the array to that. Not sure if this is worthwhile though.

**Comment by AttilaFueloep** [comment]
Managed to get rid of the `#pragma`s. Reshuffling the code in `pam_zfs_key.c` didn't help, I ended up zeroing `pw->value` before calling `mlock()` on it. I think this shouldn't be too bad.

**Comment by dioni21** [comment]
> Reshuffling the code in `pam_zfs_key.c` didn't help, I ended up zeroing `pw->value` before calling `mlock()` on it. I think this shouldn't be too bad.

Not bad, but hurts my brain optimizer.  :-)

Did you try a cast to `(const void *) ` when calling `mlock`?

Or, at least, use `calloc` instead of `malloc` + `memset`.

And in `extern crypto_mech_type_t crypto_mech2id(char *name);` I would also use `const char *`

Anyway, this may be just me doing yet another [bikeshedding](https://exceptionnotfound.net/bikeshedding-the-daily-software-anti-pattern/).   :-(

Thanks for your effort, @AttilaFueloep !

**Comment by AttilaFueloep** [comment]
@dioni21 

> Did you try a cast to `(const void *) ` when calling `mlock`?

Yep.

> Or, at least, use `calloc` instead of `malloc` + `memset`.

Yeah, good idea.

> And in `extern crypto_mech_type_t crypto_mech2id(char *name);` I would also use `const char *`

While I generally agree, this would involve refactoring the whole call chain, which I think is outside the scope of this PR.

File: include/sys/dnode.h [hunk 1]
```diff
@@ -268,6 +269,29 @@ typedef struct dnode_phys {
 	};
 } dnode_phys_t;
 
+/*
+ * This structure holds only the portable fields of a dnode_phys_t, i.e.
+ * all fields but excluding the variable sized tail region. It is used to
+ * calculate the HMAC of a dnode_phys_t in zio_crypt_do_dnode_hmac_updates().
```
Comment (ahrens) [inline include/sys/dnode.h:275]: It seems a little unfortunate to have to duplicate this.  Could we embed it in the dnode_phys_t instead?  Though I guess since it's on-disk it won't be changing very often.

Comment (AttilaFueloep) [reply include/sys/dnode.h:275]: Yes, that was my concern and reasoning as well. I do type embedding frequently in Go but I failed to figure how to do it in C without requiring  Microsoft extensions (gcc/clang `-fms-extensions` flag). Even in C11 you can't have an anonymous struct
member of a previously defined type. Am I missing something obvious here? Or are you thinking of doing some `#define` ?

Comment (ahrens) [reply include/sys/dnode.h:275]: I think the cleanest way is to do something like
```
struct dnode_phys {
    dnode_phys_core_t dn_core;
    union {
        ...
   }
}
```

The downside is that you have to change all the code that's accessing it to add `.dn_core` :( .  (And the "solution" to that of doing `#define dn_type dn_core.dn_type` seems worse.)

I'm guessing that the compiler's complaint about the current code is that you have a `dnode_phys_t*` that points to an array that is not large enough to hold a dnode_phys_t.  I think the proposed solution is decent but I wonder if there's another way to do this.  Maybe if we allocated a larger buffer to point to (might have to be on the heap due to the linux kernel's limited stack space).  That would be a little slower but it might not be significantly so.

Comment (AttilaFueloep) [reply include/sys/dnode.h:275]: > The downside is that you have to change all the code that's accessing it to add `.dn_core` :( . (And the "solution" to that of doing `#define dn_type dn_core.dn_type` seems worse.)

Yeah, fully agree. It would be so nice if we could just say
```
struct dnode_phys {
    struct dnode_phys_core;
    union {
        ...
   }
}
```

but well, maybe in ten years, using C23, that'll work. ;-)

> I'm guessing that the compiler's complaint about the current code is that you have a `dnode_phys_t*` that points to an array that is not large enough to hold a dnode_phys_t.

Exactly, `‘dnode_phys_t {aka struct dnode_phys}[0]’ is partly outside array bounds`. The full warning is [here](https://github.com/openzfs/zfs/pull/12237#issuecomment-860797080) at the bottom.

>  Maybe if we allocated a larger buffer to point to

That didn't occur to me, but your right, using a `dnode_phys_t` and just limiting the HMAC calculation to the first 64 bytes of that may be a cleaner solution. IIRC the stack size in Linux is 16k and a `dnode_phys_t` is 512 bytes,  so limited stack space shouldn't be a concern. The only drawbacks I can see is 448 more bytes on the stack and maybe slightly less clearer code. I'll push a changed version. Which approach to choose I leave up to you, I'm fine either way.

**Review by behlendorf — APPROVED** [review]
It's unfortunate we need to use the additional space on the stack for this, but I agree it shouldn't be a problem here.  Things are a bit tighter on i386 with uses 8k stacks, but I believe we'll still be OK there as well.  This does seem like the cleanest way to handle this to me.

**Comment by AttilaFueloep** [comment]
All right.  I'll hold-up squashing until a second reviewer had a chance to look at it.

**Review by ahrens — APPROVED** [review]

**Comment by ahrens** [comment]
Thanks for doing that, looks great!

**Comment by AttilaFueloep** [comment]
My pleasure. Squashed, rebased and updated commit comment.
