### PR TITLE
Enforce "-F" flag on resuming recv of full/newfs on existing dataset

### LINKED ISSUE #13856: Resuming receive of full/newfs on existing dataset doesn't enforce "-F" flag and effectively hits assert/panic
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	|
Architecture	|
OpenZFS Version	|

### Describe the problem you're observing

When receiving full/newfs on existing dataset, then it should be done with "-F" flag. Its enforced for initial
 receive in checks done in zfs_receive_one function of libzfs. Similarly, on resuming full/new recv on existing dataset,
 it should be done with "-F" flag, but it's not enforced.
 If resume receive of full/newfs receive on existing dataset is done, then it asssert/panics.

### Describe how to reproduce the problem

Test/Repro steps:

$truncate -s 100M /home/jiten/disk-1
$ sudo zpool create testpool /home/jiten/disk-1
$ sudo zfs create testpool/testfs
$ sudo zfs create -oreadonly=on testpool/dstfs
$ sudo zfs snapshot testpool/testfs@snap1
$ 

$ sudo zfs send -v -c testpool/testfs@snap1 >stream.full
TIME       BYTES   SNAPSHOT testpool/testfs@snap1
full send of testpool/testfs@snap1 estimated size is 12.6K
total estimated size is 12.6K
TIME        SENT   SNAPSHOT testpool/testfs@snap1
$ ls -l stream.full 
-rw-rw-r--. 1 jiten jiten 45264 Sep  8 07:56 stream.full

$ truncate -s 30K stream.full 
$ ls -l stream.full 
-rw-rw-r--. 1 jiten jiten 30720 Sep  8 07:57 stream.full

$ cat stream.full |sudo zfs recv -sv testpool/dstfs
cannot receive new filesystem stream: destination 'testpool/dstfs' exists
must specify -F to overwrite it

$ cat stream.full |sudo zfs recv -svF testpool/dstfs
receiving full stream of testpool/testfs@snap1 into testpool/dstfs@snap1
cannot receive new filesystem stream: checksum mismatch or incomplete stream.
Partially received snapshot is saved.
A resuming stream can be generated on the sending system by running:
    zfs send -t 1-1460efcfae-148-789c636064000310a500c4ec50360710e72765a526973030a8409460caa7a515a79630c001489e0d493ea9b224b51848efc8c2aebf243fbd3433858121a460e9e21b96ce5c0648f29c60f9bcc4dc54209d5a5c52909f9fa30f62a4153b14e725161842cde36640b83f393fb7a028b5b8383f1bbb7dc945259920f3746e482683e435a0f6c0e4538a8ad27212d38b61fe1160e060e4c1e6efe292ca02a0394c08af33000076ff297d

$ sudo zfs send -t 1-1460efcfae-148-789c636064000310a500c4ec50360710e72765a526973030a8409460caa7a515a79630c001489e0d493ea9b224b51848efc8c2aebf243fbd3433858121a460e9e21b96ce5c0648f29c60f9bcc4dc54209d5a5c52909f9fa30f62a4153b14e725161842cde36640b83f393fb7a028b5b8383f1bbb7dc945259920f3746e482683e435a0f6c0e4538a8ad27212d38b61fe1160e060e4c1e6efe292ca02a0394c08af33000076ff297d |sudo zfs recv -sv testpool/dstfs
receiving full stream of testpool/testfs@snap1 into testpool/dstfs@snap1

This resuming recv with token triggers Assert/Panic:

[  390.200051] VERIFY3(ds->ds_dir != spa_get_dsl(spa)->dp_origin_snap->ds_dir) failed (ffff8e9c33471000 != ffff8e9c33471000)
[  390.200199] PANIC at dmu_objset.c:471:dmu_objset_open_impl()
[  390.200272] Kernel panic - not syncing: VERIFY3(ds->ds_dir != spa_get_dsl(spa)->dp_origin_snap->ds_dir) failed (ffff8e9c33471000 != ffff8e9c33471000)

….
[  390.200573] Call Trace:
[  390.200642]  dump_stack+0x6d/0x8b
[  390.200697]  panic+0xe4/0x247
[  390.200770]  spl_panic+0x104/0x110 [spl]
[  390.201789]  dmu_objset_open_impl+0xb0d/0xc10 [zfs]
[  390.201983]  ? rrw_enter_read_impl+0x139/0x230 [zfs]
[  390.202150]  dmu_objset_from_ds+0x122/0x280 [zfs]
[  390.202294]  dsl_dataset_modified_since_snap+0xd8/0x130 [zfs]
[  390.202679]  dsl_dataset_clone_swap_check_impl+0x148/0x2a0 [zfs]
[  390.202888]  dmu_recv_end_check+0x1fc/0x2c0 [zfs]
[  390.203209]  dsl_sync_task_common+0x17d/0x290 [zfs]
[  390.204054]  dsl_sync_task+0x26/0x30 [zfs]
[  390.204250]  dmu_recv_existing_end+0x61/0x80 [zfs]
[  390.205238]  dmu_recv_end+0x89/0xc0 [zfs]
[  390.205385]  zfs_ioc_recv_impl+0xcf9/0x1080 [zfs]
[  390.205627]  zfs_ioc_recv_new+0x309/0x390 [zfs]
[  390.211467]  zfsdev_ioctl_common+0x493/0x910 [zfs]
[  390.212329]  zfsdev_ioctl+0x56/0xe0 [zfs]
[  390.213040]  do_vfs_ioctl+0xa8/0x620
[  390.214388]  SyS_ioctl+0x79/0x90
[  390.215031]  do_syscall_64+0x79/0x1b0
[  390.215688]  entry_SYSCALL_64_after_hwframe+0x41/0xa6
[  390.216439] RIP: 0033:0x7f73aaea2307
[  390.217102] RSP: 002b:00007ffca861c348 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[  390.217862] RAX: ffffffffffffffda RBX: 0000000000005a46 RCX: 00007f73aaea2307
[  390.218501] RDX: 00007ffca861c390 RSI: 0000000000005a46 RDI: 0000000000000004
[  390.219124] RBP: 00007ffca861f980 R08: 0000000000040000 R09: 0000000000020000
[  390.219816] R10: 000000000000007b R11: 0000000000000246 R12: 00007ffca861c390
[  390.220546] R13: 00007ffca861fa00 R14: 0000000000005a46 R15: 000000000080c150

### Include any warning/errors/backtraces from the system logs

[  390.200051] VERIFY3(ds->ds_dir != spa_get_dsl(spa)->dp_origin_snap->ds_dir) failed (ffff8e9c33471000 != ffff8e9c33471000)
[  390.200199] PANIC at dmu_objset.c:471:dmu_objset_open_impl()
[  390.200272] Kernel panic - not syncing: VERIFY3(ds->ds_dir != spa_get_dsl(spa)->dp_origin_snap->ds_dir) failed (ffff8e9c33471000 != ffff8e9c33471000)

….
[  390.200573] Call Trace:
[  390.200642]  dump_stack+0x6d/0x8b
[  390.200697]  panic+0xe4/0x247
[  390.200770]  spl_panic+0x104/0x110 [spl]
[  390.201789]  dmu_objset_open_impl+0xb0d/0xc10 [zfs]
[  390.202150]  dmu_objset_from_ds+0x122/0x280 [zfs]
[  390.202294]  dsl_dataset_modified_since_snap+0xd8/0x130 [zfs]
[  390.202679]  dsl_dataset_clone_swap_check_impl+0x148/0x2a0 [zfs]
[  390.202888]  dmu_recv_end_check+0x1fc/0x2c0 [zfs]
[  390.203209]  dsl_sync_task_common+0x17d/0x290 [zfs]
[  390.204054]  dsl_sync_task+0x26/0x30 [zfs]
[  390.204250]  dmu_recv_existing_end+0x61/0x80 [zfs]
[  390.205238]  dmu_recv_end+0x89/0xc0 [zfs]
[  390.205385]  zfs_ioc_recv_impl+0xcf9/0x1080 [zfs]
[  390.205627]  zfs_ioc_recv_new+0x309/0x390 [zfs]
[  390.211467]  zfsdev_ioctl_common+0x493/0x910 [zfs]
[  390.212329]  zfsdev_ioctl+0x56/0xe0 [zfs]
[  390.213040]  do_vfs_ioctl+0xa8/0x620
[  390.214388]  SyS_ioctl+0x79/0x90
[  390.215031]  do_syscall_64+0x79/0x1b0
[  390.215688]  entry_SYSCALL_64_after_hwframe+0x41/0xa6
[  390.216439] RIP: 0033:0x7f73aaea2307
[  390.217102] RSP: 002b:00007ffca861c348 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
[  390.217862] RAX: ffffffffffffffda RBX: 0000000000005a46 RCX: 00007f73aaea2307
[  390.218501] RDX: 00007ffca861c390 RSI: 0000000000005a46 RDI: 0000000000000004
[  390.219124] RBP: 00007ffca861f980 R08: 0000000000040000 R09: 0000000000020000
[  390.219816] R10: 000000000000007b R11: 0000000000000246 R12: 00007ffca861c390

### PR DESCRIPTION
**Pull request by jsai20**
When receiving full/newfs on existing dataset, then it should be done with "-F" flag. Its enforced for initial receive in checks done in zfs_receive_one function of libzfs. Similarly, on resuming full/newfs recv on existing dataset, it should be done with "-F" flag.

When dataset doesn't exist, then full/new recv is done on newly created dataset and it's marked INCONSISTENT. But when receiving on existing dataset, recv is first done on %recv and its marked INCONSISTENT. Existing dataset is not marked INCONSISTENT. Resume of full/newfs receive with dataset not INCONSISTENT indicates that its resuming newfs on existing dataset. So, enforce "-F" flag in this case.

Signed-off-by: Jitendra Patidar <jitendra.patidar@nutanix.com>
Closes #13856

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by jsai20** [comment]
Validation with this patch:

Validate “resume” of new/full fs on existing dataset without “-F” flag fails with error and no assert/panic seen.

$ zfs get receive_resume_token testpool/dstfs
NAME PROPERTY VALUE SOURCE
testpool/dstfs receive_resume_token 1-1460efcfae-148-789c636064000310a500c4ec50360710e72765a526973030a8409460caa7a515a79630c001489e0d493ea9b224b51848efc8c2aebf243fbd3433858121a460e9e21b96ce5c0648f29c60f9bcc4dc54209d5a5c52909f9fa30f62a4153b14e725161842cde36640b83f393fb7a028b5b8383f1bbb7dc945259920f3746e482683e435a0f6c0e4538a8ad27212d38b61fe1160e060e4c1e6efe292ca02a0394c08af33000076ff297d -
$ sudo zfs send -t 1-1460efcfae-148-789c636064000310a500c4ec50360710e72765a526973030a8409460caa7a515a79630c001489e0d493ea9b224b51848efc8c2aebf243fbd3433858121a460e9e21b96ce5c0648f29c60f9bcc4dc54209d5a5c52909f9fa30f62a4153b14e725161842cde36640b83f393fb7a028b5b8383f1bbb7dc945259920f3746e482683e435a0f6c0e4538a8ad27212d38b61fe1160e060e4c1e6efe292ca02a0394c08af33000076ff297d |sudo zfs recv -sv testpool/dstfs
cannot receive resume stream: destination 'testpool/dstfs' exists
must specify -F to overwrite it
$

Validate with "-F" it succeedes.

$ sudo zfs send -t 1-1460efcfae-148-789c636064000310a500c4ec50360710e72765a526973030a8409460caa7a515a79630c001489e0d493ea9b224b51848efc8c2aebf243fbd3433858121a460e9e21b96ce5c0648f29c60f9bcc4dc54209d5a5c52909f9fa30f62a4153b14e725161842cde36640b83f393fb7a028b5b8383f1bbb7dc945259920f3746e482683e435a0f6c0e4538a8ad27212d38b61fe1160e060e4c1e6efe292ca02a0394c08af33000076ff297d |sudo zfs recv -svF testpool/dstfs
receiving full stream of testpool/testfs@snap1 into testpool/dstfs@snap1
received 34.2K stream in 0.10 seconds (349K/sec)
$

Validate that “resume” of new/full fs with no existing dataset, doesn’t need “-F” flag.

$ sudo zfs destroy -r testpool/dstfs

$ ls -l stream.full
-rw-rw-r--. 1 jiten jiten 30720 Sep 8 07:57 stream.full
$ cat stream.full |sudo zfs recv -sv testpool/dstfs
receiving full stream of testpool/testfs@snap1 into testpool/dstfs@snap1
cannot receive new filesystem stream: checksum mismatch or incomplete stream.
Partially received snapshot is saved.
A resuming stream can be generated on the sending system by running:
zfs send -t 1-1460efcfae-148-789c636064000310a500c4ec50360710e72765a526973030a8409460caa7a515a79630c001489e0d493ea9b224b51848efc8c2aebf243fbd3433858121a460e9e21b96ce5c0648f29c60f9bcc4dc54209d5a5c52909f9fa30f62a4153b14e725161842cde36640b83f393fb7a028b5b8383f1bbb7dc945259920f3746e482683e435a0f6c0e4538a8ad27212d38b61fe1160e060e4c1e6efe292ca02a0394c08af33000076ff297d
$

$ sudo zfs send -t 1-1460efcfae-148-789c636064000310a500c4ec50360710e72765a526973030a8409460caa7a515a79630c001489e0d493ea9b224b51848efc8c2aebf243fbd3433858121a460e9e21b96ce5c0648f29c60f9bcc4dc54209d5a5c52909f9fa30f62a4153b14e725161842cde36640b83f393fb7a028b5b8383f1bbb7dc945259920f3746e482683e435a0f6c0e4538a8ad27212d38b61fe1160e060e4c1e6efe292ca02a0394c08af33000076ff297d |sudo zfs recv -sv testpool/dstfs
receiving full stream of testpool/testfs@snap1 into testpool/dstfs@snap1
received 34.2K stream in 0.07 seconds (476K/sec)
$

File: lib/libzfs/libzfs_sendrecv.c [hunk 1]
```diff
@@ -4638,6 +4638,33 @@ zfs_receive_one(libzfs_handle_t *hdl, int infd, const char *tosnap,
...
+		if (stream_resumingnewfs &&
+		    !zfs_prop_get_int(zhp, ZFS_PROP_INCONSISTENT) &&
+		    !flags->force) {
+			zfs_close(zhp);
+			zfs_error_aux(hdl, dgettext(TEXT_DOMAIN,
+			    "destination '%s' exists\n"
+			    "must specify -F to overwrite it"), name);
+			err = zfs_error(hdl, EZFS_EXISTS, errbuf);
+			goto out;
+		}
```
Comment (behlendorf) [inline lib/libzfs/libzfs_sendrecv.c:4666]: This check needs to be done in the kernel, otherwise it'll still be possible to panic the system in this way.  You can add a new `zfs_errno_t` for this case.

**Review by behlendorf — CHANGES_REQUESTED** [review]
Thanks for investigating this, your analysis looks right to me.  Just a few comments.

Please update and add your nice test case from #13856 to the ZTS for this PR.

**Comment by behlendorf** [comment]
@jsai20 if you're already working in this area, you may also be interested in 13598.

**Comment by jsai20** [comment]
> Thanks for investigating this, your analysis looks right to me. Just a few comments.
> 
> Please update and add your nice test case from #13856 to the ZTS for this PR.
Ok

File: lib/libzfs/libzfs_sendrecv.c (hunk 1 above)
Comment (jsai20) [reply lib/libzfs/libzfs_sendrecv.c:4666]: Ok.  For initial receive, Kernel does return "EEXIST" error  via dmu_recv_being_check()->recv_begin_check_existing_impl() , when full/newfs recv is done on Existing dataset without force flag.
I would add a similar check in dmu_recv_resume_begin_check() to return EEXIST error.

I would also check about new zfs_errno_t and message.

**Comment by jsai20** [comment]
> @jsai20 if you're already working in this area, you may also be interested in 13598.
I would check, but not sure, if I understand it well.

File: lib/libzfs/libzfs_sendrecv.c (hunk 1 above)
Comment (jsai20) [reply lib/libzfs/libzfs_sendrecv.c:4666]: Added new error code "ZFS_ERR_RESUME_EXISTS" in zfs_errno_t and returning it from kernel for this case.
And handling in libzfs for this error code.

**Review by behlendorf — APPROVED** [review]

**Review by tuxoko — APPROVED** [review]
