### PR TITLE
Teach zdb about DMU_OT_ERROR_LOG objects

### LINKED ISSUE #14434: zloop fails with zdb: leaked MOS object (persistent error log)
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	|
Architecture	|
OpenZFS Version	| 9cd71c8604d52def22ffaddc35755712f0fb9349

### Describe the problem you're observing
When running zloop, sometimes zdb fails due to detecting leaked objects:
```
MOS object 733 (persistent error log) leaked
MOS object 734 (persistent error log) leaked
```
It's possible that this is a bug in zdb: it might need to be taught about the new DMU_OT_ERROR_LOG objects that were introduced by #12812 (cc @gamanakis).  e.g. in dump_mos_leaks(), we simply call `mos_obj_refd(spa->spa_errlog_last)`, but now the spa_errlog_last contains a mapping from objset id to another DMU_OT_ERROR_LOG object, which also needs to be marked as in-use.

### Describe how to reproduce the problem
zloop.sh

### PR DESCRIPTION
**Pull request by gamanakis**
### Motivation and Context
Closes #14434 

### Description
With the persistent error log feature we need to account for spa_errlog_{scrub, last} containing mappings to other error log objects, which need to be marked as in-use as well.

### How Has This Been Tested?
./scripts/zloop.sh

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: cmd/zdb/zdb.c [hunk 1]
```diff
@@ -7509,6 +7509,18 @@ mos_leak_log_spacemaps(spa_t *spa)
 		mos_obj_refd(sls->sls_sm_obj);
 }
 
+static void
+traverse_errorlog(objset_t *mos, uint64_t errlog)
+{
+	zap_cursor_t zc;
+	zap_attribute_t za;
+	for (zap_cursor_init(&zc, mos, errlog);
+	    zap_cursor_retrieve(&zc, &za) == 0; zap_cursor_advance(&zc)) {
```
Comment (behlendorf) [inline cmd/zdb/zdb.c:7518]: nit: the convention used elsewhere is to put `zap_cursor_advance(&zc)` on its own line.

**Review by behlendorf — APPROVED** [review]
Thanks for sorting this out!

File: cmd/zdb/zdb.c [hunk 2]
```diff
@@ -7527,8 +7539,15 @@ dump_mos_leaks(spa_t *spa)
...
 	mos_obj_refd(spa->spa_feat_for_write_obj);
 	mos_obj_refd(spa->spa_history);
-	mos_obj_refd(spa->spa_errlog_last);
-	mos_obj_refd(spa->spa_errlog_scrub);
+
+	if (!spa_feature_is_enabled(spa, SPA_FEATURE_HEAD_ERRLOG)) {
+		mos_obj_refd(spa->spa_errlog_last);
+		mos_obj_refd(spa->spa_errlog_scrub);
+	} else {
+		traverse_errorlog(mos, spa->spa_errlog_last);
```
Comment (ahrens) [inline cmd/zdb/zdb.c:7547]: don't we need to mark the `spa_errlog_last` object itself as refd?  i.e. this should look like

```
mos_obj_refd(spa->spa_errlog_last);
mos_obj_refd(spa->spa_errlog_scrub);

if (spa_feature_is_enabled(spa, SPA_FEATURE_HEAD_ERRLOG)) {
 	traverse_errorlog(mos, spa->spa_errlog_last);
	traverse_errorlog(mos, spa->spa_errlog_scrub);
}
```

File: cmd/zdb/zdb.c [hunk 3]
```diff
@@ -7509,6 +7509,18 @@ mos_leak_log_spacemaps(spa_t *spa)
 		mos_obj_refd(sls->sls_sm_obj);
 }
 
+static void
+traverse_errorlog(objset_t *mos, uint64_t errlog)
```
Comment (ahrens) [inline cmd/zdb/zdb.c:7513]: maybe rename this to something like `errorlog_count_refd`, similar to `bpobj_count_refd`?

Comment (gamanakis) [reply cmd/zdb/zdb.c:7513]: Sure!

File: cmd/zdb/zdb.c (hunk 2 above)
Comment (gamanakis) [reply cmd/zdb/zdb.c:7547]: you are correct, will fix.

**Comment by gamanakis** [comment]
296cdce: implemented all suggestions, thank you!
