### PR TITLE
Fix setting the large_block feature after receiving a snapshot

### LINKED ISSUE #13699: per dataset large_block feature detection not reliable when sending raw encrypted large block ds
Tests for https://github.com/openzfs/zfs/pull/9372 have revealed what seems to be a bug (race ?) with the `large_blocks` zpool feature.

If we have a raw send of an encrypted dataset with large blocks present the send often fails with `warning: cannot send 'testpool/testfs5@snap1': large blocks detected but large_blocks feature is inactive; raw send unsupported` message even though the dataset in question has large block and has the feature active.

This behavior is not consistent and re-running the same test sometimes does pass and sometimes does not.

### System information
This is seen on the tip of master

### Describe the problem you're observing
Sometimes the code fails to detect that the dataset has support for large blocks and sometimes it doesn't.

A failure looks like:
```
20:49:46.93 SUCCESS: eval zfs send -L testpool/testfs1@snap1 > /var/tmp/backup
20:49:47.28 SUCCESS: eval zfs recv -o encryption=aes-256-ccm -o keyformat=passphrase     -o keylocation=file:///testpool/pwd -o primarycache=none     -o recordsize=1m testpool/testfs5 < /var/tmp/backup
20:49:47.31 warning: cannot send 'testpool/testfs5@snap1': large blocks detected but large_blocks feature is inactive; raw send unsupported
20:49:47.31 ERROR: eval zfs send --raw testpool/testfs5@snap1 > /var/tmp/raw_backup exited 1
```
When the same test succeeds it looks like:
```
20:49:57.12 SUCCESS: eval zfs send -L testpool/testfs1@snap1 > /var/tmp/backup
20:49:57.48 SUCCESS: eval zfs recv -o encryption=aes-256-ccm -o keyformat=passphrase     -o keylocation=file:///testpool/pwd -o primarycache=none     -o recordsize=1m testpool/testfs5 < /var/tmp/backup
20:49:57.51 SUCCESS: eval zfs send --raw testpool/testfs5@snap1 > /var/tmp/raw_backup
```

I spend a little time debugging this and noticed that https://github.com/openzfs/zfs/blob/master/module/zfs/dmu_send.c#L1019-L1020 doesn't always have `dsc_featureflags` set correctly.

If you run with this patch
```
diff --git a/module/zfs/dmu_send.c b/module/zfs/dmu_send.c
index 5e6ced2bb..b70002361 100644
--- a/module/zfs/dmu_send.c
+++ b/module/zfs/dmu_send.c
@@ -1965,8 +1965,9 @@ setup_featureflags(struct dmu_send_params *dspp, objset_t *os,
 #endif

        /* raw sends imply large_block_ok */
-       if ((dspp->rawok || dspp->large_block_ok) &&
-           dsl_dataset_feature_is_active(to_ds, SPA_FEATURE_LARGE_BLOCKS)) {
+       if (dspp->rawok || dspp->large_block_ok) {
+           zfs_dbgmsg("%d",(dsl_dataset_feature_is_active(to_ds, SPA_FEATURE_LARGE_BLOCKS)));
+           if (dsl_dataset_feature_is_active(to_ds, SPA_FEATURE_LARGE_BLOCKS))
                *featureflags |= DMU_BACKUP_FEATURE_LARGE_BLOCKS;
        }
```
You can see that `dsl_dataset_feature_is_active(to_ds, SPA_FEATURE_LARGE_BLOCKS)` is not reliable and will sometime return 0 and other times return 1.
I also noticed that the dataset object passed to `load_zfeature()` seems to be different for passing vs not passing tests.

### Describe how to reproduce the problem
Here is the minimal zfs-test I used to recreate the problem:
```
#!/bin/ksh -p

. $STF_SUITE/include/libtest.shlib

verify_runnable "both"

DISK=${DISKS%% *}

backup=$TEST_BASE_DIR/backup
raw_backup=$TEST_BASE_DIR/raw_backup

function cleanup
{
        log_must rm -f $backup $raw_backup $ibackup $unc_backup

        log_must eval "poolexists $TESTPOOL && destroy_pool $TESTPOOL"
        log_must zpool create -f $TESTPOOL $DISK
}

log_onexit cleanup

typeset passphrase="password"
typeset file="/$TESTPOOL/$TESTFS1/$TESTFILE0"

log_must eval "poolexists $TESTPOOL && destroy_pool $TESTPOOL"
log_must zpool create -f -o feature@head_errlog=disabled \
    -o feature@large_blocks=enabled $TESTPOOL $DISK

log_must eval "echo $passphrase > /$TESTPOOL/pwd"

log_must zfs create -o recordsize=1m -o primarycache=none \
    -o atime=off -o compression=lz4 $TESTPOOL/$TESTFS1

log_must dd if=/dev/urandom of=$file bs=1024 count=1024 oflag=sync

log_must zfs snapshot $TESTPOOL/$TESTFS1@snap1

log_must eval "zfs send -L $TESTPOOL/$TESTFS1@snap1 > $backup"

log_must eval "zfs recv -o encryption=aes-256-ccm -o keyformat=passphrase \
    -o keylocation=file:///$TESTPOOL/pwd -o primarycache=none \
    -o recordsize=1m $TESTPOOL/testfs5 < $backup"
log_must eval "zfs send --raw $TESTPOOL/testfs5@snap1 > $raw_backup"
```

### PR DESCRIPTION
**Pull request by gamanakis**
### Motivation and Context

Closes #13699 

### Description

We are not allowed to dirty a filesystem when done receiving
a snapshot. In this case the flag SPA_FEATURE_LARGE_BLOCKS will
not be set on that filesystem since the fs is not on
dp_dirty_datasets. Thus a subsequent encrypted raw send will fail.

### How Has This Been Tested?

Added a test in ZTS.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by gamanakis** [comment]
I just rebased this to master, where commit https://github.com/openzfs/zfs/commit/80a650b7bb04bce3aef5e4cfd1d966e3599dafd4 was reverted. It resolves the panic the added test causes otherwise. 

@behlendorf I also tested moving the `dsl_dataset_activate_feature()` part to the end of `dmu_objset_write_done()` or `dsl_dataset_block_born()` (as @bwatkinson suggested), but those do not resolve this issue. I believe the present PR is the way to go.

**Comment by bwatkinson** [comment]
> I just rebased this to master, where commit https://github.com/openzfs/zfs/commit/80a650b7bb04bce3aef5e4cfd1d966e3599dafd4 was reverted. It resolves the panic the added test causes otherwise. 
> 
> 
> 
> @behlendorf I also tested moving the `dsl_dataset_activate_feature()` part to the end of `dmu_objset_write_done()` or `dsl_dataset_block_born()` (as @bwatkinson suggested), but those do not resolve this issue. I believe the present PR is the way to go.

Yeah, I was hopefully my suggestion would work, but I was obviously wrong lol. Out of curiosity, if you add back your ASSERT's in dsl_scan_visitbp() are they ever hit with this PR? Just want to make sure there is still not an underlying race condition that exists. Your ASSERT's showed there is one. I honestly liked those to be honest.

**Comment by gamanakis** [comment]
bed1d66 : Re-added the ASSERTS in `dsl_scan_visitbp()`.

**Comment by bwatkinson** [comment]
>  bed1d66 : Re-added the ASSERTS in `dsl_scan_visitbp()`.

@gamanakis does the addition of the ASSERT's to this PR still hit with ztest (zloop.sh)? If so, the race condition you pointed out is still present? I have not examined these code paths for this particular PR carefully, but I think if this PR addresses the issue you point out it might make sense. My overall concern is your ASSERT's make sense and raises a race condition. So there might be two separate issues at play here? I just want to make sure we are not entangling two issues into one.

**Comment by gamanakis** [comment]
`zloop.sh` is still hitting those ASSERTS in `dsl_scan_visitbp()`. Let me try something else.

**Comment by bwatkinson** [comment]
> `zloop.sh` is still hitting those ASSERTs in `dsl_scan_visitbp()`. Let me try something else.

@gamanakis so I was looking at this a bit more today. I think for this PR, you don't need to have those `ASSERT` statements. I think this PR might address the issue you were getting at for this case as you stated. However, I think your original `ASSERT` statements did flag a race condition. So, maybe those `ASSERT`'s along with the commit `move feature_activation to dmu_objset_write_done()` should be in a separate PR. I really do want to emphasize I am no way an expert at these layers in the code. So maybe breaking that part off into a separate PR and having others review it that are more experienced in the DSL and send/recv code makes sense? @behlendorf do you read the code the same way that I do here?

**Comment by gamanakis** [comment]
@bwatkinson you are absolutely correct, thank you for the input. I realized the same thing yesterday, those are two separate issues (the snapshot being received not setting large_blocks, and the race condition). Regarding the race condition your suggestion (moving the feature activatiion to the callback `dmu_objset_write_done()` solves the problem and the ASSERTs are not triggered anymore.

I will clean up this PR and submit another one resolving the race condition.

File: module/zfs/dsl_dataset.c [hunk 1]
```diff
@@ -1757,6 +1757,20 @@ dsl_dataset_snapshot_sync_impl(dsl_dataset_t *ds, const char *snapname,
...
+	 * not be set and a subsequent encrypted raw send will fail. Hence
+	 * activate this feature if needed here.
+	 */
+	spa_feature_t f = SPA_FEATURE_LARGE_BLOCKS;
+	if (zfeature_active(f, ds->ds_feature_activation[f]) &&
+	    !(zfeature_active(f, ds->ds_feature[f]))) {
+		dsl_dataset_activate_feature(dsobj, f,
+		    ds->ds_feature_activation[f], tx);
+		ds->ds_feature[f] = ds->ds_feature_activation[f];
+	}
```
Comment (behlendorf) [inline module/zfs/dsl_dataset.c:1772]: It seems to me we should be processing `ds->ds_feature_activation[f]` for all of the features, like at the end of `dsl_dataset_sync()`.  Otherwise, we still may not correctly enable the `SPA_FEATURE_BLAKE3`, `SPA_FEATURE_SHA512`, `SPA_FEATURE_SKEIN`, `SPA_FEATURE_EDONR`, and `SPA_FEATURE_ZSTD_COMPRESS` features.  Although, I haven't tested this so I may be missing something.

**Review by behlendorf — COMMENTED** [review]
Thanks for running this down

File: module/zfs/dsl_dataset.c (hunk 1 above)
Comment (gamanakis) [reply module/zfs/dsl_dataset.c:1776]: Makes sense, I modified this as you suggested.

**Review by behlendorf — APPROVED** [review]
Thanks for updating this.
