### PR TITLE
Fix sa_add_projid to lookup and update SA_ZPL_DXATTR (avoid DXATTR loss)

### LINKED ISSUE #16287: DXATTR getting lost when sa re-layout happens by setting “projid” on old file/dir after upgrade to SPA_FEATURE_PROJECT_QUOTA
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	| 5.10.194-1.el8
Architecture	|
OpenZFS Version	|  zfs-kmod-2.2.99-1.*.c98295eed

### Describe the problem you're observing
sa_add_projid() gets called via zfs_setattr() for setting project id
on old file/dir, which were created before upgrading to project quota
feature. This function does lookup for all possible SA and update them
all together along with project ID at needed fixed offset. But its
missing lookup and update of SA_ZPL_DXATTR, effectively it losses
SA_ZPL_DXATTR.

### Include any warning/errors/backtraces from the system logs
[project-quota-dxattr-test-log.txt](https://github.com/user-attachments/files/15931730/project-quota-dxattr-test-log.txt)

### PR DESCRIPTION
**Pull request by jsai20**
sa_add_projid() gets called via zfs_setattr() for setting project id on old file/dir, which were created before upgrading to project quota feature. This function does lookup for all possible SA and update them all together along with project ID at needed fixed offset. But its missing lookup and update of SA_ZPL_DXATTR, effectively it losses SA_ZPL_DXATTR.

Signed-off-by: Jitendra Patidar <jitendra.patidar@nutanix.com>
Closes #16287

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by jsai20** [comment]
[project-quota-dxattr-test-log.txt](https://github.com/user-attachments/files/15930186/project-quota-dxattr-test-log.txt)

**Comment by tonyhutter** [comment]
I'm new to this particular bit of code and an trying to understand what is being fixed.  Is it that when you update old, pre-project-quota files with `sa_add_projid()`, that the project ID is not getting set in the SA xattrs, and this PR fixes it?

**Comment by jsai20** [comment]
> @jsai20 I'm new to this particular bit of code and an trying to understand what is being fixed. Is it that when you update old, pre-project-quota files with `sa_add_projid()`, that the project ID is not getting set in the SA xattrs, and this PR fixes it?

@tonyhutter
 Following header comment on sa_add_projid(), explains why sa_add_projid() needed.
/*
 * For the existed object that is upgraded from old system, its ondisk layout
 * has no slot for the project ID attribute. But quota accounting logic needs
 * to access related slots by offset directly. So we need to adjust these old
 * objects' layout to make the project ID to some unified and fixed offset.
 */
#define SA_PROJID_OFFSET        128

So, sa_add_projid() function basically expected to do lookup for all possible existing SA on object, reorder them
to fix offset for project id. And finally update all SA's together. 

sa_add_projid() currently doesn't lookup and update of SA_ZPL_DXATTR, effectively it losses
existing SA_ZPL_DXATTR on object.

**Comment by tonyhutter** [comment]
Ok, so it basically allows you to set project ID on a upgraded pool with xattr=sa.

**Review by tonyhutter — APPROVED** [review]

**Comment by tonyhutter** [comment]
Looking for one more reviewer on this

File: module/zfs/sa.c [hunk 1]
```diff
@@ -2237,6 +2277,7 @@ EXPORT_SYMBOL(sa_bulk_lookup);
 EXPORT_SYMBOL(sa_bulk_lookup_locked);
 EXPORT_SYMBOL(sa_bulk_update);
 EXPORT_SYMBOL(sa_size);
+EXPORT_SYMBOL(sa_size_locked);
```
Comment (robn) [inline module/zfs/sa.c:2280]: Is there a reason to export it? Or just for completeness?

(I don't think we really have any policy for what we export?)

**Review by robn — APPROVED** [review]
I don't know anything about DXATTR, but the logic seems right when compared to the way it's used elsewhere.

A couple of structure nits, but I won't hold it up because of them. Good work, thanks!

File: module/zfs/sa.c [hunk 2]
```diff
@@ -2063,6 +2083,26 @@ sa_update(sa_handle_t *hdl, sa_attr_type_t type,
...
+	if ((error = sa_attr_op(hdl, &bulk, 1, SA_LOOKUP, NULL)) != 0) {
+		return (error);
+	}
+	*size = bulk.sa_size;
+
+	return (0);
+}
+
 int
 sa_size(sa_handle_t *hdl, sa_attr_type_t attr, int *size)
```
[the remark this answers is not in the document]
Comment (jsai20) [reply module/zfs/sa.c]: done

File: module/zfs/sa.c (hunk 1 above)
Comment (jsai20) [reply module/zfs/sa.c]: Not needed. Removed it.

**Comment by jsai20** [comment]
> I don't know anything about DXATTR, but the logic seems right when compared to the way it's used elsewhere.
> 
> A couple of structure nits, but I won't hold it up because of them. Good work, thanks!

Thanks @robn. I just updated a new patch addressing your comments.

**Comment by robn** [comment]
LGTM!
