### PR TITLE
Decouple arc_read_done callback from arc buf instantiation

### LINKED ISSUE #11220: ~20% performance regression on cached reads due to zfetch changes
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	|
Linux Kernel	|
Architecture	|
ZFS Version	| master (at or after https://github.com/openzfs/zfs/commit/af20b97078af7bf4ba7552dff04cc40b643ab72c)
SPL Version	|

### Describe the problem you're observing

Performance of sequential ARC-cached reads with recordsize=8k is ~20% lower than before commit https://github.com/openzfs/zfs/commit/af20b97078af7bf4ba7552dff04cc40b643ab72c.  @tonynguien measured ~3.4GB/s vs ~4.3GB/s.

The problem is that additional CPU time is spent in dbuf_issue_final_prefetch() and callees. Previously, this function called `arc_read(done=NULL)`, so the ARC only needed to ensure the data is in the ARC.  The commit changed this to use a done-func (`dbuf_issue_final_prefetch_done`), which means that the ARC needs to provide the prefetched data, by instantiating an arc_buf_t and decompressing/copying the data.  The additional CPU time required to do this can be significant.

### Describe how to reproduce the problem

Sequential ARC-cached reads (including the test that's in the performance test suite).

cc @mattmacy @adamdmoss

### PR DESCRIPTION
**Pull request by mattmacy**
- Add ARC_FLAG_CALLBACK_ONLY to indicate that a buffer need
  not be instantiated.

This should fix #11220:
~20% performance regression on cached reads due to zfetch changes

Signed-off-by: Matt Macy <mmacy@FreeBSD.org>

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by adamdmoss** [comment]
I think I've asked this before, but do we have perf regression tests?  Even manual ones?

**Comment by mattmacy** [comment]
> I think I've asked this before, but do we have perf regression tests? Even manual ones?
> _edit_: I mean in general, not just for this issue.

`./tests/zfs-tests/tests/perf/regression`

**Comment by adamdmoss** [comment]
How'd I miss that?  Thanks.
Not automated, I presume, if they didn't catch the regression...?

**Comment by behlendorf** [comment]
@adamdmoss they're fairly long running, so not automated as part of the CI yet.

**Comment by gdevenyi** [comment]
Maybe add to the PR checklist?

File: module/zfs/dbuf.c [hunk 1]
```diff
@@ -3050,6 +3050,7 @@ dbuf_issue_final_prefetch(dbuf_prefetch_arg_t *dpa, blkptr_t *bp)
 	ASSERT3U(dpa->dpa_curlevel, ==, BP_GET_LEVEL(bp));
 	ASSERT3U(dpa->dpa_curlevel, ==, dpa->dpa_zb.zb_level);
 	ASSERT(dpa->dpa_zio != NULL);
+	aflags |= ARC_FLAG_CALLBACK_ONLY;
```
Comment (ahrens) [inline module/zfs/dbuf.c:3053]: Can we include this flag when we initialize `aflags` on line 2043?

File: module/zfs/dbuf.c [hunk 2]
```diff
@@ -3050,6 +3050,7 @@ dbuf_issue_final_prefetch(dbuf_prefetch_arg_t *dpa, blkptr_t *bp)
...
 	(void) arc_read(dpa->dpa_zio, dpa->dpa_spa, bp,
 	    dbuf_issue_final_prefetch_done, dpa,
```
Comment (ahrens) [inline module/zfs/dbuf.c:3055]: I think we can remove the call to `arc_buf_destroy()` in `dbuf_issue_final_prefetch_done()`, instead asserting that `abuf` is always NULL.

File: include/sys/arc.h [hunk 3]
```diff
@@ -154,6 +154,11 @@ typedef enum arc_flags
 	 */
 	ARC_FLAG_CACHED_ONLY		= 1 << 22,
 
+	/*
+	 * Don't instantiate an arc_buf_t for arc_read_done.
+	 */
+	ARC_FLAG_CALLBACK_ONLY		= 1 << 23,
```
Comment (ahrens) [inline include/sys/arc.h:160]: The name `CALLBACK_ONLY` doesn't immediately tell you what else could be done that we're excluding by "only" doing the callback (the comment explains it).  I was thinking that `ARC_FLAG_NO_BUF` might be more descriptive of a name.  i.e. "Do not instantiate/provide a buf when invoking the callback".  But I'm OK with the current name if you prefer it.

**Review by ahrens — COMMENTED** [review]
Thanks for addressing this!

**Comment by adamdmoss** [comment]
FYI I've been running with this for a week or so.  I haven't checked relative performance but my system hasn't exploded.

**Comment by tonynguien** [comment]
I ran the sequential cached read tests that initially saw the regression.

Before
128K I/O and 128 threads: 27914 IOPS
1M I/O and 128 threads: 3221 IOPS

With the change
128K I/O and 128 threads: 32144 IOPS
1M I/O and 128 threads: 3638 IOPS

And profiling/flame graph also confirmed dbuf_issue_final_prefetch() is no longer calling arc_buf_alloc() and arc_buf_destroy().

**Review by behlendorf — APPROVED** [review]
