### PR TITLE
zdb: add decryption support

### LINKED ISSUE #11551: zdb -O fails for encrypted datasets
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Void Linux
Distribution Version	| rolling 
Linux Kernel	| 5.10.10_1
Architecture	| x86_64
ZFS Version	| 2.0.1-1
SPL Version	| 2.0.1-1

### Describe the problem you're observing
command `zdb -O` fails for encrypted datasets with `Permission denied` error
### Describe how to reproduce the problem
```
➜  ~ whoami
root
➜  ~ mkdir /mnt/testpool
➜  ~ dd if=/dev/zero of=/tmp/zpooltest.img bs=4M count=256
256+0 records in
256+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 0.302311 s, 3.6 GB/s
➜  ~ zpool create testpool /tmp/zpooltest.img    
➜  ~ zfs create testpool/unencrypted -o mountpoint=/mnt/testpool/unencrypted
➜  ~ zfs create testpool/encrypted -o mountpoint=/mnt/testpool/encrypted -o encryption=aes-256-gcm -o keyformat=passphrase
Enter passphrase:
Re-enter passphrase:
➜  ~ 
➜  ~ touch /mnt/testpool/unencrypted/test
➜  ~ touch /mnt/testpool/encrypted/test
➜  ~ zdb -O testpool/unencrypted test 

    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
         2    1   128K    512      0     512    512    0.00  ZFS plain file
➜  ~ zdb -O testpool/encrypted test  
failed to lookup dataset=testpool/encrypted path=/test: Permission denied
```
### Include any warning/errors/backtraces from the system logs

None observed.

### LINKED ISSUE #12707: zdb -dAdvv hides file attributes (e.g. mode) for encrypted datasets (even when keys are loaded)
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.10
Kernel Version	|  5.13.0
Architecture	| x86_64
OpenZFS Version	|  2.0.6-1ubuntu2

### Describe the problem you're observing

Trying to determine if I'm affected by a data corruption bug (#11474) I had to see if file modes had weird values. Running the test command `zdb -dAdvv $FILESYSTEM | grep 'mode\s\+[0-9]' | sort | uniq -c` I learned that zdb doesn't show this information for encrypted datasets at all. Instead placeholders like "(bonus encrypted)" and "(object encrypted)" are printed even when the dataset keys are loaded and the datasets are mounted.

### Describe how to reproduce the problem

Run `zdb -dAdvv` on an enctypted dataset:
```console
$ sudo zdb -dAdvv $FILESYSTEM
[...]
    Object  lvl   iblk   dblk  dsize  dnsize  lsize   %full  type
       936    1   128K  25.5K     4K      1K  25.5K  100.00  ZFS plain file
                                               176   bonus  System attributes
        dnode flags: USED_BYTES USERUSED_ACCOUNTED USEROBJUSED_ACCOUNTED 
        dnode maxblkid: 0
                (bonus encrypted)
                (object encrypted)
[...]

```

### PR DESCRIPTION
**Pull request by robn**
The approach is straightforward: for dataset ops, if a key was offered, find the encryption root and the various encryption parameters, derive a wrapping key if necessary, and then unlock the encryption root. After that all the regular dataset ops will return unencrypted data, and that's kinda the whole thing.

Resolves #11551, resolves #12707.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: cmd/zdb/zdb.c [hunk 1]
```diff
@@ -3023,6 +3027,117 @@ verify_dd_livelist(objset_t *os)
 	return (0);
 }
 
+static char *key_material = NULL;
```
Comment (lundman) [inline cmd/zdb/zdb.c:3030]: Double-checking, can't use libzfs_crypto's derive, as libzfs is not linked with zdb, only libzfs_core .. ?

File: cmd/zdb/Makefile.am [hunk 2]
```diff
@@ -12,3 +13,5 @@ zdb_LDADD = \
 	libzpool.la \
 	libzfs_core.la \
 	libnvpair.la
+
+zdb_LDADD += $(LIBCRYPTO_LIBS)
```
Comment (lundman) [inline cmd/zdb/Makefile.am:17]: adding openssl for key folding etc, right

**Review by lundman — APPROVED** [review]
After the key stuff, the changes turn out quite small, very nice.

File: cmd/zdb/zdb.c (hunk 1 above)
Comment (robn) [reply cmd/zdb/zdb.c:3030]: Partly that, though I could have just linked it in. The other reason is that in a recovery situation the keylocation might not be valid anymore, eg, you've moved the disks to another machine or sent them to a recovery shop.

File: cmd/zdb/Makefile.am (hunk 2 above)
Comment (robn) [reply cmd/zdb/Makefile.am:17]: Yep!

**Comment by robn** [comment]
@behlendorf for your consideration, thanks.

File: cmd/zdb/zdb.c [hunk 3]
```diff
@@ -3023,6 +3027,117 @@ verify_dd_livelist(objset_t *os)
...
+
+static boolean_t
+zdb_derive_key(dsl_dir_t *dd, uint8_t *key_out)
+{
+	uint64_t keyformat, salt, iters;
+	int i;
+	unsigned char c;
+
+	zap_lookup(dd->dd_pool->dp_meta_objset, dd->dd_crypto_obj,
```
Comment (behlendorf) [inline cmd/zdb/zdb.c:3039]:
```suggestion
	VERIFY0(zap_lookup(dd->dd_pool->dp_meta_objset, dd->dd_crypto_obj,
```

Let's make this `zap_lookup` and the two below in `ZFS_KEYFORMAT_PASSPHRASE` fatal if they fail.

File: cmd/zdb/zdb.c [hunk 4]
```diff
@@ -3023,6 +3027,117 @@ verify_dd_livelist(objset_t *os)
...
+	uint64_t rddobj;
+	int err;
+
+	dp = spa_get_dsl(os->os_spa);
+	dd = os->os_dsl_dataset->ds_dir;
+
+	dsl_pool_config_enter(dp, FTAG);
+	zap_lookup(dd->dd_pool->dp_meta_objset, dd->dd_crypto_obj,
+	    DSL_CRYPTO_KEY_ROOT_DDOBJ, sizeof (uint64_t), 1, &rddobj);
+	dsl_dir_hold_obj(dd->dd_pool, rddobj, NULL, FTAG, &rdd);
```
Comment (behlendorf) [inline cmd/zdb/zdb.c:3096]: VERIFY0() for any return code's which otherwise aren't being checked.  At least then when things go off the rails we'll know where.

**Review by behlendorf — APPROVED** [review]
Thanks for adding this functionality, just a couple comments.

File: tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh [hunk 5]
```diff
@@ -57,7 +57,7 @@ set -A args "create" "add" "destroy" "import fakepool" \
     "add raidz1 fakepool" "add raidz2 fakepool" \
     "setvprop" "blah blah" "-%" "--?" "-*" "-=" \
     "-a" "-f" "-g" "-j" "-n" "-o" "-p" "-p /tmp" \
-    "-t" "-w" "-z" "-E" "-H" "-I" "-J" "-K" \
+    "-t" "-w" "-z" "-E" "-H" "-I" "-J" \
     "-Q" "-R" "-T" "-W"
 
 log_assert "Execute zdb using invalid parameters."
```
Comment (behlendorf) [inline tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh:63]: Let's also add a new `tests/functional/zdb_encrypted.ksh` test case which exercises the command line option and verifies basic functionality.  There are several existing test like `tests/functional/cli_root/zfs_mount/zfs_mount_encrypted.ksh` you can use as a starting point.

File: cmd/zdb/zdb.c (hunk 4 above)
Comment (robn) [reply cmd/zdb/zdb.c]: Good call, done.

File: tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh (hunk 5 above)
Comment (robn) [reply tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh:63]: Done in c66ecbb! We'll see if it passes :sweat_smile:

Comment (behlendorf) [reply tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh:63]: It looks like it worked.  Then I think all that's left is to sort out these few build failures, http://build.zfsonlinux.org/builders/CentOS%207%20x86_64%20%28TEST%29/builds/23556/steps/shell_1/logs/make

Comment (robn) [reply tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh:63]: Most of these are:

```
cmd/zdb/zdb.c: In function 'sublivelist_verify_blkptr':
cmd/zdb/zdb.c:297:4: error: 'for' loop initial declarations are only allowed in C99 mode
    for (int i = 0; i < SPA_DVAS_PER_BP; i++) {
    ^
```

There's only one that's possibly mine:

```
cmd/zdb/zdb.c: In function 'zdb_derive_key':
cmd/zdb/zdb.c:3049:4: warning: format '%x' expects argument of type 'unsigned int *', but argument 3 has type 'unsigned char *' [-Wformat=]
    if (sscanf(&key_material[i], "%02x", &c) != 1)
    ^
```

But even then, I'm copying the same piece of code from [`libzfs_crypto.c`](https://github.com/openzfs/zfs/blob/master/lib/libzfs/libzfs_crypto.c#L162).

I wondered if including `openssl/evp.h` was changing compiler options but `libzfs_crypto.c` also includes that. It shouldn't be a wider build change; I'm adding `LIBCRYPTO_CFLAGS` to zdb but `config.log` says its empty.

So I'm not sure where this is coming from, or why its coming up now. I'm believe you, but you might have to point me at it.

Comment (robn) [reply tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh:63]: Interestingly, FreeBSD builder is failing in a similar shape: http://build.zfsonlinux.org/builders/FreeBSD%20main%20amd64%20%28TEST%29/builds/5668/steps/shell_1/logs/make

Not exactly the same, but C99 warnings in zdb.c.

I wonder if zdb is hooked up to the build in a slightly different way and we're now bumping into something. I'll do a build on FreeBSD at least, see what I can see.

Comment (robn) [reply tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh:63]: Yeah, fine there too, and on FreeBSD 13 clang is a couple of versions behind the one in the buildbot (unlike the CentOS builder, which was GCC 4.5).

So so far this all says "buildbot is weird" but I can't yet imagine a kind of weirdness that gets us here. I'll think on it more today.

(if make was run with `V=1` the compiler flags in use might reveal more?)

Comment (behlendorf) [reply tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh:63]: This appears to be an issue with automake-1.13.4 which is what's used on CentOS 7.  Setting `zdb_CFLAGS` overwrites all of the default `AM_FLAGS` which means `std=gnu99` no longer gets passed.  The same thing can happen with `zdb_CPPFLAGS` so it always includes `AM_CPPFLAGS`.  This small change resolves the issue for me.

```diff
--- a/cmd/zdb/Makefile.am
+++ b/cmd/zdb/Makefile.am
@@ -1,5 +1,5 @@
 zdb_CPPFLAGS = $(AM_CPPFLAGS) $(FORCEDEBUG_CPPFLAGS)
-zdb_CFLAGS   = $(LIBCRYPTO_CFLAGS)
+zdb_CFLAGS   = $(AM_CFLAGS) $(LIBCRYPTO_CFLAGS)
 
 sbin_PROGRAMS   += zdb
 CPPCHECKTARGETS += zdb
```

Comment (robn) [reply tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh:63]: Interesting, good find. Seems like `ztest_CFLAGS` does this too. Fix pushed, lets see how the test run goes. Cheers!
