### PR TITLE
Make L2ARC tests more robust

### LINKED ISSUE #10981: ZTS: l2arc/persist_l2arc_007_pos failure
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Any
Distribution Version	| Any
Linux Kernel	| Any
Architecture	| x86_64
ZFS Version	| zfs-2.0.0-rc1-93-gcf26677

### Describe the problem you're observing

```
Tests with results other than PASS that are unexpected:
    FAIL l2arc/persist_l2arc_007_pos (expected PASS)
```

### Describe how to reproduce the problem

Occasionally reproduced by the CI during testing.

### Include any warning/errors/backtraces from the system logs

http://build.zfsonlinux.org/builders/CentOS%207%20x86_64%20%28TEST%29/builds/13298/steps/shell_9/logs/summary

### PR DESCRIPTION
**Pull request by gamanakis**
### Motivation and Context

Fixes #10981 

### Description

Instead of relying on arbitrary timers after pool export/import or cache
device off/online, rely on arcstats. This makes the tests more robust.
Also cleanup some functions related to persistent L2ARC.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by gamanakis** [comment]
Local testing revealed that the persist_l2arc_007 was failing with a rate 2.5% (~1/40 runs). With this PR this is 0%, locally tested in multiple runs (500 runs). 

@behlendorf Could you restart the failing buildbots? Also is there a way to see how often it failed in buildbots building the master branch?

**Comment by behlendorf** [comment]
@behlendorf Could you restart the failing buildbots?

Done. 

> Also is there a way to see how often it failed in buildbots building the master branch?

In fact there is.  We track the ZTS failures in the master branch [here](http://build.zfsonlinux.org/known-issues.html).  It looks like 5 / 316 runs on master, or about 1.55% (not counting PRs).

**Comment by behlendorf** [comment]
Looking at the full list I see we actually did get a couple other l2arc ZTS failures, but they were a bit more rare.

0.65% - 2 / 304 - [11898](http://build.zfsonlinux.org/builders/Amazon%202%20x86_64%20Release%20%28TEST%29/builds/11898) [1205](http://build.zfsonlinux.org/builders/Fedora%2032%20x86_64%20%28TEST%29/builds/1205) - tests/functional/l2arc/l2arc_mfuonly_pos
0.32% - 1 / 305 - [5006](http://build.zfsonlinux.org/builders/Debian%2010%20x86_64%20%28TEST%29/builds/5006) - tests/functional/l2arc/persist_l2arc_008_pos
0.32% - 1 / 305 - [1205](http://build.zfsonlinux.org/builders/Fedora%2032%20x86_64%20%28TEST%29/builds/1205) - tests/functional/l2arc/l2arc_arcstats_pos

**Comment by gamanakis** [comment]
> Looking at the full list I see we actually did get a couple other l2arc ZTS failures, but they were a bit more rare.
> 
> 0.65% - 2 / 304 - [11898](http://build.zfsonlinux.org/builders/Amazon%202%20x86_64%20Release%20%28TEST%29/builds/11898) [1205](http://build.zfsonlinux.org/builders/Fedora%2032%20x86_64%20%28TEST%29/builds/1205) - tests/functional/l2arc/l2arc_mfuonly_pos
> 0.32% - 1 / 305 - [5006](http://build.zfsonlinux.org/builders/Debian%2010%20x86_64%20%28TEST%29/builds/5006) - tests/functional/l2arc/persist_l2arc_008_pos
> 0.32% - 1 / 305 - [1205](http://build.zfsonlinux.org/builders/Fedora%2032%20x86_64%20%28TEST%29/builds/1205) - tests/functional/l2arc/l2arc_arcstats_pos

I saw these too, took a look and in 3/4 of those failures it seems unable to grab the arcstat, I don't know why this would happen. It doesn't seem to be a problem with the test per se. The remaining failure should be addressed by this PR.

File: module/zfs/arc.c [hunk 1]
```diff
@@ -9975,7 +9970,7 @@ l2arc_dev_hdr_read(l2arc_dev_t *dev)
 
 	err = zio_wait(zio_read_phys(NULL, dev->l2ad_vdev,
 	    VDEV_LABEL_START_SIZE, l2dhdr_asize, abd,
-	    ZIO_CHECKSUM_LABEL, NULL, NULL, ZIO_PRIORITY_ASYNC_READ,
+	    ZIO_CHECKSUM_LABEL, NULL, NULL, ZIO_PRIORITY_SYNC_READ,
```
Comment (behlendorf) [inline module/zfs/arc.c:9973]: This makes sense, was the use of async here merely causing a reporting issue?

File: tests/zfs-tests/tests/functional/l2arc/l2arc_arcstats_pos.ksh [hunk 2]
```diff
@@ -70,19 +70,59 @@ log_must fio $FIO_SCRIPTS/mkfiles.fio
...
 
 log_must zpool offline $TESTPOOL $VDEV_CACHE
+
+typeset do_once=true
+while $do_once || [ $l2size1 -ne $l2size2 ]; do
+	typeset l2size1=$(get_arcstat l2_size)
+	sleep 2
+	typeset l2size2=$(get_arcstat l2_size)
+	do_once=false
+done
```
Comment (behlendorf) [inline tests/zfs-tests/tests/functional/l2arc/l2arc_arcstats_pos.ksh:80]: nit: since all of these blocks the same moving this to a helper function might be nice.  Many of the test groups include a shared `.kshlib` file which is sourced to provide some useful functions.

**Review by behlendorf — COMMENTED** [review]
Looks good.  Thanks for running down these issues.

File: module/zfs/arc.c (hunk 1 above)
Comment (gamanakis) [reply module/zfs/arc.c:9973]: No it wasn't causing any issue. This is a synchronous read (zio_wait) and I thought it would be more correct to have the corresponding flag, or am I wrong?

File: tests/zfs-tests/tests/functional/l2arc/l2arc_arcstats_pos.ksh (hunk 2 above)
Comment (gamanakis) [reply tests/zfs-tests/tests/functional/l2arc/l2arc_arcstats_pos.ksh:80]: Yes, will do!

File: module/zfs/arc.c (hunk 1 above)
Comment (behlendorf) [reply module/zfs/arc.c:9973]: No you're right.  I just thought you might have noticed it was being reported incorrectly in something like thew `zpool status -r` output which breaks down the IOs in part by priority.  Sounds like you just noticed it by inspection which is great.

**Comment by gamanakis** [comment]
7de9372: Increase the test threshold in l2arc_mfuonly_pos test and explain why (it's also in the man page of l2arc_mfuonly). More importantly implement a function in `libtest.shlib` that l2arc tests can leverage instead of relying on timers.

**Review by behlendorf — APPROVED** [review]

File: tests/zfs-tests/tests/functional/l2arc/persist_l2arc_006_pos.ksh [hunk 3]
```diff
@@ -73,24 +73,24 @@ log_must fio $FIO_SCRIPTS/random_reads.fio
...
+typeset l2_rebuild_log_blk_end=$(arcstat_plateau l2_rebuild_log_blks)
 
-typeset l2_rebuild_log_blk_end=$(get_arcstat l2_rebuild_log_blks)
-
-log_must test $l2_dh_log_blk -eq $(( $l2_rebuild_log_blk_end - $l2_rebuild_log_blk_start ))
+log_must test $l2_dh_log_blk -eq $(( $l2_rebuild_log_blk_end - \
+	$l2_rebuild_log_blk_start ))
 log_must test $l2_dh_log_blk -gt 0
 
+log must zpoool offline $TESTPOOL $VDEV_CACHE
```
Comment (adamdmoss) [inline tests/zfs-tests/tests/functional/l2arc/persist_l2arc_006_pos.ksh:91]: 'zpoool'

File: tests/zfs-tests/include/libtest.shlib [hunk 4]
```diff
@@ -4173,6 +4173,24 @@ function get_arcstat # stat
...
 
+#
+# Wait for the specified arcstat to reach a non-zero plateau.
+#
+function arcstat_plateau # stat
+{
+	typeset stat=$1
+	typeset do_once=true
+
+	while $do_once || [ $stat1 -ne $stat2 ] || [ $stat2 -eq 0 ]; do
```
Comment (adamdmoss) [inline tests/zfs-tests/include/libtest.shlib:4184]: For stats that can go up or down, technically this will find either a plateau or a, err, valley.   Quiescence.  Is that the intent?

File: tests/zfs-tests/tests/functional/l2arc/persist_l2arc_006_pos.ksh (hunk 3 above)
Comment (gamanakis) [reply tests/zfs-tests/tests/functional/l2arc/persist_l2arc_006_pos.ksh:91]: I though I had fixed that! good catch!

File: tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh [hunk 5]
```diff
@@ -75,7 +75,13 @@ log_must fio $FIO_SCRIPTS/random_reads.fio
...
 log_must zpool export $TESTPOOL
 log_must zpool import -d $VDIR $TESTPOOL
-log_must test $(get_arcstat l2_mru_asize) -eq 0
+
+# Regardless of l2arc_noprefetch, some MFU buffers might be evicted
+# from ARC, accessed later on as prefetches and transition to MRU as prefetches.
+# If accessed again they are counted as MRU and the l2arc_mru_asize arcstat
+# will not be 0. That is the reason with we set the following test to less
+# than 1kB and not exactly 0.
+log_must test $(get_arcstat l2_mru_asize) -le 1024
```
Comment (adamdmoss) [inline tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh:84]: I appreciate the explanation but I'm not sure it really explains where the magic 1kB comes from - does the test expect <1kB recordsize or something?

File: tests/zfs-tests/include/libtest.shlib [hunk 6]
```diff
@@ -4173,6 +4173,24 @@ function get_arcstat # stat
...
+		typeset stat1=$(get_arcstat $stat)
+		sleep 2
+		typeset stat2=$(get_arcstat $stat)
+		do_once=false
+	done
+
+	echo $stat2
```
Comment (adamdmoss) [inline tests/zfs-tests/include/libtest.shlib:4191]: Did you mean to leave this echo of raw $stat2 in?

File: tests/zfs-tests/include/libtest.shlib [hunk 7]
```diff
@@ -4173,6 +4173,24 @@ function get_arcstat # stat
...
+}
```
Comment (adamdmoss) [inline tests/zfs-tests/include/libtest.shlib:4192]: Since there's no upper bound on how long this helper waits for a settle, should it echo something like 'waiting for $stat to plateau...' when it starts, to make it easy to see what happened when a test times out?

File: tests/zfs-tests/include/libtest.shlib (hunk 6 above)
Comment (adamdmoss) [reply tests/zfs-tests/include/libtest.shlib:4191]: Ah, I see, some users of arcstat_plateau use it as a value.   (Will this leave junk on stdout when they don't?)

File: tests/zfs-tests/include/libtest.shlib (hunk 7 above)
Comment (adamdmoss) [reply tests/zfs-tests/include/libtest.shlib:4192]: I guess that's in conflict with being able to use the interpolated output of the helper.  I'd like to see a wrapper for standalone calls as a separate thing from one used for interpolation, but it's not a biggie.

File: tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh (hunk 5 above)
Comment (adamdmoss) [reply tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh:84]: "it's also in the man page of l2arc_mfuonly" - sad to say I'm not sure which man page this is within :(

Comment (gamanakis) [reply tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh:84]: the man page of l2arc_mfuonly of course, in zfs-module-parameters. I will clarify.

Comment (gamanakis) [reply tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh:84]: The magic value of 1kB is based on multiple runs. When it fails, it fails with 512 in my testing, so I doubled that value.

File: tests/zfs-tests/include/libtest.shlib (hunk 4 above)
Comment (gamanakis) [reply tests/zfs-tests/include/libtest.shlib:4184]: Essentially inactivity, does not matter if plateau or valley. Quiescence. No activity on L2ARC devices judged by l2_size or complete removal of the L2ARC device as seen by l2_feeds. I will rename it to arcstat_quiescence.

File: tests/zfs-tests/include/libtest.shlib (hunk 6 above)
Comment (gamanakis) [reply tests/zfs-tests/include/libtest.shlib:4191]: It seems it does, will fix.

File: tests/zfs-tests/include/libtest.shlib (hunk 7 above)
Comment (gamanakis) [reply tests/zfs-tests/include/libtest.shlib:4192]: I can easily fix this by inserting echoes right before the call to the helper in the tests.

Comment (gamanakis) [reply tests/zfs-tests/include/libtest.shlib:4192]: Or I can implement another helper like arcstat_quiescence_echo.

**Comment by gamanakis** [comment]
e971468: addressed comments from @adamdmoss , thank you! Renamed arcstat_plateau to arcstat_quiescence, implement two variants of that function (one for interpolation, the other for standalone calls), clarify the comment in l2arc_mfuonly_pos.

File: tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh (hunk 5 above)
Comment (gamanakis) [reply tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh:85]: Perhaps I can fix this by setting zfs_prefetch_disable=1 in the test. Let me test.

**Comment by gamanakis** [comment]
@freqlabs what is the equivalent of zfs_prefetch_disable in FreeBSD?

**Comment by freqlabs** [comment]
> @freqlabs what is the equivalent of zfs_prefetch_disable in FreeBSD?

`vfs.zfs.prefetch.disable`, so in tunables.cfg it will be `prefetch.disable`

**Comment by gamanakis** [comment]
8be9ba0: fixed FreeBSD tunable (zfs_prefetch_disable, prefetch.disable).

File: tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh (hunk 5 above)
Comment (gamanakis) [reply tests/zfs-tests/tests/functional/l2arc/l2arc_mfuonly_pos.ksh]: In a local run of 1000 tests, setting zfs_prefetch_disable and restoring testing for 0 (as opposed to 1kB) produced no failures. Adopted this approach and updated the comments.

**Review by adamdmoss — APPROVED** [review]
nice!

**Comment by gamanakis** [comment]
The persist_l2arc_008_pos failed in the Debian 10 buildbot. Let me take a look.

**Comment by gamanakis** [comment]
be6f925: In all tests additionally wait for l2_size to become quiescent after importing the pool or before off-lining a cache device.

**Comment by gamanakis** [comment]
d3f5dac: Accidentally broke the persist_l2arc_001 test. Fixed.

**Comment by behlendorf** [comment]
@gamanakis I resubmitted the builds and everything looks good.  If you don't have any more changes I'd like to move forward with this.

**Comment by gamanakis** [comment]
@behlendorf I think it is good now. You can go ahead. Thank you!
