### PR TITLE
Move dmu_buf_rele() after dsl_dataset_sync_done()

### LINKED ISSUE #14522: Dereference of dataset_t after dropping reference
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	|
Architecture	|
OpenZFS Version	| after 34ce4c42ffdcd8933768533343d8b29f9612fbae

### Describe the problem you're observing
With a recent change to `dsl_dataset_sync_done()` (in 34ce4c42ffdcd8933768533343d8b29f9612fbae), a dereference to `ds` was added after the call to `dmu_buf_rele()` (for the ds-ds_dbuf) at the end of the function. Since the dataset_t can be freed after the last rele, this can lead to a reference to freed memory (and a panic).

The call to `dmu_buf_rele()` needs to be moved to the end of the function... or, better yet, perhaps moved into the caller (since the ds is being passed in).

### Include any warning/errors/backtraces from the system logs

```
[11457.108930]: VERIFY0(0 == dnode_hold(mos, object, FTAG, &dn)) failed (0 == 22)
[11457.112832]: PANIC at dmu_object.c:465:dmu_object_zapify()
[11457.116154]: Kernel panic - not syncing: VERIFY0(0 == dnode_hold(mos, object, FTAG, &dn)) failed (0 == 22)
[11457.121852]: CPU: 0 PID: 849805 Comm: txg_sync Kdump: loaded Tainted: P           OE     5.4.0-1096-dx2023021019-60d1a250c-aws #104
[11457.128811]: Hardware name: Amazon EC2 t3.large/, BIOS 1.0 10/16/2017Rk

[11457.132661]: Call Trace:
[11457.134303]:  dump_stack+0x6d/0x8b
[11457.136431]:  panic+0x101/0x2e3
[11457.140412]:  spl_panic+0xcf/0x102 [spl]
[11457.178926]:  dmu_object_zapify+0xec/0x100 [zfs]
[11457.183876]:  dsl_dataset_activate_feature+0x96/0x1a0 [zfs]
[11457.189312]:  dsl_dataset_sync_done+0xe2/0x140 [zfs]
[11457.194435]:  dsl_pool_sync+0x272/0x400 [zfs]Jk

[11457.199212]:  spa_sync_iterate_to_convergence+0xf1/0x250 [zfs]
[11457.204787]:  spa_sync+0x31c/0x6c0 [zfs]
[11457.209297]:  txg_sync_thread+0x22d/0x2d0 [zfs]
[11457.214176]:  ? txg_dispatch_callbacks+0xf0/0xf0 [zfs]
[11457.219266]:  thread_generic_wrapper+0x83/0xa0 [spl]
[11457.224219]:  kthread+0x104/0x140
```

### PR DESCRIPTION
**Pull request by gamanakis**
### Motivation and Context
Closes #14522 

### Description
Move dmu_buf_rele() after dsl_dataset_sync_done(), otherwise the dataset may be freed after the last dmu_buf_rele() leading to a panic.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/dsl_dataset.c [hunk 1]
```diff
@@ -2273,8 +2273,6 @@ dsl_dataset_sync_done(dsl_dataset_t *ds, dmu_tx_t *tx)
 
 	ASSERT(!dmu_objset_is_dirty(os, dmu_tx_get_txg(tx)));
```
Comment (mmaybee) [inline module/zfs/dsl_dataset.c:2274]: You might consider moving this ASSERT() to the end of the function.

**Review by mmaybee — APPROVED** [review]

File: module/zfs/dsl_dataset.c (hunk 1 above)
Comment (gamanakis) [reply module/zfs/dsl_dataset.c]: Done!

**Comment by gamanakis** [comment]
CC @tonyhutter for including this in 2.1.10.

File: module/zfs/dsl_dataset.c [hunk 2]
```diff
@@ -1273,9 +1273,9 @@ dsl_dataset_zero_zil(dsl_dataset_t *ds, dmu_tx_t *tx)
 		dsl_dataset_sync(ds, zio, tx);
 		VERIFY0(zio_wait(zio));
 
-		/* dsl_dataset_sync_done will drop this reference. */
 		dmu_buf_add_ref(ds->ds_dbuf, ds);
 		dsl_dataset_sync_done(ds, tx);
+		dmu_buf_rele(ds->ds_dbuf, ds);
```
Comment (ahrens) [inline module/zfs/dsl_dataset.c:1278]: We shouldn't need to add and then remove the reference.  the dataset remains valid across the call to dsl_dataset_sync_done().

File: module/zfs/dsl_crypt.c [hunk 3]
```diff
@@ -2120,9 +2120,9 @@ dsl_crypto_recv_raw_objset_sync(dsl_dataset_t *ds, dmu_objset_type_t ostype,
 		dsl_dataset_sync(ds, zio, tx);
 		VERIFY0(zio_wait(zio));
 
-		/* dsl_dataset_sync_done will drop this reference. */
 		dmu_buf_add_ref(ds->ds_dbuf, ds);
 		dsl_dataset_sync_done(ds, tx);
+		dmu_buf_rele(ds->ds_dbuf, ds);
```
Comment (ahrens) [inline module/zfs/dsl_crypt.c:2125]: We shouldn't need to add and then remove the reference.  the dataset remains valid across the call to dsl_dataset_sync_done().

**Review by ahrens — APPROVED** [review]

File: module/zfs/dsl_dataset.c (hunk 2 above)
Comment (mmaybee) [reply module/zfs/dsl_dataset.c:1278]: Yeah, I think this was originally structured this way because the rele was being done inside of the sync_done call.

Comment (gamanakis) [reply module/zfs/dsl_dataset.c]: Fixed.
