### PR TITLE
Linux: Prevent destruction while showing mount devname

### LINKED ISSUE #10892: System crashes while receiving backups. Traced to commit.
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Fedora Core
Distribution Version	| 25
Linux Kernel	| 4.13.16-100.
Architecture	| x86_64
ZFS Version	| 2.0.0-rc1
SPL Version	| 2.0.0-rc1

### Describe the problem you're observing
After updating, the system crashes with an `Oops: 0000 [#1] SMP` while sending snapshots to it (I'm using znapzend).

I've traced it to this 7b4e27232dec4595ef842ce7c0e31aafd255a20a commit.

### Describe how to reproduce the problem
Send many snapshots at once to the system when running with the above commit. The system will crash almost immediately.

### Include any warning/errors/backtraces from the system logs
```
Sep  5 19:00:27 lethe kernel: : [ 1896.126121] BUG: unable to handle kernel NULL pointer dereference at 00000000000000e8
Sep  5 19:00:27 lethe kernel: : [ 1896.126354] IP: dsl_dir_name+0x13/0x170 [zfs]
Sep  5 19:00:27 lethe kernel: : [ 1896.126392] PGD 0
Sep  5 19:00:27 lethe kernel: : [ 1896.126393] P4D 0
Sep  5 19:00:27 lethe kernel: : [ 1896.126407]
Sep  5 19:00:27 lethe kernel: : [ 1896.126433] Oops: 0000 [#1] SMP
Sep  5 19:00:27 lethe kernel: : [ 1896.126455] Modules linked in: binfmt_misc nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack libcrc32c joydev edac_mce_amd kvm_amd kvm dcdbas irqbypass ipmi_ssif tpm_tis tpm_tis_core ipmi_si ipmi_devintf ipmi_msghandler tpm sp5100_tco acpi_power_meter i2c_piix4 shpchp k10temp zfs(POE) zunicode(POE) zzstd(POE) zlua(POE) zcommon(POE) znvpair(POE) zavl(POE) icp(POE) spl(OE) mgag200 i2c_algo_bit drm_kms_helper ttm drm mpt3sas e1000e serio_raw ata_generic pata_acpi raid_class pata_atiixp bnx2 ptp scsi_transport_sas pps_core lz4 lz4_compress
Sep  5 19:00:27 lethe kernel: : [ 1896.126724] CPU: 4 PID: 4285 Comm: sshd Tainted: P        W  OE   4.13.16-100.fc25.x86_64 #1
Sep  5 19:00:27 lethe kernel: : [ 1896.126767] Hardware name: Dell Inc. PowerEdge R515/015C68, BIOS 2.2.1 09/16/2013
Sep  5 19:00:27 lethe kernel: : [ 1896.126807] task: ffff920a6d9b4a00 task.stack: ffffb28a03d34000
Sep  5 19:00:27 lethe kernel: : [ 1896.126916] RIP: 0010:dsl_dir_name+0x13/0x170 [zfs]
Sep  5 19:00:27 lethe kernel: : [ 1896.126943] RSP: 0018:ffffb28a03d37ce0 EFLAGS: 00010286
Sep  5 19:00:27 lethe kernel: : [ 1896.126973] RAX: ffff92066bbee800 RBX: 0000000000000000 RCX: 000000000000fe68
Sep  5 19:00:27 lethe kernel: : [ 1896.127012] RDX: 0000000000000100 RSI: ffff92066bbee800 RDI: 0000000000000000
Sep  5 19:00:27 lethe kernel: : [ 1896.127049] RBP: ffffb28a03d37d00 R08: ffff920a7fc1d900 R09: ffff92066f803200
Sep  5 19:00:27 lethe kernel: : [ 1896.127087] R10: ffff92066bbee800 R11: 0000000000000001 R12: ffff92066bbee800
Sep  5 19:00:27 lethe kernel: : [ 1896.127124] R13: ffff9206627ad000 R14: ffff920a60ae2388 R15: ffff920a5b695600
Sep  5 19:00:27 lethe kernel: : [ 1896.127162] FS:  00007fa5653028c0(0000) GS:ffff920a7fc00000(0000) knlGS:0000000000000000
Sep  5 19:00:27 lethe kernel: : [ 1896.127205] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Sep  5 19:00:27 lethe kernel: : [ 1896.127236] CR2: 00000000000000e8 CR3: 000000042c474000 CR4: 00000000000006e0
Sep  5 19:00:27 lethe kernel: : [ 1896.127274] Call Trace:
Sep  5 19:00:27 lethe kernel: : [ 1896.127380]  dsl_dataset_name+0x2b/0x220 [zfs]
Sep  5 19:00:27 lethe kernel: : [ 1896.127459]  dmu_objset_name+0x11/0x20 [zfs]
Sep  5 19:00:27 lethe kernel: : [ 1896.127542]  zpl_show_devname+0x43/0x70 [zfs]
Sep  5 19:00:27 lethe kernel: : [ 1896.127572]  show_mountinfo+0x198/0x280
Sep  5 19:00:27 lethe kernel: : [ 1896.127597]  m_show+0x14/0x20
Sep  5 19:00:27 lethe kernel: : [ 1896.127617]  seq_read+0x114/0x3f0
Sep  5 19:00:27 lethe kernel: : [ 1896.127641]  __vfs_read+0x37/0x160
Sep  5 19:00:27 lethe kernel: : [ 1896.127666]  ? security_file_permission+0x9b/0xc0
Sep  5 19:00:27 lethe kernel: : [ 1896.127693]  vfs_read+0x96/0x130
Sep  5 19:00:27 lethe kernel: : [ 1896.127714]  SyS_read+0x55/0xc0
Sep  5 19:00:27 lethe kernel: : [ 1896.127737]  entry_SYSCALL_64_fastpath+0x1a/0xa5
Sep  5 19:00:27 lethe kernel: : [ 1896.127763] RIP: 0033:0x7fa5625cdaf0
Sep  5 19:00:27 lethe kernel: : [ 1896.127785] RSP: 002b:00007ffdd0a55068 EFLAGS: 00000246 ORIG_RAX: 0000000000000000
Sep  5 19:00:27 lethe kernel: : [ 1896.127826] RAX: ffffffffffffffda RBX: 00005610d724cc20 RCX: 00007fa5625cdaf0
Sep  5 19:00:27 lethe kernel: : [ 1896.127864] RDX: 0000000000000400 RSI: 00005610d725efa0 RDI: 0000000000000004
Sep  5 19:00:27 lethe kernel: : [ 1896.127902] RBP: 00007fa5628933c0 R08: 00007fa5653028c0 R09: 0000000000000000
Sep  5 19:00:27 lethe kernel: : [ 1896.127939] R10: 00005610d725f35a R11: 0000000000000246 R12: 0000000000000000
Sep  5 19:00:27 lethe kernel: : [ 1896.127977] R13: 0000000000000400 R14: 00005610d725eb90 R15: 0000000000000000
Sep  5 19:00:27 lethe kernel: : [ 1896.128017] Code: 00 48 89 de e8 9f 8e fb ff 5b 41 5c 5d c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 55 48 89 e5 41 56 41 55 41 54 53 48 89 fb <48> 8b bf e8 00 00 00 49 89 f4 48 85 ff 0f 84 f4 00 00 00 e8 d5
Sep  5 19:00:27 lethe kernel: : [ 1896.130546] RIP: dsl_dir_name+0x13/0x170 [zfs] RSP: ffffb28a03d37ce0
Sep  5 19:00:27 lethe kernel: : [ 1896.131729] CR2: 00000000000000e8
Sep  5 19:00:27 lethe kernel: : [ 1896.132920] ---[ end trace 55023c1cf8be07de ]---
Sep  5 19:00:57 lethe kernel: : [ 1925.645748] BUG: unable to handle kernel NULL pointer dereference at 00000000000000e8
Sep  5 19:00:57 lethe kernel: : [ 1925.647437] IP: dsl_dir_name+0x13/0x170 [zfs]
Sep  5 19:00:57 lethe kernel: : [ 1925.648704] PGD 0
Sep  5 19:00:57 lethe kernel: : [ 1925.648705] P4D 0
Sep  5 19:00:57 lethe kernel: : [ 1925.649922]
Sep  5 19:00:57 lethe kernel: : [ 1925.652317] Oops: 0000 [#2] SMP
Sep  5 19:00:57 lethe kernel: : [ 1925.653422] Modules linked in: binfmt_misc nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack libcrc32c joydev edac_mce_amd kvm_amd kvm dcdbas irqbypass ipmi_ssif tpm_tis tpm_tis_core ipmi_si ipmi_devintf ipmi_msghandler tpm sp5100_tco acpi_power_meter i2c_piix4 shpchp k10temp zfs(POE) zunicode(POE) zzstd(POE) zlua(POE) zcommon(POE) znvpair(POE) zavl(POE) icp(POE) spl(OE) mgag200 i2c_algo_bit drm_kms_helper ttm drm mpt3sas e1000e serio_raw ata_generic pata_acpi raid_class pata_atiixp bnx2 ptp scsi_transport_sas pps_core lz4 lz4_compress
Sep  5 19:00:57 lethe kernel: : [ 1925.659087] CPU: 6 PID: 10253 Comm: sshd Tainted: P      D W  OE   4.13.16-100.fc25.x86_64 #1
Sep  5 19:00:57 lethe kernel: : [ 1925.660217] Hardware name: Dell Inc. PowerEdge R515/015C68, BIOS 2.2.1 09/16/2013
Sep  5 19:00:57 lethe kernel: : [ 1925.661342] task: ffff920a6cbc4a00 task.stack: ffffb28a03b64000
Sep  5 19:00:57 lethe kernel: : [ 1925.662625] RIP: 0010:dsl_dir_name+0x13/0x170 [zfs]
Sep  5 19:00:57 lethe kernel: : [ 1925.663785] RSP: 0018:ffffb28a03b67ce0 EFLAGS: 00010286
Sep  5 19:00:57 lethe kernel: : [ 1925.664916] RAX: ffff92066c97b700 RBX: 0000000000000000 RCX: 000000000001582f
Sep  5 19:00:57 lethe kernel: : [ 1925.666060] RDX: 0000000000000100 RSI: ffff92066c97b700 RDI: 0000000000000000
Sep  5 19:00:57 lethe kernel: : [ 1925.667203] RBP: ffffb28a03b67d00 R08: ffff920a7fd1d900 R09: ffff92066f803200
Sep  5 19:00:57 lethe kernel: : [ 1925.668345] R10: ffff92066c97b700 R11: 0000000000000001 R12: ffff92066c97b700
Sep  5 19:00:57 lethe kernel: : [ 1925.669491] R13: ffff920662418000 R14: ffff920a47d8ca08 R15: ffff920a4fdac880
Sep  5 19:00:57 lethe kernel: : [ 1925.670622] FS:  00007f6020a2c8c0(0000) GS:ffff920a7fd00000(0000) knlGS:0000000000000000
Sep  5 19:00:57 lethe kernel: : [ 1925.671762] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Sep  5 19:00:57 lethe kernel: : [ 1925.672893] CR2: 00000000000000e8 CR3: 000000080d33c000 CR4: 00000000000006e0
Sep  5 19:00:57 lethe kernel: : [ 1925.674031] Call Trace:
Sep  5 19:00:57 lethe kernel: : [ 1925.675270]  dsl_dataset_name+0x2b/0x220 [zfs]
Sep  5 19:00:57 lethe kernel: : [ 1925.676492]  dmu_objset_name+0x11/0x20 [zfs]
Sep  5 19:00:57 lethe kernel: : [ 1925.677715]  zpl_show_devname+0x43/0x70 [zfs]
Sep  5 19:00:57 lethe kernel: : [ 1925.678866]  show_mountinfo+0x198/0x280
Sep  5 19:00:57 lethe kernel: : [ 1925.680009]  m_show+0x14/0x20
Sep  5 19:00:57 lethe kernel: : [ 1925.681150]  seq_read+0x30f/0x3f0
Sep  5 19:00:57 lethe kernel: : [ 1925.682295]  __vfs_read+0x37/0x160
Sep  5 19:00:57 lethe kernel: : [ 1925.683435]  ? security_file_permission+0x9b/0xc0
Sep  5 19:00:57 lethe kernel: : [ 1925.684579]  vfs_read+0x96/0x130
Sep  5 19:00:57 lethe kernel: : [ 1925.685727]  SyS_read+0x55/0xc0
Sep  5 19:00:57 lethe kernel: : [ 1925.686865]  entry_SYSCALL_64_fastpath+0x1a/0xa5
Sep  5 19:00:57 lethe kernel: : [ 1925.688006] RIP: 0033:0x7f601dcf7af0
Sep  5 19:00:57 lethe kernel: : [ 1925.689131] RSP: 002b:00007ffe09e75e78 EFLAGS: 00000246 ORIG_RAX: 0000000000000000
Sep  5 19:00:57 lethe kernel: : [ 1925.690273] RAX: ffffffffffffffda RBX: 000056453636b940 RCX: 00007f601dcf7af0
Sep  5 19:00:57 lethe kernel: : [ 1925.691423] RDX: 0000000000000400 RSI: 000056453636f070 RDI: 0000000000000004
Sep  5 19:00:57 lethe kernel: : [ 1925.692573] RBP: 00007f601dfbd3c0 R08: 00007f6020a2c8c0 R09: 0000000000000001
Sep  5 19:00:57 lethe kernel: : [ 1925.693724] R10: 000056453636f46f R11: 0000000000000246 R12: 0000000000000000
Sep  5 19:00:57 lethe kernel: : [ 1925.694879] R13: 0000000000000400 R14: 000056453636ec60 R15: 0000000000000000
Sep  5 19:00:57 lethe kernel: : [ 1925.696005] Code: 00 48 89 de e8 9f 8e fb ff 5b 41 5c 5d c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00 00 55 48 89 e5 41 56 41 55 41 54 53 48 89 fb <48> 8b bf e8 00 00 00 49 89 f4 48 85 ff 0f 84 f4 00 00 00 e8 d5
Sep  5 19:00:57 lethe kernel: : [ 1925.698406] RIP: dsl_dir_name+0x13/0x170 [zfs] RSP: ffffb28a03b67ce0
Sep  5 19:00:57 lethe kernel: : [ 1925.699559] CR2: 00000000000000e8
Sep  5 19:00:57 lethe kernel: : [ 1925.700733] ---[ end trace 55023c1cf8be07df ]---
```

I also have the output of sysreq: https://gist.github.com/angstymeat/56939e2e0e94773f85065bada2366fa5

### PR DESCRIPTION
**Pull request by freqlabs**
### Motivation and Context

Fixes #10892

### Description

Use ZFS_ENTER and ZFS_EXIT to protect datasets while their mount
devname is being retrieved.

### How Has This Been Tested?

Ran `zfs_receive` tests for 100 iterations with `while :; do mount; done` running in another terminal.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/os/linux/zfs/zpl_super.c [hunk 1]
```diff
@@ -187,10 +187,12 @@ __zpl_show_devname(struct seq_file *seq, zfsvfs_t *zfsvfs)
 {
 	char *fsname;
 
+	ZFS_ENTER(zfsvfs);
 	fsname = kmem_alloc(ZFS_MAX_DATASET_NAME_LEN, KM_SLEEP);
 	dmu_objset_name(zfsvfs->z_os, fsname);
 	seq_puts(seq, fsname);
```
Comment (ceedriic) [inline module/os/linux/zfs/zpl_super.c:193]: wouldn't it be better to reduce the lock to just the dmu_objset_name() function call?

Comment (freqlabs) [reply module/os/linux/zfs/zpl_super.c:193]: That would potentially leak memory. ZFS_ENTER has a return in it if the file system is unmounted.

Comment (ceedriic) [reply module/os/linux/zfs/zpl_super.c:193]: OK, sorry for the noise

**Review by behlendorf — APPROVED** [review]
