### PR TITLE
Bug fix: Speed up WB_SYNC_NONE writebacks when a WB_SYNC_ALL writeback occurs simultaneously

### LINKED ISSUE #12662: msync occasionally takes several seconds (up to ~15 seconds)
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Ubuntu
Distribution Version	| 20.04
Kernel Version	| 5.11.0-1018-gcp (on a Google Cloud VM)
Architecture	| x86_64
OpenZFS Version	| zfs-0.8.3-1ubuntu12.12, zfs-kmod-2.0.2-1ubuntu5.1

### Describe the problem you're observing
When running EventStoreDB (https://github.com/EventStore/EventStore) on a Google Cloud VM, we occasionally see writes taking several seconds in the logs (it happens 1-2 times per day with a constant write load):
```
{"@t":"2021-10-19T10:51:11.5248104Z","@mt":"SLOW QUEUE MSG [{queue}]: {message} - {elapsed}ms. Q: {prevQueueCount}/{curQueueCount}.","@l":"Debug","queue":"StorageWriterQueue","message":"WritePrepares","elapsed":1574,"prevQueueCount":0,"curQueueCount":0,"SourceContext":"EventStore.Core.Bus.QueuedHandlerMRES","ProcessId":1100082,"ThreadId":10}
```
In the above case, it took ~1.5 seconds to complete a write but sometimes it can be up to ~15 seconds.

After doing an strace, I've come to the conclusion that msync is the culprit. We have a small memory-mapped file (8 bytes large) which is updated and flushed very regularly (every ~2 milliseconds).
- Note that we also have another regular (not memory-mapped) file in the same directory that is being flushed with fsync at the same time but no delay is incurred for it.
- During the slow write, there are no pending reads/writes on the system (verified with iostat and zfs iostat)
- In our code, msync is followed by an fsync on the same file descriptor but they run on the same thread, so the calls do not overlap.
- Once the slow write delay is over, everything continues normally (i.e it does not hang forever)
- ~~We don't seem to see the same problem on other cloud platforms (AWS, Azure) although they should be running in a similar environment.~~ EDIT: The issue also seems to happen on AWS/Azure
- EDIT: We also tested with a non-zfs cluster and the issue has not happened after 48+ hours of continuous writes

After doing an ftrace on msync (`__x64_sys_msync`) I've got the following output which shows that the delay is incurred  in `wait_on_page_writeback`:
```
 StorageWriterQu-1100154 [000] 1634640669.215961: funcgraph_entry:                   |  __x64_sys_msync() {
 StorageWriterQu-1100154 [000] 1634640669.215962: funcgraph_entry:                   |    down_read() {
 StorageWriterQu-1100154 [000] 1634640669.215963: funcgraph_entry:                   |      _cond_resched() {
 StorageWriterQu-1100154 [000] 1634640669.215963: funcgraph_entry:        0.355 us   |        rcu_all_qs();
 StorageWriterQu-1100154 [000] 1634640669.215963: funcgraph_exit:         0.775 us   |      }
 StorageWriterQu-1100154 [000] 1634640669.215964: funcgraph_exit:         1.409 us   |    }
 StorageWriterQu-1100154 [000] 1634640669.215964: funcgraph_entry:                   |    find_vma() {
 StorageWriterQu-1100154 [000] 1634640669.215964: funcgraph_entry:        0.186 us   |      vmacache_find();
 StorageWriterQu-1100154 [000] 1634640669.215965: funcgraph_exit:         0.636 us   |    }
 StorageWriterQu-1100154 [000] 1634640669.215965: funcgraph_entry:        0.173 us   |    up_read();
 StorageWriterQu-1100154 [000] 1634640669.215965: funcgraph_entry:                   |    vfs_fsync_range() {
 StorageWriterQu-1100154 [000] 1634640669.215966: funcgraph_entry:                   |      zpl_fsync() {
 StorageWriterQu-1100154 [000] 1634640669.215966: funcgraph_entry:                   |        filemap_write_and_wait_range() {
 StorageWriterQu-1100154 [000] 1634640669.215967: funcgraph_entry:                   |          __filemap_fdatawrite_range() {
 StorageWriterQu-1100154 [000] 1634640669.215967: funcgraph_entry:        0.306 us   |            _raw_spin_lock();
 StorageWriterQu-1100154 [000] 1634640669.215967: funcgraph_entry:        0.199 us   |            wbc_attach_and_unlock_inode();
 StorageWriterQu-1100154 [000] 1634640669.215968: funcgraph_entry:                   |            do_writepages() {
 StorageWriterQu-1100154 [000] 1634640669.215968: funcgraph_entry:      + 78.604 us  |              zpl_writepages();
 StorageWriterQu-1100154 [000] 1634640669.216047: funcgraph_exit:       + 79.316 us  |            }
 StorageWriterQu-1100154 [000] 1634640669.216047: funcgraph_entry:        0.235 us   |            wbc_detach_inode();
 StorageWriterQu-1100154 [000] 1634640669.216048: funcgraph_exit:       + 81.505 us  |          }
 StorageWriterQu-1100154 [000] 1634640669.216048: funcgraph_entry:                   |          __filemap_fdatawait_range() {
 StorageWriterQu-1100154 [000] 1634640669.216048: funcgraph_entry:                   |            pagevec_lookup_range_tag() {
 StorageWriterQu-1100154 [000] 1634640669.216048: funcgraph_entry:        0.430 us   |              find_get_pages_range_tag();
 StorageWriterQu-1100154 [000] 1634640669.216049: funcgraph_exit:         0.783 us   |            }
 StorageWriterQu-1100154 [000] 1634640669.216049: funcgraph_entry:                   |            wait_on_page_writeback() {
 StorageWriterQu-1100154 [000] 1634640669.216049: funcgraph_entry:        0.265 us   |              page_mapping();
 StorageWriterQu-1100154 [000] 1634640669.216050: funcgraph_entry:      $ 1571904 us |              wait_on_page_bit();
 StorageWriterQu-1100154 [001] 1634640670.787956: funcgraph_exit:       $ 1571907 us |            }
 StorageWriterQu-1100154 [001] 1634640670.787957: funcgraph_entry:                   |            __pagevec_release() {
 StorageWriterQu-1100154 [001] 1634640670.787957: funcgraph_entry:      + 11.553 us  |              lru_add_drain_cpu();
 StorageWriterQu-1100154 [001] 1634640670.787969: funcgraph_entry:        0.405 us   |              release_pages();
 StorageWriterQu-1100154 [001] 1634640670.787970: funcgraph_exit:       + 13.001 us  |            }
 StorageWriterQu-1100154 [001] 1634640670.787970: funcgraph_entry:                   |            _cond_resched() {
 StorageWriterQu-1100154 [001] 1634640670.787970: funcgraph_entry:        0.178 us   |              rcu_all_qs();
 StorageWriterQu-1100154 [001] 1634640670.787971: funcgraph_exit:         0.652 us   |            }
 StorageWriterQu-1100154 [001] 1634640670.787971: funcgraph_exit:       $ 1571923 us |          }
 StorageWriterQu-1100154 [001] 1634640670.787971: funcgraph_entry:        0.350 us   |          filemap_check_errors();
 StorageWriterQu-1100154 [001] 1634640670.787972: funcgraph_exit:       $ 1572005 us |        }
 StorageWriterQu-1100154 [001] 1634640670.787972: funcgraph_entry:        0.399 us   |        crhold();
 StorageWriterQu-1100154 [001] 1634640670.787973: funcgraph_entry:                   |        zfs_fsync() {
 StorageWriterQu-1100154 [001] 1634640670.787974: funcgraph_entry:                   |          tsd_set() {
 StorageWriterQu-1100154 [001] 1634640670.787974: funcgraph_entry:                   |            tsd_hash_search() {
 StorageWriterQu-1100154 [001] 1634640670.787974: funcgraph_entry:        0.279 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.787975: funcgraph_exit:         0.749 us   |            }
 StorageWriterQu-1100154 [001] 1634640670.787975: funcgraph_entry:                   |            tsd_hash_search() {
 StorageWriterQu-1100154 [001] 1634640670.787975: funcgraph_entry:        0.255 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.787976: funcgraph_exit:         0.622 us   |            }
 StorageWriterQu-1100154 [001] 1634640670.787976: funcgraph_entry:                   |            tsd_hash_add_pid() {
 StorageWriterQu-1100154 [001] 1634640670.787976: funcgraph_entry:        1.214 us   |              spl_kmem_alloc();
 StorageWriterQu-1100154 [001] 1634640670.787977: funcgraph_entry:        0.186 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.787978: funcgraph_entry:        0.238 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.787978: funcgraph_exit:         2.413 us   |            }
 StorageWriterQu-1100154 [001] 1634640670.787979: funcgraph_entry:                   |            tsd_hash_add() {
 StorageWriterQu-1100154 [001] 1634640670.787979: funcgraph_entry:        0.578 us   |              spl_kmem_alloc();
 StorageWriterQu-1100154 [001] 1634640670.787980: funcgraph_entry:        0.253 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.787980: funcgraph_entry:        1.398 us   |              tsd_hash_search();
 StorageWriterQu-1100154 [001] 1634640670.787982: funcgraph_entry:        0.350 us   |              tsd_hash_search();
 StorageWriterQu-1100154 [001] 1634640670.787982: funcgraph_entry:        0.250 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.787983: funcgraph_exit:         4.591 us   |            }
 StorageWriterQu-1100154 [001] 1634640670.787983: funcgraph_exit:         9.417 us   |          }
 StorageWriterQu-1100154 [001] 1634640670.787984: funcgraph_entry:                   |          rrm_enter_read() {
 StorageWriterQu-1100154 [001] 1634640670.787984: funcgraph_entry:                   |            rrw_enter_read() {
 StorageWriterQu-1100154 [001] 1634640670.787984: funcgraph_entry:        0.850 us   |              rrw_enter_read_impl();
 StorageWriterQu-1100154 [001] 1634640670.787985: funcgraph_exit:         1.398 us   |            }
 StorageWriterQu-1100154 [001] 1634640670.787985: funcgraph_exit:         1.791 us   |          }
 StorageWriterQu-1100154 [001] 1634640670.787986: funcgraph_entry:                   |          zil_commit() {
 StorageWriterQu-1100154 [001] 1634640670.787986: funcgraph_entry:        0.171 us   |            spa_writeable();
 StorageWriterQu-1100154 [001] 1634640670.787987: funcgraph_entry:                   |            zil_commit_impl() {
 StorageWriterQu-1100154 [001] 1634640670.787987: funcgraph_entry:        1.771 us   |              zil_async_to_sync();
 StorageWriterQu-1100154 [001] 1634640670.787989: funcgraph_entry:        1.622 us   |              zil_alloc_commit_waiter();
 StorageWriterQu-1100154 [001] 1634640670.787991: funcgraph_entry:        9.633 us   |              zil_commit_itx_assign();
 StorageWriterQu-1100154 [001] 1634640670.788001: funcgraph_entry:        4.155 us   |              zil_commit_writer();
 StorageWriterQu-1100154 [001] 1634640670.788005: funcgraph_entry:        0.784 us   |              zil_commit_waiter();
 StorageWriterQu-1100154 [001] 1634640670.788006: funcgraph_entry:        0.605 us   |              zil_free_commit_waiter();
 StorageWriterQu-1100154 [001] 1634640670.788007: funcgraph_exit:       + 20.187 us  |            }
 StorageWriterQu-1100154 [001] 1634640670.788007: funcgraph_exit:       + 21.044 us  |          }
 StorageWriterQu-1100154 [001] 1634640670.788007: funcgraph_entry:                   |          rrm_exit() {
 StorageWriterQu-1100154 [001] 1634640670.788008: funcgraph_entry:                   |            rrw_exit() {
 StorageWriterQu-1100154 [001] 1634640670.788008: funcgraph_entry:        0.325 us   |              mutex_lock();
 StorageWriterQu-1100154 [001] 1634640670.788008: funcgraph_entry:        0.263 us   |              __cv_broadcast();
 StorageWriterQu-1100154 [001] 1634640670.788009: funcgraph_entry:        0.279 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.788009: funcgraph_entry:        0.259 us   |              mutex_unlock();
 StorageWriterQu-1100154 [001] 1634640670.788010: funcgraph_exit:         2.051 us   |            }
 StorageWriterQu-1100154 [001] 1634640670.788010: funcgraph_exit:         2.497 us   |          }
 StorageWriterQu-1100154 [001] 1634640670.788010: funcgraph_entry:                   |          tsd_set() {
 StorageWriterQu-1100154 [001] 1634640670.788010: funcgraph_entry:                   |            tsd_hash_search() {
 StorageWriterQu-1100154 [001] 1634640670.788011: funcgraph_entry:        0.184 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.788011: funcgraph_exit:         0.708 us   |            }
 StorageWriterQu-1100154 [001] 1634640670.788011: funcgraph_entry:                   |            tsd_remove_entry() {
 StorageWriterQu-1100154 [001] 1634640670.788012: funcgraph_entry:        0.174 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.788012: funcgraph_entry:        0.175 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.788013: funcgraph_entry:        0.246 us   |              tsd_hash_del.constprop.0();
 StorageWriterQu-1100154 [001] 1634640670.788013: funcgraph_entry:        0.175 us   |              _raw_spin_lock();
 StorageWriterQu-1100154 [001] 1634640670.788013: funcgraph_entry:        0.191 us   |              tsd_hash_del.constprop.0();
 StorageWriterQu-1100154 [001] 1634640670.788014: funcgraph_entry:        1.373 us   |              tsd_hash_dtor();
 StorageWriterQu-1100154 [001] 1634640670.788015: funcgraph_exit:         4.004 us   |            }
 StorageWriterQu-1100154 [001] 1634640670.788016: funcgraph_exit:         5.289 us   |          }
 StorageWriterQu-1100154 [001] 1634640670.788016: funcgraph_exit:       + 42.299 us  |        }
 StorageWriterQu-1100154 [001] 1634640670.788016: funcgraph_entry:        0.204 us   |        crfree();
 StorageWriterQu-1100154 [001] 1634640670.788016: funcgraph_exit:       $ 1572050 us |      }
 StorageWriterQu-1100154 [001] 1634640670.788017: funcgraph_exit:       $ 1572051 us |    }
 StorageWriterQu-1100154 [001] 1634640670.788017: funcgraph_entry:                   |    fput() {
 StorageWriterQu-1100154 [001] 1634640670.788017: funcgraph_entry:        0.437 us   |      fput_many();
 StorageWriterQu-1100154 [001] 1634640670.788018: funcgraph_exit:         0.874 us   |    }
 StorageWriterQu-1100154 [001] 1634640670.788018: funcgraph_exit:       $ 1572058 us |  }
```

I've done an additional ftrace, but this time only on wait_on_page_bit() and I've got this output:
```
 StorageWriterQu-1100154 [006] 1634719033.236598: funcgraph_entry:                   |  wait_on_page_bit() {
 StorageWriterQu-1100154 [006] 1634719033.236601: funcgraph_entry:        0.519 us   |    _raw_spin_lock_irq();
 StorageWriterQu-1100154 [006] 1634719033.236602: funcgraph_entry:                   |    io_schedule() {
 StorageWriterQu-1100154 [006] 1634719033.236602: funcgraph_entry:        0.316 us   |      io_schedule_prepare();
 StorageWriterQu-1100154 [006] 1634719033.236603: funcgraph_entry:                   |      schedule() {
 StorageWriterQu-1100154 [006] 1634719033.236603: funcgraph_entry:                   |        rcu_note_context_switch() {
 StorageWriterQu-1100154 [006] 1634719033.236603: funcgraph_entry:        0.379 us   |          rcu_qs();
 StorageWriterQu-1100154 [006] 1634719033.236604: funcgraph_exit:         0.950 us   |        }
 StorageWriterQu-1100154 [006] 1634719033.236604: funcgraph_entry:        0.358 us   |        _raw_spin_lock();
 StorageWriterQu-1100154 [006] 1634719033.236605: funcgraph_entry:        0.419 us   |        update_rq_clock();
 StorageWriterQu-1100154 [006] 1634719033.236606: funcgraph_entry:                   |        psi_task_change() {
 StorageWriterQu-1100154 [006] 1634719033.236606: funcgraph_entry:        0.300 us   |          psi_flags_change();
 StorageWriterQu-1100154 [006] 1634719033.236607: funcgraph_entry:                   |          psi_group_change() {
 StorageWriterQu-1100154 [006] 1634719033.236607: funcgraph_entry:        0.321 us   |            record_times();
 StorageWriterQu-1100154 [006] 1634719033.236608: funcgraph_exit:         1.029 us   |          }
 StorageWriterQu-1100154 [006] 1634719033.236608: funcgraph_entry:                   |          psi_group_change() {
 StorageWriterQu-1100154 [006] 1634719033.236608: funcgraph_entry:        0.288 us   |            record_times();
 StorageWriterQu-1100154 [006] 1634719033.236609: funcgraph_exit:         0.897 us   |          }
 StorageWriterQu-1100154 [006] 1634719033.236609: funcgraph_entry:                   |          psi_group_change() {
 StorageWriterQu-1100154 [006] 1634719033.236610: funcgraph_entry:        0.305 us   |            record_times();
 StorageWriterQu-1100154 [006] 1634719033.236610: funcgraph_exit:         0.883 us   |          }
 StorageWriterQu-1100154 [006] 1634719033.236610: funcgraph_exit:         4.667 us   |        }
 StorageWriterQu-1100154 [006] 1634719033.236611: funcgraph_entry:                   |        dequeue_task_fair() {
 StorageWriterQu-1100154 [006] 1634719033.236611: funcgraph_entry:                   |          dequeue_entity() {
 StorageWriterQu-1100154 [006] 1634719033.236611: funcgraph_entry:                   |            update_curr() {
 StorageWriterQu-1100154 [006] 1634719033.236612: funcgraph_entry:        0.350 us   |              update_min_vruntime();
 StorageWriterQu-1100154 [006] 1634719033.236612: funcgraph_entry:                   |              cpuacct_charge() {
 StorageWriterQu-1100154 [006] 1634719033.236613: funcgraph_entry:        0.299 us   |                rcu_read_unlock_strict();
 StorageWriterQu-1100154 [006] 1634719033.236613: funcgraph_exit:         0.888 us   |              }
 StorageWriterQu-1100154 [006] 1634719033.236614: funcgraph_entry:                   |              __cgroup_account_cputime() {
 StorageWriterQu-1100154 [006] 1634719033.236614: funcgraph_entry:        0.285 us   |                cgroup_rstat_updated();
 StorageWriterQu-1100154 [006] 1634719033.236614: funcgraph_exit:         0.854 us   |              }
 StorageWriterQu-1100154 [006] 1634719033.236615: funcgraph_entry:        0.296 us   |              rcu_read_unlock_strict();
 StorageWriterQu-1100154 [006] 1634719033.236615: funcgraph_exit:         3.909 us   |            }
 StorageWriterQu-1100154 [006] 1634719033.236616: funcgraph_entry:        0.268 us   |            __update_load_avg_se();
 StorageWriterQu-1100154 [006] 1634719033.236616: funcgraph_entry:        0.304 us   |            __update_load_avg_cfs_rq();
 StorageWriterQu-1100154 [006] 1634719033.236617: funcgraph_entry:        0.293 us   |            clear_buddies();
 StorageWriterQu-1100154 [006] 1634719033.236617: funcgraph_entry:        0.284 us   |            update_cfs_group();
 StorageWriterQu-1100154 [006] 1634719033.236618: funcgraph_entry:        0.301 us   |            update_min_vruntime();
 StorageWriterQu-1100154 [006] 1634719033.236618: funcgraph_exit:         7.319 us   |          }
 StorageWriterQu-1100154 [006] 1634719033.236619: funcgraph_entry:                   |          dequeue_entity() {
 StorageWriterQu-1100154 [006] 1634719033.236619: funcgraph_entry:                   |            update_curr() {
 StorageWriterQu-1100154 [006] 1634719033.236619: funcgraph_entry:        0.328 us   |              __calc_delta();
 StorageWriterQu-1100154 [006] 1634719033.236620: funcgraph_entry:        0.300 us   |              update_min_vruntime();
 StorageWriterQu-1100154 [006] 1634719033.236620: funcgraph_exit:         1.487 us   |            }
 StorageWriterQu-1100154 [006] 1634719033.236621: funcgraph_entry:        0.305 us   |            __update_load_avg_se();
 StorageWriterQu-1100154 [006] 1634719033.236621: funcgraph_entry:        0.296 us   |            __update_load_avg_cfs_rq();
 StorageWriterQu-1100154 [006] 1634719033.236622: funcgraph_entry:        0.279 us   |            clear_buddies();
 StorageWriterQu-1100154 [006] 1634719033.236622: funcgraph_entry:                   |            update_cfs_group() {
 StorageWriterQu-1100154 [006] 1634719033.236623: funcgraph_entry:        0.328 us   |              reweight_entity();
 StorageWriterQu-1100154 [006] 1634719033.236623: funcgraph_exit:         0.939 us   |            }
 StorageWriterQu-1100154 [006] 1634719033.236624: funcgraph_entry:        0.287 us   |            update_min_vruntime();
 StorageWriterQu-1100154 [006] 1634719033.236624: funcgraph_exit:         5.516 us   |          }
 StorageWriterQu-1100154 [006] 1634719033.236624: funcgraph_entry:        0.239 us   |          hrtick_update();
 StorageWriterQu-1100154 [006] 1634719033.236625: funcgraph_exit:       + 14.232 us  |        }
 StorageWriterQu-1100154 [006] 1634719033.236625: funcgraph_entry:                   |        __delayacct_blkio_start() {
 StorageWriterQu-1100154 [006] 1634719033.236626: funcgraph_entry:        0.366 us   |          ktime_get();
 StorageWriterQu-1100154 [006] 1634719033.236626: funcgraph_exit:         0.921 us   |        }
 StorageWriterQu-1100154 [006] 1634719033.236627: funcgraph_entry:                   |        pick_next_task_fair() {
 StorageWriterQu-1100154 [006] 1634719033.236627: funcgraph_entry:                   |          newidle_balance() {
 StorageWriterQu-1100154 [006] 1634719033.236627: funcgraph_entry:        0.285 us   |            __msecs_to_jiffies();
 StorageWriterQu-1100154 [006] 1634719033.236628: funcgraph_entry:        0.245 us   |            rcu_read_unlock_strict();
 StorageWriterQu-1100154 [006] 1634719033.236628: funcgraph_exit:         1.419 us   |          }
 StorageWriterQu-1100154 [006] 1634719033.236628: funcgraph_exit:         1.972 us   |        }
 StorageWriterQu-1100154 [006] 1634719033.236629: funcgraph_entry:                   |        put_prev_task_fair() {
 StorageWriterQu-1100154 [006] 1634719033.236629: funcgraph_entry:                   |          put_prev_entity() {
 StorageWriterQu-1100154 [006] 1634719033.236629: funcgraph_entry:        0.278 us   |            check_cfs_rq_runtime();
 StorageWriterQu-1100154 [006] 1634719033.236630: funcgraph_exit:         0.840 us   |          }
 StorageWriterQu-1100154 [006] 1634719033.236630: funcgraph_entry:                   |          put_prev_entity() {
 StorageWriterQu-1100154 [006] 1634719033.236630: funcgraph_entry:        0.281 us   |            check_cfs_rq_runtime();
 StorageWriterQu-1100154 [006] 1634719033.236631: funcgraph_exit:         0.829 us   |          }
 StorageWriterQu-1100154 [006] 1634719033.236631: funcgraph_exit:         2.501 us   |        }
 StorageWriterQu-1100154 [006] 1634719033.236632: funcgraph_entry:                   |        pick_next_task_idle() {
 StorageWriterQu-1100154 [006] 1634719033.236632: funcgraph_entry:                   |          set_next_task_idle() {
 StorageWriterQu-1100154 [006] 1634719033.236632: funcgraph_entry:                   |            __update_idle_core() {
 StorageWriterQu-1100154 [006] 1634719033.236632: funcgraph_entry:        0.287 us   |              rcu_read_unlock_strict();
 StorageWriterQu-1100154 [006] 1634719033.236633: funcgraph_exit:         0.835 us   |            }
 StorageWriterQu-1100154 [006] 1634719033.236633: funcgraph_exit:         1.372 us   |          }
 StorageWriterQu-1100154 [006] 1634719033.236633: funcgraph_exit:         1.934 us   |        }
 StorageWriterQu-1100154 [006] 1634719033.236634: funcgraph_entry:        0.225 us   |        psi_task_switch();
 StorageWriterQu-1100154 [006] 1634719033.236634: funcgraph_entry:        1.438 us   |        __traceiter_sched_switch();
 StorageWriterQu-1100154 [006] 1634719038.397231: funcgraph_entry:        2.358 us   |        finish_task_switch();
 StorageWriterQu-1100154 [006] 1634719038.397233: funcgraph_exit:       $ 5160630 us |      }
 StorageWriterQu-1100154 [006] 1634719038.397233: funcgraph_exit:       $ 5160631 us |    }
 StorageWriterQu-1100154 [006] 1634719038.397234: funcgraph_entry:        0.206 us   |    finish_wait();
 StorageWriterQu-1100154 [006] 1634719038.397237: funcgraph_entry:        0.280 us   |    irq_enter_rcu();
 StorageWriterQu-1100154 [006] 1634719038.397237: funcgraph_entry:                   |    __sysvec_irq_work() {
 StorageWriterQu-1100154 [006] 1634719038.397238: funcgraph_entry:                   |      __wake_up() {
 StorageWriterQu-1100154 [006] 1634719038.397238: funcgraph_entry:                   |        __wake_up_common_lock() {
 StorageWriterQu-1100154 [006] 1634719038.397238: funcgraph_entry:        0.181 us   |          _raw_spin_lock_irqsave();
 StorageWriterQu-1100154 [006] 1634719038.397239: funcgraph_entry:        0.199 us   |          __wake_up_common();
 StorageWriterQu-1100154 [006] 1634719038.397239: funcgraph_entry:        0.197 us   |          __lock_text_start();
 StorageWriterQu-1100154 [006] 1634719038.397240: funcgraph_exit:         1.614 us   |        }
 StorageWriterQu-1100154 [006] 1634719038.397240: funcgraph_exit:         1.981 us   |      }
 StorageWriterQu-1100154 [006] 1634719038.397240: funcgraph_entry:                   |      __wake_up() {
 StorageWriterQu-1100154 [006] 1634719038.397240: funcgraph_entry:                   |        __wake_up_common_lock() {
 StorageWriterQu-1100154 [006] 1634719038.397240: funcgraph_entry:        0.178 us   |          _raw_spin_lock_irqsave();
 StorageWriterQu-1100154 [006] 1634719038.397241: funcgraph_entry:                   |          __wake_up_common() {
 StorageWriterQu-1100154 [006] 1634719038.397242: funcgraph_entry:                   |            autoremove_wake_function() {
 StorageWriterQu-1100154 [006] 1634719038.397242: funcgraph_entry:                   |              default_wake_function() {
 StorageWriterQu-1100154 [006] 1634719038.397243: funcgraph_entry:                   |                try_to_wake_up() {
 StorageWriterQu-1100154 [006] 1634719038.397243: funcgraph_entry:        0.427 us   |                  _raw_spin_lock_irqsave();
 StorageWriterQu-1100154 [006] 1634719038.397243: funcgraph_entry:        0.300 us   |                  __traceiter_sched_waking();
 StorageWriterQu-1100154 [006] 1634719038.397244: funcgraph_entry:                   |                  select_task_rq_fair() {
 StorageWriterQu-1100154 [006] 1634719038.397244: funcgraph_entry:                   |                    select_idle_sibling() {
 StorageWriterQu-1100154 [006] 1634719038.397244: funcgraph_entry:        0.252 us   |                      available_idle_cpu();
 StorageWriterQu-1100154 [006] 1634719038.397245: funcgraph_entry:        0.180 us   |                      cpus_share_cache();
 StorageWriterQu-1100154 [006] 1634719038.397245: funcgraph_entry:        0.227 us   |                      available_idle_cpu();
 StorageWriterQu-1100154 [006] 1634719038.397246: funcgraph_entry:        0.210 us   |                      available_idle_cpu();
 StorageWriterQu-1100154 [006] 1634719038.397246: funcgraph_entry:        0.175 us   |                      available_idle_cpu();
 StorageWriterQu-1100154 [006] 1634719038.397247: funcgraph_entry:        0.195 us   |                      available_idle_cpu();
 StorageWriterQu-1100154 [006] 1634719038.397247: funcgraph_entry:        0.212 us   |                      available_idle_cpu();
 StorageWriterQu-1100154 [006] 1634719038.397247: funcgraph_exit:         3.202 us   |                    }
 StorageWriterQu-1100154 [006] 1634719038.397248: funcgraph_entry:        0.182 us   |                    rcu_read_unlock_strict();
 StorageWriterQu-1100154 [006] 1634719038.397248: funcgraph_exit:         4.042 us   |                  }
 StorageWriterQu-1100154 [006] 1634719038.397248: funcgraph_entry:                   |                  set_task_cpu() {
 StorageWriterQu-1100154 [006] 1634719038.397248: funcgraph_entry:                   |                    migrate_task_rq_fair() {
 StorageWriterQu-1100154 [006] 1634719038.397249: funcgraph_entry:                   |                      remove_entity_load_avg() {
 StorageWriterQu-1100154 [006] 1634719038.397249: funcgraph_entry:        0.376 us   |                        __update_load_avg_blocked_se();
 StorageWriterQu-1100154 [006] 1634719038.397250: funcgraph_entry:        0.261 us   |                        _raw_spin_lock_irqsave();
 StorageWriterQu-1100154 [006] 1634719038.397250: funcgraph_entry:        0.193 us   |                        __lock_text_start();
 StorageWriterQu-1100154 [006] 1634719038.397251: funcgraph_exit:         1.612 us   |                      }
 StorageWriterQu-1100154 [006] 1634719038.397251: funcgraph_exit:         2.327 us   |                    }
 StorageWriterQu-1100154 [006] 1634719038.397251: funcgraph_entry:        0.174 us   |                    set_task_rq_fair();
 StorageWriterQu-1100154 [006] 1634719038.397252: funcgraph_exit:         3.537 us   |                  }
 StorageWriterQu-1100154 [006] 1634719038.397252: funcgraph_entry:        0.217 us   |                  ttwu_queue_wakelist();
 StorageWriterQu-1100154 [006] 1634719038.397252: funcgraph_entry:        0.216 us   |                  _raw_spin_lock();
 StorageWriterQu-1100154 [006] 1634719038.397253: funcgraph_entry:        0.289 us   |                  update_rq_clock();
 StorageWriterQu-1100154 [006] 1634719038.397253: funcgraph_entry:                   |                  ttwu_do_activate() {
 StorageWriterQu-1100154 [006] 1634719038.397253: funcgraph_entry:                   |                    psi_task_change() {
 StorageWriterQu-1100154 [006] 1634719038.397254: funcgraph_entry:        0.236 us   |                      psi_flags_change();
 StorageWriterQu-1100154 [006] 1634719038.397255: funcgraph_entry:                   |                      psi_group_change() {
 StorageWriterQu-1100154 [006] 1634719038.397256: funcgraph_entry:        0.215 us   |                        record_times();
 StorageWriterQu-1100154 [006] 1634719038.397256: funcgraph_entry:                   |                        queue_delayed_work_on() {
 StorageWriterQu-1100154 [006] 1634719038.397257: funcgraph_entry:                   |                          __queue_delayed_work() {
 StorageWriterQu-1100154 [006] 1634719038.397257: funcgraph_entry:                   |                            add_timer() {
 StorageWriterQu-1100154 [006] 1634719038.397257: funcgraph_entry:        0.359 us   |                              lock_timer_base();
 StorageWriterQu-1100154 [006] 1634719038.397258: funcgraph_entry:        0.181 us   |                              detach_if_pending();
 StorageWriterQu-1100154 [006] 1634719038.397258: funcgraph_entry:        0.176 us   |                              get_nohz_timer_target();
 StorageWriterQu-1100154 [006] 1634719038.397258: funcgraph_entry:        0.219 us   |                              _raw_spin_lock();
 StorageWriterQu-1100154 [006] 1634719038.397259: funcgraph_entry:        0.476 us   |                              internal_add_timer();
 StorageWriterQu-1100154 [006] 1634719038.397259: funcgraph_entry:        0.205 us   |                              __lock_text_start();
 StorageWriterQu-1100154 [006] 1634719038.397260: funcgraph_exit:         3.069 us   |                            }
 StorageWriterQu-1100154 [006] 1634719038.397260: funcgraph_exit:         3.513 us   |                          }
 StorageWriterQu-1100154 [006] 1634719038.397260: funcgraph_exit:         3.904 us   |                        }
 StorageWriterQu-1100154 [006] 1634719038.397260: funcgraph_exit:         5.155 us   |                      }
 StorageWriterQu-1100154 [006] 1634719038.397261: funcgraph_entry:                   |                      psi_group_change() {
 StorageWriterQu-1100154 [006] 1634719038.397261: funcgraph_entry:        0.196 us   |                        record_times();
 StorageWriterQu-1100154 [006] 1634719038.397262: funcgraph_exit:         0.838 us   |                      }
 StorageWriterQu-1100154 [006] 1634719038.397262: funcgraph_entry:                   |                      psi_group_change() {
 StorageWriterQu-1100154 [006] 1634719038.397263: funcgraph_entry:        0.192 us   |                        record_times();
 StorageWriterQu-1100154 [006] 1634719038.397263: funcgraph_exit:         0.831 us   |                      }
 StorageWriterQu-1100154 [006] 1634719038.397263: funcgraph_entry:                   |                      psi_group_change() {
 StorageWriterQu-1100154 [006] 1634719038.397263: funcgraph_entry:        0.226 us   |                        record_times();
 StorageWriterQu-1100154 [006] 1634719038.397264: funcgraph_exit:         0.649 us   |                      }
 StorageWriterQu-1100154 [006] 1634719038.397264: funcgraph_exit:       + 10.517 us  |                    }
 StorageWriterQu-1100154 [006] 1634719038.397264: funcgraph_entry:                   |                    enqueue_task_fair() {
 StorageWriterQu-1100154 [006] 1634719038.397264: funcgraph_entry:                   |                      enqueue_entity() {
 StorageWriterQu-1100154 [006] 1634719038.397265: funcgraph_entry:        0.234 us   |                        update_curr();
 StorageWriterQu-1100154 [006] 1634719038.397265: funcgraph_entry:        0.321 us   |                        __update_load_avg_cfs_rq();
 StorageWriterQu-1100154 [006] 1634719038.397266: funcgraph_entry:        0.198 us   |                        attach_entity_load_avg();
 StorageWriterQu-1100154 [006] 1634719038.397266: funcgraph_entry:        0.180 us   |                        update_cfs_group();
 StorageWriterQu-1100154 [006] 1634719038.397267: funcgraph_entry:        0.196 us   |                        __enqueue_entity();
 StorageWriterQu-1100154 [006] 1634719038.397267: funcgraph_exit:         2.875 us   |                      }
 StorageWriterQu-1100154 [006] 1634719038.397268: funcgraph_entry:                   |                      enqueue_entity() {
 StorageWriterQu-1100154 [006] 1634719038.397268: funcgraph_entry:        0.176 us   |                        update_curr();
 StorageWriterQu-1100154 [006] 1634719038.397268: funcgraph_entry:        0.240 us   |                        __update_load_avg_se();
 StorageWriterQu-1100154 [006] 1634719038.397269: funcgraph_entry:        0.276 us   |                        __update_load_avg_cfs_rq();
 StorageWriterQu-1100154 [006] 1634719038.397270: funcgraph_entry:                   |                        update_cfs_group() {
 StorageWriterQu-1100154 [006] 1634719038.397270: funcgraph_entry:        0.194 us   |                          reweight_entity();
 StorageWriterQu-1100154 [006] 1634719038.397270: funcgraph_exit:         0.698 us   |                        }
 StorageWriterQu-1100154 [006] 1634719038.397271: funcgraph_entry:        0.174 us   |                        __enqueue_entity();
 StorageWriterQu-1100154 [006] 1634719038.397271: funcgraph_exit:         3.732 us   |                      }
 StorageWriterQu-1100154 [006] 1634719038.397272: funcgraph_entry:        0.249 us   |                      hrtick_update();
 StorageWriterQu-1100154 [006] 1634719038.397272: funcgraph_exit:         7.731 us   |                    }
 StorageWriterQu-1100154 [006] 1634719038.397272: funcgraph_entry:                   |                    ttwu_do_wakeup() {
 StorageWriterQu-1100154 [006] 1634719038.397272: funcgraph_entry:                   |                      check_preempt_curr() {
 StorageWriterQu-1100154 [006] 1634719038.397273: funcgraph_entry:                   |                        resched_curr() {
 StorageWriterQu-1100154 [006] 1634719038.397273: funcgraph_entry:                   |                          native_smp_send_reschedule() {
 StorageWriterQu-1100154 [006] 1634719038.397273: funcgraph_entry:        3.417 us   |                            x2apic_send_IPI();
 StorageWriterQu-1100154 [006] 1634719038.397277: funcgraph_exit:         3.830 us   |                          }
 StorageWriterQu-1100154 [006] 1634719038.397277: funcgraph_exit:         4.254 us   |                        }
 StorageWriterQu-1100154 [006] 1634719038.397277: funcgraph_exit:         4.756 us   |                      }
 StorageWriterQu-1100154 [006] 1634719038.397277: funcgraph_entry:        0.941 us   |                      __traceiter_sched_wakeup();
 StorageWriterQu-1100154 [006] 1634719038.397279: funcgraph_exit:         6.337 us   |                    }
 StorageWriterQu-1100154 [006] 1634719038.397279: funcgraph_exit:       + 25.545 us  |                  }
 StorageWriterQu-1100154 [006] 1634719038.397279: funcgraph_entry:        0.207 us   |                  __lock_text_start();
 StorageWriterQu-1100154 [006] 1634719038.397279: funcgraph_exit:       + 36.927 us  |                }
 StorageWriterQu-1100154 [006] 1634719038.397280: funcgraph_exit:       + 37.294 us  |              }
 StorageWriterQu-1100154 [006] 1634719038.397280: funcgraph_exit:       + 38.393 us  |            }
 StorageWriterQu-1100154 [006] 1634719038.397280: funcgraph_exit:       + 39.452 us  |          }
 StorageWriterQu-1100154 [006] 1634719038.397280: funcgraph_entry:        0.197 us   |          __lock_text_start();
 StorageWriterQu-1100154 [006] 1634719038.397281: funcgraph_exit:       + 40.621 us  |        }
 StorageWriterQu-1100154 [006] 1634719038.397281: funcgraph_exit:       + 40.974 us  |      }
 StorageWriterQu-1100154 [006] 1634719038.397281: funcgraph_exit:       + 44.034 us  |    }
 StorageWriterQu-1100154 [006] 1634719038.397281: funcgraph_entry:                   |    irq_exit_rcu() {
 StorageWriterQu-1100154 [006] 1634719038.397282: funcgraph_entry:        0.194 us   |      idle_cpu();
 StorageWriterQu-1100154 [006] 1634719038.397282: funcgraph_exit:         0.670 us   |    }
 StorageWriterQu-1100154 [006] 1634719038.397283: funcgraph_exit:       $ 5160753 us |  }
```

It looks like the kernel is waiting for ZFS to complete the page write to stable storage.

### Describe how to reproduce the problem
1. Start EventStoreDB (20.10.4)
2. Write data constantly to a stream in the database
3. Check for `SLOW QUEUE` messages after 1 day in the EventStoreDB logs

I'm attempting a minimal repro with a C application which repeatedly flushes an 8-byte memory-mapped file and I've seen the issue happen once so it confirms that the issue is not with EventStoreDB (i'm trying to get the repro to work consistently). 

### Include any warning/errors/backtraces from the system logs
Nothing in the syslogs.
The machine is quite powerful as well and has plenty of free memory.

### PR DESCRIPTION
**Pull request by shaan1337**
### Motivation and Context

Fixes #12662

### Description
Page writebacks with `WB_SYNC_NONE` can take several seconds to complete since they wait for the transaction group to close before being committed. This is usually not a problem since the caller does not need to wait. However, if we're simultaneously doing a writeback with `WB_SYNC_ALL` (e.g via msync), the latter can block for several seconds (up to `zfs_txg_timeout`) due to the active `WB_SYNC_NONE` writeback since it needs to wait for the transaction to complete and the PG_writeback bit to be cleared.

This PR deals with 2 cases:

1. No page writeback is active. A WB_SYNC_ALL page writeback starts and even completes. But when it's about to check if the PG_writeback bit has been cleared, another writeback with WB_SYNC_NONE starts. The sync page writeback ends up waiting for the non-sync page writeback to complete.

One such example is a race condition that can occur in the [linux kernel in filemap_write_and_wait_range()](https://github.com/torvalds/linux/blob/cb690f5238d71f543f4ce874aa59237cf53a877c/mm/filemap.c#L712). Between the call to `__filemap_fdatawrite_range` and the call to `filemap_fdatawait_range`, it is possible that the WB_SYNC_ALL writeback completes, and another WB_SYNC_NONE writeback starts (e.g a background writeback by the kernel). The WB_SYNC_ALL writeback then ends up waiting for the WB_SYNC_NONE's writeback to complete.

2. A page writeback with WB_SYNC_NONE is already active when a WB_SYNC_ALL writeback starts. The WB_SYNC_ALL writeback ends up waiting for the WB_SYNC_NONE writeback.

One such example can occur if a WB_SYNC_NONE writeback starts at this point: https://github.com/openzfs/zfs/blob/ddc026f59ba38ae6a33fa7b6874eaa8105ad7df3/module/os/linux/zfs/zpl_file.c#L167

If a WB_SYNC_NONE writeback starts before entering filemap_write_and_wait_range and manages to clear the dirty flags on the page, the filemap_write_and_wait_range call will make an early return here in __filemap_fdatawrite_range:
https://github.com/torvalds/linux/blob/cb690f5238d71f543f4ce874aa59237cf53a877c/mm/filemap.c#L403

The function then calls filemap_fdatawait_range() and it'll wait for several seconds.

Both of the above cases have been identified with the repro application (included as a failing test) and through tracing.

The fix works by carefully keeping track of active sync/non-sync writebacks and makes sure that:
i) a sync writeback will speed up any active non-sync writeback by doing a commit
ii) a non-sync writeback will speed itself up by doing a commit if there are any active sync writebacks

### How Has This Been Tested?
- By following reproduction steps: https://github.com/openzfs/zfs/issues/12662#issuecomment-973716499
- With the included failing test

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by shaan1337** [comment]
Just clarifying something I don't understand: If there was an active writeback and it completes, shouldn't we start new I/O on the page instead of returning for data integrity reasons? (since the active writeback may have started before the data integrity sync call was made)
https://github.com/openzfs/zfs/blob/ded851b2e09b86553152bddd1d00d0ff75a8caeb/module/os/linux/zfs/zfs_vnops_os.c#L3538

**Comment by shaan1337** [comment]
I'm not very satisfied with the fix since it introduces a delay but it's the least intrusive fix I've been able to come up with. I've also thought about the following alternatives:

- Set `I_SYNC` on the inode before calling `filemap_write_and_wait_range()` in `zpl_fsync()` since [background page writebacks wait for SYNC writes to complete](https://github.com/torvalds/linux/blob/d58071a8a76d779eedab38033ae4c821c30295a5/fs/fs-writeback.c#L1863). It sounds like this approach eventually needs to lock the inode during the duration of the write otherwise it doesn't seem possible to revert back the flag to a correct value after completion.

- Immediately clear the page writeback bit when a WB_SYNC_NONE write is done instead of waiting for the write to be on disk - This is not correct since it breaks the API semantics (Pg_writeback should be cleared only after the page is on disk) and other WB_SYNC_ALL waiters will also return early which does not guarantee data integrity.

- Under specific circumstances, return -EIO in zpl_writepages so that `filemap_fdatawait_range()` is not called. This is ugly and isn't right since EIO is handled as an actual error in the kernel.
 
Any feedback or ideas for other solutions are most welcome.

**Comment by shaan1337** [comment]
ok, i came up with another more stable fix that involves adding a counter to the znode to keep track of active sync writes.

**Comment by shaan1337** [comment]
ZFS test suite results:
[20211202T174007.tar.gz](https://github.com/openzfs/zfs/files/7646906/20211202T174007.tar.gz)

```
Results Summary
PASS	 1392
FAIL	 106
SKIP	  87

Running Time:	04:27:40
Percent passed:	87.8%
Log directory:	/var/tmp/test_results/20211202T174007

Tests with results other than PASS that are expected:
    FAIL alloc_class/alloc_class_009_pos (Known issue)
    FAIL alloc_class/alloc_class_010_pos (Known issue)
    FAIL alloc_class/alloc_class_013_pos (https://github.com/openzfs/zfs/issues/11888)
    FAIL casenorm/mixed_formd_delete (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/mixed_formd_lookup (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/mixed_formd_lookup_ci (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/mixed_none_lookup_ci (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/sensitive_formd_delete (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/sensitive_formd_lookup (https://github.com/openzfs/zfs/issues/7633)
    SKIP chattr/setup (Test user execute permissions required for utilities)
    FAIL cli_root/zfs_copies/zfs_copies_003_pos (https://github.com/openzfs/zfs/issues/12301)
    FAIL cli_root/zfs_rename/zfs_rename_002_pos (Known issue)
    FAIL cli_root/zfs_rollback/zfs_rollback_001_pos (Known issue)
    FAIL cli_root/zfs_rollback/zfs_rollback_002_pos (Known issue)
    FAIL cli_root/zpool_add/zpool_add_004_pos (Known issue)
    FAIL cli_root/zpool_expand/zpool_expand_001_pos (Known issue)
    FAIL cli_root/zpool_import/import_rewind_device_replaced (Arbitrary pool rewind is not guaranteed)
    SKIP cli_root/zpool_import/zpool_import_missing_003_pos (https://github.com/openzfs/zfs/issues/6839)
    SKIP crtime/crtime_001_pos (Kernel statx(2) system call required on Linux)
    SKIP delegate/setup (Test user execute permissions required for utilities)
    FAIL history/history_006_neg (https://github.com/openzfs/zfs/issues/5657)
    FAIL history/history_008_pos (Known issue)
    SKIP history/history_010_pos (Test user execute permissions required for utilities)
    FAIL largest_pool/largest_pool_001_pos (Known issue)
    FAIL no_space/enospc_002_pos (Exact free space reporting is not guaranteed)
    SKIP pam/setup (pamtester might be not available)
    SKIP projectquota/setup (Test user execute permissions required for utilities)
    SKIP pyzfs/pyzfs_unittest (Python modules missing: python-cffi)
    FAIL refreserv/refreserv_004_pos (Known issue)
    FAIL refreserv/refreserv_raidz (Known issue)
    SKIP removal/removal_with_zdb (Known issue)
    FAIL rsend/rsend_007_pos (Known issue)
    SKIP rsend/rsend_008_pos (https://github.com/openzfs/zfs/issues/6066)
    FAIL rsend/rsend_010_pos (Known issue)
    FAIL rsend/rsend_011_pos (Known issue)
    FAIL rsend/send-c_volume (https://github.com/openzfs/zfs/issues/6087)
    FAIL snapshot/clone_001_pos (Known issue)
    FAIL snapshot/rollback_003_pos (Known issue)
    SKIP userquota/setup (Test user execute permissions required for utilities)
    FAIL vdev_zaps/vdev_zaps_007_pos (Known issue)
    FAIL zvol/zvol_misc/zvol_misc_snapdev (https://github.com/openzfs/zfs/issues/12621)
    FAIL zvol/zvol_misc/zvol_misc_volmode (Known issue)

Tests with result of PASS that are unexpected:

Tests with results other than PASS that are unexpected:
    FAIL cli_root/zfs_copies/zfs_copies_006_pos (expected PASS)
    FAIL cli_root/zfs_destroy/zfs_destroy_001_pos (expected PASS)
    FAIL cli_root/zfs_destroy/zfs_destroy_005_neg (expected PASS)
    FAIL cli_root/zfs_destroy/zfs_destroy_008_pos (expected PASS)
    FAIL cli_root/zfs_destroy/zfs_destroy_009_pos (expected PASS)
    FAIL cli_root/zfs_destroy/zfs_destroy_010_pos (expected PASS)
    FAIL cli_root/zfs_destroy/zfs_destroy_011_pos (expected PASS)
    FAIL cli_root/zfs_destroy/zfs_destroy_012_pos (expected PASS)
    FAIL cli_root/zfs_destroy/zfs_destroy_013_neg (expected PASS)
    FAIL cli_root/zfs_mount/zfs_mount_013_pos (expected PASS)
    FAIL cli_root/zfs_mount/zfs_multi_mount (expected PASS)
    FAIL cli_root/zfs_program/zfs_program_json (expected PASS)
    FAIL cli_root/zfs_rename/zfs_rename_001_pos (expected PASS)
    FAIL cli_root/zfs_rename/zfs_rename_004_neg (expected PASS)
    FAIL cli_root/zfs_rename/zfs_rename_005_neg (expected PASS)
    FAIL cli_root/zfs_rename/zfs_rename_006_pos (expected PASS)
    FAIL cli_root/zfs_rename/zfs_rename_007_pos (expected PASS)
    FAIL cli_root/zfs_set/readonly_001_pos (expected PASS)
    FAIL cli_root/zfs_unmount/zfs_unmount_nested (expected PASS)
    FAIL cli_root/zpool_create/zpool_create_014_neg (expected PASS)
    FAIL cli_root/zpool_create/zpool_create_015_neg (expected PASS)
    FAIL cli_root/zpool_create/zpool_create_features_007_pos (expected PASS)
    FAIL cli_root/zpool_create/zpool_create_features_008_pos (expected PASS)
    FAIL cli_root/zpool_destroy/zpool_destroy_001_pos (expected PASS)
    FAIL cli_root/zpool_import/zpool_import_errata3 (expected PASS)
    FAIL cli_root/zpool_import/zpool_import_errata4 (expected PASS)
    FAIL cli_root/zpool_status/zpool_status_features_001_pos (expected PASS)
    FAIL cli_root/zpool_upgrade/zpool_upgrade_features_001_pos (expected PASS)
    FAIL cli_user/misc/zfs_allow_001_neg (expected PASS)
    FAIL cli_user/misc/zfs_get_001_neg (expected PASS)
    FAIL cli_user/misc/zfs_set_001_neg (expected PASS)
    FAIL cli_user/misc/zfs_unallow_001_neg (expected PASS)
    SKIP cli_user/misc/zfs_upgrade_001_neg (expected PASS)
    FAIL cli_user/misc/zpool_detach_001_neg (expected PASS)
    FAIL cli_user/misc/zpool_export_001_neg (expected PASS)
    FAIL cli_user/misc/zpool_get_001_neg (expected PASS)
    FAIL cli_user/misc/zpool_remove_001_neg (expected PASS)
    FAIL cli_user/misc/zpool_status_001_neg (expected PASS)
    FAIL cli_user/misc/zpool_upgrade_001_neg (expected PASS)
    FAIL cli_user/misc/zpool_wait_privilege (expected PASS)
    FAIL cli_user/zfs_list/zfs_list_001_pos (expected PASS)
    FAIL cli_user/zfs_list/zfs_list_002_pos (expected PASS)
    FAIL cli_user/zfs_list/zfs_list_003_pos (expected PASS)
    FAIL cli_user/zfs_list/zfs_list_007_pos (expected PASS)
    FAIL cli_user/zpool_iostat/zpool_iostat_-c_disable (expected PASS)
    FAIL cli_user/zpool_iostat/zpool_iostat_-c_homedir (expected PASS)
    FAIL cli_user/zpool_iostat/zpool_iostat_-c_searchpath (expected PASS)
    FAIL cli_user/zpool_iostat/zpool_iostat_001_neg (expected PASS)
    FAIL cli_user/zpool_iostat/zpool_iostat_002_pos (expected PASS)
    FAIL cli_user/zpool_iostat/zpool_iostat_004_pos (expected PASS)
    FAIL cli_user/zpool_iostat/zpool_iostat_005_pos (expected PASS)
    FAIL cli_user/zpool_list/zpool_list_001_pos (expected PASS)
    FAIL cli_user/zpool_status/zpool_status_-c_disable (expected PASS)
    FAIL cli_user/zpool_status/zpool_status_-c_homedir (expected PASS)
    FAIL cli_user/zpool_status/zpool_status_-c_searchpath (expected PASS)
    FAIL cli_user/zpool_status/zpool_status_003_pos (expected PASS)
    FAIL devices/devices_001_pos (expected PASS)
    FAIL events/zed_fd_spill (expected PASS)
    FAIL fault/auto_replace_001_pos (expected PASS)
    FAIL limits/filesystem_limit (expected PASS)
    FAIL limits/snapshot_limit (expected PASS)
    FAIL nopwrite/nopwrite_volume (expected PASS)
    FAIL redacted_send/redacted_mounts (expected PASS)
    FAIL redacted_send/redacted_volume (expected PASS)
    FAIL rsend/recv_dedup_encrypted_zvol (expected PASS)
    FAIL rsend/rsend_004_pos (expected PASS)
    FAIL rsend/send-c_stream_size_estimate (expected PASS)
    FAIL rsend/send-wR_encrypted_zvol (expected PASS)
    FAIL slog/slog_replay_volume (expected PASS)
    FAIL xattr/xattr_004_pos (expected PASS)
    FAIL zvol/zvol_ENOSPC/setup (expected PASS)
    SKIP zvol/zvol_ENOSPC/zvol_ENOSPC_001_pos (expected PASS)
    FAIL zvol/zvol_misc/zvol_misc_002_pos (expected PASS)
    FAIL zvol/zvol_misc/zvol_misc_rename_inuse (expected PASS)
    FAIL zvol/zvol_swap/zvol_swap_001_pos (expected PASS)
    FAIL zvol/zvol_swap/zvol_swap_002_pos (expected PASS)
    FAIL zvol/zvol_swap/zvol_swap_004_pos (expected PASS)
```

**Comment by shaan1337** [comment]
ok, ready for review. the last push just added tracepoints for the new counters so it shouldn't affect the zfs test suite results.

some things I've not tested:
- the changes to FreeBSD fsync
- the new tracepoints (not sure what the full tracepoint names are)

**Comment by sempervictus** [comment]
@shaan1337: in practice, does this end up increasing the number of IOPs issued to backing drives, and is there any increase in the number of partial-dnode-writes in the event that there are more sync-outs of small data volumes which may impact space efficiency over time?

**Comment by shaan1337** [comment]
@sempervictus in the absence of a concurrent `WB_SYNC_NONE` page writeback (usually due to a kernel-triggered background page writeback), a `WB_SYNC_ALL` page writeback (e.g triggered by `msync`) would have called zil_commit() anyway for data integrity purposes. 

The fix works by calling zil_commit() whenever there are concurrent WB_SYNC_ALL and WB_SYNC_NONE writebacks. So in principle, it should not affect the layers underneath in any negative way. Even if there are extra zil_commit() calls, they would be without effect most of the time since the transactions in the queue would have already been committed.

Also, in practice the issue itself (simultaneous WB_SYNC_NONE and WB_SYNC_ALL writebacks) occurs very rarely (~once per day on a busy system with continuous writes), so the extra zil_commit(), if any, will be negligible.

**Comment by shaan1337** [comment]
@sempervictus  one important case worth mentioning though is when you're doing a partial msync of a file. since we keep track of active sync/non-sync page writes at the znode level (not at the page level), this means that all dirty pages related to the file will be written to stable storage in the event of a concurrent WB_SYNC_NONE and WB_SYNC_ALL writeback.

This would apply mainly when one or more parts of a file are msync-ed for data integrity purposes while the other parts are not. I'm not sure how common this pattern is.

**Comment by adamdmoss** [comment]
FWIW I ran with this branch for a couple of months and nothing conspicuously exploded.

File: module/os/linux/zfs/zpl_file.c [hunk 1]
```diff
@@ -161,21 +173,40 @@ static int
...
 
+	ZPL_ENTER(zfsvfs);
+	ZPL_VERIFY_ZP(zp);
+	atomic_inc_32(&zp->z_sync_writes_cnt);
+	/*
+	 * speed up any non-sync page writebacks since
+	 * they may take several seconds to complete
+	 */
+	if (atomic_load_32(&zp->z_async_writes_cnt) > 0) {
+		zil_commit(zfsvfs->z_log, zp->z_id);
```
Comment (behlendorf) [inline module/os/linux/zfs/zpl_file.c:190]: Isn't this already handled by the `zil_commmit()` in the  `filemap_write_and_wait_range()->...>do_writepages()->zpl_writepages()` call below?  It not, it still seems like a more appropriate place for this check.

**Review by behlendorf — COMMENTED** [review]
Thank for looking in to this, and sorry about the slow review for this PR.  Comments inline.

File: tests/zfs-tests/tests/functional/page_writeback/cleanup.ksh [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+if [ $(cat /proc/sys/vm/dirty_expire_centisecs) -eq 1 ]; then
+    sudo /bin/sh -c "echo 3000 > /proc/sys/vm/dirty_expire_centisecs"
+fi
+
+if [ $(cat /proc/sys/vm/dirty_background_ratio) -eq 0 ]; then
+    sudo /bin/sh -c "echo 10 > /proc/sys/vm/dirty_background_ratio"
+fi
+
+if [ $(cat /proc/sys/vm/dirty_writeback_centisecs) -eq 1 ]; then
+    sudo /bin/sh -c "echo 500 > /proc/sys/vm/dirty_writeback_centisecs"
```
Comment (nabijaczleweli) [inline tests/zfs-tests/tests/functional/page_writeback/cleanup.ksh:47]: (a) these are all ran as root already – `s:/bin/sh -c:log_must eval:`; (b) useless cat – `[ $(</proc/sys/...) -eq 1 ]`

File: tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+# Description:
+# Run the tests for msync.
+#
+
+if is_linux; then
+    log_assert "Run the tests for msync"
+
+    saved_vm_dirty_expire_centisecs=$(cat /proc/sys/vm/dirty_expire_centisecs)
+    saved_vm_dirty_background_ratio=$(cat /proc/sys/vm/dirty_background_ratio)
+    saved_vm_dirty_writeback_centisecs=$(cat /proc/sys/vm/dirty_writeback_centisecs)
```
Comment (nabijaczleweli) [inline tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh:30]: `read -r saved_vm_dirty_expire_centisecs < /proc/sys/vm/dirty_expire_centisecs` &c.

**Comment by shaan1337** [comment]
@behlendorf @nabijaczleweli thanks for the thorough review! i'll go through and apply the requested changes as soon as possible.

File: module/os/linux/zfs/zpl_file.c [hunk 4]
```diff
@@ -127,17 +127,29 @@ static int
...
+	znode_t *zp = ITOZ(inode);
+	zfsvfs_t *zfsvfs = ITOZSB(inode);
 	cred_t *cr = CRED();
 	int error;
 	fstrans_cookie_t cookie;
 
+	ZPL_ENTER(zfsvfs);
+	ZPL_VERIFY_ZP(zp);
+	atomic_inc_32(&zp->z_sync_writes_cnt);
+	ZPL_EXIT(zfsvfs);
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply module/os/linux/zfs/zpl_file.c:139]: @behlendorf iirc, i had considered this but then we run into a double-counting issue in the range zpl_fsync method (when HAVE_FSYNC_RANGE is defined): 
https://github.com/shaan1337/zfs/blob/f02f991a52cb99db2ae565bfe684f359222e58df/module/os/linux/zfs/zpl_file.c#L173

In this method, it's important to increment `z_sync_writes_cnt` before entering `filemap_write_and_wait_range()`.

However, if we adopt the simple way, it seems that it will still work fine if we just decrement `z_sync_writes_cnt` after the call to `filemap_write_and_wait_range()` and before calling `zfs_fsync()` (where it'll be incremented and decremented again).

File: module/os/linux/zfs/zpl_file.c (hunk 1 above)
Comment (shaan1337) [reply module/os/linux/zfs/zpl_file.c:190]: @behlendorf originally i did not have this check in the fix but after some testing with the failing test, the issue was still persisting (albeit more rarely).

i finally found out that it was due to this early return here (described as case 2 in the PR description):
https://github.com/torvalds/linux/blob/cb690f5238d71f543f4ce874aa59237cf53a877c/mm/filemap.c#L403

due to this early return, we don't get back into zfs code and still call filemap_write_and_wait_range() which can block for several seconds.

i wasn't too happy about scattering the logic around but i haven't found a simpler way to make the fix work

Comment (shaan1337) [reply module/os/linux/zfs/zpl_file.c:190]: the fix can roughly be reasoned about this way:
- if the sync writeback doesn't "see" that there is an overlapping sync & non-sync writeback, then it is guaranteed that the non-sync writeback will "see" it

Comment (shaan1337) [reply module/os/linux/zfs/zpl_file.c:190]: it's important to increment `z_sync_writes_cnt` before doing the check on `z_async_writes_cnt` to provide this guarantee

File: module/os/linux/zfs/zpl_file.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (behlendorf) [reply module/os/linux/zfs/zpl_file.c:139]: > it seems that it will still work fine if we just decrement z_sync_writes_cnt after the call to filemap_write_and_wait_range() and before calling zfs_fsync()

Right, this seems preferable to me.

File: module/os/linux/zfs/zpl_file.c (hunk 1 above)
Comment (behlendorf) [reply module/os/linux/zfs/zpl_file.c:190]: I wish I saw a better way to handle this myself, but I can't say I do.  Let's at least expand the comment here to make it more clear why this is important and under what circumstances this is needed.

File: module/os/freebsd/zfs/zfs_vnops_os.c [hunk 5]
```diff
@@ -4742,9 +4742,23 @@ struct vop_fsync_args {
...
+	zfsvfs_t *zfsvfs = zp->z_zfsvfs;
+
+	ZFS_ENTER(zfsvfs);
+	ZFS_VERIFY_ZP(zp);
+	atomic_inc_32(&zp->z_sync_writes_cnt);
+	ZFS_EXIT(zfsvfs);
 
 	vop_stdfsync(ap);
-	return (zfs_fsync(VTOZ(ap->a_vp), 0, ap->a_td->td_ucred));
+	int error = (zfs_fsync(zp, 0, ap->a_td->td_ucred));
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply module/os/freebsd/zfs/zfs_vnops_os.c]: fixed: these FreeBSD code changes are no longer present

File: module/os/linux/zfs/zpl_file.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (shaan1337) [reply module/os/linux/zfs/zpl_file.c]: fixed

File: tests/runfiles/linux.run [hunk 6]
```diff
@@ -124,6 +124,10 @@ tags = ['functional', 'mmp']
 tests = ['umount_unlinked_drain']
 tags = ['functional', 'mount']
 
+[tests/functional/page_writeback:Linux]
+tests = ['run_msync_test']
+tags = ['functional', 'page_writeback']
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply tests/runfiles/linux.run]: fixed

File: tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh [hunk 7]
```diff
@@ -0,0 +1,43 @@
...
+
+. $STF_SUITE/include/libtest.shlib
+
+#
+# Description:
+# Run the tests for msync.
+#
+
+if is_linux; then
+    log_assert "Run the tests for msync"
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh]: fixed

File: tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh [hunk 8]
```diff
@@ -0,0 +1,43 @@
...
+
+    saved_vm_dirty_expire_centisecs=$(cat /proc/sys/vm/dirty_expire_centisecs)
+    saved_vm_dirty_background_ratio=$(cat /proc/sys/vm/dirty_background_ratio)
+    saved_vm_dirty_writeback_centisecs=$(cat /proc/sys/vm/dirty_writeback_centisecs)
+
+    log_must sudo /bin/sh -c "echo 1 > /proc/sys/vm/dirty_expire_centisecs"
+    log_must sudo /bin/sh -c "echo 1 > /proc/sys/vm/dirty_background_bytes"
+    log_must sudo /bin/sh -c "echo 1 > /proc/sys/vm/dirty_writeback_centisecs"
+
+    log_must $STF_SUITE/tests/functional/page_writeback/msync_test
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh]: fixed

File: tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+if is_linux; then
+    log_assert "Run the tests for msync"
+
+    saved_vm_dirty_expire_centisecs=$(cat /proc/sys/vm/dirty_expire_centisecs)
+    saved_vm_dirty_background_ratio=$(cat /proc/sys/vm/dirty_background_ratio)
+    saved_vm_dirty_writeback_centisecs=$(cat /proc/sys/vm/dirty_writeback_centisecs)
+
+    log_must sudo /bin/sh -c "echo 1 > /proc/sys/vm/dirty_expire_centisecs"
+    log_must sudo /bin/sh -c "echo 1 > /proc/sys/vm/dirty_background_bytes"
+    log_must sudo /bin/sh -c "echo 1 > /proc/sys/vm/dirty_writeback_centisecs"
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh]: fixed

File: tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh [hunk 10]
```diff
@@ -0,0 +1,43 @@
...
+
+    log_must $STF_SUITE/tests/functional/page_writeback/msync_test
+
+    sudo /bin/sh -c "echo $saved_vm_dirty_expire_centisecs > /proc/sys/vm/dirty_expire_centisecs"
+    sudo /bin/sh -c "echo $saved_vm_dirty_background_ratio > /proc/sys/vm/dirty_background_ratio"
+    sudo /bin/sh -c "echo $saved_vm_dirty_writeback_centisecs > /proc/sys/vm/dirty_writeback_centisecs"
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh]: fixed

File: tests/zfs-tests/tests/functional/page_writeback/msync_test.c [hunk 11]
```diff
@@ -0,0 +1,121 @@
...
+			fprintf(stderr, "msync failed!\n");
+			cleanup(file);
+			return (1);
+		}
+
+		gettimeofday(&t2, NULL);
+
+		double elapsed = (t2.tv_sec - t1.tv_sec) * 1000.0;
+		elapsed += ((t2.tv_usec - t1.tv_usec) / 1000.0);
+		if (elapsed > 1000.0) {
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply tests/zfs-tests/tests/functional/page_writeback/msync_test.c]: fixed: the command now takes 2 optional arguments: mmap_sync [run time in mins] [max msync time in ms]

File: module/os/linux/zfs/zpl_file.c (hunk 1 above)
Comment (shaan1337) [reply module/os/linux/zfs/zpl_file.c:192]: fixed: i've added some comments, feel free to let me know if it needs to be trimmed down if it's too much

File: tests/zfs-tests/tests/functional/page_writeback/cleanup.ksh (hunk 2 above)
Comment (shaan1337) [reply tests/zfs-tests/tests/functional/page_writeback/cleanup.ksh]: fixed

File: tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh (hunk 3 above)
Comment (shaan1337) [reply tests/zfs-tests/tests/functional/page_writeback/run_msync_test.ksh]: fixed

**Comment by shaan1337** [comment]
@behlendorf @nabijaczleweli  i have applied the suggested changes. the full test suite is currently running - i'll post the results when it's done (the mmap_sync unit test passes when run individually)

**Comment by shaan1337** [comment]
Below are the new test results:

[zfs_results.tar.gz](https://github.com/openzfs/zfs/files/8509913/zfs_results.tar.gz)

```
Results Summary
PASS	 1518
FAIL	  27
SKIP	  62

Running Time:	04:18:13
Percent passed:	94.5%
Log directory:	/var/tmp/test_results/20220418T165538

Tests with results other than PASS that are expected:
    FAIL casenorm/mixed_formd_delete (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/mixed_formd_lookup (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/mixed_formd_lookup_ci (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/mixed_none_lookup_ci (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/sensitive_formd_delete (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/sensitive_formd_lookup (https://github.com/openzfs/zfs/issues/7633)
    FAIL cli_root/zpool_import/import_rewind_device_replaced (Arbitrary pool rewind is not guaranteed)
    SKIP cli_root/zpool_import/zpool_import_missing_003_pos (https://github.com/openzfs/zfs/issues/6839)
    SKIP crtime/crtime_001_pos (Kernel statx(2) system call required on Linux)
    SKIP limits/filesystem_limit (Known issue)
    SKIP limits/snapshot_limit (Known issue)
    SKIP pam/setup (pamtester might be not available)
    FAIL refreserv/refreserv_004_pos (Known issue)
    SKIP removal/removal_with_zdb (Known issue)
    SKIP rsend/rsend_008_pos (https://github.com/openzfs/zfs/issues/6066)
    FAIL vdev_zaps/vdev_zaps_007_pos (Known issue)

Tests with result of PASS that are unexpected:

Tests with results other than PASS that are unexpected:
    FAIL acl/off/cleanup (expected PASS)
    SKIP acl/off/dosmode (expected PASS)
    SKIP acl/off/posixmode (expected PASS)
    FAIL acl/off/setup (expected PASS)
    FAIL acl/posix-sa/cleanup (expected PASS)
    SKIP acl/posix-sa/posix_001_pos (expected PASS)
    SKIP acl/posix-sa/posix_002_pos (expected PASS)
    SKIP acl/posix-sa/posix_003_pos (expected PASS)
    SKIP acl/posix-sa/posix_004_pos (expected PASS)
    FAIL acl/posix-sa/setup (expected PASS)
    FAIL acl/posix/cleanup (expected PASS)
    SKIP acl/posix/posix_001_pos (expected PASS)
    SKIP acl/posix/posix_002_pos (expected PASS)
    SKIP acl/posix/posix_003_pos (expected PASS)
    SKIP acl/posix/posix_004_pos (expected PASS)
    FAIL acl/posix/setup (expected PASS)
    FAIL cli_root/zpool_add/add_nested_replacing_spare (expected PASS)
    FAIL cli_root/zpool_create/zpool_create_features_007_pos (expected PASS)
    FAIL cli_root/zpool_create/zpool_create_features_008_pos (expected PASS)
    FAIL cli_root/zpool_expand/cleanup (expected PASS)
    FAIL cli_root/zpool_status/zpool_status_features_001_pos (expected PASS)
    FAIL cli_root/zpool_upgrade/zpool_upgrade_features_001_pos (expected PASS)
    FAIL delegate/cleanup (expected PASS)
    FAIL delegate/setup (expected PASS)
    FAIL events/cleanup (expected PASS)
    FAIL limits/cleanup (expected PASS)
    SKIP limits/filesystem_count (expected PASS)
    FAIL limits/setup (expected PASS)
    SKIP limits/snapshot_count (expected PASS)
    FAIL xattr/setup (expected PASS)
    SKIP xattr/xattr_001_pos (expected PASS)
    SKIP xattr/xattr_002_neg (expected PASS)
    SKIP xattr/xattr_003_neg (expected PASS)
    SKIP xattr/xattr_004_pos (expected PASS)
    SKIP xattr/xattr_005_pos (expected PASS)
    SKIP xattr/xattr_006_pos (expected PASS)
    SKIP xattr/xattr_007_neg (expected PASS)
    SKIP xattr/xattr_011_pos (expected PASS)
    SKIP xattr/xattr_012_pos (expected PASS)
    SKIP xattr/xattr_013_pos (expected PASS)
    SKIP xattr/xattr_compat (expected PASS)
```

File: tests/zfs-tests/tests/functional/mmap/mmap_sync_001_pos.ksh [hunk 12]
```diff
@@ -0,0 +1,62 @@
...
+	fi
+
+	if [ $(</proc/sys/vm/dirty_writeback_centisecs) -eq 1 ]; then
+		log_must eval "echo 500 > /proc/sys/vm/dirty_writeback_centisecs"
+	fi
+}
+
+if ! is_linux; then
+	log_unsupported "Only supported on Linux, requires /proc/sys/vm/ tunables"
+fi
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply tests/zfs-tests/tests/functional/mmap/mmap_sync_001_pos.ksh:48]: @behlendorf thanks for the pointers, i've added this line

File: module/os/linux/zfs/zfs_vnops_os.c [hunk 13]
```diff
@@ -3396,21 +3396,43 @@ zfs_link(znode_t *tdzp, znode_t *szp, char *name, cred_t *cr,
...
+	end_page_writeback(pp);
+
+	struct inode	*ip = pp->mapping->host;
+	znode_t		*zp = ITOZ(ip);
+	zfsvfs_t	*zfsvfs = ITOZSB(ip);
+
+	ZFS_ENTER(zfsvfs);
+	ZFS_VERIFY_ZP(zp);
+	atomic_dec_32(&zp->z_async_writes_cnt);
+	ZFS_EXIT(zfsvfs);
```
Comment (behlendorf) [inline module/os/linux/zfs/zfs_vnops_os.c:3422]: We don't need to call any of these `ZFS_*` macro's here since we're guaranteed the inode, and thus znode, will remain valid and because we're not accessing the `zp->z_sa_hdl`.  This function can then return `void`.  This could be simplified to.

```c
static void
zfs_putpage_async_commit_cb(void *arg)
{
        struct page *pp = arg;
        znode_t *zp = ITOZ(pp->mapping->host);

        ClearPageError(pp);
        end_page_writeback(pp);
        atomic_dec_32(&zp->z_async_writes_cnt);
}
```

File: module/os/linux/zfs/zpl_file.c [hunk 14]
```diff
@@ -161,17 +161,60 @@ static int
...
+	znode_t *zp = ITOZ(inode);
+	zfsvfs_t *zfsvfs = ITOZSB(inode);
 	cred_t *cr = CRED();
 	int error;
 	fstrans_cookie_t cookie;
 
+	ZPL_ENTER(zfsvfs);
+	ZPL_VERIFY_ZP(zp);
+	/*
+	 * the variables z_sync_writes_cnt and z_async_writes_cnt work in
```
Comment (behlendorf) [inline module/os/linux/zfs/zpl_file.c:173]:
```suggestion
	 * The variables z_sync_writes_cnt and z_async_writes_cnt work in
```

Proper capitalization throughout this comment and the next.

File: module/os/linux/zfs/zpl_file.c [hunk 15]
```diff
@@ -161,17 +161,60 @@ static int
...
 {
 	struct inode *inode = filp->f_mapping->host;
+	znode_t *zp = ITOZ(inode);
+	zfsvfs_t *zfsvfs = ITOZSB(inode);
 	cred_t *cr = CRED();
 	int error;
 	fstrans_cookie_t cookie;
 
+	ZPL_ENTER(zfsvfs);
+	ZPL_VERIFY_ZP(zp);
```
Comment (behlendorf) [inline module/os/linux/zfs/zpl_file.c:171]: Looking at this again, it seems to me there's no need for the `ZPL_*` calls here.  The inode/znode will have a reference held and these atomics can be safely accessed.  Unless you've seen an issue I'm missing why don't we drop these.

**Review by behlendorf — COMMENTED** [review]
Almost there, just a few more comments and questions.

File: module/os/linux/zfs/zpl_file.c (hunk 14 above)
Comment (shaan1337) [reply module/os/linux/zfs/zpl_file.c]: fixed, i've also added capitalization to the comments in zfs_vnops_os.c
& in mmap_sync_001_pos.ksh i've updated the script's description to make the purpose of the test clearer.

File: module/os/linux/zfs/zfs_vnops_os.c [hunk 16]
```diff
@@ -3583,7 +3620,9 @@ zfs_putpage(struct inode *ip, struct page *pp, struct writeback_control *wbc)
 	err = sa_bulk_update(zp->z_sa_hdl, bulk, cnt, tx);
 
 	zfs_log_write(zfsvfs->z_log, tx, TX_WRITE, zp, pgoff, pglen, 0,
-	    zfs_putpage_commit_cb, pp);
+	    for_sync ? zfs_putpage_sync_commit_cb :
+	    (void *) zfs_putpage_async_commit_cb, pp);
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply module/os/linux/zfs/zfs_vnops_os.c]: fixed

File: module/os/linux/zfs/zpl_file.c (hunk 15 above)
Comment (shaan1337) [reply module/os/linux/zfs/zpl_file.c]: > Looking at this again, it seems to me there's no need for the ZPL_* calls here. The inode/znode will have a reference held and these atomics can be safely accessed.

fixed, this does make the code simpler

> Unless you've seen an issue I'm missing why don't we drop these.

nope, i basically followed the pattern in other parts of the code and made these calls -  i wasn't sure about the guarantees about the inode validity at this point.

File: module/os/linux/zfs/zfs_vnops_os.c (hunk 13 above)
Comment (shaan1337) [reply module/os/linux/zfs/zfs_vnops_os.c]: fixed

File: module/os/linux/zfs/zfs_vnops_os.c [hunk 17]
```diff
@@ -3517,6 +3531,16 @@ zfs_putpage(struct inode *ip, struct page *pp, struct writeback_control *wbc)
...
 
 		if (wbc->sync_mode != WB_SYNC_NONE) {
+			/*
+			 * Speed up any non-sync page writebacks since
+			 * they may take several seconds to complete.
+			 * Refer to the comment in zpl_fsync() (when
+			 * HAVE_FSYNC_RANGE is defined) for details.
+			 */
+			if (atomic_load_32(&zp->z_async_writes_cnt) > 0) {
+				zil_commit(zfsvfs->z_log, zp->z_id);
```
Comment (behlendorf) [inline module/os/linux/zfs/zfs_vnops_os.c:3541]: My oversight, we do want to keep the `ZPL_*` calls, but only around this `zil_commit` and not the atomics.  Can you please add them back to this conditional block, sorry about the hassle.

```c
		if (atomic_load_32(&zp->z_async_writes_cnt) > 0) {
			ZPL_ENTER(zfsvfs);
			ZPL_VERIFY_ZP(zp);
			zil_commit(zfsvfs->z_log, zp->z_id);
			ZPL_EXIT(zfsvfs);
		}						
```

Comment (shaan1337) [reply module/os/linux/zfs/zfs_vnops_os.c:3541]: no worries, yes, i'll add them back again in a moment

Comment (shaan1337) [reply module/os/linux/zfs/zfs_vnops_os.c:3541]: pushed

**Comment by shaan1337** [comment]
@behlendorf i'm running the full test suite again with the latest changes (on a2b982a0e0bbcb5b623a9676a7907f57b1ff8f52) just to make sure the changes didn't break anything. will post the results in a few hours. i can confirm the failing test passes when run individually.

**Comment by behlendorf** [comment]
Thank you.  I'll make another review pass of the PR and post any additional comments.  We should expect a pretty clean CI run as long as this has been rebased against the latest commits on the master branch.

**Comment by shaan1337** [comment]
Test results (on Ubuntu 20.04)
[zfs_results_a2b982.tar.gz](https://github.com/openzfs/zfs/files/8537185/zfs_results_a2b982.tar.gz)

```
Results Summary
PASS     1577
FAIL      13
SKIP      17

Running Time:   04:12:23
Percent passed: 98.1%
Log directory:  /var/tmp/test_results/20220421T184342

Tests with results other than PASS that are expected:
    FAIL casenorm/mixed_formd_delete (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/mixed_formd_lookup (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/mixed_formd_lookup_ci (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/mixed_none_lookup_ci (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/sensitive_formd_delete (https://github.com/openzfs/zfs/issues/7633)
    FAIL casenorm/sensitive_formd_lookup (https://github.com/openzfs/zfs/issues/7633)
    FAIL cli_root/zpool_import/import_rewind_device_replaced (Arbitrary pool rewind is not guaranteed)
    SKIP cli_root/zpool_import/zpool_import_missing_003_pos (https://github.com/openzfs/zfs/issues/6839)
    SKIP crtime/crtime_001_pos (Kernel statx(2) system call required on Linux)
    SKIP pam/setup (pamtester might be not available)
    FAIL refreserv/refreserv_004_pos (Known issue)
    SKIP removal/removal_with_zdb (Known issue)
    SKIP rsend/rsend_008_pos (https://github.com/openzfs/zfs/issues/6066)
    FAIL vdev_zaps/vdev_zaps_007_pos (Known issue)

Tests with result of PASS that are unexpected:

Tests with results other than PASS that are unexpected:
    FAIL cli_root/zpool_create/zpool_create_features_007_pos (expected PASS)
    FAIL cli_root/zpool_create/zpool_create_features_008_pos (expected PASS)
    FAIL cli_root/zpool_status/zpool_status_features_001_pos (expected PASS)
    FAIL cli_root/zpool_upgrade/zpool_upgrade_features_001_pos (expected PASS)
```

It looks like the failing tests on CI are probably flakey tests and need a re-run but i'm not 100% sure.

File: module/os/linux/zfs/zpl_file.c [hunk 18]
```diff
@@ -161,17 +161,57 @@ static int
...
+	 * If the following check does not detect an overlapping non-sync write
+	 * (say because it's just about to start), then it is guaranteed that
+	 * the non-sync write will detect this sync write. This is because we
+	 * always increment z_sync_writes_cnt / z_async_writes_cnt before doing
+	 * the check on z_async_writes_cnt / z_sync_writes_cnt here and in
+	 * zfs_putpage() respectively.
+	 */
+	if (atomic_load_32(&zp->z_async_writes_cnt) > 0) {
+		ZPL_ENTER(zfsvfs);
+		ZPL_VERIFY_ZP(zp);
```
Comment (behlendorf) [inline module/os/linux/zfs/zpl_file.c:191]: Internally `ZPL_VERIFY_ZP` may call `return` when expanded, in which case we need to decrement `z_sync_writes_cnt` to keep the accounting correct.  Yes, this is terrible behavior for a macro.  This _should_ never fail when `z_async_writes_cnt > 0`, but to be absolutely sure this can't happen let's remove the `ZPL_VERIFY_ZP` call entirely.

File: include/sys/zfs_znode.h [hunk 19]
```diff
@@ -199,6 +199,8 @@ typedef struct znode {
 	uint64_t	z_size;		/* file size (cached) */
 	uint64_t	z_pflags;	/* pflags (cached) */
 	uint32_t	z_sync_cnt;	/* synchronous open count */
+	uint32_t	z_sync_writes_cnt; /* synchronous write count */
+	uint32_t	z_async_writes_cnt; /* asynchronous write count */
```
Comment (behlendorf) [inline include/sys/zfs_znode.h:203]: To make absolutely certain the accounting is correct, let's go ahead and assert these counters are zero when the znode is destroyed.  The best place to do this would be in the `zfs_znode_cache_destructor()`.

```
ASSERT0(atomic_load_32(&zp->z_sync_writes_cnt));
ASSERT0(atomic_load_32(&zp->z_async_writes_cnt));
```

Comment (shaan1337) [reply include/sys/zfs_znode.h:203]: good idea, i was worried about the possibility of the count drifting away from 0 if there are any bugs which would cause all writes to be committed immediately - this should help catch any issue during test runs

File: module/os/linux/zfs/zpl_file.c (hunk 18 above)
Comment (shaan1337) [reply module/os/linux/zfs/zpl_file.c]: good catch! i've removed the ZPL_VERIFY_ZP call

**Comment by shaan1337** [comment]
@behlendorf there may be an issue with the failing test, it no longer seems to fail after i revert the fix :thinking: please don't merge yet, i'll try to figure out what's wrong asap

File: tests/zfs-tests/cmd/mmap_sync.c [hunk 20]
```diff
@@ -0,0 +1,145 @@
...
+#include <stdio.h>
+#include <string.h>
+#include <sys/mman.h>
+#include <sys/stat.h>
+#include <sys/time.h>
+#include <fcntl.h>
+#include <unistd.h>
+#include <time.h>
+
+void cleanup(char *file);
```
Comment (behlendorf) [inline tests/zfs-tests/cmd/mmap_sync.c:32]: No need for the extra prototype here.

File: tests/zfs-tests/cmd/mmap_sync.c [hunk 21]
```diff
@@ -0,0 +1,145 @@
...
+	char *file = &filepath[0];
+
+	strcat(file, testdir);
+	strcat(file, "/msync_file");
+
+	const int LEN = 8;
+	cleanup(file);
+
+	int fd = open(file, O_CREAT | O_RDWR, S_IRUSR | S_IWUSR |
+	    S_IRGRP | S_IROTH);
```
Comment (behlendorf) [inline tests/zfs-tests/cmd/mmap_sync.c:85]:
```c
	int fd = open(file, O_CREAT | O_RDWR, S_IRUSR | S_IWUSR |
	    S_IRGRP | S_IROTH);
	if (fd == -1) {
		(void) fprintf(stderr, "%s: %s: ", argv[0]; file);
		perror("open");
		return (1);
	}
```

File: tests/zfs-tests/cmd/mmap_sync.c [hunk 22]
```diff
@@ -0,0 +1,145 @@
...
+	if (ftruncate(fd, LEN) != 0) {
+		fprintf(stderr, "ftruncate failed\n");
+		cleanup(file);
+		return (1);
+	}
+
+	void *ptr = mmap(NULL, LEN, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
+
+	if (ptr == MAP_FAILED) {
+		fprintf(stderr, "mmap failed!\n");
```
Comment (behlendorf) [inline tests/zfs-tests/cmd/mmap_sync.c:96]: perror

File: tests/zfs-tests/cmd/mmap_sync.c [hunk 23]
```diff
@@ -0,0 +1,145 @@
...
+			break;
+		}
+	}
+
+	int ret = munmap(ptr, LEN);
+	if (ret == -1) {
+		fprintf(stderr, "munmap failed!\n");
+		cleanup(file);
+		return (1);
+	}
```
Comment (behlendorf) [inline tests/zfs-tests/cmd/mmap_sync.c:141]: Missing `close(fd)`

**Review by behlendorf — APPROVED** [review]
Things look like they're in good shape and you sorted out the accounting issue.  Were you also able to verify the test case is working as expected?

**Comment by shaan1337** [comment]
> Things look like they're in good shape and you sorted out the accounting issue.
yes, the accounting issue has been sorted out - we just needed to initialize the variables in the znode cache constructor function.

> Were you also able to verify the test case is working as expected?
i can confirm that there's an issue with the test - with the fix reverted, the mmap_sync application does produce slow msyncs when I test it on with a real disk but not when i run the test. i'm trying to further narrow down the possibilities

**Comment by shaan1337** [comment]
i am probably not running the individual test correctly or there's an issue with my environment - when i do `zpool status` while the test is running, for some reason i don't see the 3 loopback devices listed. running only setup.ksh appears to create a test pool with only one loopback device under it. hoping it's a common error people run into - i'll continue to look further

File: tests/zfs-tests/cmd/mmap_sync.c (hunk 20 above)
Comment (shaan1337) [reply tests/zfs-tests/cmd/mmap_sync.c]: fixed

File: tests/zfs-tests/cmd/mmap_sync.c [hunk 24]
```diff
@@ -0,0 +1,145 @@
...
+	strcat(file, "/msync_file");
+
+	const int LEN = 8;
+	cleanup(file);
+
+	int fd = open(file, O_CREAT | O_RDWR, S_IRUSR | S_IWUSR |
+	    S_IRGRP | S_IROTH);
+
+	if (ftruncate(fd, LEN) != 0) {
+		fprintf(stderr, "ftruncate failed\n");
```
[the remark this answers is not in the document]
Comment (shaan1337) [reply tests/zfs-tests/cmd/mmap_sync.c]: fixed

File: tests/zfs-tests/cmd/mmap_sync.c (hunk 21 above)
Comment (shaan1337) [reply tests/zfs-tests/cmd/mmap_sync.c:83]: fixed

File: tests/zfs-tests/cmd/mmap_sync.c (hunk 22 above)
Comment (shaan1337) [reply tests/zfs-tests/cmd/mmap_sync.c]: fixed

File: tests/zfs-tests/cmd/mmap_sync.c (hunk 23 above)
Comment (shaan1337) [reply tests/zfs-tests/cmd/mmap_sync.c:144]: fixed

File: tests/zfs-tests/cmd/mmap_sync.c (hunk 20 above)
Comment (shaan1337) [reply tests/zfs-tests/cmd/mmap_sync.c]: ohh actually, this makes CI fail with:
```
mmap_sync.c:33:1: error: no previous prototype for ‘cleanup’ [-Werror=missing-prototypes]
```

i'm adding it back

**Comment by shaan1337** [comment]
yes, it was my bad. maybe i'm doing some extra steps here, but this makes the test work or fail as expected:
```
make -s -j$(nproc)
sudo ./scripts/zfs.sh  -u
sudo ./scripts/zfs.sh 
./scripts/zfs-tests.sh -vx -t ./tests/zfs-tests/tests/functional/mmap/setup.ksh
./scripts/zfs-tests.sh -v -t ./tests/zfs-tests/tests/functional/mmap/mmap_sync_001_pos
```

nothing else to add on my side - it should be good to go if it's also ok on your side.

thanks for all the feedback and guidance!

**Comment by behlendorf** [comment]
Glad to help.  Can you just rebase this against the current master branch and for update the PR.  That should get us a mostly clean CI run and this should be good to go.

You should also be able to use `./scripts/zfs-tests.sh -v ./scripts/zfs-tests.sh -v -T mmap` to run all the mmap tests.

**Comment by shaan1337** [comment]
> Can you just rebase this against the current master branch and for update the PR. That should get us a mostly clean CI run and this should be good to go.

Yup, i've just rebased it.

> You should also be able to use `./scripts/zfs-tests.sh -v ./scripts/zfs-tests.sh -v -T mmap` to run all the mmap tests.

noted :+1:
