### PR TITLE
Fix ddtprune causing space leak

### LINKED ISSUE #17982: ddtprune seems to cause space leak
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Kernel Version	|
Architecture	|
OpenZFS Version	| master, 2.3.2

### Describe the problem you're observing

After ddtprune, it seems every blocks pruned from the ddt table will leak when removed.

### Describe how to reproduce the problem

```
$ sudo zpool create pp sdb sdc
$ sudo zfs set dedup=on pp
$ sudo chmod ugo+w /pp
$ dd if=/dev/urandom bs=1M count=16 of=/pp/test
$ while :; do zpool sync; done # wait for a few seconds for ddt log to flush
^C
$ sudo zpool ddtprune -p 100 pp

$ rm /pp/test
$ while :; do zpool sync; done # wait for a few seconds for async delete
^C

$ sudo zdb -bcc pp

Traversing all blocks to verify checksums and verify nothing leaked ...

loading concrete vdev 1, metaslab 126 of 127 ...
leaked space: vdev 0, offset 0x40029000, size 8126464
leaked space: vdev 0, offset 0x407ea000, size 262144
leaked space: vdev 1, offset 0x40029000, size 8126464
leaked space: vdev 1, offset 0x407ea000, size 262144
block traversal size 528384 != alloc 17305600 (leaked 16777216)

        bp count:                    77
        ganged count:                 0
        bp logical:             3081216      avg:  40015
        bp physical:             181248      avg:   2353     compression:  17.00
        bp allocated:            528384      avg:   6862     compression:   5.83
        bp deduped:                   0    ref>1:      0   deduplication:   1.00
        bp cloned:                    0    count:      0
        Normal class:          17367040     used:  0.01%
        Embedded log class              0     used:  0.00%

        additional, non-pointer bps of type 0:         31
        Dittoed blocks on same vdev: 34
```

### PR DESCRIPTION
**Pull request by tuxoko**
In zio_ddt_free, if a pruned dde is still in ddt, it would do nothing and cause space leak.

Fixes #17982

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Quality assurance (non-breaking change which makes the code more robust against bugs)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/zio.c [hunk 1]
```diff
@@ -4111,6 +4111,9 @@ zio_ddt_free(zio_t *zio)
 		ddt_phys_variant_t v = ddt_phys_select(ddt, dde, bp);
 		if (v != DDT_PHYS_NONE)
 			ddt_phys_decref(dde->dde_phys, v);
+		else
+			/* dde was pruned */
```
Comment (robn) [inline module/zfs/zio.c]:
```suggestion
			/*
			 * If the entry was found but the phys was not, then
			 * this block must have been pruned from the dedup
			 * table, and the entry refers to a later version of
			 * this data. Therefore, the caller is trying to delete
			 * the only stored instance of this block, and so we
			 * need to do a normal (not dedup) free. Clear dde so
			 * we fall into the block below.
			 */
```

**Review by allanjude — APPROVED** [review]

**Comment by tuxoko** [comment]
> This might be a fix, but I think some deeper look would be good. With `B_TRUE` passed to `ddt_lookup()` as `verify` argument, it should call `ddt_entry_lookup_is_valid()` for the returned blocks. Which should verify the block pointers. It does not verify the birth time (which might be not good), but in this scenario it should be irrelevant, since there are no new writes after the prune.

I just tried checking phys birth in ddt_entry_lookup_is_valid, but without the original fix in zio_ddt_free, it doesn't fix the leak. Not sure if I did the right thing here.
```patch
diff --git a/module/zfs/ddt.c b/module/zfs/ddt.c
index 0dc9adc7f..b7b332212 100644
--- a/module/zfs/ddt.c
+++ b/module/zfs/ddt.c
@@ -1143,6 +1143,9 @@ ddt_entry_lookup_is_valid(ddt_t *ddt, const blkptr_t *bp, ddt_entry_t *dde)
 	const dva_t *dvas = (ddt->ddt_flags & DDT_FLAG_FLAT) ?
 	    dde->dde_phys->ddp_flat.ddp_dva :
 	    dde->dde_phys->ddp_trad[ndvas].ddp_dva;
+	const uint64_t phys_birth = (ddt->ddt_flags & DDT_FLAG_FLAT) ?
+	    dde->dde_phys->ddp_flat.ddp_phys_birth :
+	    dde->dde_phys->ddp_trad[ndvas].ddp_phys_birth;
 
 	/*
 	 * Compare entry DVAs with the BP. They should all be there, but
@@ -1154,6 +1157,8 @@ ddt_entry_lookup_is_valid(ddt_t *ddt, const blkptr_t *bp, ddt_entry_t *dde)
 		if (!DVA_EQUAL(&dvas[d], &bp->blk_dva[d]))
 			return (B_FALSE);
 	ASSERT3U(d, ==, ndvas);
+	if (BP_GET_PHYSICAL_BIRTH(bp) != phys_birth)
+		return (B_FALSE);
 
 	return (B_TRUE);
 }

```

**Comment by tuxoko** [comment]
@behlendorf 
Added a test
