### PR TITLE
Values printed by zpool-iostat(8) should be right-aligned

### LINKED ISSUE #14749: `zpool iostat` columns are misaligned
### System information

Type | Version/Name
 --- | ---
Distribution Name	|Ubuntu
Distribution Version	|
Kernel Version	|
Architecture	|
OpenZFS Version	|0e96db931979eff8685bd380684d426ec4681f19

### Describe the problem you're observing
```
$ zpool iostat test 1
              capacity     operations     bandwidth
pool        alloc   free   read  write   read  write
----------  -----  -----  -----  -----  -----  -----
test        1.13T  512P   115    36.4K  312K   108M
test        1.13T  512P   0      0      0      0
test        1.13T  512P   0      0      0      0
test        1.13T  512P   0      392    0      6.06M
test        1.13T  512P   0      225    0      4.06M
test        1.13T  512P   0      740    0      14.1M
test        1.13T  512P   0      1.59K  0      26.2M
test        1.13T  512P   0      1.32K  0      26.2M
test        1.13T  512P   0      304    0      6.02M
```
Columns should be right-justified, so that they are aligned.

The bug was likely introduced by https://github.com/openzfs/zfs/pull/14621 @mcmilk @behlendorf @Low-power 

See `print_stat_color()`

### Describe how to reproduce the problem
run `zpool iostat` (any arguments)

### PR DESCRIPTION
**Pull request by Low-power**
### Motivation and Context
Fix #14749.

### Description
See the title and #14749.

### How Has This Been Tested?
Tested locally.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: cmd/zpool/zpool_main.c [hunk 1]
```diff
@@ -4272,13 +4272,17 @@ print_iostat_header(iostat_cbdata_t *cb)
  * by order of magnitude. Uses column_size to add padding.
  */
 static void
-print_stat_color(char *statbuf, unsigned int column_size)
+print_stat_color(const char *statbuf, unsigned int column_size)
 {
 	fputs("  ", stdout);
+	size_t len = strlen(statbuf);
+	while (len < column_size) {
```
Comment (mcmilk) [inline cmd/zpool/zpool_main.c:4279]: I would add a new line before the while() .... but this is cosmetic ;)

File: cmd/zpool/zpool_main.c [hunk 2]
```diff
@@ -4272,13 +4272,17 @@ print_iostat_header(iostat_cbdata_t *cb)
...
+		fputc(' ', stdout);
+		column_size--;
+	}
 	if (*statbuf == '0') {
 		color_start(ANSI_GRAY);
 		fputc('0', stdout);
-		column_size--;
```
Comment (mcmilk) [inline cmd/zpool/zpool_main.c:4281]: How about adding `color_end();` and `return;` here ....
And we can put the whole `for()` loop a tab to the left.

**Review by mcmilk — APPROVED** [review]
Thanks for this fast response and fix @Low-power.

**Review by ahrens — APPROVED** [review]

**Comment by ahrens** [comment]
@Low-power thanks!

File: cmd/zpool/zpool_main.c (hunk 2 above)
Comment (Low-power) [reply cmd/zpool/zpool_main.c:4281]: Good point. May be we can do these code cleanups later.
Now I also feels that the series of `else if` inside `for` should probably be turned into a `switch` instead for readability.

File: cmd/zpool/zpool_main.c [hunk 3]
```diff
@@ -4272,13 +4272,17 @@ print_iostat_header(iostat_cbdata_t *cb)
...
 static void
-print_stat_color(char *statbuf, unsigned int column_size)
+print_stat_color(const char *statbuf, unsigned int column_size)
 {
 	fputs("  ", stdout);
+	size_t len = strlen(statbuf);
+	while (len < column_size) {
+		fputc(' ', stdout);
+		column_size--;
+	}
```
[the remark this answers is not in the document]
Comment (tonyhutter) [reply cmd/zpool/zpool_main.c:4282]: :arrow_up: This is a minor nitpick and should not hold up merging.

**Review by tonyhutter — APPROVED** [review]
I tested this PR manually and verified it fixes the column alignment.

**Review by behlendorf — APPROVED** [review]
