### PR TITLE
Linux 5.16 compat: don't use XSTATE_XSAVE to save FPU state

### LINKED ISSUE #13042: Linux 5.16 broke FPU handling
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Arch Linux
Distribution Version	| rolling
Kernel Version	|  5.16.3-arch1-1
Architecture	| x86
OpenZFS Version	|  zfs-2.1.99-717_g73e972af7a, zfs-kmod-2.1.99-1

### Describe the problem you're observing

Recent master broke SIMD acceleration for AES-GCM, I suspect the recent ICP changes. Both, `pclmulqdq` and `avx` are missing.

Sorry, I can't look into this before midweek.

### Describe how to reproduce the problem

```sh
cat /sys/module/icp/parameters/icp_gcm_impl 
cycle [fastest] generic
```

### PR DESCRIPTION
**Pull request by AttilaFueloep**
### Motivation and Context

Linux 5.16 moved XSTATE_XSAVE and XSTATE_XRESTORE out of our reach.

Closes  #13042

### Description

Add our own XSAVE{,OPT,S} code and use it for Linux 5.16.

Please note that this differs from previous behavior in that it
won't handle exception created by XSAVE an XRSTOR. This is sensible
for three reasons.

 - Exceptions during XSAVE and XRSTOR can only occur if the feature
   is not supported or enabled or the memory operand isn't aligned
   on a 64 byte boundary. If this happens something else went
   terribly wrong, and it may be better to stop execution.

 - Previously we just printed a warning and didn't handle the fault,
   this is arguable for the above reason.

 - All other *SAVE instruction also don't handle exceptions, so this
   at least aligns behavior.

### How Has This Been Tested?

Verified with gdb that the FPU registers are properly restored.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:
- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by AttilaFueloep** [comment]
Sorry, pushed from wrong branch, fixed now. If there is a need to handle exceptions as the previous version was doing, I can try to wrap my head around the `.fixup`, `__ex_table` etc. stuff.

**Comment by rincebrain** [comment]
Might it make sense to switch over unconditionally, not just for 5.16+, if there's no important downsides? (Or, if we think there might be but we haven't spotted them yet, to rip off the band-aid and spot them faster?)

**Comment by AttilaFueloep** [comment]
Yes, it might, I just choose the least intrusive approach to play it safe. There may also be a slight performance loss involved since the `XSTATE_XSAVE` macro used [ALTERNATIVE*](https://elixir.bootlin.com/linux/v5.15.19/source/arch/x86/include/asm/alternative.h#L159) to choose between the different XSAVE instruction, but I'm just using a plain C `if` statement. This, and the changed exception handling may justify to use it only for 5.16+, but I'm somewhat undecided here.

File: include/os/linux/kernel/linux/simd_x86.h [hunk 1]
```diff
@@ -322,7 +441,7 @@ kfpu_end(void)
 #define	kfpu_init()		0
 #define	kfpu_fini()		((void) 0)
 
-#endif /* defined(HAVE_KERNEL_FPU_INTERNAL) */
+#endif /* defined HAVE_KERNEL_FPU_INTERNAL || HAVE_KERNEL_FPU_XSAVE INTERNAL */
```
Comment (nabijaczleweli) [inline include/os/linux/kernel/linux/simd_x86.h:444]: space in `HAVE_KERNEL_FPU_XSAVE INTERNAL` (also a better phrasing would be `defined(HAVE_KERNEL_FPU_INTERNAL) || defined(HAVE_KERNEL_FPU_XSAVE_INTERNAL)` or `defined(HAVE_KERNEL_FPU_INTERNAL || HAVE_KERNEL_FPU_XSAVE_INTERNAL)`)

Comment (AttilaFueloep) [reply include/os/linux/kernel/linux/simd_x86.h:444]: Thanks for catching that, fixed.

**Comment by tonyhutter** [comment]
> Might it make sense to switch over unconditionally, not just for 5.16+, if there's no important downsides? (Or, if we think there might be but we haven't spotted them yet, to rip off the band-aid and spot them faster?)

I would vote for this as well.  That way it gets exercised by buildbot for all kernels and simplifies the code.  If there is a slight performance loss, that's fine, since it's just something we're going to have to live with going forward anyway.

**Comment by behlendorf** [comment]
Applying these changes to just 5.16+ kernels would be the lowest risk option, and it's consistent with how we've tried to handle this in the past.  But in this case I could see making an exception.  Applying this to all kernels which don't provide fpu symbols looks like it would significantly simplify the code which would be nice.

Perhaps a reasonable compromise would be to apply this patch to master which only using the new code for 5.16+.  This could then be easily backported for the 2.1.3 release.  Then follow up with a commit to master which uses the new code unconditionally.  Which is really what we'd prefer to maintain long term. 

Previously we found that running the `mprime` stress test from https://www.mersenne.org/download/ while performing read/write IO was an excellent way to verify the fpu was being saved/restored correctly.  Running it over night would be a good way to develop confidence in the change.

I also agree for the reasons you mentioned it's reasonable to not handle exceptions here.  Thanks again for tackling this!

**Comment by AttilaFueloep** [comment]
Yes, I think this is a good idea, that way we would make sure that changes to stable releases are minimal, while having a broader range of systems running master exercising  the new code.

Thinking more of it, I could come up with an edge case where things may break: a very old kernel with eagerfpu=off will use the CR0.TS bit during context switching and calling XSAVE with CR0.TS=1 will generate a #NM fault. So if this kernel happens to have backported the GPL only kfpu patch, it will panic. Not sure if we support such a setup at all. It's a very unlikely scenario also, and no one would intentionally  set eagerfpu=off on a CPU supporting SIMD extension since manipulating the CT0.TS bits takes longer than storing the FPU state. So not sure if we should add a test for `eagerfpu == off` inside `kfpu_init()` if we remove `XSTATE_XSAVE`.

Setting up some test datasets with encryption, fletcher, sha2, skein and edonr checksums on a raidz pool and doing  I/O in loop on them while running  mprime is on my todo list.  That should cover all code paths which use `simd_x86.h`. Since the testvm is on my notebook I can only do this overnight, and being in a UCT+1 timezone this will have to wait for ~16 hours. (Having traced with gdb the code path inside ICP makes me pretty confident that the tests will stand though..)

**Comment by behlendorf** [comment]
If you get a chance to rebase and force  update this PR this should clear up the CI failures,

**Comment by AttilaFueloep** [comment]
I added a regression test to make sure FPU support won't break without notice again, not sure where to put it though. I'd appreciate any hint. Once I know where to put the test I'll squash and rebase.

**Comment by AttilaFueloep** [comment]
The tests didn't went so well, I'm seeing system freezes. Have to look into it more deeply.

**Comment by AttilaFueloep** [comment]
D'oh once you push from a wrong branch things will start to go south.. Will run the tests with the proper version tonight.

**Comment by behlendorf** [comment]
`functional/simd/` sounds good. 

The `Requires-builders: style` comment is currently only understood by the buildbit CI builders, and not the GitHub actions CI builders.  So those always run.

**Comment by AttilaFueloep** [comment]
> `functional/simd/` sounds good.

All right, will put it there.

> The `Requires-builders: style` comment is currently only understood by the buildbit CI builders, and not the GitHub actions CI builders. So those always run.

I see, thanks for the explanation.

**Comment by rincebrain** [comment]
I forget if I mentioned in this thread, but my intent after this gets fixed
was to make a configure check that would make the FPU configure checks hard
fail on "not found' instead of continuing - that way, we can catch those on
the build-only bots, too.

Not suggesting the two are mutually exclusive, just mentioning as a data
point for where I was planning to catch this.

**Comment by AttilaFueloep** [comment]
Not that I know of. That may make sense, just trying  to think of some edge cases where this may come in the way.  Maybe an embedded system with a striped down Linux kernel? Does this make sense? I think if you make it hard fail, a configure option like `--without-fpu`  should be put in place. Of course that would collide with a zfs-test. Since I wrote the test already, let me add it. If need be, we can remove it later with no fuss.

**Comment by rincebrain** [comment]
Oh of course, I wasn't suggesting you not add something already written and
fit for purpose, and I'm sorry if it came off that way.

**Comment by AttilaFueloep** [comment]
No sorry, you didn't come off that way. What  I wanted to say was that it's a good idea, and you shouldn't feel that the zfs-test  is in your way (and just go ahead as you see fit). 

I've to leave the room now, four fio and a mprime torture run make for really noisy box :-)

**Comment by AttilaFueloep** [comment]
Squashed and rebased. Added a regression test.

**Comment by AttilaFueloep** [comment]
Tested this PR now. Made a 3 disk (actual 3 partition on the same SSD) raidz1 pool, created three datasets on it, one encrypted/fletcher3, one unencrypted/sha512 and one unencrypted/skein. Ran a 4 thread/16 files `fio` on each of them, started a `mprime -t` torture test and let all of this run for six hours on a six vCPU 16G mem kvm vm.

All went well, no `mprime` failures, no checksum error, no I/O errors, scrub showed no errors either. A `mprime` run on a version where the call to XRSTOR was comment out failed within seconds after starting a `fio` run, so this looks solid.

**Comment by AttilaFueloep** [comment]
This is ready for review, looks like I can't remove the draft tag.

**Comment by rincebrain** [comment]
IIRC there should be a button around the CI status window at the bottom for "ready for review? mark as not draft any more" - it has a notice that only people with write access to the branch can make that change, for me, here.

**Comment by AttilaFueloep** [comment]
D'oh, yes there is, thanks!

**Comment by AttilaFueloep** [comment]
Sorry for force pushing again, fixed up the commit message. This seems not to be my year.

File: config/kernel-fpu.m4 [hunk 2]
```diff
@@ -1,9 +1,12 @@
...
+dnl #
 dnl # Handle differences in kernel FPU code.
 dnl #
 dnl # Kernel
 dnl # 5.16:	XCR code put into asm/fpu/xcr.h
-dnl # 		HAVE_KERNEL_FPU_XCR_HEADER
+dnl #		HAVE_KERNEL_FPU_XCR_HEADER
+dnl #
+dnl #		XSTATE_XSAVE and XSTATE_XRESTORE aren't accessible any more
+dnl #		HAVE_KERNEL_FPU_INTERNAL_NO_XSTATE
```
Comment (behlendorf) [inline config/kernel-fpu.m4:9]: This isn't defined anywhere, shouldn't this be `HAVE_KERNEL_FPU_XSAVE_INTERNAL`?

File: tests/runfiles/linux.run [hunk 3]
```diff
@@ -168,3 +168,9 @@ tags = ['functional', 'user_namespace']
 tests = ['groupspace_001_pos', 'groupspace_002_pos', 'groupspace_003_pos',
     'userquota_013_pos', 'userspace_003_pos']
 tags = ['functional', 'userquota']
+
+[tests/functional/simd:Linux]
+pre =
+post =
+tests = ['simd_supported']
+tags = ['functional', 'simd']
```
Comment (behlendorf) [inline tests/runfiles/linux.run:176]: nit: can you move this up in to alphabetical order with the other test groups.

**Review by behlendorf — COMMENTED** [review]
Looks good.

File: tests/runfiles/linux.run (hunk 3 above)
Comment (AttilaFueloep) [reply tests/runfiles/linux.run:176]: Will do. Also missed to add the new test dir to `SUBDIRS` in `Makefile.am` and to `configure.ac`. I gues that's the reason the test fails verification.

File: include/os/linux/kernel/linux/simd_x86.h [hunk 4]
```diff
@@ -136,9 +136,28 @@
...
+ * For kernels >= 5.16 we have to use inline assembly with the XSAVE{,OPT,S}
+ * instructions, so we need the toolchain to support at least XSAVE.
+ */
+#if !defined(HAVE_XSAVE)
+#error "Toolchain needs to support the XSAVE assembler instruction"
+#endif
+#endif
 
 #include <linux/mm.h>
+/* XXX Linux 5.16 has kzalloc and kfree in slab.h, create autoconf check? */
```
[the remark this answers is not in the document]
Comment (AttilaFueloep) [reply include/os/linux/kernel/linux/simd_x86.h:159]: So out of scope I guess. Will remove the comment.

File: config/kernel-fpu.m4 (hunk 2 above)
Comment (AttilaFueloep) [reply config/kernel-fpu.m4:9]: Yes, will fix.

**Review by behlendorf — APPROVED** [review]

**Review by tonyhutter — APPROVED** [review]

**Comment by AttilaFueloep** [comment]
Squashed and rebased.

**Comment by behlendorf** [comment]
@AttilaFueloep thanks for tackling this one, merged.

**Comment by AttilaFueloep** [comment]
As discussed here, I'll open a new PR, factoring out the XSTATE stuff for all kernels not exporting *kfpu_{begin,end}.

@rincebrain 

> I forget if I mentioned in this thread, but my intent after this gets fixed was to make a configure flag that would make the FPU configure checks hard fail on "not found' instead of continuing

I think the above mentioned PR will be fail-safe per se by not using any kernel fpu stuff.
