### PR TITLE
Fix lua stack overflow on recursive call to gsub()

### LINKED ISSUE #10611: ZFS Channel Programs can cause a stack overflow in the kernel and block future `zfs` operations
### System information

Type | Version/Name
 --- | ---
Distribution Name	| NixOS
Distribution Version	| 20.09pre235551.3112aa3e2fa
Linux Kernel	| Linux example 5.4.52 #1-NixOS SMP Thu Jul 16 06:16:48 UTC 2020 x86_64 GNU/Linux
Architecture	| x86_64-linux
ZFS Version	| 0.8.4-1
SPL Version	| 0.8.4-1

### Describe the problem you're observing

Channel programs cause a segfault in `zfs program`, and any subsequent `zfs` executions block and are unkillable, though `zpool` seems to work okay.

Note, I would have sent this privately but it has been discussed publicly in #zfsonlinux several times and has been referenced here for about 20 days: https://github.com/cyberitsolutions/cyber-zfs-backup/commit/7c0ccc15c760a72ae722052fe9c316093da084d5

From that commit:
 
> but I bet they didn't know about how gsub allocates a ton of stack
> there are three problematic functions that can do this, gsub is one of them
> hm, the table.concat one might not work on 5.2

### Describe how to reproduce the problem

```
[root@example:/]# cat > crasher.lua
local function f(s) s:gsub(".", f) return "x" end f("foo")
return tostring(setmetatable({},{__tostring=function(t) string.format("%s",t) end}))

[root@example:/]# zfs program -n bogus ./crasher.lua
Segmentation fault

[root@example:/]# zfs list
^C^C^C^Z


(new terminal)

[root@example:~]# zpool list
NAME    SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
bogus  3.75G   110K  3.75G        -         -     0%     0%  1.00x    ONLINE  -
```

### Include any warning/errors/backtraces from the system logs

<details>

<summary> **_click to expand_** for the kernel backtrace </summary>

```
BUG: stack guard page was hit at 0000000085e0fbd2 (stack is 00000000c3441ff5..0000000048bbafb2)
kernel stack overflow (double-fault): 0000 [#1] SMP PTI
CPU: 0 PID: 1122 Comm: zfs Tainted: P           OE     5.4.52 #1-NixOS
Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
RIP: 0010:str_gsub+0x1e/0x4c0 [zlua]
Code: 00 be 01 00 00 00 e9 f1 fc ff ff 90 0f 1f 44 00 00 41 57 be 01 00 00 00 41 56 41 55 41 54 55 53 48 89 fb 48 81 ec a0 03 00 00 <48> 89 7c 24 20 48 8d 54 24 30 65 48 8b 04 25 28 00 00 00 48 89 84
RSP: 0018:ffffa42ec072bdc8 EFLAGS: 00010282
RAX: ffff89f98ebd18d8 RBX: ffff89f98ebd1808 RCX: 0000000000008219
RDX: ffff89f989995678 RSI: 0000000000000001 RDI: ffff89f98ebd1808
RBP: ffff89f98ebd1808 R08: ffff89f99e22d320 R09: ffffffffc0257c00
R10: ffff89f99dc01540 R11: 0000000000000001 R12: 0000000000000000
R13: ffff89f992fe5248 R14: ffff89f9899954f8 R15: 0000000000000000
FS:  00007f740ef687c0(0000) GS:ffff89f99e200000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: ffffa42ec072bde8 CR3: 000000001abbe003 CR4: 00000000000206f0
Call Trace:
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? propagatemark+0x26c/0x680 [zlua]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? singlestep+0x1a0/0x4c0 [zlua]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? kfree+0xd0/0x200
 ? zcp_lua_alloc+0x6b/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? luaM_growaux_+0x63/0xb0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? kfree+0xd0/0x200
 ? zcp_lua_alloc+0x6b/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? close_func+0x140/0x1f0 [zlua]
 ? body+0x1df/0x2e0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 ? luaD_precall+0x3b2/0x3f0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 ? push_captures+0x4f/0x90 [zlua]
 lua_callk+0x3c/0x80 [zlua]
 str_gsub+0x142/0x4c0 [zlua]
 ? funcargs+0xac/0x170 [zlua]
 ? inclinenumber+0xb5/0xd0 [zlua]
 ? llex+0x869/0xe70 [zlua]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? luaK_code+0x25/0xe0 [zlua]
 ? funcargs+0xac/0x170 [zlua]
 ? suffixedexp+0xfd/0x180 [zlua]
 ? subexpr+0x432/0x470 [zlua]
 ? llex+0xa5c/0xe70 [zlua]
 ? luaK_code+0x25/0xe0 [zlua]
 ? statement+0x472/0xe10 [zlua]
 ? luaX_newstring+0x51/0xb0 [zlua]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? __kmalloc_node+0x1ec/0x300
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? spl_kmem_alloc_impl+0xd8/0x120 [spl]
 ? zcp_lua_alloc+0xf7/0x120 [zfs]
 ? luaM_realloc_+0x39/0xa0 [zlua]
 ? str_find+0x10/0x10 [zlua]
 luaD_precall+0x265/0x3f0 [zlua]
 luaV_execute+0xc60/0x15a0 [zlua]
 luaD_call+0xa1/0xd0 [zlua]
 luaD_rawrunprotected+0x6e/0xb0 [zlua]
 ? lua_setmetatable+0x110/0x110 [zlua]
 ? luaD_rawrunprotected+0x57/0xb0 [zlua]
 luaD_pcall+0x34/0x90 [zlua]
 lua_pcallk+0x85/0x120 [zlua]
 zcp_eval_impl+0x108/0x440 [zfs]
 zcp_eval+0x560/0x810 [zfs]
 ? nvlist_lookup_nvpair_ei_sep+0x244/0x400 [znvpair]
 zfs_ioc_channel_program+0xea/0x120 [zfs]
 zfsdev_ioctl+0x1d9/0x8c0 [zfs]
 ? selinux_file_ioctl+0x174/0x220
 do_vfs_ioctl+0x3fe/0x660
 ksys_ioctl+0x5e/0x90
 __x64_sys_ioctl+0x16/0x20
 do_syscall_64+0x4e/0x120
 entry_SYSCALL_64_after_hwframe+0x44/0xa9
RIP: 0033:0x7f740f061397
Code: 00 00 90 48 8b 05 f9 9a 0c 00 64 c7 00 26 00 00 00 48 c7 c0 ff ff ff ff c3 66 2e 0f 1f 84 00 00 00 00 00 b8 10 00 00 00 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d c9 9a 0c 00 f7 d8 64 89 01 48
RSP: 002b:00007ffe2d68a908 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
RAX: ffffffffffffffda RBX: 00007ffe2d68dfd8 RCX: 00007f740f061397
RDX: 00007ffe2d68a930 RSI: 0000000000005a48 RDI: 0000000000000005
RBP: 00007ffe2d68df10 R08: 00007f74013d7010 R09: 0000000000000000
R10: 0000000000000022 R11: 0000000000000246 R12: 0000000000005a48
R13: 00007ffe2d68a930 R14: 0000000000000005 R15: 0000000000005a48
Modules linked in: af_packet cfg80211 rfkill 8021q intel_rapl_msr virtio_net net_failover failover vboxvideo(OE) intel_rapl_common intel_pmc_core_pltdrv ttm intel_pmc_core intel_powerclamp rapl drm_kms_helper input_leds led_class drm snd_intel8x0 serio_raw psmouse snd_ac97_codec ac97_bus snd_pcm fb_sys_fops evdev snd_timer intel_agp syscopyarea sysfillrect sysimgblt joydev i2c_piix4 virtio_pci intel_gtt snd mousedev mac_hid i2c_core virtio_ring soundcore agpgart virtio video battery backlight ac button ip6table_nat iptable_nat nf_nat xt_conntrack nf_conntrack nf_defrag_ipv4 libcrc32c ip6t_rpfilter ipt_rpfilter ip6table_raw iptable_raw xt_pkttype nf_log_ipv6 nf_log_ipv4 nf_log_common xt_LOG xt_tcpudp ip6table_filter ip6_tables sch_fq_codel iptable_filter loop tun tap macvlan bridge stp llc ip_tables x_tables ipv6 nf_defrag_ipv6 crc_ccitt autofs4 ext4 crc32c_generic crc16 mbcache jbd2 sd_mod ahci libahci atkbd libps2 libata rtc_cmos crc32c_intel i8042 scsi_mod serio dm_mod
 vboxsf(OE) vboxguest(OE) zfs(POE) zunicode(POE) zavl(POE) icp(POE) zlua(POE) zcommon(POE) znvpair(POE) spl(OE)
---[ end trace eec70f6456e9c09e ]---
RIP: 0010:str_gsub+0x1e/0x4c0 [zlua]
Code: 00 be 01 00 00 00 e9 f1 fc ff ff 90 0f 1f 44 00 00 41 57 be 01 00 00 00 41 56 41 55 41 54 55 53 48 89 fb 48 81 ec a0 03 00 00 <48> 89 7c 24 20 48 8d 54 24 30 65 48 8b 04 25 28 00 00 00 48 89 84
RSP: 0018:ffffa42ec072bdc8 EFLAGS: 00010282
RAX: ffff89f98ebd18d8 RBX: ffff89f98ebd1808 RCX: 0000000000008219
RDX: ffff89f989995678 RSI: 0000000000000001 RDI: ffff89f98ebd1808
RBP: ffff89f98ebd1808 R08: ffff89f99e22d320 R09: ffffffffc0257c00
R10: ffff89f99dc01540 R11: 0000000000000001 R12: 0000000000000000
R13: ffff89f992fe5248 R14: ffff89f9899954f8 R15: 0000000000000000
FS:  00007f740ef687c0(0000) GS:ffff89f99e200000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: ffffa42ec072bde8 CR3: 000000001abbe003 CR4: 00000000000206f0
------------[ cut here ]------------
WARNING: CPU: 0 PID: 0 at kernel/rcu/tree.c:569 rcu_idle_enter+0xee/0x100
Modules linked in: af_packet cfg80211 rfkill 8021q intel_rapl_msr virtio_net net_failover failover vboxvideo(OE) intel_rapl_common intel_pmc_core_pltdrv ttm intel_pmc_core intel_powerclamp rapl drm_kms_helper input_leds led_class drm snd_intel8x0 serio_raw psmouse snd_ac97_codec ac97_bus snd_pcm fb_sys_fops evdev snd_timer intel_agp syscopyarea sysfillrect sysimgblt joydev i2c_piix4 virtio_pci intel_gtt snd mousedev mac_hid i2c_core virtio_ring soundcore agpgart virtio video battery backlight ac button ip6table_nat iptable_nat nf_nat xt_conntrack nf_conntrack nf_defrag_ipv4 libcrc32c ip6t_rpfilter ipt_rpfilter ip6table_raw iptable_raw xt_pkttype nf_log_ipv6 nf_log_ipv4 nf_log_common xt_LOG xt_tcpudp ip6table_filter ip6_tables sch_fq_codel iptable_filter loop tun tap macvlan bridge stp llc ip_tables x_tables ipv6 nf_defrag_ipv6 crc_ccitt autofs4 ext4 crc32c_generic crc16 mbcache jbd2 sd_mod ahci libahci atkbd libps2 libata rtc_cmos crc32c_intel i8042 scsi_mod serio dm_mod
 vboxsf(OE) vboxguest(OE) zfs(POE) zunicode(POE) zavl(POE) icp(POE) zlua(POE) zcommon(POE) znvpair(POE) spl(OE)
CPU: 0 PID: 0 Comm: swapper/0 Tainted: P      D    OE     5.4.52 #1-NixOS
Hardware name: innotek GmbH VirtualBox/VirtualBox, BIOS VirtualBox 12/01/2006
RIP: 0010:rcu_idle_enter+0xee/0x100
Code: 45 00 48 8b 7d 08 48 83 c5 18 45 89 e8 31 c9 ba 01 00 00 00 4c 89 e6 e8 80 b2 90 00 48 8b 45 00 48 85 c0 75 dd e9 7c ff ff ff <0f> 0b e9 3f ff ff ff 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 44 00
RSP: 0000:ffffffffbc003e98 EFLAGS: 00010002
RAX: ffff89f99e22ad00 RBX: 000000000002ad00 RCX: 0000000000000000
RDX: 4000000000000000 RSI: ffffffffbc003e40 RDI: 00000066a2f9f28a
RBP: ffffffffbc013780 R08: 0000000000000001 R09: 00000000001db2b4
R10: 000000000000076e R11: 0000000000000001 R12: ffffffffbc013780
R13: 0000000000000000 R14: 0000000000000000 R15: ffffffffbc013780
FS:  0000000000000000(0000) GS:ffff89f99e200000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007f35d990df90 CR3: 000000000d364004 CR4: 00000000000206f0
Call Trace:
 do_idle+0x1e8/0x250
 cpu_startup_entry+0x19/0x20
 start_kernel+0x4d9/0x4fb
 secondary_startup_64+0xa4/0xb0
---[ end trace eec70f6456e9c09f ]---
```

</summary>

### PR DESCRIPTION
**Pull request by ahrens**
### Motivation and Context

The `zfs program` subcommand invokes a LUA interpreter to run ZFS
"channel programs".  This interpreter runs in a constrained environment,
with defined memory limits.  The LUA stack (used for LUA functions that
call each other) is allocated in the kernel's heap, and is limited by
the `-m MEMORY-LIMIT` flag and the `zfs_lua_max_memlimit` module
parameter.  The C stack is used by certain LUA features that are
implemented in C.  The C stack is limited by `LUAI_MAXCCALLS=20`, which
limits call depth.

Some LUA C calls use more stack space than others, and `gsub()` uses an
unusually large amount.  With a programming trick, it can be invoked
recursively using the C stack (rather than the LUA stack).  This
overflows the 16KB Linux kernel stack after about 11 iterations, less
than the limit of 20.

Closes #10611

### Description

One solution would be to decrease `LUAI_MAXCCALLS`.  This could be made
to work, but it has a few drawbacks:

1. The existing test suite does not pass with `LUAI_MAXCCALLS=10`.

2. There may be other LUA functions that use a lot of stack space, and
the stack space may change depending on compiler version and options.

This commit addresses the problem by adding a new limit on the amount of
free space (in bytes) remaining on the C stack while running the LUA
interpreter: `LUAI_MINCSTACK=4096`.  If there is less than this amount
of stack space remaining, a LUA runtime error is generated.

### How Has This Been Tested?

added a new test case
ran ZTS

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/lua/ldo.c [hunk 1]
```diff
@@ -447,6 +459,11 @@ void luaD_call (lua_State *L, StkId func, int nResults, int allowyield) {
     else if (L->nCcalls >= (LUAI_MAXCCALLS + (LUAI_MAXCCALLS>>3)))
       luaD_throw(L, LUA_ERRERR);  /* error while handing stack error */
   }
+  intptr_t remaining = stack_remaining();
+  if (L->runerror == 0 && remaining < LUAI_MINCSTACK)
+    luaG_runerror(L, "C stack overflow");
+  if (L->runerror != 0 && remaining < LUAI_MINCSTACK / 2)
+    luaD_throw(L, LUA_ERRERR);  /* error while handing stack error */
```
Comment (sdimitro) [inline module/lua/ldo.c:466]: nit: s/handing/handling/

File: tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+#
+
+. $STF_SUITE/tests/functional/channel_program/channel_common.kshlib
+
+#
+# DESCRIPTION:
+#       Overflowing the C stack using recursive gsub() should be handled
+#       gracefully.  gsub() uses more stack space than typical, so
+#	LUAI_MAXCCALLS must be set lower to ensure that we don't overflow
+#	the Linux kernel's stack.
```
Comment (sdimitro) [inline tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh:24]: nit: indentation

File: module/lua/ldo.c [hunk 3]
```diff
@@ -447,6 +459,11 @@ void luaD_call (lua_State *L, StkId func, int nResults, int allowyield) {
     else if (L->nCcalls >= (LUAI_MAXCCALLS + (LUAI_MAXCCALLS>>3)))
       luaD_throw(L, LUA_ERRERR);  /* error while handing stack error */
   }
+  intptr_t remaining = stack_remaining();
+  if (L->runerror == 0 && remaining < LUAI_MINCSTACK)
+    luaG_runerror(L, "C stack overflow");
+  if (L->runerror != 0 && remaining < LUAI_MINCSTACK / 2)
```
Comment (grwilson) [inline module/lua/ldo.c:465]: Is there something special about 1/2 of `LUAI_MINCSTACK` that indicates an error handling the stack overflow error? For example, if `LUAI_MINCSTACK` is ever changed is 1/2 still the correct value?

File: tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+# Copyright (c) 2020 by Delphix. All rights reserved.
+#
+
+. $STF_SUITE/tests/functional/channel_program/channel_common.kshlib
+
+#
+# DESCRIPTION:
+#       Overflowing the C stack using recursive gsub() should be handled
+#       gracefully.  gsub() uses more stack space than typical, so
+#	LUAI_MAXCCALLS must be set lower to ensure that we don't overflow
```
Comment (grwilson) [inline tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh:23]: Should this be `LUA_MAX_MEMLIMIT` instead of `LUAI_MAXCCALLS`?

Comment (grwilson) [inline tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh:23]: I don't see where you're setting `LUAI_MAXCCALLS` lower so wondering if this comment is no longer valid.

File: tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+#	the Linux kernel's stack.
+#
+
+verify_runnable "global"
+
+log_assert "recursive gsub() should be handled gracefully"
+
+log_mustnot_program $TESTPOOL $ZCP_ROOT/lua_core/tst.stack_gsub.zcp
+
```
Comment (grwilson) [inline tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh:32]: Given that the bug reported `zfs` command failing afterwards, does it make sense to run a simple `zfs` operation here that must succeed?

File: module/lua/ldo.c (hunk 1 above)
Comment (ahrens) [reply module/lua/ldo.c:466]: LOL, this is copy-pasted from the comment above, I'll fix it too.

File: module/lua/ldo.c (hunk 3 above)
Comment (ahrens) [reply module/lua/ldo.c:465]: > Is there something special about 1/2 of LUAI_MINCSTACK that indicates an error handling the stack overflow error?

No, it's just that we are saying that when you get to only LUAI_MINCSTACK (4KB) remaining, then we generate the runtime error (which has the nice message and stack trace, see `tst.stack_gsub.err`).  Generating the runtime error calls more LUA code and we allow it to use another LUAI_MINCSTACK/2 (2KB) of the stack, before falling back on `luaD_throw()`, which generates a generic message like "error while handling error".

If we allowed unlimited stack use while handling the error, then in theory (but not in practice) the error handling code could overflow the kernel's stack causing a panic.  If we didn't allow any additional stack use while handling the error, it would always fall back on the less helpful "error while handling error".

This is the same behavior as the handling of `LUAI_MAXCCALLS` a few lines above, although the mechanism for detecting that we are handling an error is different (and IMO more clear) in the new code.

>  For example, if LUAI_MINCSTACK is ever changed is 1/2 still the correct value?

It would probably still be reasonable, if imperfect.  This is a similar mechanism used for LUAI_MAXCCALLS, which allows 1/8th the calls (20/8=2) for error handling.

File: tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh (hunk 4 above)
Comment (ahrens) [reply tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh:23]: Thanks, this was based on an older revision.  Fixed.

File: tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh (hunk 5 above)
Comment (ahrens) [reply tests/zfs-tests/tests/functional/channel_program/lua_core/tst.stack_gsub.ksh:32]: That was because the "kernel panicked", meaning that the kernel killed the zfs module without rebooting.  In our system configuration the system would actually reboot if the kernel pancked.  In any case, `zfs program` would exit nonzero (as seen in the bug report) so this test would fail.

File: module/lua/ldo.c [hunk 6]
```diff
@@ -29,6 +29,18 @@
...
 
 
+/* Return the number of bytes available on the stack. */
+#if defined (_KERNEL) && defined(__linux__)
+#include <asm/current.h>
+static intptr_t stack_remaining(void) {
+  char local;
+  return (intptr_t)(&local - (char *)current->stack);
+}
+#else
```
Comment (freqlabs) [inline module/lua/ldo.c:39]: I'll see if I can come up with something that works for FreeBSD.

File: module/lua/ldo.c [hunk 7]
```diff
@@ -29,6 +29,18 @@
 
 
 
+/* Return the number of bytes available on the stack. */
+#if defined (_KERNEL) && defined(__linux__)
```
Comment (behlendorf) [inline module/lua/ldo.c:33]: It looks to me like this issue isn't specific to Linux, FreeBSD's default stack size is also 16K (KSTACK_PAGES=4).

File: module/lua/ldo.c (hunk 6 above)
Comment (freqlabs) [reply module/lua/ldo.c:39]:
```C
#include <sys/pcpu.h>
struct thread *td = curthread;
return (intptr_t)((char *)&td - (char *)td->td_kstack);
```

File: module/lua/llimits.h [hunk 8]
```diff
@@ -122,6 +122,12 @@ typedef LUAI_UACNUMBER l_uacNumber;
 #define LUAI_MAXCCALLS		20
 #endif
 
+/*
+ * Minimum amount of available stack space (in bytes) to make a C call.  With
+ * gsub() recursion, the stack space between each luaD_call() is 1256 bytes.
+ */
+#define LUAI_MINCSTACK		4096
```
Comment (behlendorf) [inline module/lua/llimits.h:129]: Can we safely decrease this further for 32-bit platforms where the default on x86_32 is still 8K.

File: module/lua/ldo.c (hunk 7 above)
Comment (allanjude) [reply module/lua/ldo.c:33]: Yes, the same LUA test program instantly panics FreeBSD

Comment (behlendorf) [reply module/lua/ldo.c:33]: Looks like I was a little to slow. Thanks @freqlabs.

File: module/lua/llimits.h (hunk 8 above)
Comment (ahrens) [reply module/lua/llimits.h:129]: Probably, but 4K might also work fine (leaving 4K for normal LUA stuff). Do you know how to test this?  It looks like there's a "Ubuntu 16.04 i386" build, but not an associated test?

Comment (behlendorf) [reply module/lua/llimits.h:129]: There a 32-bit builder to test the compile but none that run the test suite.  We'd need to manually test in a VM.  4K may be fine, though leaving 4K for everything else feels a bit tight to me.  Using an Ubuntu 16.04 iso is probably the easiest route.

File: module/lua/ldo.c (hunk 6 above)
Comment (ahrens) [reply module/lua/ldo.c:45]: Thanks!  I've added this to the PR.  I changed the code slightly so that both linux and freebsd have the same form with the `local`, take a look.

**Comment by grahamc** [comment]
Thank you, everyone!
