### PR TITLE
Avoid deadlock when removing L2ARC devices under I/O

### LINKED ISSUE #10286: removing L2ARC device from pool sometimes causes a freeze
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| Debian
Distribution Version	| 10.3
Linux Kernel	| 4.19.98-1+deb10u1
Architecture	| amd64
ZFS Version	| 0.8.3-1~bpo10+1
SPL Version	| 0.8.3-1~bpo10+1

### Describe the problem you're observing
I have been using a pool with two L2ARC devices for a while now and tried to remove them. Running 'zpool remove stor device-id' resulted in a freeze - this command stayed in D state and all zvols stopped working (iostat showed utilization 100% on some of them, but no reads/writes/etc).
I hit "reset" on the server. After it rebooted, both L2ARC devices were still present. I tried to remove one again and succeeded. Tried to remove the second one and got the same exact problem.
After a second reboot I was able to remove the second L2ARC device.

I tried adding them back and removing them again, but did not encounter the problem.
### Describe how to reproduce the problem
Try to remove a L2ARC device from a pool or try to remove two L2ARC devices from a pool in rapid succession.
### Include any warning/errors/backtraces from the system logs

This is from my first attempt to remove the L2ARC device. I did not wait long enough after the second time - just hit reset immediately after I saw the problem.
```
May  3 18:27:39 starlight kernel: [4828316.142069] INFO: task zvol:942 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.142865]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.143561] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.144247] zvol            D    0   942      2 0x80000000
May  3 18:27:39 starlight kernel: [4828316.144927] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.145604]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.146328]  ? __kmalloc+0x177/0x210
May  3 18:27:39 starlight kernel: [4828316.146978]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.147613]  cv_wait_common+0xfb/0x130 [spl]
May  3 18:27:39 starlight kernel: [4828316.148239]  ? finish_wait+0x80/0x80
May  3 18:27:39 starlight kernel: [4828316.148917]  spa_config_enter+0xed/0x100 [zfs]
May  3 18:27:39 starlight kernel: [4828316.149563]  zfs_blkptr_verify+0x2f2/0x3e0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.150215]  zio_read+0x3d/0xb0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.150845]  ? arc_buf_destroy+0x100/0x100 [zfs]
May  3 18:27:39 starlight kernel: [4828316.151475]  arc_read+0x88a/0xff0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.152081]  ? spl_kmem_zalloc+0xe0/0x130 [spl]
May  3 18:27:39 starlight kernel: [4828316.152703]  dbuf_issue_final_prefetch+0x74/0xc0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.153322]  dbuf_prefetch+0x561/0x5c0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.153938]  ? dbuf_rele_and_unlock+0x630/0x630 [zfs]
May  3 18:27:39 starlight kernel: [4828316.154563]  dmu_zfetch+0x4f1/0x5a0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.155180]  dmu_buf_hold_array_by_dnode+0x37d/0x480 [zfs]
May  3 18:27:39 starlight kernel: [4828316.155798]  dmu_read_uio_dnode+0x47/0xf0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.156398]  ? generic_start_io_acct+0xd7/0xf0
May  3 18:27:39 starlight kernel: [4828316.157013]  zvol_read+0x10f/0x2c0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.157583]  taskq_thread+0x2df/0x520 [spl]
May  3 18:27:39 starlight kernel: [4828316.158142]  ? wake_up_q+0x70/0x70
May  3 18:27:39 starlight kernel: [4828316.158678]  ? taskq_thread_spawn+0x50/0x50 [spl]
May  3 18:27:39 starlight kernel: [4828316.159198]  kthread+0x112/0x130
May  3 18:27:39 starlight kernel: [4828316.159698]  ? kthread_bind+0x30/0x30
May  3 18:27:39 starlight kernel: [4828316.160183]  ret_from_fork+0x35/0x40
May  3 18:27:39 starlight kernel: [4828316.160648] INFO: task dbuf_evict:964 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.161110]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.161582] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.162066] dbuf_evict      D    0   964      2 0x80000000
May  3 18:27:39 starlight kernel: [4828316.162554] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.163029]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.163493]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.163937]  schedule_preempt_disabled+0xa/0x10
May  3 18:27:39 starlight kernel: [4828316.164373]  __mutex_lock.isra.8+0x2b5/0x4a0
May  3 18:27:39 starlight kernel: [4828316.164804]  ? _cond_resched+0x15/0x30
May  3 18:27:39 starlight kernel: [4828316.165232]  ? mutex_lock+0xe/0x30
May  3 18:27:39 starlight kernel: [4828316.165660]  ? __thread_exit+0x20/0x20 [spl]
May  3 18:27:39 starlight kernel: [4828316.166133]  arc_buf_destroy+0x5f/0x100 [zfs]
May  3 18:27:39 starlight kernel: [4828316.166583]  dbuf_destroy+0x2e/0x3f0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.167000]  ? __thread_exit+0x20/0x20 [spl]
May  3 18:27:39 starlight kernel: [4828316.167427]  dbuf_evict_one+0xec/0x130 [zfs]
May  3 18:27:39 starlight kernel: [4828316.167853]  dbuf_evict_thread+0x122/0x1d0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.168279]  ? dbuf_evict_one+0x130/0x130 [zfs]
May  3 18:27:39 starlight kernel: [4828316.168678]  thread_generic_wrapper+0x6f/0x80 [spl]
May  3 18:27:39 starlight kernel: [4828316.169069]  kthread+0x112/0x130
May  3 18:27:39 starlight kernel: [4828316.169451]  ? kthread_bind+0x30/0x30
May  3 18:27:39 starlight kernel: [4828316.169825]  ret_from_fork+0x35/0x40
May  3 18:27:39 starlight kernel: [4828316.170243] INFO: task l2arc_feed:984 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.170629]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.171023] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.171427] l2arc_feed      D    0   984      2 0x80000000
May  3 18:27:39 starlight kernel: [4828316.161110]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.161582] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.162066] dbuf_evict      D    0   964      2 0x80000000
May  3 18:27:39 starlight kernel: [4828316.162554] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.163029]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.163493]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.163937]  schedule_preempt_disabled+0xa/0x10
May  3 18:27:39 starlight kernel: [4828316.164373]  __mutex_lock.isra.8+0x2b5/0x4a0
May  3 18:27:39 starlight kernel: [4828316.164804]  ? _cond_resched+0x15/0x30
May  3 18:27:39 starlight kernel: [4828316.165232]  ? mutex_lock+0xe/0x30
May  3 18:27:39 starlight kernel: [4828316.165660]  ? __thread_exit+0x20/0x20 [spl]
May  3 18:27:39 starlight kernel: [4828316.166133]  arc_buf_destroy+0x5f/0x100 [zfs]
May  3 18:27:39 starlight kernel: [4828316.166583]  dbuf_destroy+0x2e/0x3f0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.167000]  ? __thread_exit+0x20/0x20 [spl]
May  3 18:27:39 starlight kernel: [4828316.167427]  dbuf_evict_one+0xec/0x130 [zfs]
May  3 18:27:39 starlight kernel: [4828316.167853]  dbuf_evict_thread+0x122/0x1d0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.168279]  ? dbuf_evict_one+0x130/0x130 [zfs]
May  3 18:27:39 starlight kernel: [4828316.168678]  thread_generic_wrapper+0x6f/0x80 [spl]
May  3 18:27:39 starlight kernel: [4828316.169069]  kthread+0x112/0x130
May  3 18:27:39 starlight kernel: [4828316.169451]  ? kthread_bind+0x30/0x30
May  3 18:27:39 starlight kernel: [4828316.169825]  ret_from_fork+0x35/0x40
May  3 18:27:39 starlight kernel: [4828316.170243] INFO: task l2arc_feed:984 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.170629]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.171023] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.171427] l2arc_feed      D    0   984      2 0x80000000
May  3 18:27:39 starlight kernel: [4828316.171834] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.172236]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.172639]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.173039]  schedule_preempt_disabled+0xa/0x10
May  3 18:27:39 starlight kernel: [4828316.173439]  __mutex_lock.isra.8+0x2b5/0x4a0
May  3 18:27:39 starlight kernel: [4828316.173839]  ? finish_wait+0x80/0x80
May  3 18:27:39 starlight kernel: [4828316.174264]  l2arc_feed_thread+0x102/0x10e0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.174668]  ? __switch_to+0x4a/0x440
May  3 18:27:39 starlight kernel: [4828316.175064]  ? __switch_to_asm+0x35/0x70
May  3 18:27:39 starlight kernel: [4828316.175479]  ? l2arc_evict+0x2a0/0x2a0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.175874]  ? __thread_exit+0x20/0x20 [spl]
May  3 18:27:39 starlight kernel: [4828316.176265]  thread_generic_wrapper+0x6f/0x80 [spl]
May  3 18:27:39 starlight kernel: [4828316.176655]  kthread+0x112/0x130
May  3 18:27:39 starlight kernel: [4828316.177040]  ? kthread_bind+0x30/0x30
May  3 18:27:39 starlight kernel: [4828316.177424]  ret_from_fork+0x35/0x40
May  3 18:27:39 starlight kernel: [4828316.177818] INFO: task txg_quiesce:2289 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.178250]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.178654] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.179066] txg_quiesce     D    0  2289      2 0x80000000
May  3 18:27:39 starlight kernel: [4828316.179479] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.179889]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.180301]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.180707]  cv_wait_common+0xfb/0x130 [spl]
May  3 18:27:39 starlight kernel: [4828316.181108]  ? finish_wait+0x80/0x80
May  3 18:27:39 starlight kernel: [4828316.181533]  txg_quiesce_thread+0x2a9/0x3a0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.181954]  ? txg_sync_thread+0x460/0x460 [zfs]
May  3 18:27:39 starlight kernel: [4828316.182352]  ? __thread_exit+0x20/0x20 [spl]
May  3 18:27:39 starlight kernel: [4828316.182742]  thread_generic_wrapper+0x6f/0x80 [spl]
May  3 18:27:39 starlight kernel: [4828316.183134]  kthread+0x112/0x130
May  3 18:27:39 starlight kernel: [4828316.183524]  ? kthread_bind+0x30/0x30
May  3 18:27:39 starlight kernel: [4828316.183914]  ret_from_fork+0x35/0x40
May  3 18:27:39 starlight kernel: [4828316.184301] INFO: task mmp:2291 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.184699]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.185106] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.185522] mmp             D    0  2291      2 0x80000000
May  3 18:27:39 starlight kernel: [4828316.185941] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.186398]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.186814]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.187230]  cv_wait_common+0xfb/0x130 [spl]
May  3 18:27:39 starlight kernel: [4828316.187645]  ? finish_wait+0x80/0x80
May  3 18:27:39 starlight kernel: [4828316.188091]  spa_config_enter+0xed/0x100 [zfs]
May  3 18:27:39 starlight kernel: [4828316.188539]  vdev_count_leaves+0x20/0x50 [zfs]
May  3 18:27:39 starlight kernel: [4828316.188986]  mmp_thread+0x2f6/0x6c0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.189434]  ? mmp_write_uberblock+0x720/0x720 [zfs]
May  3 18:27:39 starlight kernel: [4828316.189851]  ? __thread_exit+0x20/0x20 [spl]
May  3 18:27:39 starlight kernel: [4828316.190266]  thread_generic_wrapper+0x6f/0x80 [spl]
May  3 18:27:39 starlight kernel: [4828316.190669]  kthread+0x112/0x130
May  3 18:27:39 starlight kernel: [4828316.191061]  ? kthread_bind+0x30/0x30
May  3 18:27:39 starlight kernel: [4828316.191453]  ret_from_fork+0x35/0x40
May  3 18:27:39 starlight kernel: [4828316.191847] INFO: task z_wr_int:3886 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.192250]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.192662] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.193084] z_wr_int        D    0  3886      2 0x80000000
May  3 18:27:39 starlight kernel: [4828316.193508] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.193927]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.194383]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.194802]  schedule_preempt_disabled+0xa/0x10
May  3 18:27:39 starlight kernel: [4828316.195224]  __mutex_lock.isra.8+0x2b5/0x4a0
May  3 18:27:39 starlight kernel: [4828316.195681]  ? zio_taskq_member.isra.8.constprop.13+0x70/0x70 [zfs]
May  3 18:27:39 starlight kernel: [4828316.196132]  buf_hash_insert+0x53/0x150 [zfs]
May  3 18:27:39 starlight kernel: [4828316.196583]  arc_write_done+0x12a/0x410 [zfs]
May  3 18:27:39 starlight kernel: [4828316.197045]  zio_done+0x43e/0x1030 [zfs]
May  3 18:27:39 starlight kernel: [4828316.197508]  zio_execute+0x90/0xf0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.197931]  taskq_thread+0x2df/0x520 [spl]
May  3 18:27:39 starlight kernel: [4828316.198352]  ? wake_up_q+0x70/0x70
May  3 18:27:39 starlight kernel: [4828316.198792]  ? zio_taskq_member.isra.8.constprop.13+0x70/0x70 [zfs]
May  3 18:27:39 starlight kernel: [4828316.199201]  ? taskq_thread_spawn+0x50/0x50 [spl]
May  3 18:27:39 starlight kernel: [4828316.199607]  kthread+0x112/0x130
May  3 18:27:39 starlight kernel: [4828316.200012]  ? kthread_bind+0x30/0x30
May  3 18:27:39 starlight kernel: [4828316.200419]  ret_from_fork+0x35/0x40
May  3 18:27:39 starlight kernel: [4828316.200830] INFO: task txg_sync:4042 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.201247]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.201671] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.202139] txg_sync        D    0  4042      2 0x80000000
May  3 18:27:39 starlight kernel: [4828316.202574] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.203001]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.203461]  ? spa_taskq_dispatch_ent+0x66/0xd0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.203893]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.204324]  schedule_timeout+0x16b/0x390
May  3 18:27:39 starlight kernel: [4828316.204752]  ? __next_timer_interrupt+0xc0/0xc0
May  3 18:27:39 starlight kernel: [4828316.205174]  io_schedule_timeout+0x19/0x40
May  3 18:27:39 starlight kernel: [4828316.205589]  __cv_timedwait_common+0x125/0x160 [spl]
May  3 18:27:39 starlight kernel: [4828316.205998]  ? finish_wait+0x80/0x80
May  3 18:27:39 starlight kernel: [4828316.206445]  zio_wait+0x13a/0x280 [zfs]
May  3 18:27:39 starlight kernel: [4828316.206885]  dsl_pool_sync+0x106/0x510 [zfs]
May  3 18:27:39 starlight kernel: [4828316.207330]  spa_sync+0x5af/0xfb0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.207774]  ? spa_txg_history_init_io+0x106/0x110 [zfs]
May  3 18:27:39 starlight kernel: [4828316.208222]  txg_sync_thread+0x294/0x460 [zfs]
May  3 18:27:39 starlight kernel: [4828316.208637]  ? __switch_to_asm+0x41/0x70
May  3 18:27:39 starlight kernel: [4828316.209084]  ? txg_thread_exit.isra.9+0x60/0x60 [zfs]
May  3 18:27:39 starlight kernel: [4828316.209504]  ? __thread_exit+0x20/0x20 [spl]
May  3 18:27:39 starlight kernel: [4828316.209922]  thread_generic_wrapper+0x6f/0x80 [spl]
May  3 18:27:39 starlight kernel: [4828316.210377]  kthread+0x112/0x130
May  3 18:27:39 starlight kernel: [4828316.210792]  ? kthread_bind+0x30/0x30
May  3 18:27:39 starlight kernel: [4828316.211204]  ret_from_fork+0x35/0x40
May  3 18:27:39 starlight kernel: [4828316.211629] INFO: task worker:28937 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.212053]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.212479] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.212907] worker          D    0 28937      1 0x00000320
May  3 18:27:39 starlight kernel: [4828316.213330] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.213742]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.214159]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.214573]  cv_wait_common+0xfb/0x130 [spl]
May  3 18:27:39 starlight kernel: [4828316.214989]  ? finish_wait+0x80/0x80
May  3 18:27:39 starlight kernel: [4828316.215435]  spa_config_enter+0xed/0x100 [zfs]
May  3 18:27:39 starlight kernel: [4828316.215882]  metaslab_alloc+0x3c/0x240 [zfs]
May  3 18:27:39 starlight kernel: [4828316.216295]  ? apic_timer_interrupt+0xa/0x20
May  3 18:27:39 starlight kernel: [4828316.216735]  zio_alloc_zil+0xfd/0x3a0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.217147]  ? _cond_resched+0x15/0x30
May  3 18:27:39 starlight kernel: [4828316.217553]  ? mutex_lock+0xe/0x30
May  3 18:27:39 starlight kernel: [4828316.217994]  ? txg_list_add+0x72/0x90 [zfs]
May  3 18:27:39 starlight kernel: [4828316.218480]  zil_lwb_write_issue+0x1eb/0x3f0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.218927]  zil_commit_impl+0x8f9/0xe10 [zfs]
May  3 18:27:39 starlight kernel: [4828316.219370]  zvol_request+0x224/0x3b0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.219776]  generic_make_request+0x1a4/0x400
May  3 18:27:39 starlight kernel: [4828316.220179]  submit_bio+0x45/0x130
May  3 18:27:39 starlight kernel: [4828316.220582]  ? bio_alloc_bioset+0xdc/0x220
May  3 18:27:39 starlight kernel: [4828316.220987]  submit_bio_wait+0x53/0x80
May  3 18:27:39 starlight kernel: [4828316.221387]  blkdev_issue_flush+0x7c/0xb0
May  3 18:27:39 starlight kernel: [4828316.221783]  blkdev_fsync+0x2f/0x40
May  3 18:27:39 starlight kernel: [4828316.222173]  do_fsync+0x38/0x70
May  3 18:27:39 starlight kernel: [4828316.222547]  __x64_sys_fdatasync+0x13/0x20
May  3 18:27:39 starlight kernel: [4828316.222923]  do_syscall_64+0x53/0x110
May  3 18:27:39 starlight kernel: [4828316.223296]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
May  3 18:27:39 starlight kernel: [4828316.223672] RIP: 0033:0x7f9d884c62e7
May  3 18:27:39 starlight kernel: [4828316.224046] Code: Bad RIP value.
May  3 18:27:39 starlight kernel: [4828316.224418] RSP: 002b:00007f9d773fe560 EFLAGS: 00000293 ORIG_RAX: 000000000000004b
May  3 18:27:39 starlight kernel: [4828316.224810] RAX: ffffffffffffffda RBX: 0000000000000014 RCX: 00007f9d884c62e7
May  3 18:27:39 starlight kernel: [4828316.225205] RDX: 0000000000000000 RSI: 0000000000000008 RDI: 0000000000000014
May  3 18:27:39 starlight kernel: [4828316.225600] RBP: 0000560d0c806500 R08: 0000000000000000 R09: 00000000ffffffff
May  3 18:27:39 starlight kernel: [4828316.225993] R10: 00007f9d773fe660 R11: 0000000000000293 R12: 0000560d0bb29100
May  3 18:27:39 starlight kernel: [4828316.226419] R13: 0000560d0c7e25e8 R14: 0000560d0dac1b10 R15: 0000560d0d9c9b60
May  3 18:27:39 starlight kernel: [4828316.226818] INFO: task worker:31513 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.227219]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.227625] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.228038] worker          D    0 31513      1 0x00000320
May  3 18:27:39 starlight kernel: [4828316.228454] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.228863]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.229271]  ? __switch_to_asm+0x35/0x70
May  3 18:27:39 starlight kernel: [4828316.229678]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.230089]  cv_wait_common+0xfb/0x130 [spl]
May  3 18:27:39 starlight kernel: [4828316.230497]  ? finish_wait+0x80/0x80
May  3 18:27:39 starlight kernel: [4828316.230937]  spa_config_enter+0xed/0x100 [zfs]
May  3 18:27:39 starlight kernel: [4828316.231373]  metaslab_alloc+0x3c/0x240 [zfs]
May  3 18:27:39 starlight kernel: [4828316.231805]  zio_alloc_zil+0xfd/0x3a0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.232195]  ? _cond_resched+0x15/0x30
May  3 18:27:39 starlight kernel: [4828316.232577]  ? mutex_lock+0xe/0x30
May  3 18:27:39 starlight kernel: [4828316.232987]  ? txg_list_add+0x72/0x90 [zfs]
May  3 18:27:39 starlight kernel: [4828316.233401]  zil_lwb_write_issue+0x1eb/0x3f0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.233787]  ? cv_timedwait_hires+0x35/0x90 [spl]
May  3 18:27:39 starlight kernel: [4828316.234247]  zil_commit_impl+0x3c4/0xe10 [zfs]
May  3 18:27:39 starlight kernel: [4828316.234668]  zvol_request+0x224/0x3b0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.235053]  generic_make_request+0x1a4/0x400
May  3 18:27:39 starlight kernel: [4828316.235437]  submit_bio+0x45/0x130
May  3 18:27:39 starlight kernel: [4828316.235819]  ? bio_alloc_bioset+0xdc/0x220
May  3 18:27:39 starlight kernel: [4828316.236202]  submit_bio_wait+0x53/0x80
May  3 18:27:39 starlight kernel: [4828316.236585]  blkdev_issue_flush+0x7c/0xb0
May  3 18:27:39 starlight kernel: [4828316.236968]  blkdev_fsync+0x2f/0x40
May  3 18:27:39 starlight kernel: [4828316.237350]  do_fsync+0x38/0x70
May  3 18:27:39 starlight kernel: [4828316.237728]  __x64_sys_fdatasync+0x13/0x20
May  3 18:27:39 starlight kernel: [4828316.238114]  do_syscall_64+0x53/0x110
May  3 18:27:39 starlight kernel: [4828316.238493]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
May  3 18:27:39 starlight kernel: [4828316.238875] RIP: 0033:0x7f9d884c62e7
May  3 18:27:39 starlight kernel: [4828316.239255] Code: Bad RIP value.
May  3 18:27:39 starlight kernel: [4828316.239633] RSP: 002b:00007f995a0e3560 EFLAGS: 00000293 ORIG_RAX: 000000000000004b
May  3 18:27:39 starlight kernel: [4828316.240030] RAX: ffffffffffffffda RBX: 0000000000000011 RCX: 00007f9d884c62e7
May  3 18:27:39 starlight kernel: [4828316.240432] RDX: 0000000000000000 RSI: 0000000000000008 RDI: 0000000000000011
May  3 18:27:39 starlight kernel: [4828316.240837] RBP: 0000560d0c7e8470 R08: 0000000000000000 R09: 00000000ffffffff
May  3 18:27:39 starlight kernel: [4828316.241244] R10: 00007f995a0e3660 R11: 0000000000000293 R12: 0000560d0bb29100
May  3 18:27:39 starlight kernel: [4828316.241652] R13: 0000560d0c7e25e8 R14: 0000560d0cc32b90 R15: 0000560d0bb25688
May  3 18:27:39 starlight kernel: [4828316.242109] INFO: task zpool:31949 blocked for more than 120 seconds.
May  3 18:27:39 starlight kernel: [4828316.242522]       Tainted: P          IOE     4.19.0-8-amd64 #1 Debian 4.19.98-1
May  3 18:27:39 starlight kernel: [4828316.242939] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
May  3 18:27:39 starlight kernel: [4828316.243367] zpool           D    0 31949   2446 0x00000000
May  3 18:27:39 starlight kernel: [4828316.243791] Call Trace:
May  3 18:27:39 starlight kernel: [4828316.244204]  ? __schedule+0x2a2/0x870
May  3 18:27:39 starlight kernel: [4828316.244617]  schedule+0x28/0x80
May  3 18:27:39 starlight kernel: [4828316.245027]  schedule_preempt_disabled+0xa/0x10
May  3 18:27:39 starlight kernel: [4828316.245438]  __mutex_lock.isra.8+0x2b5/0x4a0
May  3 18:27:39 starlight kernel: [4828316.245872]  l2arc_evict+0x273/0x2a0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.246305]  l2arc_remove_vdev+0x12c/0x1d0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.246736]  spa_load_l2cache+0x3a5/0x4c0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.247162]  spa_vdev_remove+0x5cf/0x800 [zfs]
May  3 18:27:39 starlight kernel: [4828316.247578]  ? spa_open_common+0x295/0x4c0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.247964]  ? apparmor_capable+0x6b/0xc0
May  3 18:27:39 starlight kernel: [4828316.248380]  zfs_ioc_vdev_remove+0x4f/0x90 [zfs]
May  3 18:27:39 starlight kernel: [4828316.248801]  zfsdev_ioctl+0x6cf/0x8c0 [zfs]
May  3 18:27:39 starlight kernel: [4828316.249193]  do_vfs_ioctl+0xa4/0x630
May  3 18:27:39 starlight kernel: [4828316.249578]  ? do_munmap+0x33c/0x430
May  3 18:27:39 starlight kernel: [4828316.249961]  ksys_ioctl+0x60/0x90
May  3 18:27:39 starlight kernel: [4828316.250376]  __x64_sys_ioctl+0x16/0x20
May  3 18:27:39 starlight kernel: [4828316.250755]  do_syscall_64+0x53/0x110
May  3 18:27:39 starlight kernel: [4828316.251132]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
May  3 18:27:39 starlight kernel: [4828316.251514] RIP: 0033:0x7f4816c40427
May  3 18:27:39 starlight kernel: [4828316.251896] Code: Bad RIP value.
May  3 18:27:39 starlight kernel: [4828316.252277] RSP: 002b:00007ffe2f6c0418 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
May  3 18:27:39 starlight kernel: [4828316.252674] RAX: ffffffffffffffda RBX: 0000556fe6cd03d0 RCX: 00007f4816c40427
May  3 18:27:39 starlight kernel: [4828316.253076] RDX: 00007ffe2f6c0430 RSI: 0000000000005a0c RDI: 0000000000000003
May  3 18:27:39 starlight kernel: [4828316.253481] RBP: 00007ffe2f6c3e20 R08: 0000000000000100 R09: 0000000000000000
May  3 18:27:39 starlight kernel: [4828316.253882] R10: 0000000000000001 R11: 0000000000000246 R12: 00007ffe2f6c0430
May  3 18:27:39 starlight kernel: [4828316.254291] R13: 0000556fe6cce430 R14: 00007ffe2f6c39e0 R15: 0000556fe6d04f20
```

### PR DESCRIPTION
**Pull request by gamanakis**
### Motivation and Context

Closes  #10286, #11880, #11782, #11635 

### Description

In case we have I/O and try to remove an L2ARC device a deadlock might
occur. arc_read()->zio_read()->zfs_blkptr_verify() waits for SCL_VDEV
to be dropped while holding the hash_lock. However, spa_l2cache_load()
holds SCL_ALL and waits for the hash_lock in l2arc_evict().

Fix this by moving zfs_blkptr_verify() to the top top arc_read() before
the hash_lock is taken. Verify the block pointer and return a checksum
error if damaged rather than halting the system, by using
BLK_VERIFY_LOG instead of BLK_VERIFY_HALT.

### How Has This Been Tested?

Manually by generating high IO and repeatedly adding/removing a cache device.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by gamanakis** [comment]
e0c1ca1: Updated comments.

File: module/zfs/arc.c [hunk 1]
```diff
@@ -9645,6 +9645,16 @@ l2arc_remove_vdev(vdev_t *vd)
 	atomic_dec_64(&l2arc_ndev);
 	mutex_exit(&l2arc_dev_mtx);
 
+	/*
+	 * Since we removed the L2ARC device from the global list
+	 * the SCL_ALL lock is not required anymore. Drop it to prevent
+	 * l2arc_evict() from deadlocking with arc_read().
+	 * arc_read() waits for SCL_ALL to be dropped in zio_read() while
```
[the remark this answers is not in the document]
Comment (gamanakis) [reply module/zfs/arc.c]: Great suggestion, thank you!

File: module/zfs/arc.c [hunk 2]
```diff
@@ -6431,6 +6428,17 @@ arc_read(zio_t *pio, spa_t *spa, const blkptr_t *bp,
...
+		/*
+		 * Gracefully handle a damaged logical block size as a
+		 * checksum error.
+		 */
+		if (lsize > spa_maxblocksize(spa)) {
+			rc = SET_ERROR(ECKSUM);
+			if (hash_lock != NULL)
+				mutex_exit(hash_lock);
+			goto out;
+		}
```
Comment (behlendorf) [inline module/zfs/arc.c:6440]: We should be able to drop this hunk entirely since it'll be handled by the `zfs_blkptr_verify()` check in `arc_read()`.  We also want to remove this same check from `zio_read()` to resolve the deadlock.

File: module/zfs/arc.c [hunk 3]
```diff
@@ -5948,6 +5949,13 @@ arc_read(zio_t *pio, spa_t *spa, const blkptr_t *bp,
 		 * Embedded BP's have no DVA and require no I/O to "read".
 		 * Create an anonymous arc buf to back it.
 		 */
+		blkptr_valid = zfs_blkptr_verify(spa, bp, zio_flags &
```
Comment (behlendorf) [inline module/zfs/arc.c:5952]: Since `blkptr_valid` isn't used elsewhere we could just do the check in the conditional.

**Review by behlendorf — APPROVED** [review]
Perfect, thanks for revising this.

File: module/zfs/zio.c [hunk 4]
```diff
@@ -1107,9 +1107,6 @@ zio_read(zio_t *pio, spa_t *spa, const blkptr_t *bp,
 {
 	zio_t *zio;
 
-	(void) zfs_blkptr_verify(spa, bp, flags & ZIO_FLAG_CONFIG_WRITER,
-	    BLK_VERIFY_HALT);
-
```
Comment (mmaybee) [inline module/zfs/zio.c:1112]: The arc is not the only caller of zio_read(). Is it appropriate for all other callers that we no longer verify the blkptr?

Related: the existing semantics (calling zfs_panic_recover on error) seem a bit over-the-top. Although I suppose that the logic here is that a blkptr in this context should be coming from a checksum-verified block, so we should never really encounter an invalid blkptr...

Comment (behlendorf) [reply module/zfs/zio.c:1112]: I think it's actually preferable that we move this.  As you pointed out in `zio_read()` it's really a requirement that the block pointer be valid (there's nothing to do but panic if it isn't!), so this is really just an additional correctness check.  Moving it up in to `arc_read()` at least gives us the option to handle it as an error for this call path.  I wouldn't be against doing this same check for the other `zio_read()` callers, but it seems a little out of scope for this particular deadlock fix to me.

**Comment by mmatuska** [comment]
@behlendorf @gamanakis I have hit into this and would be very grateful if it could make it into 2.1.0-release
