### PR TITLE
Fix zfs_get_data access to files with wrong generation

### LINKED ISSUE #10593: Consistent General Protection Fault; zfs_rangelock_enter() -> avl_nearest() -> avl_walk()
### System information
Type | Version/Name
 --- | ---
Distribution Name	| Proxmox
Distribution Version	|  Proxmox 6.2 (Debian Buster)
Linux Kernel	| 5.4.44-2-pve
Architecture	| x86_64
ZFS Version	| 0.8.4-pve1
SPL Version	| 0.8.4-pve1

### Describe the problem you're observing
I'm experiencing a consistent general protection fault after upgrade from 0.7.x (Proxmox 5.4.x) to 0.8.4 (Proxmox 6.2). This fault looks similar to issue #7873, but not exactly the same. The result of this fault is a complete hang of most processes running within the Linux Container that uses the associated ZFS volume, along with various other unresponsive host processes. I cannot regain use of the container until the entire Proxmox host is (hard) rebooted. The normal reboot process fails to proceed due to the hung LXC.

### Describe how to reproduce the problem
ZFS is my root (rpool), two JBOD drives mirrored, with several Linux Containers using their own ZFS volumes. 

Bug can be encountered by using the system normally; I can make it maybe two days before the issue forces me to reboot the machine.

I believe Proxmox has a scheduled scrub that - while running - increases the chance of occurrence. However, daily use also seems to cause the same issue. This has been consistently triggered by the `Plex Media Server` process for me; I have not seen any other processes noted in the errors, but I do not see how this can be a Plex issue (all fingers point to a ZFS issue).

I use ECC memory and have run memtest86+ recently to verify that memory is good.
Drives are healthy, pool is as well.

### Include any warning/errors/backtraces from the system logs
```log
[136422.505658] general protection fault: 0000 [#1] SMP PTI
[136422.505866] CPU: 15 PID: 25510 Comm: Plex Media Serv Tainted: P          IO      5.4.44-2-pve #1
[136422.506115] Hardware name: HP ProLiant ML350 G6, BIOS D22 05/05/2011
[136422.506303] RIP: 0010:avl_walk+0x33/0x70 [zavl]
[136422.506437] Code: 10 b9 01 00 00 00 29 d1 4c 01 c6 48 89 e5 48 85 f6 74 48 48 63 d2 48 89 f7 48 8b 04 d6 48 85 c0 74 20 48 63 c9 eb 03 48 89 d0 <48> 8b 14 c8 48 85 d2 75 f4 48 89 c2 48 89 d0 5d 4c 29 c0 c3 39 f1
[136422.507020] RSP: 0018:ffffacf29a163c80 EFLAGS: 00010282
[136422.507171] RAX: e089443875c085d0 RBX: ffffa0aac4d9c150 RCX: 0000000000000000
[136422.507375] RDX: 0000000000000001 RSI: ffffffffc01c1478 RDI: ffffffffc01c1478
[136422.507579] RBP: ffffacf29a163c80 R08: 0000000000000008 R09: ffffa0a8c3406f40
[136422.507784] R10: ffffa0ab33be8000 R11: 0000008000000000 R12: ffffa0ab33be8000
[136422.508031] R13: ffffa0aac4d9c178 R14: 0000000000000000 R15: 0000000000000000
[136422.508236] FS:  00007f6f78ff9700(0000) GS:ffffa0adc39c0000(0000) knlGS:0000000000000000
[136422.508465] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[136422.508630] CR2: 00007f6fbc294278 CR3: 0000000469bfc000 CR4: 00000000000006e0
[136422.508834] Call Trace:
[136422.508910]  avl_nearest+0x2a/0x30 [zavl]
[136422.509140]  zfs_rangelock_enter+0x405/0x580 [zfs]
[136422.509286]  ? spl_kmem_zalloc+0xe9/0x140 [spl]
[136422.509419]  ? spl_kmem_zalloc+0xe9/0x140 [spl]
[136422.509587]  zfs_get_data+0x157/0x340 [zfs]
[136422.509746]  zil_commit_impl+0x9ad/0xd90 [zfs]
[136422.509913]  zil_commit+0x3d/0x60 [zfs]
[136422.510062]  zfs_fsync+0x77/0xe0 [zfs]
[136422.510252]  zpl_fsync+0x68/0xa0 [zfs]
[136422.510364]  vfs_fsync_range+0x48/0x80
[136422.510474]  ? __fget_light+0x59/0x70
[136422.510582]  do_fsync+0x3d/0x70
[136422.510674]  __x64_sys_fsync+0x14/0x20
[136422.510786]  do_syscall_64+0x57/0x190
[136422.510895]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[136422.511041] RIP: 0033:0x7f6fffef4b17
[136422.511146] Code: 00 00 0f 05 48 3d 00 f0 ff ff 77 3f f3 c3 0f 1f 44 00 00 53 89 fb 48 83 ec 10 e8 04 f5 ff ff 89 df 89 c2 b8 4a 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 2b 89 d7 89 44 24 0c e8 46 f5 ff ff 8b 44 24
[136422.511700] RSP: 002b:00007f6f78ff79c0 EFLAGS: 00000293 ORIG_RAX: 000000000000004a
[136422.511916] RAX: ffffffffffffffda RBX: 000000000000000c RCX: 00007f6fffef4b17
[136422.512121] RDX: 0000000000000000 RSI: 0000000000000002 RDI: 000000000000000c
[136422.512373] RBP: 00000000038164b8 R08: 0000000000000000 R09: 00007f6fbc447770
[136422.512583] R10: 00007f6fbc0c4460 R11: 0000000000000293 R12: 0000000000000000
[136422.512792] R13: 0000000003825eb8 R14: 0000000000000002 R15: 0000000000000000
[136422.512999] Modules linked in: veth ebtable_filter ebtables ip_set ip6table_raw iptable_raw ip6table_filter ip6_tables mptctl mptbase binfmt_misc iptable_filter bpfilter softdog cpuid nfnetlink_log nfnetlink radeon ttm drm_kms_helper drm i2c_algo_bit fb_sys_fops syscopyarea sysfillrect sysimgblt intel_powerclamp usblp kvm_intel ipmi_ssif input_leds kvm hpilo i7core_edac pcspkr irqbypass serio_raw ipmi_si intel_cstate ipmi_devintf ipmi_msghandler mac_hid vhost_net vhost tap ib_iser rdma_cm iw_cm ib_cm ib_core iscsi_tcp libiscsi_tcp libiscsi scsi_transport_iscsi coretemp parport_pc ppdev lp parport sunrpc ip_tables x_tables autofs4 zfs(PO) zunicode(PO) zlua(PO) zavl(PO) icp(PO) zcommon(PO) znvpair(PO) spl(O) btrfs xor zstd_compress raid6_pq libcrc32c hid_generic usbkbd usbmouse usbhid hid gpio_ich psmouse pata_acpi uhci_hcd ehci_pci lpc_ich tg3 ehci_hcd hpsa scsi_transport_sas
[136422.515330] ---[ end trace b7f8cd7b0f091d95 ]---
[136422.515472] RIP: 0010:avl_walk+0x33/0x70 [zavl]
[136422.515649] Code: 10 b9 01 00 00 00 29 d1 4c 01 c6 48 89 e5 48 85 f6 74 48 48 63 d2 48 89 f7 48 8b 04 d6 48 85 c0 74 20 48 63 c9 eb 03 48 89 d0 <48> 8b 14 c8 48 85 d2 75 f4 48 89 c2 48 89 d0 5d 4c 29 c0 c3 39 f1
[136422.516197] RSP: 0018:ffffacf29a163c80 EFLAGS: 00010282
[136422.516352] RAX: e089443875c085d0 RBX: ffffa0aac4d9c150 RCX: 0000000000000000
[136422.516577] RDX: 0000000000000001 RSI: ffffffffc01c1478 RDI: ffffffffc01c1478
[136422.516826] RBP: ffffacf29a163c80 R08: 0000000000000008 R09: ffffa0a8c3406f40
[136422.517030] R10: ffffa0ab33be8000 R11: 0000008000000000 R12: ffffa0ab33be8000
[136422.517235] R13: ffffa0aac4d9c178 R14: 0000000000000000 R15: 0000000000000000
[136422.517439] FS:  00007f6f78ff9700(0000) GS:ffffa0adc39c0000(0000) knlGS:0000000000000000
[136422.517669] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[136422.517875] CR2: 00007f6fbc294278 CR3: 0000000469bfc000 CR4: 00000000000006e0
```

### PR DESCRIPTION
**Pull request by tuxoko**
### Description

If TX_WRITE is create on a file, and the file is later deleted and a new
directory is created on the same object id, it is possible that when
zil_commit happens, zfs_get_data will be called on the new directory.
This may result in panic as it tries to do range lock.

This patch fixes this issue by record the generation number during
zfs_log_write, so zfs_get_data can check if the object is valid.

Signed-off-by: Chunwei Chen <david.chen@nutanix.com>
Closes #10593

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by problame** [comment]
Maybe a newb question because I am not familiar with the concept of ZPL generations but: What if the destroy + mkdir happens in the same txg? Wouldn't the generation number be the same?

**Comment by tuxoko** [comment]
@problame 
generation number is assigned at file creation.
In order to have 2 files on the same inode having the same gen number, you need create, remove and create happen on the same txg.
But regardless, remove and subsequent create can't happen on the same txg, because you can't create before remove is finished in the syncing context.

**Comment by adamdmoss** [comment]
While I can't vouch for its correctness, I've been running with this PR for a week or two now with no apparent ill effects.

File: include/sys/zil.h [hunk 1]
```diff
@@ -393,6 +393,7 @@ typedef void (*zil_callback_t)(void *data);
 typedef struct itx {
 	list_node_t	itx_node;	/* linkage on zl_itx_list */
 	void		*itx_private;	/* type-specific opaque data */
+	uint64_t	itx_private2;
```
Comment (behlendorf) [inline include/sys/zil.h:396]:
```suggestion
	uint64_t	itx_gen;
```

Perhaps it would make more sense to add this a common member and rename it `itx_gen`?  We already do something similar in `zfs_log_rename` and `zfs_log_remove` where we set an `itx->itx_oid`.  Then move it down after `itx_oid`.

**Review by behlendorf — COMMENTED** [review]
Nice job running this down.  The fix itself makes good sense to me, I just wonder if we want to give it a more clear name since private2 is only ever used as a generation number.

File: include/sys/zil.h (hunk 1 above)
Comment (tuxoko) [reply include/sys/zil.h:396]: Right, I use private2 because it's used for callback argument just like private.
But I guess itx_gen makes more sense. I'll change that.

**Comment by scineram** [comment]
I can't find this in 2.0.5-staging. @tonyhutter

**Comment by tonyhutter** [comment]
@scineram thanks, I just pushed it into my zfs-2.0.5 patchset (https://github.com/openzfs/zfs/pull/12182)
