### PR TITLE
Fix available space accounting for special/dedup

### LINKED ISSUE #18190: ZFS 2.4.0 Special Device + Data VDEV Report Very Wrong Remaining Space
Distribution Name	|  Proxmox 9.1.5 Debian Trixie 13
Distribution Version	|  Proxmox 9.1.5 Debian Trixie 13
Kernel Version	| Linux 6.17.9-1-pve
Architecture	| x86_64
OpenZFS Version	| zfs-2.4.0-pve1 - zfs-kmod-2.4.0-pve1

My zpool has 2 device: sdb (HDD) and sda (nvme)

The issue is all dataset report the remaining free space by using the “HDD (data) size - (HDD + NVME usage) = 448GB” while hardware wise the HDD has 1.6T and the NVME has 800G left.

My expectation would be for it to consider the HDD remaining (1.6T) as actual free space. As in report the free space by what’s available left to write to, not what using the substraction since that gives the wrong info to other programs.

Is this a bug?

Image

Image

Image

Image

### PR DESCRIPTION
**Pull request by amotin**
Currently, `spa_dspace` (base to calculate dataset `AVAIL`) only includes the normal allocation class capacity, but `dd_used_bytes` tracks space allocated across all classes.  Since we don't want to report free space of other classes as available (we can't promise new allocations will be able to use it), report only allocated space, similar to how we report space saved by dedup and block cloning.

Since we need deflated space here, make allocation classes track deflated allocated space also.  While here, make `mc_deferred` also deflated, matching its use contexts.  Also while there, use `atomic_load()` to read the allocation class stats.  Also while there, moved `spa_deflate` setting earlier during pool creation, since it should not change when we are already writing something.

Closes #18190

### How Has This Been Tested?
Create a pool with normal and special vdevs.  Observe capacity of normal vdev reported as available.  Use big chunk of special vdev capacity without using any normal vdev.  Observe reported available space reduced, while it should not.  Reboot with the patch applied, and observe all normal vdev capacity is available.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Quality assurance (non-breaking change which makes the code more robust against bugs)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/metaslab.c [hunk 1]
```diff
@@ -713,6 +716,12 @@ metaslab_class_get_alloc(metaslab_class_t *mc)
 	return (mc->mc_alloc);
 }
 
+uint64_t
+metaslab_class_get_dalloc(metaslab_class_t *mc)
+{
+	return (mc->mc_dalloc);
```
Comment (robn) [inline module/zfs/metaslab.c]: I know you're just following the surrounding style, but should this (and the others?) be `atomic_load_64()`?

Comment (amotin) [reply module/zfs/metaslab.c]: I'll take a look on it tomorrow, but I am not sure there is really a concurrency here.

Comment (amotin) [reply module/zfs/metaslab.c]: ZFS didn't have a concept of `atomic_load()` till 4 years ago.  But formally you are right.  Added.

File: module/zfs/metaslab.c [hunk 2]
```diff
@@ -573,8 +575,10 @@ metaslab_class_balance(metaslab_class_t *mc, boolean_t onsync)
 		 * relative to average.  Bigger vdevs should get more to
 		 * fill up at the same time as smaller ones.
 		 */
-		if (mc->mc_space > 0 && vs->vs_space > 0) {
-			ratio = vs->vs_space / (mc->mc_space / (mc->mc_groups *
+		uint64_t mc_space = atomic_load_64(&mc->mc_space);
```
Comment (ryan-moeller) [inline module/zfs/metaslab.c:578]: Up to your preference, this could be `metaslab_class_get_space(mc)`, and same below for `metaslab_class_get_alloc(mc)`.

File: module/zfs/metaslab.c [hunk 3]
```diff
@@ -710,25 +719,34 @@ metaslab_class_get_name(metaslab_class_t *mc)
...
 {
-	return (mc->mc_alloc);
+	return (atomic_load_64(&mc->mc_alloc));
+}
+
+uint64_t
+metaslab_class_get_dalloc(metaslab_class_t *mc)
+{
+	return (spa_deflate(mc->mc_spa) ? atomic_load_64(&mc->mc_dalloc) :
+	    atomic_load_64(&mc->mc_alloc));
```
Comment (ryan-moeller) [inline module/zfs/metaslab.c:729]: Likewise, this could be `metaslab_class_get_alloc(mc)` if you don't prefer the explicit atomic load, and again below for `metaslab_class_get_space(mc)` in `metaslab_class_get_dspace`.

File: module/zfs/metaslab.c [hunk 4]
```diff
@@ -573,8 +575,10 @@ metaslab_class_balance(metaslab_class_t *mc, boolean_t onsync)
 		 * relative to average.  Bigger vdevs should get more to
 		 * fill up at the same time as smaller ones.
 		 */
-		if (mc->mc_space > 0 && vs->vs_space > 0) {
-			ratio = vs->vs_space / (mc->mc_space / (mc->mc_groups *
+		uint64_t mc_space = atomic_load_64(&mc->mc_space);
+		uint64_t vs_space = atomic_load_64(&vs->vs_space);
```
Comment (ryan-moeller) [inline module/zfs/metaslab.c:579]: Some observations stemming from this, though maybe these do not apply in practice:

There are no corresponding atomic stores for `vs_space`, nor is it loaded atomically elsewhere. Same for `vs_alloc` below. Instead, they are manipulated under `vd->vdev_stat_lock`.

This also appears in `metaslab_group_alloc_update`.

The same type of race appears in the use of metaslab class stats (typically to calculate free space). While atomic operations ensure the individual stats are not corrupted, it seems nothing ensures these values are consistent in aggregate. The atomic operations have relaxed ordering, and no locking is apparent.

Of course, we would rather avoid using a lock for aggregate access to these stats. Is there is some rationale for why these races are safe?

**Comment by ryan-moeller** [comment]
Hi Mav, I am working in this same area and have a few thoughts to share. I'll also be opening a draft PR for exposing metaslab class allocator stats as zpool properties shortly, which I'm told you may have some interest in as well.

File: module/zfs/metaslab.c (hunk 2 above)
Comment (amotin) [reply module/zfs/metaslab.c:578]: It could.  But we don't have similar helpers for vdevs, plus it would be a function call, since the function is external, so left it like this for now.  The `atomic_load()` on most architectures will be just a memory read.

File: module/zfs/metaslab.c (hunk 3 above)
Comment (amotin) [reply module/zfs/metaslab.c:729]: The code is obviously aware of what it does. I don't see a point to use wrappers made for external callers.

File: module/zfs/metaslab.c (hunk 4 above)
Comment (amotin) [reply module/zfs/metaslab.c:579]: You are right that it is a bit racy.  But values there change quite rarely, once per TXG as part of metaslabs sync, and we don't really care whether we get a stale one from old TXG or a new one here.  And most writes are also done by sync context, so they won't even hit this race.  I primarily added the atomic_load's for helper functions, since those can be used asynchronously as part of random IOCTL's, and we definitely don't want some torn reads there, while stale values are acceptable in a lack of some wider locking.

**Comment by amotin** [comment]
> I'll also be opening a draft PR for exposing metaslab class allocator stats as zpool properties shortly, which I'm told you may have some interest in as well.

@ryan-moeller I am happy to see you back, and I am indeed looking forward to see that PR.

File: module/zfs/metaslab.c (hunk 4 above)
Comment (amotin) [reply module/zfs/metaslab.c:579]: Just for a note, I hate using vdev stats here, since it may include several allocation classes since introduction of embedded logs.  I'd prefer we have the same stats in metaslab groups, but that is a topic for another day.
