### PR TITLE
assertion failed in arc_wait_for_eviction()

### LINKED ISSUE #11285: Memory pressure may result in violated assertion in arc_wait_for_eviction()
### System information

Type | Version/Name
 --- | ---
Distribution Name	| Archlinux
Distribution Version	| rolling
Linux Kernel	| 5.9.10
Architecture	| x64
ZFS Version	| 8f158ae
SPL Version	| 8f158ae

### Describe the problem you're observing
Memory stressing a system with mprime results in a  panic in `arc_wait_for_eviction()`.
### Describe how to reproduce the problem
In a system with 128GB memory, of which 40GB were consumed by ARC running mprime panicked in the assertion of `arc_wait_for_eviction()`. mprime was run in torture-test mode, type of test was "4. Blend (tests all of the above)" (ie both large and small fast Fourrier transforms). In this test mode mprime tries to consume all available memory.

I believe what happened is that the system was running low on memory so that the if clause at https://github.com/openzfs/zfs/blob/master/module/zfs/arc.c#L4166 was not true and arc_evict_waiters were not woken. However, arc_evict_count was still incremented at https://github.com/openzfs/zfs/blob/master/module/zfs/arc.c#L4164 which led to the panicked assertion in `arc_wait_for_eviction()`.

Just a thought though.

### Include any warning/errors/backtraces from the system logs
```
VERIFY3(last->aew_count > arc_evict_count) failed (850903552 > 868262400)
PANIC at arc.c:5255:arc_wait_for_eviction()
Showing stack for process 1429448
CPU: 4 PID: 1429448 Comm: mprime Tainted: P           OE     5.9.10-1-vfio #1
Call Trace:
 dump_stack+0x6b/0x83
 spl_panic+0xef/0x117 [spl]
 ? sysvec_call_function+0x36/0x80
 ? asm_sysvec_call_function+0x12/0x20
 arc_wait_for_eviction+0x1db/0x1f0 [zfs]
 arc_shrinker_scan+0x36/0xd0 [zfs]
 do_shrink_slab+0x146/0x290
 shrink_slab+0xd0/0x2f0
 shrink_node+0x2c0/0x6e0
 do_try_to_free_pages+0xda/0x4c0
 try_to_free_pages+0xef/0x1c0
 __alloc_pages_slowpath.constprop.0+0x384/0xce0
 ? tick_nohz_next_event+0x8f/0x180
 __alloc_pages_nodemask+0x2e6/0x310
 alloc_pages_vma+0x80/0x250
 handle_mm_fault+0xebd/0x1930
 do_user_addr_fault+0x1b8/0x3f0
 exc_page_fault+0x82/0x1a0
 ? asm_exc_page_fault+0x8/0x30
 asm_exc_page_fault+0x1e/0x30
```

### PR DESCRIPTION
**Pull request by ahrens**
### Motivation and Context

If the system is very low on memory (specifically,
`arc_free_memory() < arc_sys_free/2`, i.e. less than 1/16th of RAM
free), `arc_evict_state_impl()` will defer wakups.  In this case, the
arc_evict_waiter_t's remain on the list, even though `arc_evict_count`
has been incremented past their `aew_count`.

The problem is that `arc_wait_for_eviction()` assumes that if there are
waiters on the list, the count they are waiting for has not yet been
reached.  However, the deferred wakeups may violate this, causing
`ASSERT(last->aew_count > arc_evict_count)` to fail.

Closes #11285

### Description

This commit resolves the issue by having new waiters use the greater of
`arc_evict_count` and the last `aew_count`.

cc @gamanakis 

### How Has This Been Tested?

I was able to reproduce the issue reliably in conjunction with some other changes, while running the zfs test suite on a system with 7 GB RAM.  With the fix, the issue is not reproduced.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Review by behlendorf — APPROVED** [review]

**Comment by gamanakis** [comment]
Thank you for addressing this, it resolves the panic seen in #11285.

File: module/zfs/arc.c [hunk 1]
```diff
@@ -5242,14 +5242,20 @@ arc_wait_for_eviction(uint64_t amount)
...
+			if (!list_is_empty(&arc_evict_waiters)) {
+				arc_evict_waiter_t *last =
+				    list_tail(&arc_evict_waiters);
+				last_count = last->aew_count;
 			}
+			/*
+			 * Note, the last waiter's count may be less than
+			 * arc_evict_count if we are low on memory in which
+			 * case arc_evict_state_impl() may have deferred
+			 * wakeups (but still incremnted arc_evict_count).
```
Comment (gamanakis) [inline module/zfs/arc.c:5255]: nit: incremented

**Review by grwilson — APPROVED** [review]
