### PR TITLE
Limit dbuf cache sizes based only on ARC target size by default

### LINKED ISSUE #10563: dbuf cache size is 1/32nd what was intended
### System information

Type | Version/Name
 --- | ---
Distribution Name	|
Distribution Version	|
Linux Kernel	|
Architecture	|
ZFS Version	| 17ca30185af139588b9617ca0bdbf57027bd3303
SPL Version	|

### Describe the problem you're observing

The size of the dbuf cache is supposed to be ~1/32nd of memory (plus 1/64th of memory for MOS metadata).  However, it's actually 1/1024th of memory.

The problem is that 17ca30185af139588b9617ca0bdbf57027bd3303 changed the starting ARC size from arc_c_max to arc_c_min.  The dbuf cache size is based on `arc_target_bytes()`, which is based on the current ARC target size (arc_c).  See `dbuf_init()`.

One way to fix this would be to make dbuf cache size based on `arc_c_max`, instead of `arc_c`.  We would also need to change `dbuf_cache_target_bytes()`.

@amotin @behlendorf 

### Describe how to reproduce the problem
`grep target /proc/spl/kstat/zfs/dbufstats`

### PR DESCRIPTION
**Pull request by freqlabs**
### Motivation and Context

Fixes #10563

Dbuf caches are incorrectly limited to too small max size.

### Description

Set the initial max sizes to ULONG_MAX to allow the caches to grow
with the ARC.

Recalculate the metadata cache size on demand so it can adapt, too.

Update descriptions in zfs-module-parameters(5).

### How Has This Been Tested?

Built on FreeBSD, passes ZTS

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [x] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the ZFS on Linux [code style requirements](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [x] I have updated the documentation accordingly.
- [x] I have read the [**contributing** document](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/zfsonlinux/zfs/tree/master/tests) to cover my changes.
- [x] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/zfsonlinux/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

**Comment by freqlabs** [comment]
I think including arc_impl.h might be a sign I'm breaking some organizational boundary. Maybe a function should be added in arc.h to return arc_c_max, similar to arc_target_bytes().

File: module/zfs/dbuf.c [hunk 1]
```diff
@@ -613,8 +614,7 @@ dbuf_cache_multilist_index_func(multilist_t *ml, void *obj)
 static inline unsigned long
 dbuf_cache_target_bytes(void)
 {
-	return MIN(dbuf_cache_max_bytes,
-	    arc_target_bytes() >> dbuf_cache_shift);
+	return MIN(dbuf_cache_max_bytes, arc_c_max >> dbuf_cache_shift);
```
Comment (ahrens) [inline module/zfs/dbuf.c:617]: This seems like it would still defeat any manual increase to the `dbuf_cache_max_bytes` module parameter.  Is that the intention?  If so then it seems like we should initialize dbuf_cache_max_bytes to ULONG_MAX, and then we don't need to do anything with it in `dbuf_init()` (it can be tuned down from there and it will take effect here in dbuf_cache_target_bytes()).

Comment (amotin) [inline module/zfs/dbuf.c:617]: Why have you changed this? To me previous dbuf sizing based on ARC sizing looked reasonable.  With this you practically remove back-pressure on dbuf cache when OS asks for RAM back.

Comment (freqlabs) [reply module/zfs/dbuf.c:617]: How about `MIN(dbuf_cache_max_bytes, arc_c_max)`? I think the intent here is to allow this to be tunable, but not allow for an unreasonable value.

Comment (freqlabs) [reply module/zfs/dbuf.c:617]: But on the other hand, initializing `dbuf_cache_max_bytes` to ULONG_MAX makes the dbuf cache target follow changes to `arc_c_max` (via `zfs_arc_max`).

Comment (amotin) [reply module/zfs/dbuf.c:617]: There is not much difference between setting dbuf_cache_max_bytes to ULONG_MAX and the change below.  Setting it to ULONG_MAX just leaves the question about dbuf_metadata_cache_max_bytes. I remember some requests to remove the dbuf metadata limit, but I don't remember motivation why it was added to vote for removal.

This particular chunk either way I'd leave as it is, as I have told.

**Comment by freqlabs** [comment]
I'll need to update zfs-module-parameters(5) with this change, too.

**Comment by freqlabs** [comment]
Should I just go ahead and make the metadata limit follow the target arc size as well? ie
```C
static inline unsigned long
dbuf_metadata_cache_target_bytes(void)
{
        return (MIN(dbuf_metadata_cache_max_bytes,
            arc_target_bytes() >> dbuf_metadata_cache_shift));
}
```

**Comment by amotin** [comment]
> Should I just go ahead and make the metadata limit follow the target arc size as well?

It may have sense.  IIRC there is no eviction from the dbuf metadata cache at all, so at least making it grow slower together with ARC may be better then nothing from the memory pressure side.  But it was written by @ahrens , so I'll leave it to him to comment.

**Comment by ahrens** [comment]
I think it would be OK for the dbuf metadata limit to also scale with arc_c.

File: module/zfs/dbuf.c [hunk 2]
```diff
@@ -807,20 +808,14 @@ dbuf_init(void)
 
 	/*
 	 * Setup the parameters for the dbuf caches. We set the sizes of the
-	 * dbuf cache and the metadata cache to 1/32nd and 1/16th (default)
-	 * of the target size of the ARC. If the values has been specified as
-	 * a module option and they're not greater than the target size of the
-	 * ARC, then we honor that value.
+	 * dbuf metadata cache to 1/16th (default) of the max size of the ARC.
```
Comment (ahrens) [inline module/zfs/dbuf.c:811]: [nit]  It's actually 1/64th (`dbuf_metadata_cache_shift = 6`).  I have a fix for this in another branch that I'll get opened soon, but if you have a mind to fix it now that would be fine too.

File: man/man5/zfs-module-parameters.5 [hunk 3]
```diff
@@ -47,13 +46,12 @@ Default value: \fB0\fR.
 \fBdbuf_metadata_cache_max_bytes\fR (ulong)
 .ad
 .RS 12n
-Maximum size in bytes of the metadata dbuf cache.  When \fB0\fR this value will
-default to \fB1/2^dbuf_cache_shift\fR (1/16) of the target ARC size, otherwise
-the provided value in bytes will be used.  The behavior of the metadata dbuf
-cache and its associated settings can be observed via the
-\fB/proc/spl/kstat/zfs/dbufstats\fR kstat.
+Maximum size in bytes of the metadata dbuf cache.  The target size is
+determined by the MIN versus \fB1/2^dbuf_cache_shift\fR (1/16) of the target
```
Comment (amotin) [inline man/man5/zfs-module-parameters.5:50]: dbuf_metadata_cache_shift

File: module/zfs/dbuf.c (hunk 2 above)
Comment (freqlabs) [reply module/zfs/dbuf.c]: Fixed this in the manual. The comment here was removed but I added comments to describe the dbuf cache targets elsewhere, without this error.

**Comment by freqlabs** [comment]
* Fixed errors in the tunable descriptions in zfs-module-parameters(5) while touching those lines
* Added comments to dbuf_cache_target_bytes and dbuf_metadata_cache_target_bytes to convey their intent

**Comment by freqlabs** [comment]
I don't need to include arc_impl.h anymore.

**Comment by freqlabs** [comment]
* Rebased
* Dropped unnecessary header changes
