### PR TITLE
ZAP: Fix leaf references on zap_expand_leaf() errors

### LINKED ISSUE #12366: extra zap_put_leaf in an unlikely code path
The problem is found by a code review of the latest code, so no OS / version details.
But the code has been unchanged for many years.

`fzap_add` and `fzap_update` may need to call `zap_expand_leaf` if there is not enough room for a new entry.
`zap_expand_leaf` may need to call `zap_grow_ptrtbl` if the current pointer table is not large enough.
In the very unlikely -- but not impossible -- event that the `zap_grow_ptrtbl` call fails, `zap_expand_leaf` would return with the original leaf, `l`, released by a call to `zap_put_leaf` and with the output leaf pointer, `lp`, keeping it original value.
Both `fzap_add` and `fzap_update` call `zap_expand_leaf` like this:
```
err = zap_expand_leaf(zn, l, tag, tx, &l);
```
So, in the described scenario, `l` would still point to the original leaf, but the leaf would be released.
In the epilogue parts of the functions there is a call to `zap_put_leaf_maybe_grow_ptrtbl` that would `zap_put_leaf` the leaf again.

One potential consequence, in non-debug builds, is that a dirty hold would get released for the leaf's underlying dbuf.
Thus, the dbuf would both be free for a re-use and still be referenced from its dirty record.

### PR DESCRIPTION
**Pull request by amotin**
Depending on kind of error zap_expand_leaf() may return with or without valid leaf reference held.  Make sure it returns NULL if due to error it has no leaf to return.  Make its callers to check the returned leaf pointer, and release the leaf if it is not NULL.

Closes #12366

### How Has This Been Tested?
Not really.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/zap.c [hunk 1]
```diff
@@ -920,21 +921,17 @@ fzap_add_cd(zap_name_t *zn,
...
-			return (err);
-		}
 	}
 
 out:
-	if (zap != NULL)
-		zap_put_leaf_maybe_grow_ptrtbl(zn, l, tag, tx);
+	if (l != NULL) {
+		if (err == ENOSPC)
+			zap_put_leaf(l);
```
Comment (snajpa) [inline module/zfs/zap.c:931]: (not a review, I'm trying to understand this)

it gets here because it was `zap_grow_ptrtbl` which returned `ENOSPC`; when can that happen? a) the ZAP is way too large (2^46 entries, right?) and b) on transition from 2^28 to 2^48 `zap_hashbits`, that is when upgrading from micro to fat zap? Is there any other case that I'm missing why ENOSPC can happen here?

I mean, I'm trying to understand which separate two leaves does the `zap_put_leaf` get called for and whether that could cause additional trouble - this is the second occasion, the first is on line 713.

Comment (amotin) [reply module/zfs/zap.c:931]: I've primarily just refactored already present code.  I was actually thinking about actual out of space, but it seems not checked at this point, and you seem right that hash size limit may be the primary (and pretty unlikely) factor.

zap_expand_leaf() puts one leaf inside, while another (where the entry is going to be inserted) returns to the caller.  So it is the leaf that gets new entry is checked for coming overflow and possible hash table grow.  I.e. I see no problems, unless you specify better.
