### PR TITLE
Block remap for cloned blocks on device removal

### LINKED ISSUE #15604: VERIFY3(counts[index] + inner_size <= size) failed (8192 <= 4096)
### System information

Type | Version/Name
 --- | ---
Distribution Name	|fedora
Distribution Version	|39
Kernel Version	|6.5.12-300.fc39.x86_64
Architecture	|x86_64
OpenZFS Version	|zfs-2.2.1-1,zfs-kmod-2.2.1-1

### Describe the problem you're observing
 Kernel Panic with zfs on root.
Rebooting the system hangs after "dracut wraning: unmounted /oldroot"
```
11月 29 13:57:23 fedora kernel: VERIFY3(counts[index] + inner_size <= size) failed (8192 <= 4096)
11月 29 13:57:23 fedora kernel: PANIC at vdev_indirect_mapping.c:528:vdev_indirect_mapping_increment_obsolete_count()
11月 29 13:57:23 fedora kernel: Showing stack for process 741
11月 29 13:57:23 fedora kernel: CPU: 1 PID: 741 Comm: z_indirect_cond Tainted: P           OE      6.5.12-300.fc39.x86_64 #1
11月 29 13:57:23 fedora kernel: Hardware name: LENOVO 20WE/LNVNB161216, BIOS FNCN40WW(V2.10) 09/14/2022
11月 29 13:57:23 fedora kernel: Call Trace:
11月 29 13:57:23 fedora kernel:  <TASK>
11月 29 13:57:23 fedora kernel:  dump_stack_lvl+0x47/0x60
11月 29 13:57:23 fedora kernel:  spl_panic+0x100/0x120 [spl]
11月 29 13:57:23 fedora kernel:  vdev_indirect_mapping_increment_obsolete_count+0xe2/0x120 [zfs]
11月 29 13:57:23 fedora kernel:  load_obsolete_sm_callback+0x20/0x30 [zfs]
11月 29 13:57:23 fedora kernel:  space_map_iterate+0x195/0x410 [zfs]
11月 29 13:57:23 fedora kernel:  ? __pfx_load_obsolete_sm_callback+0x10/0x10 [zfs]
11月 29 13:57:23 fedora kernel:  ? __pfx_thread_generic_wrapper+0x10/0x10 [spl]
11月 29 13:57:23 fedora kernel:  vdev_indirect_mapping_load_obsolete_spacemap+0x47/0x90 [zfs]
11月 29 13:57:23 fedora kernel:  spa_condense_indirect_thread+0xdf/0x560 [zfs]
11月 29 13:57:23 fedora kernel:  ? __slab_free+0xf1/0x330
11月 29 13:57:23 fedora kernel:  ? set_next_entity+0xe2/0x160
11月 29 13:57:23 fedora kernel:  ? __pfx_thread_generic_wrapper+0x10/0x10 [spl]
11月 29 13:57:23 fedora kernel:  zthr_procedure+0x137/0x150 [zfs]
11月 29 13:57:23 fedora kernel:  ? __pfx_zthr_procedure+0x10/0x10 [zfs]
11月 29 13:57:23 fedora kernel:  thread_generic_wrapper+0x5b/0x70 [spl]
11月 29 13:57:23 fedora kernel:  kthread+0xe5/0x120
11月 29 13:57:23 fedora kernel:  ? __pfx_kthread+0x10/0x10
11月 29 13:57:23 fedora kernel:  ret_from_fork+0x31/0x50
11月 29 13:57:23 fedora kernel:  ? __pfx_kthread+0x10/0x10
11月 29 13:57:23 fedora kernel:  ret_from_fork_asm+0x1b/0x30
11月 29 13:57:23 fedora kernel:  </TASK>
```
### Describe how to reproduce the problem
Boot with commad line : single init=/bin/bash
```
zfs import -N <pool>
```
or

Booting with zfs on root when dracut  import pool

### PR DESCRIPTION
**Pull request by amotin**
When after device removal we handle block pointers remap, skip blocks that might be cloned.  BRTs are indexed by vdev id and offset from block pointer's DVA[0].  So if we start addressing the same block by some different DVA, we won't get the proper reference counter.  As result, we might either remap the block twice, that may result in assertion during indirect mapping condense, or free it prematurely, that may result in data overwrite, or free it twice, that may result in assertion in spacemap code.

Fixes #15604

### How Has This Been Tested?
Written and cloned a file on a pool of several vdevs.  Removed one of vdevs.  Overwritten each 128th block of the file to trigger block pointers remap.  Run `zdb` on the pool and observed it crashing due to incorrect block reference counting.  Applied the patch and observed `zdb` passing clean.  I wonder if it may also fix some space leaks periodically reported by `zdb` after `ztest`.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [x] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

### CODE REVIEW

File: module/zfs/metaslab.c [hunk 1]
```diff
@@ -5536,6 +5537,13 @@ spa_remap_blkptr(spa_t *spa, blkptr_t *bp, spa_remap_cb_t callback, void *arg)
 	if (BP_GET_NDVAS(bp) < 1)
 		return (B_FALSE);
 
+	/*
+	 * Cloned blocks can not be remapped since BRT depends on specific
+	 * vdev id and offset in the DVA[0] for its reference counting.
+	 */
+	if (!BP_IS_METADATA(bp) && brt_maybe_exists(spa, bp))
```
Comment (pcd1193182) [inline module/zfs/metaslab.c:5544]: I imagine it's not a big deal, but are we worried about pinning some blocks in the indirection table because they are false positives in `brt_maybe_exists`? I guess they can only show up as a false positive if there's another true-positive nearby, which would prevent us from fully deleting the indirect mapping anyway.

**Review by pcd1193182 — APPROVED** [review]

File: module/zfs/metaslab.c (hunk 1 above)
Comment (behlendorf) [reply module/zfs/metaslab.c:5544]: False positives seem like they shouldn't be a major problem.  It's unfortunate we can't remap BPs with a BRT entry, but there's not much we can do about that.  Thanks for running this down.

**Review by behlendorf — APPROVED** [review]

**Comment by mmatuska** [comment]
@amotin is this eligible for both 2.3 and 2.2?

**Comment by amotin** [comment]
@mmatuska Yes. Everything that has block cloning already.
